### ISSUE TITLE
Qtwebengine fails with graphite, internal compile error I think

### ISSUE THREAD

**Issue by qtwebenginedoesntcompilewithgraphite** [InBetweenNames/gentooLTO#102]
Nothing big, just figured I'd let you know.

**Comment by preney** [comment]
Interesting. I have these Qt packages built with graphite and no LTO: dev-qt/qtcore dev-qt/qtscript dev-qt/qtwebengine dev-qt/qtwebkit

i.e., I don't have an issue with graphite with these packages.

**Comment by InBetweenNames** [comment]
Thanks for the report -- Is this the latest Qt beta? I haven't had a chance to build it quite yet.

**Comment by preney** [comment]
I needed these settings earlier. I currently have the following installed:
dev-qt/qtcore-5.9.4-r2 dev-qt/qtwebengine-5.9.4 dev-qt/qtscript-5.9.4 dev-qt/qtwebkit-5.9.1

**Comment by InBetweenNames** [comment]
I managed to rebuild everything and I had no problems with qtwebengine with the latest Qt beta (5.11.0 beta 2). Can you provide a `build.log`?

**Comment by preney** [comment]
To be running Qt 5.11 you must be using the KDE overlay or something similar. If the issue is not an issue with the beta Qt/KDE that is good news.

**Comment by InBetweenNames** [comment]
I can confirm 5.10.x works as well.

**Comment by InBetweenNames** [comment]
@qtwebenginedoesntcompilewithgraphite has this issue been resolved for you?
