### ISSUE TITLE
Mix of license models

### ISSUE THREAD

**Issue by mgomersbach** [InBetweenNames/gentooLTO#11]
Full disclosure: I have no idea, because "I am not a lawyer"

The project as a whole is under the BSD license whereas the ebuild is under GPLv2,

Anybody can shed some light on the implications?

**Comment by preney** [comment]
IANAL. My guess would be that all of the ebuilds are held to the more restrictive licence stipulation whichever one it may be for that issue. For everything else BSD.

Perhaps for sanity, everything should match the .ebuild licence: GPLv2. If something should truly be BSD, then that item can mention it explicitly.

**Comment by InBetweenNames** [comment]
Yeah that's a holdover from when this repo was actually just my own `/etc/portage`.  I know `repoman` complains if I have anything other than the Gentoo Foundation copyright + GPLv2 license on it, and in general I do prefer the GPL anyway, so I am inclined to change the license to GPLv2.  For the end users, there should be no difference, and I doubt anyone would be packaging this stuff into a binary anyways

**Comment by InBetweenNames** [comment]
Fixed as of 85b0a3d -- thanks for bringing this to my attention
