### ISSUE TITLE
parallelize execution of profiles tests for python 3 pgo USE flag

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#112]
for pgo, profiling execution time is very significant, for python 3.6, 1.5 minutes without pgo and 31 minutes with. executing the profiled tests in parallel could massively speed up this process.

**Comment by wolfwood** [comment]
python 2.7 only takes 1.5 minutes with pgo, so either there are significant differences in the tests run, or it's test execution is already parallelized

**Comment by InBetweenNames** [comment]
Indeed, it would be a lot easier to upstream this if we could parallelize the tests. I've got a paper I need to get done for Tuesday, but I'll try to take a look after that.

**Comment by InBetweenNames** [comment]
Should be fixed as of HEAD.
