### ISSUE TITLE
LTO errors

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#113]
I get the following errors with a few packages, most notably `kde-frameworks/kross` (it was the first to break) and lately `kde-apps/kmail-account-wizard`:    
`lto1: fatal error: bytecode stream in file ‘/usr/lib64/libQt5UiTools.a’ generated with LTO version 6.0 instead of the expected 7.0`

`emerge --info '=kde-frameworks/kross-5.45.0::gentoo'`:    
https://gist.github.com/f5553ae1aef2826faa921dcfdccf5234

Build log for kross:    
https://gist.github.com/6fcb8839659d56ce1940ac8fc561b722

I use GCC 8.1.

**Comment by wolfwood** [comment]
it looks like maybe you need to re-emerge qt5 with the new gcc?

if you haven't rebuild world after switching to the latest gcc you can do that with `emerge -eav @world`

**Comment by Althorion** [comment]
The thing is, my troubles with kross are older than the upgrade to GCC 8.1, it failed on 7.3. Then I `emerge -e @world` and _it actually built that time_ (out of all my packages, only Firefox failed, and that was patched up since), but now it won’t rebuild. Plus, I’ve run `emerge -e kross kmail-account-wizard` before posting, to no luck.

I’ll try rebuilding world again and see if that makes a difference.

**Comment by Althorion** [comment]
Things are failing left and right now. About everything QT-related fails with the same bug. I’ll turn off LTO and try to recover.

**Comment by InBetweenNames** [comment]
Yeah it's definitely old Qt symbols. At least very least do a qfile to see
which package owns UiTools and rebuild that.

**Comment by InBetweenNames** [comment]
To expand on my previous post, the full world rebuild is absolutely necessary after upgrading your compiler -- no way around it. Even if it means you have to skip some packages, it will likely mean only a few and it will greatly reduce the chances of running into problems like this. You can try to get away with rebuilding as needed for a while by using `qfile` to find which package owns the older library, but it's more trouble than it's worth in the long run.

I use `emerge --keep-going -e @world` myself, with `emerge --resume --skipfirst` in those rare cases when `--keep-going` won't play nice. Sometimes, even that won't work well and I have to manually inspect and edit the list of packages remaining and do an `emerge -1 $(cat list_of_remaining_packages)`.

**Comment by Althorion** [comment]
As I said, I've done just that. And to make double sure, I've turned off the LTO system-wide, tried again—it works; then turned it on again—linker error galore.

Maybe it's a case of leftover rogue files? What folders should I clean to make sure?

**Comment by Althorion** [comment]
My current linker errors, after multiple tries of building and rebuilding everything, are `error: undefined reference to 'qt_version_tag'`.

Can anyone help me with that?

**Comment by Althorion** [comment]
OK, you can close it now. My bad, everything with ltoize is all right.

First, I’ve somehow managed to cause it not to sync, so it missed the `qtcore` LTO exception.    
Then, for reason unknown `emerge -e @world` tries to build `qtcore` as one of the _last_ packages, completely blowing up packages depending on it.

**Comment by InBetweenNames** [comment]
No worries! Thanks for following up. Glad everything is working for you now. I'll close the issue accordingly, but if you have further trouble just comment and I'll reopen.

**Comment by pchome** [comment]
> My current linker errors, after multiple tries of building and rebuilding everything, are `error: undefined reference to 'qt_version_tag'`.
> Can anyone help me with that?

You can experiment with `dev-qt/qtcore *FLAGS+="-DQT_NO_VERSION_TAGGING"`.
I'm not checked this further than building `dev-qt/qtgui` to be sure error is gone, but probably you need to rebuild whole Qt toolkit with same flag if you want to test.
