### ISSUE TITLE
mesa segfaults in `alu_group_tracker::alu_group_tracker` on r600 with gcc 8.1

### ISSUE THREAD

**Issue by Hello71** [InBetweenNames/gentooLTO#114]
it is probably a mesa bug. I turned off both LTO and graphite and it works fine now.

**Comment by InBetweenNames** [comment]
Agreed that the problem is upstream, but one of the purposes of this overlay is to document these failures. After I get my next paper done I'll add a workaround in.

**Comment by InBetweenNames** [comment]
Managed to build Mesa without any problems -- this must be an `r600` specific thing. I'll see if I can implement a flag-based workaround for this.

**Comment by InBetweenNames** [comment]
Excellent, thanks!
