### ISSUE TITLE
ACCESS DENIED to /var/cache/pgo/dev-lang:python-2.7.14

### ISSUE THREAD

**Issue by HollowKnight** [InBetweenNames/gentooLTO#120]
Hello,
I've tried compiling all versions of dev-lang/python 2.7 3.4 3.5 3.6 with EXTRA_ECONF="--enable-optimization" and flag "dev-lang/python" PGO=true config in portage-bashrc-mv. Despite various settings of FEATURES enabled or disabled *sandbox* userpriv and permissions/owership of /var/cache/pgo to sticky world-writeable 1777, either root:root or portage:portage, still got the access denied as follows:
[code]
profiling:/var/cache/pgo/dev-lang:python-2.7.14:Cannot create directory
profiling:/var/cache/pgo/dev-lang:python-2.7.14/Objects/classobject.gcda:Skip
profiling:/var/cache/pgo/dev-lang:python-2.7.14:Cannot create directory
profiling:/var/cache/pgo/dev-lang:python-2.7.14/Objects/cobject.gcda:Skip
profiling:/var/cache/pgo/dev-lang:python-2.7.14:Cannot create directory
profiling:/var/cache/pgo/dev-lang:python-2.7.14/Objects/codeobject.gcda:Skip
[/code]
Compiling is still finished. But how can I tell my python packages are really PGO-enabled?
Thanks,

**Comment by InBetweenNames** [comment]
I strongly recommend using the pgo USE flag with Python instead of what you
have done. See the readme in this repo for details

**Comment by HollowKnight** [comment]
Hello the issue is due to sandbox configuration. It solved with config /etc/sandbox.d/99python:
`SANDBOX_PREDICT=/var/cache/pgo
SANDBOX_WRITE=/var/cache/pgo`
Thanks
