### ISSUE TITLE
dev-lang/python:2.7 - enable PGO for extensions

### ISSUE THREAD

**Issue by stefantalpalaru** [InBetweenNames/gentooLTO#122]
Patch: https://github.com/stefantalpalaru/gentoo-overlay/blob/9c4a4efd5d938bf607e280f154e0f23092ec07b0/dev-lang/python/files/python-2.7.15-PGO.patch

Story: https://www.reddit.com/r/Gentoo/comments/8n38ak/devlangpython2715r104_enable_pgo_for_extensions/

Some the fixes were moved from the ebuild into the patch, so the emake call in src_compile() was simplified: https://github.com/stefantalpalaru/gentoo-overlay/blob/e7700112a3a8aaa18b1e6bafc736e9ab72aa0021/dev-lang/python/python-2.7.15-r104.ebuild#L238

**Comment by InBetweenNames** [comment]
Wonderful! I'm on holiday right now, but I'll take a look when I'm back home

**Comment by InBetweenNames** [comment]
@stefantalpalaru sorry for taking so long to address this -- I only made a couple very minor modifications (mainly to use the LTO flags of the system rather than forcing `-ffat-lto-objects` as Python does).
