### ISSUE TITLE
enable -march=native for 4.17 kernel

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#124]
https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.17-march-native

experimental patch in need of daring testers :)
http://lkml.iu.edu/hypermail/linux/kernel/1806.0/02406.html

**Comment by bobwya** [comment]
Hasn't this been available for years with the experimental **USE** flag for **sys-kernel/gentoo-sources** ??
This gives you the option to set **Native** options detected by **gcc*,* in the kernel **CONFIG** flags.

**Comment by wolfwood** [comment]
It looks like it has the same purpose, but the patches are not fromt he same source.

the experimental USE patches look like they effectively only add the -march=native flag, whereas this patchset seems to disable FP flags, e.g. AVX512 flags, that would be enabled by native.

there are also various code patches relating to alignments, asm routines, etc. which seem reasonable at a glance.

**Comment by InBetweenNames** [comment]
Completely understandable, as AVX2 and greater typically imposes clock speed restrictions that would be detrimental to the performance of the rest of the code in the kernel (overclocks that remove the AVX offset excepting). Typically it only makes sense to use these instructions if the code is largely "numeric", that is, dominated by vector calculations.  In these cases, improving throughput by 16x through AVX512 is very profitable, even with the clock speed hit.

**Comment by wolfwood** [comment]
i think the main goal is to avoid having to restore and/or save FP/ vector register context, by having the kernel promise to not use these registers, at least during interrupts.

i don't know if the Linux kernel mandates that x87 and mmx registers are not used in certain places, in which case the experimental USE flag would actually potentially break my kernel by allowing avx512 instructions to be emitted, or if the kernel just opportunistically avoids restoring the registers if they aren't overwritten.

but in either case, yes i think this patch has the potential for better results on skylake-X, at least, than the gentoo-sources experimental USE flag.

**Comment by InBetweenNames** [comment]
Closing this as this is now in the mainline kernel
