### ISSUE TITLE
glibmm-2.4 issues?

### ISSUE THREAD

**Issue by prototype99** [InBetweenNames/gentooLTO#125]
posting here simply because unsure what the root cause is, however dev-cpp/gtkmm-3.22.2 will fail to build, due to the error that is mentioned at https://bugzilla.redhat.com/show_bug.cgi?id=1540795 (note it's specifically only brought to light with the use of gcc 8) i found the exact same offending file they mention at /usr/include/glibmm-2.4/glibmm/threads.h. I fix it and built easy peasy

**Comment by InBetweenNames** [comment]
Not an LTO issue, but this is good to know.  I actually don't have this on my system, so I never encountered it.  Thanks!

**Comment by wolfwood** [comment]
i think this is the same issue as #115, there is a link to the gentoo bug there, and a patch
