### ISSUE TITLE
dev-util/perf fails to build with LTO

### ISSUE THREAD

**Issue by Hello71** [InBetweenNames/gentooLTO#126]
doesn't work with bfd or gold, oddly enough with different errors. below errors for gold:

```
<artificial>:memcpy_functions: error: undefined reference to 'memcpy_orig'
<artificial>:memcpy_functions: error: undefined reference to '__memcpy'
<artificial>:memcpy_functions: error: undefined reference to 'memcpy_erms'
<artificial>:memset_functions: error: undefined reference to 'memset_orig'
<artificial>:memset_functions: error: undefined reference to '__memset'
<artificial>:memset_functions: error: undefined reference to 'memset_erms'
```

**Comment by InBetweenNames** [comment]
Does it work with fat LTO?

**Comment by Hello71** [comment]
as I recall, the other set of errors weren't typical of losing the GIMPLE, they were some other weird errors. although since it uses raw `$LD` it's possible it will work with fat objects.

**Comment by Hello71** [comment]
wait, no, I'm an idiot, that's the problem, it uses `$LD` instead of `$CC` to link. I wonder how to fix it though...

**Comment by InBetweenNames** [comment]
Yeah I can't even get it working with no-lto right now.  It'll probably need some ebuild surgery.

**Comment by InBetweenNames** [comment]
Still can't get this to build, even with just plain `-O2`.  I wonder if it's a GCC 8 thing.

**Comment by InBetweenNames** [comment]
Going to close this for now as it does not appear to be GentooLTO related.
