### ISSUE TITLE
dev-lisp/clisp-2.49.92 fails to build with LTO

### ISSUE THREAD

**Issue by zeule** [InBetweenNames/gentooLTO#128]
The failing command is:
```
./lisp.run -B . -N locale -E UTF-8 -Emisc 1:1 -Epathname 1:1 -norc -m 2MW -lp ../src/ -x '(and (load "../src/init.lisp") (sys::%saveinitmem) (ext::exit)) (ext::exit t)'
PSEUDOCODE_ALIGNMENT is not fulfilled. &equal = 0x55d3c5b0d657.
Add -falign-functions=8 to FALIGNFLAGS in the Makefile.
make: *** [Makefile:1470: interpreted.mem] Aborted (core dumped)
```

**Comment by InBetweenNames** [comment]
Fixed.  You just needed the following:

~~~
dev-lisp/clisp *FLAGS+=-falign-functions=8 
~~~

**Comment by zeule** [comment]
I've tried that, and, besides, -falign-functions=n (8 on amd64) is enabled by -O2 and above, AFAIK.

**Comment by zeule** [comment]
Does this workaround worked for you?

**Comment by InBetweenNames** [comment]
Yup, I have it installed right now with the new workaround

**Comment by InBetweenNames** [comment]
I'll reopen this until we confirm it's resolved on your end

**Comment by zeule** [comment]
Thanks. I must have mistyped flag or package name when I tried this workaround locally, because now it works. However, I believe the flag setting has to be replaced with `*FLAGS+=-falign-functions` to use the default alignment for a platform. Tested here and that works for me on amd64.

**Comment by InBetweenNames** [comment]
Thanks for the followup!  Should be fixed in `HEAD`.

**Comment by zeule** [comment]
Thank you!
