### ISSUE TITLE
A couple more packages that don't seem to work with LTO

### ISSUE THREAD

**Issue by monoidic** [InBetweenNames/gentooLTO#131]
sys-libs/libse{pol,linux,manage}, app-crypt/efitools, gnome-base/gnome-keyring, dev-libs/weston, app-crypt/veracrypt, dev-qt/qtscript
I currently have `*FLAGS-=-flto*` set for all of them except for efitools, which has `*FLAGS+=-ffat-lto-objects`, which makes them compile and, seemingly, work. I am not sure if there's a better way to handle these packages though.

**Comment by InBetweenNames** [comment]
Excellent -- could you make a PR out of this issue so I can merge these exceptions in?
