### ISSUE TITLE
Gentoo agressive flags

### ISSUE THREAD

**Issue by wmyrda** [InBetweenNames/gentooLTO#132]
I noticed You guys take care of [nonstandard](https://github.com/InBetweenNames/gentooLTO/issues/98) issues so I come with similar setup and using git master snapshot as source

So how about [that one](https://pastebin.com/YCKEWhDS)? ;)

**Comment by wmyrda** [comment]
pffff. It is actually same error. I should have looked more closely at the code.

Anyways why those errors do not make it in the main Gentoo repo ebuilds as fillter-flag option or something similar?

**Comment by InBetweenNames** [comment]
This error is caused by Graphite in your compiler.

~~~
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
~~~

Have you tried GCC 8.1.0?  I noticed Graphite plays nicer with the latest GCC, which is what is mandated by this repo.

**Comment by InBetweenNames** [comment]
FYI, the latest GCC is 8.2.0 now.  Could you try with that version?

**Comment by InBetweenNames** [comment]
No worries, best of luck with the business!  I usually only contribute once a week or so here myself, so no rush.

**Comment by InBetweenNames** [comment]
Just going to shelve this for now, but I have not forgotten about it!  If you are still experiencing issues just comment and I'll reopen the issue.

**Comment by wmyrda** [comment]
I looked at the issue and saw that [pastebin](https://pastebin.com/YCKEWhDS) deleted my text file, so I can only guess that my bug report was about openjpeg. ;)
Hence gcc-8.2.0 has hit unstable portage branch I tested it with openjpeg git and to my surprise compilation works with lto & full graphite enabled 

Here are changes to my local ebuild
```
--- /usr/portage/media-libs/openjpeg/openjpeg-2.3.0.ebuild	2018-06-22 12:09:25.000000000 +0200
+++ openjpeg-2.3.0.1.ebuild	2018-07-12 14:45:48.552883841 +0200
@@ -2,15 +2,16 @@
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=6
-inherit multilib cmake-multilib
+inherit eutils multilib cmake-multilib
 
 # Make sure that test data are not newer than release;
 # otherwise we will see "Found-But-No-Test" test failures!
 MY_TESTDATA_COMMIT="c07f38fae1e67adc288c2d6679df5d3652017fbe"
+MY_COMMIT="d2205ba2ee78faeea659263383446c4472b1f9df"
 
 DESCRIPTION="An open-source JPEG 2000 library"
 HOMEPAGE="http://www.openjpeg.org"
-SRC_URI="https://github.com/uclouvain/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
+SRC_URI="https://github.com/uclouvain/${PN}/tarball/${MY_COMMIT} -> ${P}.tar.gz
 	test? ( https://github.com/uclouvain/openjpeg-data/archive/${MY_TESTDATA_COMMIT}.tar.gz -> ${PN}-data_20170814.tar.gz )"
 
 LICENSE="BSD-2"
@@ -26,6 +27,7 @@
 	doc? ( app-doc/doxygen )"
 
 DOCS=( AUTHORS.md CHANGELOG.md NEWS.md README.md THANKS.md )
+S="${WORKDIR}/uclouvain-${PN}-${MY_COMMIT:0:7}"
 
 src_prepare() {
 	if use test; then

```

**Comment by InBetweenNames** [comment]
Confirmed and fixed.  Thanks!
