### ISSUE TITLE
problem emerging dev-qt/qtscript-5.9.6 

### ISSUE THREAD

**Issue by zwim** [InBetweenNames/gentooLTO#133]
Hello,

First i could not emerge dev-qt/qtscript-5.9.6, but after 
setting  link with 
             ln -s qtscript-5.9.6 qtscript-5.9.3
in  /etc/portage/patches/dev-qt
it was possible to emerge qtscript

**Comment by InBetweenNames** [comment]
Yeah the qtscript LTO patch has not been updated in a bit.  I have disabled LTO on qtscript until I can take a look at the problem further.  For the record, I'm on the latest Qt in the `qt` overlay

**Comment by InBetweenNames** [comment]
OK, should be fixed in `HEAD` now.
