### ISSUE TITLE
cargo building requires --no-as-needed

### ISSUE THREAD

**Issue by eugene-bright** [InBetweenNames/gentooLTO#141]
Compilation of cargo fails at the very late linking process if option `LDFLAGS+="-Wl,--as-needed"` is enabled.
At the first glance it seems that libssh2 causes troubles but it's not. The error keeps the same if libssh2 is built without LTO.
```
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/dev-util/cargo-0.29.0/work/cargo-0.29.0/target/release/deps/liblibssh2_sys-79f68005d05542bc.rlib(libssh2_sys-79f68005d05542bc.libssh2_sys2-688af8bdebcb978a29e097a96822ec6d.rs.rcgu.o): undefined reference to symbol 'libssh2_exit'
```
Appending `LDFLAGS+="-Wl,--no-as-needed"` is a workaround.
Just be aware of it.

I'm experimenting with LTO in my own way. I found [gentoo environment control](https://wiki.gentoo.org/wiki//etc/portage/package.env) mechanism to be a very powerful tool. It provides me to append arbitrary flags for any chosen package on individual basis and thus allows keeping global configuration to be the most generic (I've enabled LTO globally). Also I can stack more then one overlaying environment adjusting scripts.
As example:
```
$ cat /etc/portage/package.env/cargo 
dev-util/cargo no_lto no_as_needed
```

```
$ cat /etc/portage/env/no_lto 
CFLAGS="$CFLAGS -fno-lto"
CXXFLAGX="$CFLAGS"
LDFLAGS="$LDFLAGS -Wl,-fno-lto"
```

```
$ cat /etc/portage/env/no_as_needed 
LDFLAGS="$LDFLAGS -Wl,--no-as-needed"
```

**Comment by eugene-bright** [comment]
What is the `flag detection` you are talking about?
Actually I do not care about options list length. List `-flto -fno-lto` is effectively equal to just `-fno-lto`, thus the only the latest one option takes place and I do not think about what was before it. I do not have to read all options and guess which options was explicitly/implicitly implied.
Anyway thank you for your work. List of common pitfalls help me a lot.

**Comment by InBetweenNames** [comment]
The flag detection logic is in `flag-o-matic` in Portage.  See the README section titled "Additional details about LTOize" for more details -- it covers the exact case `-flto -fno-lto` as you have mentioned (and I agree SHOULD work!!  But doesn't :( )

The upstream Gentoo developers have expressed no interest in accepting patches to fix `flag-o-matic` to have the correct behaviour.  I tried at some point last year.

**Comment by eugene-bright** [comment]
Oh my!
`flag-o-matic` has a bad smell.
Thank you again. I should read your notes first.
Now I'm starting to understand the reason for overcomplication.

**Comment by InBetweenNames** [comment]
No problem!  I agree, `flag-o-matic` needs a major overhaul.  I'd do it myself, but I know for sure it would get rejected upstream.  Ideally, we could overhaul that and switch back to `package.env`, but here we are I guess!

**Comment by InBetweenNames** [comment]
I managed to get `cargo-0.29.0` built on my system with just `-ffat-lto-objects` and no removing of `-Wl,--as-needed` or adding ``-Wl,--no-as-needed`, and I'll be updating the repo accordingly.  Thanks!
