### ISSUE TITLE
net-proxy/privoxy-3.0.26

### ISSUE THREAD

**Issue by Supded** [InBetweenNames/gentooLTO#145]
With LTO:
sudo rc-service privoxy start
 * Caching service dependencies ...                                                                                                                                                                                                      [ ok ]
 * Starting privoxy ...
 * start-stop-daemon: failed to start `/usr/sbin/privoxy'                                                                                                                                                                                [ !! ]
 * ERROR: privoxy failed to start

gcc-8.2.0-r2

**Comment by InBetweenNames** [comment]
Was able to reproduce -- workaround is in `master`.  Thanks for the report!
