### ISSUE TITLE
media-plugins/caps-plugins-0.9.24

### ISSUE THREAD

**Issue by fxkrait** [InBetweenNames/gentooLTO#148]
This package is required by lmms.
Still learning how this works, so I haven't tried with compiling w/o graphite, LTO, or just with -O2.
Just using stock make.conf configs from repo.
make.conf:
https://pastebin.com/ccKJgWZ8
build output:
https://pastebin.com/WvfWdDBH

**Comment by fxkrait** [comment]
I restored by configs back to stock, and it still fails to build. So I will assume this is unrelated to gentooLTO and close this.

**Comment by pchome** [comment]
```
CFLAGS="-march=native -O3 ${GRAPHITE} ${FLTO} -fuse-linker-plugin -pipe"
CXXFLAGS="${CFLAGS}"

...

# LTO-Overlay
FLTO="-flto=8"
STRIP_MASK="*.a"
GRAPHITE="-fgraphite-identity -floop-nest-optimize"
```
:confused:

**Comment by fxkrait** [comment]
Yeah, I was unaware order mattered.
Got it working now though.
