### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by fxkrait** [InBetweenNames/gentooLTO#149]
Update: I have closed #148, as I think it is not a gentooLTO Issue.
However, I am still dealing with Issue 1, as I have to keep rebuilding my entire system all over again due to a one package not building.

Hey, in #148 I'm having an issue running the **emerge -e @world** command to rebuild my system with LTO, graphic, -O3, etc.

Here are my two main issues:

1) Improved **emerge -e @world**
Some packages fail to build.
Lets say the 208th package fails.
However when running emerge -e @world again, I have to rebuild everything all over again.
- even packages that successfully built

There is no --keep-going functionality to this command.
  - This is is incredibly annoying, as I want to stop rebuilding packages that have worked, and focus on rebuilding packages that I either haven't rebuild or that have failed.

2) Improved **whitelisting documentation**
per #148, I am unable to figure how to whitelist the optimizations for packages that fail to build.

There is mention of a **env/O2*.conf**, where one can whitelist packages and compile with -O2.
However, I have no such file in my /etc/portage, and there are no examples of what should be in that config file to whitelist a given application.

**Comment by Althorion** [comment]
`--keep-going` should work, you must have mistyped it. Plus, you can always do `emerge --resume --exclude <package that fails>` after it borked.

**Comment by fxkrait** [comment]
Ok, my main issue with the `--keep-going`, is that will not keep track of packages that successfully installed/upgraded. 
If a upgrade fails with `--keep-going`, I just re-run it, till I get a small list of failed packages, then go from there.
How would I identify all failed packages? Will they all appear in portage logs?
I'll try the commands above, thanks. I think the `--resume` would probably work better.

**Comment by fxkrait** [comment]
I guess to answer my own question:
don't look at failed packages logs, just keep doing --keep-going and then --resume if packages failed like @Althorion said.

I'll close this if I don't have any issues upgrading.

**Comment by bobwya** [comment]
@fxkrait 

There's a script snippet I found online, which i've plugged into my full world building script:

```
starttime="$( cat "/root/.emergestart" )"
eix '-I*' --format '<installedversions:DATESORT>' | cut -f1,3 >"/tmp/tmplist"
echo "${starttime}" >>"/tmp/tmplist"
sort -n "/tmp/tmplist" | sed -e/$starttime/q | sed -e'/[0-9]*\t*/s///' | sort | comm -23 - <(sort "/root/omitlist") | comm -23 - <(sort "/etc/portage/profile/package.provided" 2>/dev/null) >"/root/.buildlist"

[[ -f "/root/.buildlist" ]] || exit 2

build_list="$(cat "/root/.buildlist")"
emerge $1 -1 --keep-going ${build_list}
```

Unfortunately, owing to senility I can't credit the original author... I think it was pulled from the Gentoo forums or Linux Questions... It's a god send. Especially since you can exclude all the crap that isn't actually compiled (**/root/omitlist**)!

This code snippet has the advantage that you can reboot (or even a kernel oops!) and just go right back to where you were before!

**Comment by InBetweenNames** [comment]
That's a nice script!

@fxkrait, consider using `emerge --skipfirst --resume` to skip over rebuilding a troublesome package.  That's what I do whenever I rebuild.  Currently, all failures except mesa are due to GCC 8 and not LTO, the `ltoworkarounds.conf` blacklist notwithstanding.  `--keep-going` is usually used when you start a new emerge, rather than resume an existing one.  I'm unsure how it would interact with `--resume` as I've never combined the two methods.

> Improved whitelisting documentation

Could you elaborate on what you mean by whitelisting?  GentooLTO uses a blacklist, rather than a whitelist, in `ltoworkarounds.conf`.  In other words, packages are assumed to build with LTO unless demonstrated otherwise.

**Comment by fxkrait** [comment]
@InBetweenNames 
Yes I'm colorblind, I meant a **"blacklist"**, instead of a whitelist.

I'm still rebuilding my world, so I can't fully comment on package issues right now, but for now...

1) How to get **python** with `pgo`?
  - python 2/3 does not compile with `pgo` use flag. 
  - apparently a "bug" on bugtracker
    - I've added a package.use `>=dev-lang/python-2.7.15-r1 -pgo` for it to compile
  - **However**, I see there is a .ebuilds in this repo for python pgo.
     - Am I not using them? Do I need to use them? If so how?

2) Do I need to manually implement the ltoworkarounds.conf (copy and paste into my configs like make.conf.lto)?
  - Should I assume that all known LTO blacklists are implemented on my system by default?

**Comment by InBetweenNames** [comment]
Before we get to any of that, I want to review your `make.conf` settings:
https://pastebin.com/ccKJgWZ8

Here, you set `CFLAGS` before you set `FLTO` and `GRAPHITE`:

~~~
CFLAGS="-march=native -O3 ${GRAPHITE} ${FLTO} -fuse-linker-plugin -pipe"
...
# LTO-Overlay
FLTO="-flto=8"
STRIP_MASK="*.a"
GRAPHITE="-fgraphite-identity -floop-nest-optimize"
~~~

Have you verified LTO is being added to your build?  I don't think this will work.  According to the `build.log` you posted:

~~~
...
CFLAGS='-march=native -O3 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'
...
~~~

I don't see LTO in there anywhere.  Before we go any further, could you check and ensure your `make.conf` is set correctly?

**Comment by fxkrait** [comment]
Hmmm. The only thing I have mainly changed is copying and pasting some lines from the `make.conf.lto` like it says below.
I though that was all that was required under the **How to use this configuration** and that the given make.conf.lto has the **"recommended settings for LTO."**

> " It will create a make.conf.lto in /etc/portage with the recommended settings for LTO. Modify your own make.conf accordingly--there are comments in make.conf.lto to help guide you through the process, including for enabling Graphite."

I'm a little confused here. So I need to add a LTO cflag? 
What documentation besides the `make.conf.lto` should I be using as a reference?

**Comment by fxkrait** [comment]
Wait. @InBetweenNames, are you saying the **order** of each statement **matters** for my make.conf?

In that I need to have 
FLTO="-flto=8"
before 
CFLAGS="-march=native -O3 ${GRAPHITE} ${FLTO} -fuse-linker-plugin -pipe"

**Comment by InBetweenNames** [comment]
Yup!

**Comment by fxkrait** [comment]
make.conf v2:
https://pastebin.com/sfQBsDvJ
python 3.7 (pgo) build log fail.
https://bin.disroot.org/?286886c1fb057092#5xK/G0LyHvAhGEqCMfJOKzzpdUEC0wGHgL0CIwHwgtQ=

`CFLAGS='-march=native -O3 -fgraphite-identity -floop-nest-optimize -flto=8 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu'`

I think its working now?

**Comment by InBetweenNames** [comment]
Does it build if you set `USE=-pgo`?  The ebuilds in this overlay for Python have a special `USE` to enable profile guided optimization training directly from the test suite in Python.  I'm seeing some sandbox violations in your build logs, so I just want to narrow down where the problems might be.

**Comment by fxkrait** [comment]
Yes, I have to build both python 2.7 and 3.6 with `-pgo` for it to build successfully

**Comment by fxkrait** [comment]
Alright, So I rebooted my computer, and now python 2.7.15, 3.7.0 all compile with pgo.
I have no idea what's going on, but it's working now.

Python 3.6.6 does compile, but I do not see a pgo use flag available, so I don't think it has pgo.
Regardless though as long as 3.7 is working, 3.6.6 shouldn't matter.


 

> Installed versions:  2.7.15-r1(2.7)[?](01:36:24 PM 10/02/2018)(bluetooth gdbm ipv6 ncurses `pgo` readline sqlite ssl threads wide-unicode xml -berkdb -build -doc -examples -hardened -libressl -tk -wininst ELIBC="-uclibc") 3.6.6(3.6/3.6m)^t(01:40:01 PM 10/02/2018)(bluetooth gdbm ipv6 ncurses readline sqlite ssl threads xml -build -examples -hardened -libressl -test -tk -wininst) 3.7.0-r1(3.7/3.7m)^t[?](01:22:14 PM 10/02/2018)(bluetooth gdbm ipv6 ncurses `pgo` readline sqlite ssl xml -build -examples -hardened -libressl -test -tk -wininst)

**Comment by fxkrait** [comment]
Alright, So I rebooted my computer, and now python 2.7.15, 3.6.6, 3.7.0 all compile with pgo.
I have no idea what's going on, but it's working now.
The ebuilds in the repo should be fine.

**Comment by fxkrait** [comment]
I think I should have the setup fully functional now.
Thanks @InBetweenNames  and everyone else that helped.
I'll open an a new issue If I run into any problems.

**Comment by InBetweenNames** [comment]
@fxkrait just letting you know I have added the ability to source `make.conf.lto` directly in your `make.conf`.  It should help avoid issues like these.

**Comment by fxkrait** [comment]
Awesome brother. Sounds good.
