### ISSUE TITLE
[Optimization] AutoFDO

### ISSUE THREAD

**Issue by pchome** [InBetweenNames/gentooLTO#150]
I've spent some time for investigating [AutoFDO](https://gcc.gnu.org/wiki/AutoFDO), started from reproducing [AutoFDO/Tutorial](https://gcc.gnu.org/wiki/AutoFDO/Tutorial) experience and then trying to profile more advanced applications. So now I have basic understanding how this feature work, and hope we can discuss/improve/integrate this.

#### Pros
* profile data can be collected using optimized binaries
* do not require additional instrumentation code (PGO)
* profile data can be collected during regular application usage
* no noticeable performance hit by using `perf` tool
* performance benefit near equal to PGO
* profiles can be shared (I suppose) between different systems (and versions?)

#### Cons
* requires additional third-party tools:
    - perf (dev-util/perf) and/or [pmu-tools](https://github.com/andikleen/pmu-tools)
    - [create_gcov](https://github.com/google/autofdo)
* requires additional settings for `perf` to work correctly (may depend on system):
- `# echo "-1" > /proc/sys/kernel/perf_event_paranoid` - for testing, to be able to run commands from regular user
- `CONFIG_DEBUG_FS=y`
* prefers systems with LBR (Last Branch Record),  PEBS (Processor Event-Based Sampling) etc., which is only(?) available on Intel systems
* requires debug symbols (unstripped binary) during profile creation step
* profile data can take noticeable amount of HDD space, depending on collected events/data

#### So, additional steps I need to do to be able reproduce `./sort` example on my AMD system
* <s>`-g3`</s> `-g` flag for unstripped binary
* `-b` and `:pp` `perf` options are not supported by hardware, ignored
*  `-e br_inst_retired.near_taken` not supported/used (since I'm using pure `perf` instead of Intel-specific `ocperf.py`), so I had to find alternative in [BKDG](https://developer.amd.com/resources/developer-guides-manuals/)
    - EventSelect 0C4h Retired Taken Branch Instructions
      `-e cpu/event=0xc4,umask=0x0,name=br_inst_retired_taken/`, also 
      `-e cpu/branch-instructions/` from `perf list` probably suitable
* `-use_lbr=false` for `create_gcov` (and other) tool

#### AutoFDO tutorial example
```sh
# binary for both use/profile purposes 
gcc -march=native -O3 -g3 sort.c -o sort
# collect profile data
perf record -e cpu/event=0xc4,umask=0x0,name=br_inst_retired.taken/ -- ./sort
# generate profile
create_gcov --binary=./sort --profile=perf.data --gcov=sort.afdo -gcov_version=1 -use_lbr=false
# check generated profile (at least function names should be there)
dump_gcov -gcov_version=1 sort.afdo
# optimized binary
gcc -O3 -fauto-profile=sort.afdo sort.c -o sort_autofdo
```

#### I hope investigating this feature is suitable for gentooLTO project, and we can proceed further by
* adding ebuilds for required tools
* investigating the ability to minimization of generated profile data w/o losing profile quality (e.g. using only required events, `perf -F 99` frequency, e.t.c)
* creating an tool to collect profile data and create profiles (maybe even for sharing profiles)
  e.g. `$ afdo-generate ./something` , will create afdo profile in `/var/cache/<category>/<package>-<version>/`, which can be used by  `<category>/<package>[+afdo]`
* describing all required steps in documentation
* e.t.c.

#### More info
* perf: http://www.brendangregg.com/perf.html#EventProfiling
* Intel profiling/optimizations: https://dendibakh.github.io/notes/

**Comment by pchome** [comment]
Additional example for more advanced package, using DXVK under wine (winelib)
```sh
# AutoFDO
so_path=/tmp/lib64
data_path=/var/tmp/dxvk.profile

# Record profile data
perf record -e branch-instructions -o $data_path/dxvk.data  d3d11-triangle.exe

# Create afdo profile
create_gcov --binary=$so_path/d3d11.dll.so --profile=$data_path/dxvk.data --gcov=$data_path/d3d11.dll.so.afdo -gcov_version=1 -use_lbr=false
create_gcov --binary=$so_path/dxgi.dll.so --profile=$data_path/dxvk.data --gcov=$data_path/dxgi.dll.so.afdo -gcov_version=1 -use_lbr=false

profile_merger $data_path/d3d11.dll.so.afdo $data_path/dxgi.dll.so.afdo -output_file=$data_path/dxvk.afdo -gcov_version=1 -use_lbr=false

# Use -fauto-profile=/var/tmp/dxvk.profile/dxvk.afdo
```
but it still too complex (wine, multithreading, ...), failing w/ ICEs during compilation, and produces valid binaries only for `-O0` optimization levels on my system.
Added as example of `profile_merger` tool.

**Comment by pchome** [comment]
Good news, everyone! (c)

* We can have debug symbols in separate files, and portage supports this via `splitdebug` and `compressdebug` FEATURES
  - https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html
  - man make.conf
  - /usr/lib/debug/*

* Intel's `BR_INST_RETIRED.NEAR_TAKEN` have a same(similar) params as for AMD
  - /usr/src/linux/tools/perf/pmu-events/arch/x86/*/pipeline.json
    ```js
    {
            "PEBS": "1",
            "PublicDescription": "This is a precise version (that is, uses PEBS) of the event that counts taken branch instructions retired.",
            "EventCode": "0xC4",
            "Counter": "0,1,2,3",
            "UMask": "0x20",
            "Errata": "SKL091",
            "EventName": "BR_INST_RETIRED.NEAR_TAKEN",
            "SampleAfterValue": "400009",
            "BriefDescription": "Taken branch instructions retired.",
            "CounterHTOff": "0,1,2,3,4,5,6,7"
        },
    ```
   - `UMask` not used for AMD `0xc4` event, so I believe it ignored
   -  `EventName` there only for human readable outputs, so can be anything your want (I hope so)
   - so can be used explicitly for wider range of CPU models/vendors like
      `-e 'cpu/event=0xc4,umask=0x20,name=BR_INST_RETIRED.TAKEN,period=400009/'`

Bad ones (news)
* google's autofdo utils seems not fully support debug symbols in separate files, so may require additional patches/params
* Intel systems may still require `-b` and `:pp` `perf` params, so probably there is no universal command for profile data collection

I'm currently looking into google's autofdo dependencies, and want to create missing ebuilds. Looks like some of them already present in portage tree (`dev-libs/protobuf`,`dev-cpp/gflags`, `dev-cpp/glog`, etc.), while bundled in `autofdo` and [quipper](https://github.com/google/perf_data_converter/tree/master/src) (which also bundling `dev-cpp/gtest` and parts from `perf`).

@InBetweenNames, I'm still waiting for some feedback/reaction, since AutoFDO is a bit different optimization compared to PGO, and may require user interaction. So I'm not fully sure this project is the right place to discuss such sings, and want you to let me know if I'm posting information which will never be used here.

**Comment by pchome** [comment]
I anyone want to play with this: I created [perf2afdo](https://github.com/pchome/perf2afdo) and [perf-gentoo-overlay](https://github.com/pchome/perf-gentoo-overlay), so no need to fetch ~600Mb of data from original google repositories (perf2afdo ~1Mb total), and no need to manually resolve dependencies.

Wrappers:
```sh
$ perf2afdo-record -- ./sort 
Bubble sorting array of 30000 elements
2054 ms
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.156 MB perf.data (3903 samples) ]
```
```sh
$ perf2afdo-create -binary=sort
I1006 19:31:50.584215 23660 perf_reader.cc:798] Number of events stored: 3965
I1006 19:31:50.599323 23660 perf_parser.cc:268] Parser processed: 57 MMAP/MMAP2 events, 2 COMM events, 0 FORK events, 1 EXIT events, 3903 SAMPLE events, 3903 of these were mapped
W1006 19:31:50.601646 23660 module_grouper.cc:60] Cannot read compilation info from binary. Please use -frecord-compilation-info-in-elf when building the binary
```
```sh
$ perf2afdo-dump fbdata.afdo
sort_array total:3107 head:0
  0: 0
  3: 0
  4: 0
  4.3: 0
  7: 0
  1: printf total:0
    2: 0
  6: bubble_sort total:3107
    2: 1
    4: 1063
    5: 1357
    7: 63
    8: 434
    9: 189
```
```sh
$ gcc -march=native -O3 -fgraphite-identity -floop-nest-optimize -flto -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fauto-profile=fbdata.afdo sort.c -o sort_autofdo
$ ./sort_autofdo 
Bubble sorting array of 30000 elements
1426 ms
```

**Comment by InBetweenNames** [comment]
Hi @pchome, finally getting a chance to look at this.  One way I could see this being integrated into the overlay is if we included a portage patch that would basically create wrappers for binaries to run them with `perf2afdo-record`.  For example, instead of installing the binary `firefox` to `/usr/bin/firefox`, we'd install it somewhere else and create wrapper `/usr/bin/firefox` that calls the real binary using `perf2afdo-record`.  Then, next time Firefox is rebuilt, it checks for the `.afdo` associated with that version associated on the system, and if it is present, uses it during the compile.  To the user, this should be a fairly transparent process.  Your thoughts?

On another note, I'm curious if AutoFDO data is unique to the system or if it can be shared with others.  For example, if I build Firefox locally on my Intel hardware using AutoFDO, if that same profile might be of use to someone with AMD hardware.  If so, it may be worthwhile collecting AutoFDO profiles and hosting them in `lto-overlay`, if they aren't too big.  Then we could all benefit from existing profile data collected.  However, if it is affected by things like `-march`, that of course won't be useful.

**Comment by pchome** [comment]
1. I had a thoughts about more automation using locally modified `bashrc.d` wrappers. There is PGO variable  and "creating folders" logic in `bashrc.d` scripts, moreover I have one modified. Nothing more, but I agree this is the way to automation.


2. Yes, may I ask you to create a script and produce data on your side, than someone should reproduce test results running your script (which shall use local data, and then your generated data).

**Comment by pchome** [comment]
Also, may I ask you to adopt `perf2afdo`, it is basically `meson.build` scripts with original sources copied.

**Comment by InBetweenNames** [comment]
For sure, I'd be glad to use it for this.  I wonder if we could implement it in `bashrc.d`.  One thing I'd want to guarantee is that the `emerge --unmerge` processes understand that the wrapper, original binary, and `.afdo` should be removed.

**Comment by InBetweenNames** [comment]
OK -- investigating further.  I think it makes the most sense to have our wrappers make a new profile on each run, and then using `sample_merger` to merge them all into one large profile.  [This issue](https://github.com/google/autofdo/issues/51) seems to have some info relating on how to achieve that.

So, the merge would happen whenever a package rebuild is triggered, and then that merged profile would be used for the executable.

One other thing I need to research: handling multiple executable objects per package.  The tutorials all use just one monolithic executable for everything, but in practice we have shared objects, static archives, other executables... I need to figure out if I can just pass the same profile to all of them, or if they need to be disambiguated somehow.  I see that a flag once existed in Google's fork of GCC, `frecord-compilation-info-in-elf`, to help with this -- it would record the individual TUs, modules, etc to disambiguate cases like these.  However, it seems this option did not make it upstream, which makes me wonder if either it is handled another way internally or if the user is expected to handle this somehow.

**Comment by sjnewbury** [comment]
I suspect the use case for the existing code is very much as described in the tutorials and the Google patch is necessary for this to work.

**Comment by justanerd** [comment]
Is the buildid detection working for you guys because all I get is:
W1106 18:15:48.283656 512936 addr2line.cc:41] File '/usr/libexec/Xorg' has no .debug_info section.                                                                               
W1106 18:15:48.283675 512936 addr2line.cc:41] File '/usr/libexec/Xorg' has no .debug_ranges section.                                                                             
W1106 18:15:48.283679 512936 addr2line.cc:41] File '/usr/libexec/Xorg' has no .debug_line section.

this is with splitdebug

**Comment by pchome** [comment]
@justanerd 
Not for me. See https://github.com/InBetweenNames/gentooLTO/issues/150#issuecomment-427000875 "Bad news" part.

**Comment by pchome** [comment]
The `.gnu_debuglink` section contains `dbg_file_name` and `CRC-32` only, so for `splitdebug` to work with `afdo` --  https://github.com/google/autofdo/blob/master/addr2line.cc#L89 should be able to locate and read debug sections in such files:
* dbg_file_name
* .debug/dbg_file_name
* /usr/lib/debug/path/to/dbg_file_name

For `compressdebug` support: zlib support required and `.zdebug_*` sections names reading (_`Note - if compression would actually make a section larger, then it is not compressed nor renamed.`_).

`man objcopy` for more info (`--add-gnu-debuglink`, `--only-keep-debug` and `--compress-debug-sections=zlib` parts)

**Comment by justanerd** [comment]
I found a workaround. You can use elfutils unstrip like this:
eu-unstrip /bin/zsh /usr/lib/debug/bin/zsh.debug -o zsh
eu-elfcompress -t none zsh
With the generated file you can use create_gcov.

**Comment by 6blender6** [comment]
@pchome I did some tests these days, and I think the biggest problem is how to collecting profile. To generate a good collection of sample profiles, it is necessary to have a robust benchmark that exercises most of the paths of the applications. But some of them have plenty of arguments, and it's hard to do the benchmark like that.

P.S. English is not my native language, please excuse typing errors.

**Comment by wolfwood** [comment]
@6blender6 I agree that representative benchmarking and profiling is a big challenge, however I think autoFDO intends to be a way to manage that difficulty by working even in the absence of total information, and by allowing you to combine multiple profiles even when captured from different binaries.

How good it is at solving those challenges, I don't know, but i think they have the right strategy. maybe we can make it better.

**Comment by 6blender6** [comment]
@wolfwood Actually I'm talking about AutoFDO right now. For example, I need to optimize `xz-utils` with AutoFDO. The first step is building the package with the flags it required (e.g. -g ), and next we need to profiling with perf (`perf record -e br_inst_retired:near_taken -b -o perf.data  -- your_program`), to get the data we'll run it, and we need to give it **stdin**. But how to make sure the **stdin** can exercise most of the paths of the package? After the big challenge, just rebuild the package, and enjoy the high performance.

GCC 9.2 will release next Monday, and we will rebuild the world or something like that. So I think it's the best time to find some solutions regarding AutoFDO/PGO.
