### ISSUE TITLE
dev-qt/qtscript-5.9.6 causes kwin to segfault during runtime when successfully built with LTO

### ISSUE THREAD

**Issue by vkraven** [InBetweenNames/gentooLTO#152]
QT's success rate with LTO is probably already well known, but I'm hoping this might eventually come in handy sometime.

I noticed dev-qt/qtscript-5.10.1 already has build patches and -flto* flags declared in ltoworkarounds.conf. dev-qt/qtscript-5.9.6 builds fine, but causes kwin to segfault during runtime (from gdb trace of kwin crashes).

My workaround was:
`>=dev-qt/qtscript-5.9.6 *FLAGS-=-flto*`

System built with gcc-8.2.0-r2 with pgo. Graphite and -O3/O2 do not seem to affect qtscript / kwin. STRIP_MASK is enabled.

Really enjoying the project and would be happy to help in any way!

**Comment by InBetweenNames** [comment]
Thanks for the report!  I'm not sure if there are many users here using Qt 5.9.6, but I have observed some LTO problems with 5.11.1 at the very least.  I will remove the 5.9.6 patch for now unless someone says that it works fine on their system, which would be worth investigating.
