### ISSUE TITLE
app-cdr/cdrtools-3.02_alpha09 runtime error when built with LTO enabled

### ISSUE THREAD

**Issue by owenthewizard** [InBetweenNames/gentooLTO#154]
`cdrecord -v -speed=52 -sao dev=/dev/sr0 admincd-amd64-20181011T214502Z.iso`
> Cdrecord-ProDVD-ProBD-Clone 3.02a09 (x86_64-pc-linux-gnu) Copyright (C) 1995-2016 Joerg Schilling
TOC Type: 1 = CD-ROM
scsidev: '/dev/sr0'
devname: '/dev/sr0'
scsibus: -2 target: -2 lun: -2
Warning: Open by 'devname' is unintentional and not supported.
Linux sg driver version: 3.5.27
Using libscg version 'schily-0.9'.
cdrecord: SCSI buffer size: 0
: **Unknown error 64512**

[info.txt](https://github.com/InBetweenNames/gentooLTO/files/2476127/info.txt)

No error after unsetting `$FLTO`.

**Comment by InBetweenNames** [comment]
Thanks!
