### ISSUE TITLE
The Connection is Closed

### ISSUE THREAD

**Issue by funghetto** [InBetweenNames/gentooLTO#159]
I decided to awake my secondary machine after more than a year but when compiling @ world with LTO, Graphite etc... I experience some networkmanager/polkit/dbus problems:

> Oct 28 12:54:28 gentoo2 NetworkManager[1981]: <error> [1540727668.6817] auth: could not get polkit proxy: The connection is closed
> Oct 28 12:54:28 gentoo2 NetworkManager[1981]: <warn>  [1540727668.6817] sleep-monitor-sd: failed to acquire D-Bus proxy: The connection is closed
> Oct 28 12:54:28 gentoo2 NetworkManager[1981]: <warn>  [1540727668.6817] firewall: could not connect to system D-Bus (The connection is closed)
> 
> Oct 28 12:54:32 gentoo2 polkitd[1987]: Finished loading, compiling and executing 4 rules
> Oct 28 12:54:32 gentoo2 polkitd[1987]: Lost the name org.freedesktop.PolicyKit1 - exiting
> 
> Oct 28 12:34:53 gentoo2 NetworkManager[1794]: <info> [1540726493.7173] bus-manager: could not connect to the system bus (The connection is closed); only the private D-Bus socket will be available

When compiling the same world set with the default CFLAGS and bdeps everything works, I tried to rebuild systemd, dbus, polkit & networkmanager with the default CFLAGS but same problems.

System specs:

Intel Xeon E5450
Asus P5KPL AM SE
4gb ddr2
Nvidia GTS 250

make.conf:

> CFLAGS="-march=native -O3 ${GRAPHITE} ${FLTO} ${IPA} -fuse-linker-plugin -pipe -mtune=native"
> CXXFLAGS="${CFLAGS}"
> LDFLAGS="${LDFLAGS} -Wl,--hash-style=gnu"
> CHOST="x86_64-pc-linux-gnu"
> IPA="-fipa-pta"
> USE="systemd policykit dbus udisks truetype type1 cleartype corefonts -gallium -classic lm_sensors alsa -bindist -xinerama abi_x86_32 -a52 -bluetooth -cdda -cdr -cups -ppds -spell gtk xvmc nvidia vdpau -gpm pulseaudio networkmanager -consolekit"
> PORTDIR="/usr/portage"
> DISTDIR="${PORTDIR}/distfiles"
> PKGDIR="${PORTDIR}/packages"
> MAKEOPTS="-j4"
> INPUT_DEVICES="libinput"
> VIDEO_CARDS="nvidia"
> GENTOO_MIRRORS="ftp://ftp.uni-erlangen.de/pub/mirrors/gentoo"
> FLTO="-flto=4"
> GRAPHITE="-fgraphite-identity -floop-nest-optimize"
> PORTAGE_NICENESS="19"
> CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 sse4_1 ssse3"
>

**Comment by InBetweenNames** [comment]
Interesting.  I haven't tried LTO with any systemd related config.  From what it looks like, either DBus or polkit is not functioning properly on your system.  Could you post an `emerge --info` dump here?

**Comment by InBetweenNames** [comment]
Ah ha!  I see that FLTO, GRAPHITE, and IPA are defined after your CFLAGS, when they need to be before them in order to have any effect.  This leads me to believe you are compiling with just `-O3` and `-march=native`.  Actually `-march=native` should imply `-mtune=native`.

So, what you are seeing is some case of undefined behaviour that is exposed by `-O3`, likely in a dependency of polkit.

**Comment by funghetto** [comment]
> I see that FLTO, GRAPHITE, and IPA are defined after your CFLAGS, when they need to be before them in order to have any effect

whoops actually I had the IPA ones above and the others bellow, did a full -e world and now everything is working as expected, maybe adding a warning or something about having all those ABOVE the CFLAGS in the make.conf.lto would be great for big noobs like me.

**Comment by InBetweenNames** [comment]
No worries! At least one other person ran into the same problem.  I think I'll end up switching `make.conf.lto` into something that can be sourced directly in your `make.conf` so users can transparently get updates and not worry about the order of the definitions.

**Comment by InBetweenNames** [comment]
Hi @funghetto ,

I went ahead and implemented the ability to source from `make.conf.lto` directly in `master`.  Would you mind trying it out if you get a chance?

**Comment by funghetto** [comment]
It works, good job.
