### ISSUE TITLE
media-gfx/inkscape-0.92.3-r1 fails to build

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#161]
`media-gfx/inkscape-0.92.3-r1` fails to build, even with LTO disabled, and I cannot track which dependency it has requires no LTO.

Full build log:
https://gist.github.com/1d4065634e478ea82e9705f48b5d5923

`emerge --info '=media-gfx/inkscape-0.92.3-r1::gentoo'`:
https://gist.github.com/43c6ed9a5f996a4e700786b11616a58e

`emerge -pqv '=media-gfx/inkscape-0.92.3-r1::gentoo'`:
`[ebuild   R   ] media-gfx/inkscape-0.92.3-r1  USE="cdr dbus exif jpeg lcms nls openmp spell -dia -gnome -imagemagick -inkjar -latex -postscript -static-libs -visio -wpg" PYTHON_TARGETS="python2_7"`

**Comment by InBetweenNames** [comment]
A few things:
* I notice you are using portage-mgorny.  He just accepted my patch for ranlibbing static libraries in that package.  However, do you have that version?  You may need to use `portage-mgorny-9999` or equivalent.  The portage patch in `sys-config/ltoize` currently applies only to `sys-apps/portage`.
* Your CFLAGS are:
`CFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -flto=32-pipe"`
The last item, in particular, seems malformed.  Does this work for sure? You probably meant to add `-pipe` separately.  I'm guessing you have something like this in your `make.conf`:
~~~
...
CFLAGS="-march=native -O3 ${GRAPHITE} ${FLTO}-pipe"
~~~
* Your binutils is a little older.  I don't think it'll matter too much, but I wanted to let you know.
* You're missing the new support for `-fipa-pta`, just letting you know.

Currently I can build inkscape fine without fat-lto.  I haven't tried your pull request yet but I'll try it out in a bit.

**Comment by Althorion** [comment]
* No, I run the stable version. Let me rebuild it and come back to you when ready.
* Yeah, I missed that, thanks. I have no idea how it worked till this day, since I changed `make.conf` over a month ago and rebuild everything at least twice since then…
* Older binutils [were necessary](https://gist.github.com/43c6ed9a5f996a4e700786b11616a58e) when I tried building my system with Clang and I have `-~amd64` for them since—I’m quite scared of removing that, to be honest…
* Thanks, missed that completely.

I’ll make necessary changes to `make.conf`, update the `portage-mgorny`, rebuild the world (I’m not sure if it LTO’d correctly, plus no IPA and I have the server free for the night, which won’t be a case for quite a while starting the day after tomorrow) and come back to you.

**Comment by InBetweenNames** [comment]
Sounds good!  I think you could get away with just using unstable portage-mgorny and doing a deep rebuild for inkscape (and possibly the package in your PR too).  If that fails, then it's full system rebuild time :P

**Comment by Althorion** [comment]
I don’t want to miss on IPA, mostly.

And I seriously doubt that the `exa` will compile with full LTO, since it gives exactly the same errors as `cargo`, which is already on your list. It seems to be a common case with Rust programs, as I see `alacritty` there too.

**Comment by InBetweenNames** [comment]
No worries!  Yeah it looks here like the same thing.  I'll go ahead and accept your other PR.

**Comment by Althorion** [comment]
After a full rebuild, inkscape builds just fine. Thanks for your help.
