### ISSUE TITLE
dev-qt/qtcore-5.11.2-r1 LTO failure

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#167]
using gold. 

this one goes away reliably if I disable LTO:
/etc/portage/package.cflags/myhacks.conf ->
dev-qt/qtcore *FLAGS-=-flto* *FLAGS=-fuse-linker-plugin

[qtcore-build.log](https://github.com/InBetweenNames/gentooLTO/files/2543493/qtcore-build.log)
[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/2543494/emerge-info.txt)

**Comment by InBetweenNames** [comment]
`dev-qt/qtcore` is already blacklisted for LTO -- are you on the latest config?

**Comment by wolfwood** [comment]
wolfwood@BMO ~ $ eix ltoize 
[I] sys-config/ltoize [1]
     Available versions:  (~)0.8.1 (~)0.8.2 (~)0.9.0 (~)0.9.1 {override-flagomatic}
     Installed versions:  0.9.1(03:22:06 PM 11/01/2018)(-override-flagomatic)
     Homepage:            https://github.com/InBetweenNames/gentooLTO
     Description:         A configuration for portage to make building with LTO easy.

[1] "lto-overlay" /var/lib/layman/lto-overlay


but I haven't switched to the new sourcing scheme, could that be the problem?

**Comment by InBetweenNames** [comment]
Looking at your build.log:

> Out of memory  in /var/tmp/portage/dev-qt/qtcore-5.11.2-r1/work/qtbase-everywhere-src-5.11.2/src/corelib/tools/qstring.cpp, line 2148
> terminate called without an active exception

I find this strange since your system clearly has a ton of memory available.  Since `-flto*` is already disabled via your config (confirmed through your build.log), it seems that `-fuse-linker-plugin` is making the difference for you.  Could you try rebuilding with and without this flag, without LTO in both cases, to confirm?  It would be the first I've ever heard of this flag doing anything in non-LTO builds.

**Comment by InBetweenNames** [comment]
The offending line is here in `qstring.cpp`:

~~~
void QString::reallocData(uint alloc, bool grow)
{
    auto allocOptions = d->detachFlags();
    if (grow)
        allocOptions |= QArrayData::Grow;

    if (d->ref.isShared() || IS_RAW_DATA(d)) {
        Data *x = Data::allocate(alloc, allocOptions);
        Q_CHECK_PTR(x);                                            //<------------ line 2148
        x->size = qMin(int(alloc) - 1, d->size);
        ::memcpy(x->data(), d->data(), x->size * sizeof(QChar));
        x->data()[x->size] = 0;
        if (!d->ref.deref())
            Data::deallocate(d);
        d = x;
    } else {
        Data *p = Data::reallocateUnaligned(d, alloc, allocOptions);
        Q_CHECK_PTR(p);
        d = p;
    }
}
~~~

From Qt's documentation: http://doc.qt.io/qt-5/qtglobal.html#Q_CHECK_PTRx
> If pointer is 0, prints a message containing the source code's file name and line number, saying that the program ran out of memory and aborts program execution. It throws std::bad_alloc instead if exceptions are enabled.
> Q_CHECK_PTR does nothing if QT_NO_DEBUG and QT_NO_EXCEPTIONS were defined during compilation. Therefore you must not use Q_CHECK_PTR to check for successful memory allocations because the check will be disabled in some cases.

Indeed, it appears you have the `debug` flag set for qtcore.  Attempting to merge myself using `USE=debug` flag yields no errors, however.  Could you try building without `USE=debug` and seeing if it helps?

**Comment by wolfwood** [comment]
debug is not set, and an explicit `USE=-debug emerge -av qtcore` leads to the same outcome.

but, `dev-qt/qtcore *FLAGS=-fuse-linker-plugin` worked!

**Comment by InBetweenNames** [comment]
Now that's very strange.  What if you lower your parallelizaiton level?  Say, to `-flto=8`?

**Comment by wolfwood** [comment]
still dies with -flto=8

**Comment by InBetweenNames** [comment]
What about lowering your MAKEOPTS -j levels too?

**Comment by wolfwood** [comment]
FLTO="-flto -fuse-linker-plugin"
EMERGE_DEFAULT_OPTS=""
MAKEOPTS=""

still fails

**Comment by InBetweenNames** [comment]
Wow.  I'm actually at a loss right now.  How much memory is in your system?  Given how many cores it has, I figure you probably have at least 64 GB?  And you haven't tweaked the default memory allocator or anything right?  As far as I know, the linker plugin shouldn't be invoked unless `-flto` is in use... 

Recently, I updated the default flags used in GentooLTO.  I added a few goodies like `-fno-semantic-interposition` and `-fipa-pta`, as well as a recommendation for `-falign-functions=32` per a conversation with a Clear Linux developer.  Could you try the latest default flags in your install?  No system rebuild should be necessary from what I can tell, based on your setup.  I'm just trying to rule out every possible option before definitely tying use of the LTO linker plugin with `-fuse-linker-plugin`.

**Comment by pchome** [comment]
Ok, I see they use the "Link-time Code Generation" name for both LTO and [LTCG](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=vs-2017), so `-no-ltcg` option is the correct thing to enable/disable LTO support in Qt.

But, while we need this option disabled, to control LTO flags manually, we also need to apply LTO-specific workarounds used by Qt. Like https://github.com/qt/qtbase/blob/5.11/src/corelib/global/global.pri#L109

I'm going to try this hack with LTO enabled:
```patch
--- a/src/corelib/global/global.pri
+++ b/src/corelib/global/global.pri
@@ -106,7 +106,7 @@
 qtConfig(journald): \
     QMAKE_USE_PRIVATE += journald
 
-gcc:ltcg {
+gcc {
     versiontagging_compiler.commands = $$QMAKE_CXX -c $(CXXFLAGS) $(INCPATH)
 
     # Disable LTO, as the symbols disappear somehow under GCC

```
I hope this should fix missed `qt_version_tag` symbols.

**Comment by pchome** [comment]
@pchome 
> I hope this should fix missed qt_version_tag symbols.

And seems it does. After rebuilding `dev-qt/qtcore` (LTO+above hack) and `dev-qt/qtgui` some random Qt applications are launching w/o errors.

**Note**: I'm still using extra flags hack for `dev-qt/qtcore`
`/etc/portage/package.env/lto`
```
# Missing flags
# ...
# g++ -c -o qlibraryinfo_final.o   -std=c++11 -ffunction-sections  -I/var/tmp/ ....
# ...
# qlibraryinfo_final.o: warning: relocation against `_ZN11QStringListD1Ev' in readonly section `.text._ZN16QLibrarySettings4loadEv'
# qlibraryinfo_final.o: In function `QLibrarySettings::load()':
# qlibraryinfo.cpp:(.text._ZN16QLibrarySettings4loadEv+0x28f): undefined reference to `QStringList::~QStringList()'
# qlibraryinfo.cpp:(.text._ZN16QLibrarySettings4loadEv+0x32e): undefined reference to `QStringList::~QStringList()'
# /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating a DT_TEXTREL in a shared object.
#
dev-qt/qtcore +extra-flags-var
```

`/etc/portage/env/+extra-flags-var`
```
# QtCore cmake/ dir compiled w/ wrong flags
#
# CXXFLAGS = $(EXTRA_CXXFLAGS) $(CONFIG_CXXFLAGS) $(CPPFLAGS)
# LFLAGS = $(EXTRA_LFLAGS) $(CONFIG_LFLAGS)
#
EXTRA_CXXFLAGS="${CXXFLAGS}"
EXTRA_LFLAGS="${LDFLAGS}"
```

**Comment by InBetweenNames** [comment]
@pchome I've tested your patch and I have confirmed it works here!  Before I commit this, I wanted to let you know that I managed to build `dev-qt/qtcore` with and without the `EXTRA_*FLAGS` workaround -- in both cases, it looks like all `*FLAGS` are honoured based on the command lines shown during the build.  Is the workaround still necessary?

**Comment by pchome** [comment]
> Is the workaround still necessary?

I'm not sure, probably not required for recent `dev-qt/qtcore` versions.

Also, I'm not using `gentooLTO` overlay and still have custom overrides/settings, which are likely fixed/handled by `gentooLTO` overlay internally.

Anyway, those flags shouldn't harm, and was there for a long time.

**Comment by InBetweenNames** [comment]
OK thanks -- I will merge your patch into the overlay.  @wolfwood , could you sync with GentooLTO and try the new qtcore workaround?

**Comment by wolfwood** [comment]
[emerge.log.txt](https://github.com/InBetweenNames/gentooLTO/files/2593912/emerge.log.txt)
[build.log](https://github.com/InBetweenNames/gentooLTO/files/2593914/build.log)

still failing.
and with flagomatic-overrides
[build.log](https://github.com/InBetweenNames/gentooLTO/files/2593926/build.log)

**Comment by wolfwood** [comment]
did you disable gold with that patch?

**Comment by wolfwood** [comment]
[build.log](https://github.com/InBetweenNames/gentooLTO/files/2593935/build.log)
fails if I manually switch default to ld.bfd too

**Comment by wolfwood** [comment]
still succeeds with `dev-qt/qtcore *FLAGS=-fuse-linker-plugin`

**Comment by InBetweenNames** [comment]
Okay, it seems that it's qmake itself that's getting the Out of Memory error.

**Comment by wolfwood** [comment]
:sheepish grin:  dev-qt/qtcore *FLAGS **=** -fuse-linker-plugin is _setting_ *FLAGS to -fuse-linker-plugin
it works because it _removes_ some underlying problem flag

using either:
`dev-qt/qtcore *FLAGS-=-march=native`
`dev-qt/qtcore *FLAGS-=-O3`
fixes the problem.

remembering an issue I had in a personal project, I tried:
`dev-qt/qtcore *FLAGS+=-mno-avx512vl`

which also seems to succeed.

I had been under the impression that this bug was fixed in gcc 8.2 (I stopped having to use -mno-avx512vl for my personal project after upgrading) but it seems there is still an issue.

perhaps related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85342 as `*FLAGS-=-O3 *FLAGS+=-O2` also triggues the bug  but `*FLAGS+=-O1` does not

I also noticed this bug about -mavz512vl and C++ type errors which feels really familar. will have to revisit some other package failures... https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70290

**Comment by wolfwood** [comment]
now it looks like every other qt lib, and qt-based application failed to rebuild overnight. 

`dev-qt/* *FLAGS+=-mno-avx512vl` is easy enough for the libs, but is there any way to apply flags to anything that _depends_ on qt?

**Comment by elsandosgrande** [comment]
@wolfwood Is the issue still present, or not?

**Comment by wolfwood** [comment]
@elsandosgrande retested sucessfully without additional workarounds. closing.
