### ISSUE TITLE
sci-electronics/kicad-5.0.0-r1 LTO failure

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#168]
gold linker

goes away with lto disabled

[kicad-build.log](https://github.com/InBetweenNames/gentooLTO/files/2543500/kicad-build.log)
[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/2543501/emerge-info.txt)

**Comment by InBetweenNames** [comment]
Confirmed!  Could you make this into a PR?

**Comment by wolfwood** [comment]
done

**Comment by InBetweenNames** [comment]
Thanks!
