### ISSUE TITLE
app-emulation/looking-glass-1_alpha11 build failure

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#169]
gold. not fixed by simply disabling LTO.

[looking-glass-build.log](https://github.com/InBetweenNames/gentooLTO/files/2543510/looking-glass-build.log)
[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/2543511/emerge-info.txt)

**Comment by InBetweenNames** [comment]
I get the same error.  This is from the `nest` overlay?  It looks to me like it may be a GCC 8 incompatibility, as I can't even build it with `-march=native -O2 -pipe`.

**Comment by wolfwood** [comment]
oh, yeah its from nest.  you're right the macro errors seem like a maybe gcc-8 change in what is tolerated, or maybe it needs something newer than -std=gnu99 ?

**Comment by wolfwood** [comment]
version 1_alpha10 is installed just fine, I just can't upgrade to (~)1_alpha11

**Comment by InBetweenNames** [comment]
Not sure! Are you able to install this package on a system without ltoize installed?

**Comment by InBetweenNames** [comment]
Closing the issue as this is a GCC 8 problem and not a GentooLTO problem

**Comment by wolfwood** [comment]
I was able to reproduce issue on a non-ltoize'd system

**Comment by wolfwood** [comment]
also, it had gcc 6.4.0 ...so lol, code is just broken?

**Comment by gcs-github** [comment]
Well. It is an alpha... for what it's worth, you might want to look into the Makefiles and CMakeLists.txt files in the project. Maybe you'll have better luck with the author's own CFLAGS and LDFLAGS, see for example https://github.com/gnif/LookingGlass/blob/master/client/CMakeLists.txt#L6-L7
