### ISSUE TITLE
LTO patch fails - www-client/torbrowser-60.3.0_p803::torbrowser

### ISSUE THREAD

**Issue by CGretski** [InBetweenNames/gentooLTO#173]
* Applying lto.patch ...
1 out of 1 hunk FAILED -- saving rejects to file security/sandbox/linux/moz.build.rej
1 out of 1 hunk FAILED -- saving rejects to file ipc/app/moz.build.rej
The text leading up to this was:

|diff --git a/ipc/app/pie/moz.build b/ipc/app/pie/moz.build
|index 0247b25b4b11..88ef1905d3c3 100644
|--- a/ipc/app/pie/moz.build
|+++ b/ipc/app/pie/moz.build

No file to patch.  Skipping patch.
1 out of 1 hunk ignored                                                                                                                                                     [ !! ]
 * ERROR: www-client/torbrowser-60.3.0_p803::torbrowser failed (prepare phase):
 *   patch -p1  failed with /var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/www-client/torbrowser/lto.patch

[moz.build.rej.txt](https://github.com/InBetweenNames/gentooLTO/files/2548653/moz.build.rej.txt)
[moz.build.rej-ipc.txt](https://github.com/InBetweenNames/gentooLTO/files/2548661/moz.build.rej-ipc.txt)

**Comment by InBetweenNames** [comment]
Actually, can you compile this without the patch using LTO?  You should be able to just rm the patch from your overlay.

**Comment by InBetweenNames** [comment]
OK -- removed the old patch and used the Firefox settings.  Thanks!
