### ISSUE TITLE
cannot emerge polybar with CMAKE_MAKEFILE_GENERATOR=ninja

### ISSUE THREAD

**Issue by aw1cks** [InBetweenNames/gentooLTO#175]
With ninja: [link](https://pastebin.com/raw/cpt7J0Wg)
With emake: no errors, emerges without problem.
I just created /etc/portage/package.cflags/polybar.conf with "x11-misc/polybar CMAKE_MAKEFILE_GENERATOR=emake". Maybe it's a good idea to add a note like with kinfocenter?

**Comment by aw1cks** [comment]
It's done. See the PR [here](https://github.com/InBetweenNames/gentooLTO/pull/176) :)

**Comment by aw1cks** [comment]
Just an afterthought: given that I have created a new section in ltoworkarounds.conf in my PR, perhaps it would be prudent to remove the note about kinfocenter and simply add it to the file straight away.

**Comment by InBetweenNames** [comment]
Thanks!  I think you did the right thing -- we can move these helpful workarounds into a separate file if we get more than, say, five of them.
