### ISSUE TITLE
thermald failing, needs *FLAGS-=-flto*

### ISSUE THREAD

**Issue by 0rmi** [InBetweenNames/gentooLTO#179]
With LTO disabled it compiles fine, with it, failure. -ffat-lto-objects doesn't help.
emerge --info: https://pastebin.com/x3bLtyfq 
build.log: https://pastebin.com/TKEwqSBx

**Comment by aw1cks** [comment]
After reproducing the issue on my laptop, I created a [PR](https://github.com/InBetweenNames/gentooLTO/pull/180).

**Comment by InBetweenNames** [comment]
Actually, I managed to get it to build with LTO with this:
~~~
sys-power/thermald *FLAGS+=-Wl,--no-fatal-warnings *FLAGS+=-Wno-error
~~~

Could you try this out?

**Comment by 0rmi** [comment]
Works for me. Thanks!

**Comment by InBetweenNames** [comment]
Excellent.  Will use this workaround instead and close the issue.
