### ISSUE TITLE
Redefinition of set 'toolchain' (sections: 'usersets', 'lto-overlay sets') 

### ISSUE THREAD

**Issue by InBetweenNames** [InBetweenNames/gentooLTO#18]
Looks like the toolchain set we added recently has a name clash--we should probably rename this to something else or perhaps look at using the existing toolchain set.  See this thread:

https://forums.gentoo.org/viewtopic-p-8119934.html#8119934

**Comment by InBetweenNames** [comment]
Also the @toolchain set has `sys-devel/binutils-libs` instead of `sys-libs/binutils-libs`

**Comment by mgomersbach** [comment]
Ah my fault, I added that because I missed in my tc set. sorry for that.

**Comment by mgomersbach** [comment]
Also I cannot reproduce that "redefinition of "toolchain"" here. Maybe the user reporting has created one himself?

**Comment by mgomersbach** [comment]
Also "careful, you could break portage!"...
Actually we are going to bend it a lot. Intentionally ;P

**Comment by InBetweenNames** [comment]
No worries!  I think I've made pretty clear in the README that people should expect bugs and breakage :P at least for the short while

Perhaps we could prefix our set names with "ltooverlay_" or something as a crude form of namespacing?

And yes, just wait until we start patching Portage... lol
