### ISSUE TITLE
eix-sync can't source make.conf.lto

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#182]
I use eix-sync which is an emerge --sync wrapper that updates  the eix db andoutputs a diff of what was fetched. when it first runs it outputs a message saying: **failed to source make.conf.lto**

```
wolfwood@BMO ~ $ sudo eix-sync               
/etc/portage/make.conf: failed to source make.conf.lto (cannot read file make.conf.lto)
 * Running emerge --sync                                                                    
>>> Syncing repository 'gentoo' into '/usr/portage'...
 * Using keys from /usr/share/openpgp-keys/gentoo-release.asc                                                                                                                                                      
 * Refreshing keys from keyserver ...                                                                                                                                                                        [ ok ]
>>> Starting rsync with rsync://91.186.30.235/gentoo-portage...
>>> Checking server timestamp ...   
```

I'm guessing its either because its a symlink, or its a permissions issue.

**Comment by The-Bishop** [comment]
another workaround for this is `cd /etc/portage && sudo eix-sync`.

**Comment by wolfwood** [comment]
I guess I'l do the cd for now and open an issue upstream, thanks @The-Bishop

**Comment by wolfwood** [comment]
this was addressed by upstream in https://github.com/vaeth/eix/issues/57

the author mentions feeling having the files in a directory and sourcing said directory might be a 'more correct' way to handle sourcing make.conf.lto and make.conf.lto.defines, but in this case the use needs to rename to symlink for make.conf.lto to get the defines only behavior

feel free to close, thanks.

**Comment by InBetweenNames** [comment]
Yeah, I had similar thoughts.  Perhaps I'll refactor the configurations after I put together the GentooLTO usage report, and I'll tell users to use absolute sourcing instead.

**Comment by InBetweenNames** [comment]
#307 should help fix this

**Comment by wolfwood** [comment]
it would, although vaerth already fixed eix. we can close this.

**Comment by InBetweenNames** [comment]
Thanks!
