### ISSUE TITLE
app-admin/localepurge is now masked in portage

### ISSUE THREAD

**Issue by cb88** [InBetweenNames/gentooLTO#185]
```
# required by app-portage/portage-bashrc-mv-15.0::mv
# required by sys-config/ltoize-0.9.1::lto-overlay
# required by @selected
# required by @world (argument)
# /usr/portage/profiles/package.mask:
# Pacho Ramos <pacho@gentoo.org> (11 Nov 2018)
# Unmaintained for years, buggy (#183273, #491010, #605544). You can rely on
# INSTALL_MASK to skip unwanted locales and install only foo locale:
# INSTALL_MASK="/usr/share/locale -/usr/share/locale/foo"
# Removal in a month.
=app-admin/localepurge-0.5.4-r2
```

**Comment by InBetweenNames** [comment]
GentooLTO depends only on `app-portage/portage-bashrc-mv[cflags]` -- it does not depend on any locale purging machinery.  This is an issue that should be filed in the `mv` overlay.

**Comment by cb88** [comment]
https://github.com/vaeth/mv-overlay/issues/7

I'll close this as soon as I get home and check that is working this evening. I did check yesterday so... I'm not sure if there is an issue somewhere since my mv overlay should have already had that fix.

**Comment by InBetweenNames** [comment]
No worries!

**Comment by cb88** [comment]
Just synced and "emerge -uDNa"-ed no issues... so must have been my mv overlay was out of sync.
