### ISSUE TITLE
issues with CFLAGS and the double-option-reduction

### ISSUE THREAD

**Issue by The-Bishop** [InBetweenNames/gentooLTO#186]
since i enabled gentooLTO, my CFLAGS get mangled so that merging of any package fails.

i use to have a very long list of CFLAGS, and they do not contain doubled options, but double words. i will strip my example to the bare minimum to make my point.

before activating "source make.conf.lto":
in make.conf:
`NTHREADS="5"`
`#source make.conf.lto`
`CFLAGS="--param l1-cache-size=32 --param l1-cache-line-size=64 ${CFLAGS}"`
building some package like "ccache" succeeds and its "config.log" contains:
`configure:2881: checking whether the C compiler works`
`configure:2903: x86_64-pc-linux-gnu-gcc --param l1-cache-size=32 --param l1-cache-line-size=64 -Wl,-O1 -Wl,--as-needed  -Wl,-O1 -Wl,--as-needed conftest.c  >&5`

now, when i try with gentooLTO, my make.conf reads:
`NTHREADS="5"`
`source make.conf.lto`
`CFLAGS="--param l1-cache-size=32 --param l1-cache-line-size=64 ${CFLAGS}"`
the build fails and in "config.log" i read:
`configure:2881: checking whether the C compiler works`
`configure:2903: x86_64-pc-linux-gnu-gcc --param l1-cache-size=32 --param l1-cache-line-size=64 -O3 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -flto=5 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed  -Wl,-O1 -Wl,--as-needed --param l1-cache-size=32 l1-cache-line-size=64 -O3 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -flto=5 -fuse-linker-plugin conftest.c  >&5`
`x86_64-pc-linux-gnu-gcc: error: l1-cache-line-size=64: No such file or directory`

so, the option filter clearly happens somewhere in gentooLTO and i have no clue where to look. the problem here is obviously the space between "--param" and the parameter value, for that the second "--param" is deduplicated in error.

besides, all the CFLAGS are doubled anyway, so the deduplication seems of limited value here.

**Comment by ionenwks** [comment]
I don't use the overlay itself (mostly use it as a very helpful reference), but reading comments I believe CFLAGS gets automatically included in LDFLAGS for LTO purposes (thus duplicated), and params isn't valid there I believe, thus leading to link time errors.

That aside, if it is, I'm personally not sure why the inclusion in LDFLAGS is still done though, the full optimization options get saved in the .o files and can be read by the linker without them being on the command line. I believe it __used__ to be a problem. I can do something like `gcc -flto -O3 -o test.o -c test.c` with a test.c that has some room for optimization, then `gcc -o test test.o` will give the same binary as `gcc -flto -O3 -o test test.o`

**Comment by pchome** [comment]
`--param=l1-cache-size=32`

**Comment by InBetweenNames** [comment]
This is actually caused by `portage-bashrc-mv`!  @ionenwks I recall GCC explicitly supporting different compile time and link time optimization options -- for example, you can do `-Os` on your object files and do `-O3` at link time.  Has this behaviour been deprecated or removed?  It's actually quite hard to find docs on this and often times I find myself reading the sources to get the answers.

**Comment by The-Bishop** [comment]
@InBetweenNames i did test it, `--param=...` works out und does not suffer the deduplication problem.
THX to @pchome for the tip!
