### ISSUE TITLE
dev-lang/R-3.5.1 requires *FLAGS-="${IPA}"

### ISSUE THREAD

**Issue by jelinekto** [InBetweenNames/gentooLTO#188]
[build.log](https://github.com/InBetweenNames/gentooLTO/files/2584972/build.log)

[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/2584974/emerge-info.txt)

**Comment by InBetweenNames** [comment]
Confirmed -- Could you make a PR for this?

**Comment by InBetweenNames** [comment]
Merged -- thanks!
