### ISSUE TITLE
Claim IRC channel

### ISSUE THREAD

**Issue by mgomersbach** [InBetweenNames/gentooLTO#19]
Any of you people interested to gather on IRC as well?

**Comment by InBetweenNames** [comment]
Absolutely!  I was actually looking at ways to add a "forum" on github.  I think either approach would be a great way to discuss ideas, etc, as the issue tracker is rather limited and forces a "binary" decision where the reality is a little more gradient.  I have never actually admined an IRC channel before but I would be willing to learn.

**Comment by darkbasic** [comment]
I think that gathering the technical discussions on the tracker would be a better idea while the project is so small, anyway IRC could be useful as well.

**Comment by InBetweenNames** [comment]
If we do IRC, is there a way for us to keep the conversation "running" when people are logged out?  It would be nice for people to be able to hop in and out of the channel and search through the chat logs.  If not IRC, are there any good open source approaches that let us do that?

**Comment by mgomersbach** [comment]
For claiming a channel: http://freenode.net/news/registering-a-channel-on-freenode
We can setup a logbot: https://github.com/globau/logbot (or another)

**Comment by darkbasic** [comment]
What about something more modern like slack or gitter? Or do you think that Gentoo users would prefer the old way?

**Comment by preney** [comment]
If log history is valued, Slack costs money if one wants to keep the logs around above a certain number of log entries (otherwise they are overwritten).

**Comment by mgomersbach** [comment]
https://gitter.im/ Seems to fulfill the requirements I've seen? Have not tried it yet myself.

**Comment by InBetweenNames** [comment]
Actually I just opened up a Freenode channel per your suggestion -- the channel is ##gentoolto (I would have used #gentoolto but I don't want to step on the toes of any official Gentoo devs :P )  Going to add it to the README shortly.  I also sent in a request to the botbot.me site to log the IRC chats.
