### ISSUE TITLE
dev-scheme/guile (2.2.3) fails to build with LTO

### ISSUE THREAD

**Issue by The-Bishop** [InBetweenNames/gentooLTO#193]
`*FLAGS+=-ffat-lto-objects` was not enough, so had to use the big knife to cut out LTO alltogether to make the package build.

PR adds `*FLAGS-=-flto*` to `sys-config/ltoize/files/package.cflags/ltoworkarounds.conf`

**Comment by InBetweenNames** [comment]
Thanks!
