### ISSUE TITLE
New portage version fails to apply lto.patch

### ISSUE THREAD

**Issue by mateuszmandera** [InBetweenNames/gentooLTO#199]
This happens when trying to upgrade to sys-apps/portage-2.3.52

[lto.patch.out](https://github.com/InBetweenNames/gentooLTO/files/2594838/lto.patch.out.log)

lto.patch seems to need updating for this portage version.

**Comment by ionenwks** [comment]
It doesn't, it needs removing. Portage applied the same patch upstream, so now it's trying to apply the fix over something already fixed.

**Comment by InBetweenNames** [comment]
This is excellent news!  Thanks to everyone who tested this patch.  I have updated the README as well.
