### ISSUE TITLE
dev-java/openjdk fails to build with LTO

### ISSUE THREAD

**Issue by mateuszmandera** [InBetweenNames/gentooLTO#204]
With *FLAGS-=-flto* it builds fine.

[build.log](https://github.com/InBetweenNames/gentooLTO/files/2625821/build.log)
[emerge-info.log](https://github.com/InBetweenNames/gentooLTO/files/2625828/emerge-info.log)

**Comment by InBetweenNames** [comment]
I have actually been having trouble with the openjdk packages recently.  Unfortunately, I'm preparing for my thesis proposal on December 3rd, so I won't be able to investigate any issues until then.  I can review pull requests at least, if they are simple.

**Comment by aphypnise** [comment]
Can confirm, tried with -ffat-lto-objects but it's uniquely without LTO that the compilation works. I'm going to send a PR.

**Comment by InBetweenNames** [comment]
Reproduced and merged the PR.  Thanks!
