### ISSUE TITLE
ltoize feature request...

### ISSUE THREAD

**Issue by preney** [InBetweenNames/gentooLTO#21]
Could the ltoize package produce "pre-merge" messages and "post-merge" messages to inform the user of important items?

"Premerge" messages are in these (e.g., see pkg_pretend()):
- dev-lang/nqp-2017.08
- dev-lang/rakudo-2017.08

"Postmerge" messages are in these:
- dev-db/postgresql-9.6.5 , e.g., see pkg_postinst()

**Comment by InBetweenNames** [comment]
Hi @preney , could you provide some examples of the kinds of messages you'd like to see as part of the emerge process?
