### ISSUE TITLE
portage-2.3.53-r1 fails to patch

### ISSUE THREAD

**Issue by bemeurer** [InBetweenNames/gentooLTO#216]
Logs & info:
`emerge --info '=sys-apps/portage-2.3.53-r1::gentoo'`: https://paste.pound-python.org/show/SBEic2FQBR61jWdEwo9h/
`emerge -pqv '=sys-apps/portage-2.3.53-r1::gentoo'`: https://paste.pound-python.org/show/FyKh5Xh0VDJVg0jz05mx/
`cat /var/tmp/portage/sys-apps/portage-2.3.53-r1/temp/environment`: https://paste.pound-python.org/show/YzWEjJFFGhCE4daX8VaH/
`cat /var/tmp/portage/sys-apps/portage-2.3.53-r1/temp/build.log`: https://paste.pound-python.org/show/zgnSdvJPSWTjX4pYLihl/

**Comment by funghetto** [comment]
> Portage applied the same patch upstream, so now it's trying to apply the fix over something already fixed.
https://github.com/InBetweenNames/gentooLTO/issues/199#issuecomment-439871287

**Comment by bemeurer** [comment]
@funghetto What exactly should I do? The README tells me to remove a variable from my make.conf that does not exist and to make sure I have a recent version of portage, which I do. Still it attempts to apply the patch.

**Comment by bemeurer** [comment]
Changing to `portage-mgorny` seems to work around this.

**Comment by InBetweenNames** [comment]
~~~
[31;01m*[0m Failed Patch: lto.patch !
 [31;01m*[0m  ( /var/db/repos/lto-overlay/sys-config/ltoize/files/patches/sys-apps/portage/lto.patch )
 [31;01m*[0m 
 [31;01m*[0m Include in your bugreport the contents of:
 [31;01m*[0m 
 [31;01m*[0m   /var/tmp/portage/sys-apps/portage-2.3.53-r1/temp/lto.patch.out

~~~

sys-apps/portage shouldn't have any patches from LTO overlay.  Are you sure it's synchronized?

**Comment by bemeurer** [comment]
@InBetweenNames Turns out the problem was eselect repository defaulting to the Gentoo mirrors, which weren't up to date!
