### ISSUE TITLE
sys-apps/fwupd Does not work with LTO

### ISSUE THREAD

**Issue by bemeurer** [InBetweenNames/gentooLTO#225]
I had to build `fwupd` with the following options (no LTO) for it to work properly
```
CFLAGS="-march=native -O3 ${SEMINTERPOS} ${GRAPHITE} ${IPA} -pipe -falign-functions=32"
CXXFLAGS="${CFLAGS}"
LDFLAGS="${LDFLAGS} -Wl,--hash-style=gnu"
```
Otherwise it fails it start and all it's commands fail to execute properly.

**Comment by InBetweenNames** [comment]
Would you mind making a PR for this?

**Comment by bemeurer** [comment]
@InBetweenNames Done!
