### ISSUE TITLE
dev-python/grpcio Fails to build with LTO

### ISSUE THREAD

**Issue by bemeurer** [InBetweenNames/gentooLTO#229]
Package fails during linking, disabling LTO fixes it.

**Comment by pchome** [comment]
```diff
--- a/setup.py
+++ b/setup.py
@@ -174,7 +174,7 @@
         ' -static-libgcc -static-libstdc++ -mcrtdll={msvcr} '
         '-static'.format(msvcr=msvcr))
   if "linux" in sys.platform:
-    EXTRA_ENV_LINK_ARGS += ' -Wl,-wrap,memcpy  -static-libgcc'
+    EXTRA_ENV_LINK_ARGS += ' -static-libgcc'
 
 EXTRA_COMPILE_ARGS = shlex.split(EXTRA_ENV_COMPILE_ARGS)
 EXTRA_LINK_ARGS = shlex.split(EXTRA_ENV_LINK_ARGS)
```

**Comment by bemeurer** [comment]
@InBetweenNames Should we add that patch to ltoize?

**Comment by InBetweenNames** [comment]
@bemeurer does @pchome 's patch work on your system?  If so, I think we should use that instead of no-lto.

**Comment by bemeurer** [comment]
@InBetweenNames I haven't had a chance to try, my laptop broke (currupt BIOS) last night. It might be a few days until I can test it :(

**Comment by bemeurer** [comment]
@pchome Do you know / can you explain why do those extra link args cause LTO to fail?

**Comment by pchome** [comment]
https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/wrap_memcpy.cc

**Comment by bemeurer** [comment]
@pchome Aha!

**Comment by InBetweenNames** [comment]
@bemeurer no worries!

**Comment by bemeurer** [comment]
I'm back! How can I test that patch?

**Comment by pchome** [comment]
@bemeurer 
> How can I test that patch?

Are you kidding?

Well, you can either:
* modify ebuild w/ appropriate `sed` to replace the string
* modify ebuild w/ the patch in the `files/` dir
* modify overlay 
* drop the patch into `/etc/portage/patches/dev-python/grpcio/`
* ... use patched sources, https://github.com/grpc/grpc fork, `patch -p1 < this.patch` ...

**Comment by bemeurer** [comment]
@pchome I wasn't; I've just only recently moved to Gentoo; thanks for the info! I dropped the patch in `/etc/portage/patches/...` and am testing it now. Cheers!

**Comment by bemeurer** [comment]
I can confirm the patch works!

**Comment by InBetweenNames** [comment]
Perfect.  It has been committed.  Thanks @pchome and @bemeurer !

**Comment by wolfwood** [comment]
patch is now failing to apply on grpcio 1.24.3, but I can't figure out why its trjected. tried changing the line number to 200, but still fails.
