### ISSUE TITLE
media-sound/pulseaudio LTO support

### ISSUE THREAD

**Issue by pchome** [InBetweenNames/gentooLTO#23]
`$ echo "lt_cv_sys_$(grep -o "^global_symbol_pipe=.*$" /usr/bin/libtool)"`
**`lt_cv_sys_global_symbol_pipe="sed -n -e 's/^.*[  ]\\([ABCDGIRSTW][ABCDGIRSTW]*\\)[       ][      ]*\\([_A-Za-z][_A-Za-z0-9]*\\)\$/\\1 \\2 \\2/p' | sed '/ __gnu_lto/d'"`**

`$ echo "lt_cv_sys_$(grep -o "^global_symbol_to_cdecl=.*$" /usr/bin/libtool)"`
**`lt_cv_sys_global_symbol_to_cdecl="sed -n -e 's/^T .* \\(.*\\)\$/extern int \\1();/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \\(.*\\)\$/extern char \\1;/p'"`**

According to bug https://bugs.freedesktop.org/show_bug.cgi?id=99675#c3 local `libtool` differs from `/usr/bin/libtool`.
Can be fixed by simply adding this variables to **env/** for `pulseaudio` or even to `make.conf` if there is other packages affected.

**Comment by mgomersbach** [comment]
Correct me if I'm wrong but looking at that car is not 'simply setting'. To be honest this should be fixed upstream instead?

**Comment by pchome** [comment]
I'm not sure whom this should be fixed by, but this definitely happened during configure phase.
`  checking command to parse gcc-nm output from x86_64-pc-linux-gnu-gcc object... failed`
(`gcc-nm` here is $NM and `x86_64-pc-linux-gnu-gcc` also taken from corresponding variable)

Can be found by searching `symbol_pipe` in `/var/tmp/portage/media-sound/pulseaudio-11.0/work/` for example.
```
config.status
libtool
configure
ltmain.sh
libtool.m4
```
(excluding logs and outputs)

Almost everything (or even everything)  from this list is generated.

**Comment by pchome** [comment]
> When building on some GNU/Linux systems for multilib targets libtool sometimes guesses the wrong paths that the linker and dynamic linker search by default. If this occurs for the dynamic library path, you may use the LT_SYS_LIBRARY_PATH environment variable to adjust. Otherwise, at configure time you may override libtool’s guesses by setting the autoconf cache variables lt_cv_sys_lib_search_path_spec and lt_cv_sys_lib_dlsearch_path_spec respectively.

https://www.gnu.org/software/libtool/manual/html_node/Configure-notes.html

so overriding that `lt_cv_sys_` variables is not big deal, they are there for this

**Comment by pchome** [comment]
from pulseaudio-11.1.ebuild:
```
# hack around unnecessary checks
# (results don't matter, we're not building anything using it)
ac_cv_lib_ltdl_lt_dladvise_init=yes
```

so some ebuilds already contains `cache variables` (?) overrides
maybe can be fixed in ebuild

**Comment by InBetweenNames** [comment]
This is interesting and definitely an upstream bug.  I wonder if perhaps we could install something in `/etc/patches` to fix this.  I tried a quick hack, just copying `/usr/bin/libtool` into the build directories (replacing the build `libtool`) and it worked perfectly fine.
