### ISSUE TITLE
qtcore-5.11.3-r2 fails to build

### ISSUE THREAD

**Issue by prototype99** [InBetweenNames/gentooLTO#232]
[dev-qt:qtcore-5.11.3-r2:20190118-141329.log](https://github.com/InBetweenNames/gentooLTO/files/2773271/dev-qt.qtcore-5.11.3-r2.20190118-141329.log)
the relevant part appears to be
` [32;01m*[0m Applying lto.patch ...
1 out of 1 hunk FAILED -- saving rejects to file src/corelib/global/global.pri.rej`

**Comment by monoidic** [comment]
Unless I'm mistaken, newer versions of ltoize use a bashrc.d hook to apply LTO patches rather than sticking symlinks in /etc/portage/patches/ (/etc/portage/bashrc.d/41-lto-patch.sh)
Simply removing the patch/symlink from patches/ should work.

**Comment by prototype99** [comment]
ahhh yes that done the trick nicely. generally if i want a patch i try to keep things neat by putting it in an ebuild, so presumably that means all the patches in that folder are from here, would it be best to clear all of them to mitigate potential future issues from cropping up?

**Comment by monoidic** [comment]
You can use patches/ for "local patches" without having to edit any ebuilds (as long as they're on a new enough EAPI/have eapply_user, anyway). Though if you haven't added any patches there yourself, then there should probably only be the ones added by earlier versions of ltoize, which you can get rid of.
