### ISSUE TITLE
sys-apps/systemd systemd-boot EFI application hangs / crashes on boot if linked with gold

### ISSUE THREAD

**Issue by zhuyifei1999** [InBetweenNames/gentooLTO#237]
I've reported the issue upstream on systemd/systemd#11541, but so far it's not apparent on how to get it fixed. While it's being fixed upstream, I wonder if gentooLTO project should force the EFI application being linked with BFD, considering (I think) gentooLTO users are more likely than 'ordinary gentoo users' to set system default linker as gold. :)

The patch I'm using to force BFD linking is:
```diff
diff --git a/src/boot/efi/meson.build b/src/boot/efi/meson.build
index 9c0ae5ace..8cd3751b6 100644
--- a/src/boot/efi/meson.build
+++ b/src/boot/efi/meson.build
@@ -39,7 +39,7 @@ if conf.get('ENABLE_EFI') == 1 and get_option('gnu-efi') != 'false'
         endif
         efi_ld = get_option('efi-ld')
         if efi_ld == ''
-                efi_ld = find_program('ld', required: true)
+                efi_ld = find_program('ld.bfd', required: true)
         endif
         efi_incdir = get_option('efi-includedir')
 

```

I did not test sys-boot/systemd-boot. It could be affected as well.

**Comment by zhuyifei1999** [comment]
Fixed upstream

**Comment by javashin** [comment]
happening here how it gets fixed ?

**Comment by zhuyifei1999** [comment]
https://github.com/systemd/systemd/commit/2f92b1e99a8343248fba2118793f754bac2b50c7

**Comment by javashin** [comment]
fixed building systemd with no lto and linker bfd thanks
