### ISSUE TITLE
ld.gold required for LTO on dev-db/mysql[jemalloc]

### ISSUE THREAD

**Issue by gcs-github** [InBetweenNames/gentooLTO#239]
## Summary

I'm reporting this as a way to document that dev-db/mysql[jemalloc] can crash if compiled with LTO through ld.bfd. Removing LTO on ld.bfd fixes the issue. Compiling with LTO on ld.gold fixes the issue.

## Recommendations

It suggests that LTO might generally work better with ld.gold. Unless I missed it, I haven't seen it documented here, and it could be worth it to recommend that ld.gold be used with this overlay by default.

Alternatively, we could also add an entry in ltoworkarounds.conf to force the usage of ld.gold for dev-db/mysql. It could also be worth it to revisit #121 similarly.

## Original Issue

Problem originally noticed on dev-db/mysql-5.7.25 compiled with jemalloc support, with the following toolchain:
* sys-devel/gcc-8.2.0-r6
* sys-devel/binutils-2.31.1-r3
* sys-libs/glibc-2.28-r5
* dev-libs/jemalloc-5.1.0

Segfault log sample on a test database:
```
21:13:40 UTC - mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
Attempting to collect some information that could help diagnose the problem.
As this is a crash and something is definitely wrong, the information
collection process might fail.

key_buffer_size=33554432
read_buffer_size=262144
max_used_connections=0
max_threads=100
thread_count=0
connection_count=0
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 3336506 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0 thread_stack 0x40000
/usr/sbin/mysqld(my_print_stacktrace+0x36)[0x7137cb2b76]
/usr/sbin/mysqld(handle_fatal_signal+0x38a)[0x713818f57a]
/lib64/libc.so.6(+0x396e0)[0x3ceaee626e0]
/usr/lib64/libjemalloc.so.2(+0x1875f)[0x3ceaebc775f]
/usr/lib64/libjemalloc.so.2(+0x18f11)[0x3ceaebc7f11]
/lib64/libpthread.so.0(+0x73f1)[0x3ceaee0d3f1]
/lib64/libpthread.so.0(+0x8464)[0x3ceaee0e464]
/lib64/libc.so.6(clone+0x3f)[0x3ceaef305af]
```

**Comment by gcs-github** [comment]
Just stumbled upon a news item intimating that relying on ld.gold might be a bad idea in terms of being future-proof: https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1082277-gnu-s-gold-linker-is-stagnating-fedora-looking-to-punt-it-off-into-a-separate-package

**Comment by barolo** [comment]
Yeah, just switched back to bfd. There is also lld when it comes to stuff compiled with clang  [ firefox upstream switched to it and as of current release gcc with pgo/lto fails to compile properly for me now ]

**Comment by gcs-github** [comment]
Closing, as this is no longer happening, on a system compiled fully on ld.bfd with a newer toolchain (GCC 8.3.0 + binutils 2.32).
