### ISSUE TITLE
net-misc/dhcp LTO support

### ISSUE THREAD

**Issue by pchome** [InBetweenNames/gentooLTO#24]
Please check `net-misc/dhcp`, seems it's ok w/ `graphite` and `lto`.

Since it contains `*.a` :
```
...
# Uncomment if you have problems with packages depends on net-misc/dhcp
# net-misc/dhcp lto/ltofat.conf
...
```
something like this can be added to workarounds

**Comment by InBetweenNames** [comment]
Getting a `lto1: fatal error: multiple prevailing defs for ‘dhcp_type_interface`, and a number of other ODR violations.  What version is your GCC?  On my system, I can confirm Graphite works fine.

**Comment by pchome** [comment]
gcc 7.2.0
maybe `net-misc/dhcp -server` use flag did the trick

**Comment by InBetweenNames** [comment]
I'll leave this as no-lto but leave a comment in about using `USE=-server` .  Thanks!
