### ISSUE TITLE
GentooLTO with musl libc

### ISSUE THREAD

**Issue by NexusAlpha** [InBetweenNames/gentooLTO#240]
So I tried adding GentooLTO on my musl based installation and it breaks a lot of packages. Several won't compile, others compile but don't work. And around 40% compile and work without problems. The make.conf doesn't even have an LDFLAGS option but FC- and FFLAGS. I don't really know how to start solving this problem because I haven't found any info regarding LTO on musl.

**Comment by NexusAlpha** [comment]
EDIT: Removing ${FLTO} but keeping all other optimizations solved the errors. So it's a problem with LTO somewhere.

**Comment by NexusAlpha** [comment]
Turns out my installation ignores package.cflags for some reasons. Because setting something like *FLAGS-=-flto* on a package and then reemerging it results in the package still trying to use -flto despite the given change.

**Comment by wolfwood** [comment]
you gotta do *FLAGS-=-flto , the wild card matches CFLAGS, CXXFLAGS and
LDFLAGS.

FLAGS isn't a variable used by portage.

**Comment by NexusAlpha** [comment]
GitHub converted the two * and made the letters italic so I indeed meant *FLAGS. And even all other packages listet ltoworkaround.conf are ignored. It behaves like this file doesn't exist.

**Comment by NexusAlpha** [comment]
Re-emerged portage-bashrc-mv. Works now. Strange why it didn't work before.
