### ISSUE TITLE
dev-libs/protobuf-3.6.1 fails at runtime

### ISSUE THREAD

**Issue by kryptt** [InBetweenNames/gentooLTO#243]
Apparently protobuf currently doesn't work with -flto enabled.

I believe the upstream bug is: 
[protobuf#4958](https://github.com/protocolbuffers/protobuf/issues/4958)

and the workaround was:
`=dev-libs/protobuf-3.6.1 *FLAGS-=-flto*`

**Comment by InBetweenNames** [comment]
Fixed, thanks!
