### ISSUE TITLE
sys-libs/musl doesn't compile with -flto

### ISSUE THREAD

**Issue by NexusAlpha** [InBetweenNames/gentooLTO#244]
Compiling with -ffat-lto-objects doesn't work either. Only when compiling without -flto.

**Comment by InBetweenNames** [comment]
Strange -- I've used musl on my router in LTO mode.  I'll have to look into this...

**Comment by Kokokokoka** [comment]
I can confirm this on both clang and gcc LTO

**Comment by InBetweenNames** [comment]
Confirmed.  I was mistaken previously.  I'll add a workaround.

**Comment by Promaethius** [comment]
I've just run into this same problem while cross compiling for embedded targets using `crossdev`
