### ISSUE TITLE
media-libs/x264-0.0.20190214 needs LTO patch bump

### ISSUE THREAD

**Issue by monoidic** [InBetweenNames/gentooLTO#247]
This version still appears to fail on the endianness check, but simply using the old patch appears to fix it. 
I think this could simply be moved into the ltoize patches and away from its own seperate ebuild as well, unless the blocker on certain configurations of app-emulation/emul-linux-x86-medialibs is still relevant.

**Comment by bemeurer** [comment]
@InBetweenNames Pinging because this is breaking world updates

**Comment by InBetweenNames** [comment]
Sorry it took so long to get to this -- life's been real hectic lately.  I've migrated both the x264 and x264-encoder LTO patches to using the LTO-overlay patching mechanism introduced previously.  I tested with both old and new versions and it seems to work just fine.  Hopefully this should help with the world update woes!
