### ISSUE TITLE
dev-qt/qtcore-5.11.3-r2 LTO build failure

### ISSUE THREAD

**Issue by Gurgel100** [InBetweenNames/gentooLTO#250]
Fails at linking stage

It works when compiling without 
lto. I also tried to compile with `-ffat-lto-objects` but it also doesn't link.

There is also a bug in the [gentoo bugzilla](https://bugs.gentoo.org/633930).

I saw that lto is already deactivated for qtcore but the line is commented out. So a fix would be to enable this line again for this version.

[build.txt](https://github.com/InBetweenNames/gentooLTO/files/2896437/build.txt)
[emerge_info.txt](https://github.com/InBetweenNames/gentooLTO/files/2896438/emerge_info.txt)

**Comment by pchome** [comment]
`$ cat /var/db/pkg/dev-qt/qtcore-5.11.3-r2/CFLAGS`
```
-march=native -O3 -pipe -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -fipa-pta -flto=3 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu
```

**Comment by Gurgel100** [comment]
Sorry just remembered that I was using gcc 7.3.0 which is not supported. Sorry for the bug report.

**Comment by InBetweenNames** [comment]
Marked as resolved.  Thanks!
