### ISSUE TITLE
net-mail/mailutils fails to build with USE=-ldap because of workaround

### ISSUE THREAD

**Issue by rx80** [InBetweenNames/gentooLTO#262]
Following workaround added -llber which should only be added when "ldap" USE is enabled. Package won't build on systems without net-nds/openldap otherwise.
https://github.com/InBetweenNames/gentooLTO/blob/4705a8da1e642346b174413da10e43544dd554ec/sys-config/ltoize/files/package.cflags/ltoworkarounds.conf#L130

**Comment by InBetweenNames** [comment]
Fixed, thanks!
