### ISSUE TITLE
media-libs/musicbrainz does not compile with ninja

### ISSUE THREAD

**Issue by ElDavoo** [InBetweenNames/gentooLTO#267]
Hello,
since media-libs/musicbrainz does not compile with ninja, I propose to use emake for this package.
This is the error:
ninja: error: '/var/tmp/portage/media-libs/musicbrainz-5.1.0/work/libmusicbrainz-5.1.0/src/*.inc', needed by 'include/musicbrainz5/mb5_c.h', missing and no known rule to make it

**Comment by InBetweenNames** [comment]
Fixed, thanks!
