### ISSUE TITLE
Migrate to bashrc.d from the mv overlay?

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [InBetweenNames/gentooLTO#27]
Have you considered using https://github.com/vaeth/portage-bashrc-mv?

**Comment by InBetweenNames** [comment]
Very cool!  Yes this looks very good--the installer could just symlink bashrc into the bashrc.d directory and leave a message to the user that they should install portage-bashrc-mv.  I would of course modify the bashrc to comply with that author's specification.

**Comment by InBetweenNames** [comment]
Holy crap, this bashrc.d thing does a whole lot more than just this--it has it's own method of filtering CFLAGS and everything!  And it supports PGO on arbitrary packages!  It may be better than what we have in right now.  This could be very useful.

**Comment by InBetweenNames** [comment]
I just did a quick test and it's working fantastic.  The only thing I had to do was remove certain scripts from the default bashrc.d directory that I didn't want (`10-title.sh`, `80-localepurge.sh`, and `80-remove_la.sh`).  I wonder if the author would consider a PR to make those optional?  I installed it via the `mv` overlay with `app-portage/portage-bashrc-mv`.  

By the way, what would be the best way to handle this integration?  I can think of three ways:

1. depend on `app-portage/portage-bashrc-mv`, and ask users to edit out things they don't want out of their `bashrc.d`

2. depend on `app-portage/portage-bashrc-mv[cflags]`, where `cflags` would be a USE created by aforementioned PR to install the `package.cflags` functionality

3. expect users to already have `portage-bashrc-mv` installed and configured, either through the ebuild or through the git repo itself

I think what it comes down to is how people use bashrc.d already.  In all cases, we can use the `package.cflags` functionality in bashrc.d to do ALL overrides.  Very, very nice.

@mgomersbach I think this should still work with your PR.  Nothing fundamental changes--we would get rid of the `env` directory and instead directly override flags like this (excerpt from my test today):

~~~
...
#Packages which Graphite optimizations don't play nice with
media-libs/lcms *FLAGS-="${GRAPHITE}"
media-video/ffmpeg *FLAGS-=-flto* *FLAGS-="${GRAPHITE}"
...
~~~

**Comment by preney** [comment]
I think it is important to not require users to edit bashrc.d for a number of reasons including having to redo edits after repo updates. IMHO it would be best, if it is possible and efficient, for each bashrc.d file to only be used based on a trigger that the user sets. Another way would be to have the bashrc.d files in a directory that is otherwise not used, then have another directory that is always used that symlinks each desired file to the bashrc.d directory, e.g., like Debian's /etc/apache2/sites-available and /etc/apache2/sites-enabled .

**Comment by Alessandro-Barbieri** [comment]
You can have a sample of his package.cflags here https://github.com/vaeth/portage-env-mv/

**Comment by Alessandro-Barbieri** [comment]
I vote for this:

> depend on app-portage/portage-bashrc-mv, and ask users to edit out things they don't want out of their bashrc.d

**Comment by InBetweenNames** [comment]
Yeah actually Martin Väth was kind enough to implement the USE functionality we need to do this cleanly.  So doing it with `app-portage/portage-bashrc-mv[cflags]` should be possible now--existing users of `bashrc.d` will be unaffected.

**Comment by InBetweenNames** [comment]
Incorporated this change.  Thanks for bringing this to my attention, @Alessandro-Barbieri !
