### ISSUE TITLE
media-libs/flac: combining -O3 and LTO breaks decoding

### ISSUE THREAD

**Issue by jelinekto** [InBetweenNames/gentooLTO#270]
How to reproduce:
1. Build `media-libs/flac` with flags containing both `-O3` and `-flto`, e.g. `-march=native -O3 ${FLTO} -pipe`.
2. Try to decode a flac file using something like `flac -d file.flac`
3. Watch the process hang.

As far as I know, other functionality is not affected.

Either `media-libs/flac /-O3/-O2` or `media-libs/flac *FLAGS-="${FLTO}"` can be used to resolve the issue.

[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/3038310/emerge-info.txt)

**Comment by gcs-github** [comment]
Looks like `-fipa-cp-clone` (enabled by default at -O3) doesn't play well with `-flto` here, at least under GCC 8.3.0.

Since running this overlay supposes that one wants `-flto` on, I suggest `*FLAGS+=-fno-ipa-cp-clone` as a workaround.
