### ISSUE TITLE
Gcc 9.1 Released What To Do To Fix -fipa-pta And Enable It ?

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#282]
https://www.phoronix.com/scan.php?page=news_item&px=GCC-9.1-Compiler-Released

Can The gcc 8.3.0-r1 ebuild Be Bumped To gcc-9.1 ? or we have to wait for new ebuild ?

**Comment by InBetweenNames** [comment]
Testing now!  Going to do a rebuild and if everything looks good, I will post a 9.1.0 ebuild in GentooLTO and advise all users to upgrade.  I'll also re-enable `-fipa-pta` when I do this.

**Comment by javashin** [comment]
Thanks So Much @InBetweenNames Nice Job!

**Comment by InBetweenNames** [comment]
OK, we're now all set for GCC 9.1.0.  I have left `-fipa-pta` off for now, but I will add it to the defaults in a few weeks once everyone has migrated.

**Comment by wolfwood** [comment]
thank you for including an ebuild!

This is a good discussion of LTO improvements
http://hubicka.blogspot.com/2019/05/gcc-9-link-time-and-inter-procedural.html

it also mentions in passing that gcc pgo optimizes cold code for size, might be important to remember w.r.t. autoFDO

**Comment by javashin** [comment]
Hi Again Well . I had Compiled Gcc with This Before :::

sys-devel/gcc-8.3.0-r1::gentoo was built with the following:
USE="cxx fortran graphite (multilib) nls nptl openmp pch pgo (pie) sanitize ssp vtv (-altivec) -debug -doc (-fixed-point) -go (-hardened) (-jit) (-libssp) -mpx -objc -objc++ -objc-gc -systemtap -test -vanilla" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"

using override-flagomatic but now i cant ?

how i can enable again override-flagomatic for GCC ?

**Comment by javashin** [comment]
>>> Emerging (1 of 1) sys-devel/gcc-9.1.0::lto-overlay
 * gcc-9.1.0.tar.xz BLAKE2B SHA512 size ;-) ...                                                                                                [ ok ]
gcc: Fri Mar 15 16:24:38 2019: 2 minutes, 18 seconds
gcc: Sun Mar 17 16:29:27 2019: 2 hours, 9 minutes, 9 seconds
gcc: Mon Mar 18 15:28:50 2019: 3 hours, 44 minutes, 5 seconds
gcc: Wed Mar 27 18:28:02 2019: 22 hours, 7 minutes, 47 seconds
gcc: Sat Mar 30 16:35:20 2019: 45 seconds
gcc: Sat Mar 30 16:56:48 2019: 44 seconds
gcc: Sun Apr  7 03:06:49 2019: 1 hour, 53 minutes, 35 seconds
gcc: 7 times
gcc: 4 hours, 16 minutes, 54 seconds for 7 merges
 * /etc/portage/package.cflags/ltoworkarounds.conf -> sys-devel/gcc: "has pgo ${IUSE//+} && use pgo && FlagSubAllFlags -flto*" #Internal compiler error when used with PGO
 * /etc/portage/package.cflags/ltoworkarounds.conf -> sys-devel/gcc: LTO_ENABLE_FLAGOMATIC=yes
 * /etc/portage/package.cflags/ltoworkarounds.conf -> sys-devel/gcc: *FLAGS-="${IPA}"
 * FEATURES='assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr'
 * CFLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CXXFLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CPPFLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe'
 * FFLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * FCFLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * F77FLAGS='-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * LDFLAGS='-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * MAKEOPTS='-j3'
 * gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
 * Linux igloo-l440 5.0.0-pf7 #1 SMP PREEMPT Fri May 3 03:12:47 AST 2019 x86_64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz GenuineIntel GNU/Linux
>>> Unpacking source...
>>> Unpacking gcc-9.1.0.tar.xz to /var/tmp/portage/sys-devel/gcc-9.1.0/work
>>> Source unpacked in /var/tmp/portage/sys-devel/gcc-9.1.0/work
>>> Preparing source in /var/tmp/portage/sys-devel/gcc-9.1.0/work/gcc-9.1.0 ...
 * Updating gcc to use automatic PIE building ...
 * Updating gcc to use automatic SSP building ...
 * using upstream multilib; disabling lib32 autodetection
 * Running elibtoolize in: gcc-9.1.0/
 *   Applying portage/2.2 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.2.6 patch ...
 * Using GNU config files from /usr/share/gnuconfig
 *   Updating config.sub                                                                                                                       [ ok ]
 *   Updating config.guess                                                                                                                     [ ok ]
 * Fixing misc issues in configure files
 * Applying gcc-configure-texinfo.patch ...                                                                                                    [ ok ]
 * Touching generated files
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sys-devel/gcc-9.1.0/work/gcc-9.1.0 ...
 * strip-flags: CFLAGS: changed '-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu' to '-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2'
 * strip-flags: CPPFLAGS: changed '-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe' to '-march=native -fuse-ld=gold -pipe -O2'
 * strip-flags: CXXFLAGS: changed '-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu' to '-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2'
 * strip-flags: FFLAGS: changed '-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu' to '-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2'
 * strip-flags: FCFLAGS: changed '-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu' to '-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2'
 * CFLAGS="-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2"
 * CXXFLAGS="-march=native -fuse-ld=gold -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -O2"
 * LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"

**Comment by javashin** [comment]
and how i clean the history of how many times i emerged a pkg showing everytime i emerge something ::::

gcc: Fri Mar 15 16:24:38 2019: 2 minutes, 18 seconds
gcc: Sun Mar 17 16:29:27 2019: 2 hours, 9 minutes, 9 seconds
gcc: Mon Mar 18 15:28:50 2019: 3 hours, 44 minutes, 5 seconds
gcc: Wed Mar 27 18:28:02 2019: 22 hours, 7 minutes, 47 seconds
gcc: Sat Mar 30 16:35:20 2019: 45 seconds
gcc: Sat Mar 30 16:56:48 2019: 44 seconds
gcc: Sun Apr 7 03:06:49 2019: 1 hour, 53 minutes, 35 seconds
gcc: 7 times
gcc: 4 hours, 16 minutes, 54 seconds for 7 merges

**Comment by javashin** [comment]
NeverMind I know Now How To Override The Lto Workarounds :)

This Is Good News To All Of Us Who Use This Overlay , And Good News To Me Today I re-pasted My Laptop Cpu With Grizzly Thermal Paste Kryonaut , And Temps Are Nicely Fine Compiling with -j3 on a intel i5 4200M Higher Temps At 72C-73C before 85C-87C .

**Comment by InBetweenNames** [comment]
@wolfwood pretty cool that Gentoo was mentioned in there too!  Great post, thanks for sharing.

@javashin I had to `LTO_ENABLE_FLAGOMATIC=yes` with GCC because at some point, it wasn't possible to build without it.  It's still that way with GCC 9.1.0 unfortunately.  I did have GCC 7.4.0 building with `override-flagomatic` enabled without issues, so I suspect it's a build system problem and not something inherent.

**Comment by javashin** [comment]
@InBetweenNames i did override it and compiled with ::::

sys-devel/gcc-9.1.0::lto-overlay was built with the following:
USE="cxx fortran graphite (multilib) nls nptl openmp pch pgo (pie) sanitize ssp vtv (-altivec) -debug -doc (-fixed-point) -go (-hardened) (-jit) (-libssp) -mpx -objc -objc++ -objc-gc -systemtap -test -vanilla" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -mfpmath=387 -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -mfpmath=387 -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"

**Comment by javashin** [comment]
im recompiling it again to make sure but now removing -mfpmath=387

**Comment by javashin** [comment]
Kernel Compiled Fine with -march=native and -O3
[    0.000000] Linux version 5.0.0-pf7 (root@igloo-l440) (gcc version 9.1.0 (Gentoo 9.1.0)) #1 SMP PREEMPT Fri May 3 18:55:32 AST 2019

**Comment by javashin** [comment]
first pkg compiled with -fipa-pta : working fine

sys-libs/glibc-2.29-r2::gentoo was built with the following:
USE="multiarch (multilib) ssp -audit -caps (-cet) (-compile-locales) -doc -gd -headers-only -nscd -profile (-selinux) -suid -systemtap -test (-vanilla)" ABI_X86="(64)"
CFLAGS="-O3 -march=native -fipa-pta -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-O3 -march=native -fipa-pta -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -fuse-ld=bfd"

**Comment by javashin** [comment]
sys-devel/binutils-2.32-r1::gentoo was built with the following:
USE="cxx default-gold gold nls plugins -doc -multitarget -static-libs -test" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe"

**Comment by javashin** [comment]
sys-devel/libtool-2.4.6-r5::gentoo was built with the following:
USE="-vanilla" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe"

**Comment by javashin** [comment]
cc1: error: SSE instruction set disabled, using 387 arithmetics [-Werror] without -mfpmath=387


if i want to compile gcc with all the flags needs -mfpmath=387 to be added

sys-devel/gcc-9.1.0::lto-overlay was built with the following:
USE="cxx fortran graphite (multilib) nls nptl openmp pch pgo (pie) sanitize ssp vtv (-altivec) -debug -doc (-fixed-point) -go (-hardened) (-jit) (-libssp) -mpx -objc -objc++ -objc-gc -systemtap -test -vanilla" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -mfpmath=387 -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -mfpmath=387 -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"



-fipa-pta  is not compatible to compile gcc Stops on Configure nothing gets compiled

**Comment by InBetweenNames** [comment]
Just curious, what is the benefit of using 387 arithmetic?  It may double the number of architectural registers, but the number of physical registers should be the same in both modes in a modern out of order processor.

**Comment by javashin** [comment]
https://patchwork.ozlabs.org/patch/563680/

**Comment by InBetweenNames** [comment]
Just trying to understand -- I see you are using `-mfpmath=both` by default, and then using `-mfpmath=387` to override that.  My question is what benefit does `-mfpmath=both` bring?  As I understood it, both instruction sets are effectively decoded to use the same ports (and hence execution units) of the processor.

**Comment by javashin** [comment]
This is Old but related https://ubuntuforums.org/showthread.php?t=1477356

**Comment by javashin** [comment]
i copied the cflags from https://cloveros.ga/ some of them this guy Jesus is being doing LTO for everything before us on gentoo i mean his own distro cloverOS look at The News.

**Comment by InBetweenNames** [comment]
Huh.  I guess there are processors out there that have separate execution units for SSE and x87 code.  Neat!

It looks like the commit history for CloverOS goes back to June 2017 -- actually, if you count my work before I published GentooLTO, I'd say both these projects likely started around the same time.  Interesting!  Not much activity on their forums unfortunately.  I'm actually surprised we haven't heard from the person running it.

**Comment by javashin** [comment]
Thanks To You @InBetweenNames LTO is more accessible on Gentoo :) There is no Gentoo install i do without this overlay .

**Comment by javashin** [comment]
i dont use -mfpmath=387 to build anything else the problem comes when gcc wants to link the 32bit compiler if i use  mfpmath=both -mfpmath=387 needs to be passed to complete the compilation thats all i had no problem with anything else but is strange this only happen with gcc 9.1 , gcc 8.3 never failed only with mfpmath=both linking the 32bits compiler

**Comment by nivedita76** [comment]
for gcc, I've been building since gcc-8 using an env file that
1) EXTRA_ECONF='--with-build-config=bootstrap-lto' this uses gcc build system's builtin lto support
2) USE=pgo this uses gcc build system's builtin pgo support
3) BOOT_CFLAGS="-march=native -O3 ..." this makes the stage1 compiler bootstrap gcc with these flags, bypassing all the stripping in toolchain.eclass

gcc-9.1.0 builds fine for me with -O3 and ipa-pta enabled via BOOT_CFLAGS

**Comment by nivedita76** [comment]
Also note that gentoo now has the gcc-9.1.0 ebuild with the standard gentoo patches.

**Comment by javashin** [comment]
can i have a description @nivedita76  Of -fira-loop-pressure -flive-range-shrinkage -ftree-lrs -falign-{functions,jumps,loops}=32 ?

**Comment by javashin** [comment]
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/wiki/Understanding-compiler-options

**Comment by nivedita76** [comment]
The flags are somewhat contradictory but I'm just trying them out as some of the few optimizations not enabled with -O3 and profiling (note that profiling turns on extra optimizers with -O3).

fira-loop-pressure: Use IRA to evaluate register pressure in loops for decisions to move loop invariants. This option usually results in generation of faster and smaller code on machines with large register files (>= 32 registers), but it can slow the compiler down. 
flive-range-shrinkage: Attempt to decrease register pressure through register live range shrinkage. This is helpful for fast processors with small or moderate size register sets. 
ftree-lrs: This actually seems to be undocumented and I think I should remove it -- it was for "Perform live range splitting during the SSA->normal pass." It's listed as an option but I don't think there is anything actually using it. LRS seems to have been integrated into some other pass.

**Comment by barolo** [comment]
I'm currenly in the middle of —e @world with ipa, so far I couldn't compile binutils with it and firefox fails at profiling phase, with/without/with defaults, not sure what this one is about yet

**Comment by wolfwood** [comment]
@barolo firefox just hangs while building for me. cpu drops to 0 and never progresses. there is a bug about USE="pgo lto" with gcc.

firefox built successfully with -pgo. it would probably also build if you did USE="clang pgo lto"

**Comment by barolo** [comment]
@wolfwood I am somewhat aware of this unless it's strictly. GCC 9 related, I was building the same version of FF with GCC 8  just week ago

**Comment by nivedita76** [comment]
Firefox was building for me with lto and pgo and O3 etc. it has stopped now with same symptom of getting stuck in profile. I’m guessing something broke with the ipa addition trying to turn it off for all the dependencies now.

**Comment by barolo** [comment]
@nivedita76 I'm going the other way, redoing world with IPA ;) let me know how it goes. It's weird nonetheless, I can see profiled FF being launched and that's the end.

**Comment by wolfwood** [comment]
I don't have IPA and was (re)building with gcc 8.3. so at some point it had worked for me, too. maybe whatever dependency triggered the rebuild was responsible.

**Comment by nivedita76** [comment]
Btw without pgo it built for me but segfaults on startup

**Comment by javashin** [comment]
Firefox is Tricky Only way to build it now is with :: Clang if i want the goodies of html5test it gives 511 score 


www-client/firefox-66.0.3::gentoo was built with the following:
USE="clang custom-cflags custom-optimization dbus gmp-autoupdate hwaccel lto pgo pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp wayland wifi -bindist -debug -eme-free -geckodriver -hardened -jack (-neon) (-selinux) -test" ABI_X86="(64)" CPU_FLAGS_X86="avx2" L10N="-ach -af -an -ar -as -ast -az -bg -bn-BD -bn-IN -br -bs -ca -cak -cs -cy -da -de -dsb -el -en-GB -en-ZA -eo -es-AR -es-CL -es-ES -es-MX -et -eu -fa -ff -fi -fr -fy -ga -gd -gl -gn -gu -he -hi -hr -hsb -hu -hy -id -is -it -ja -ka -kab -kk -km -kn -ko -lij -lt -lv -mai -mk -ml -mr -ms -nb -nl -nn -or -pa -pl -pt-BR -pt-PT -rm -ro -ru -si -sk -sl -son -sq -sr -sv -ta -te -th -tr -uk -uz -vi -xh -zh-CN -zh-TW"
CFLAGS="-march=native -funroll-loops -falign-functions=32 -fsplit-lto-unit -pipe -fstack-check"
CXXFLAGS="-march=native -funroll-loops -falign-functions=32 -fsplit-lto-unit -pipe -fstack-check"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=lld -Wl,--hash-style=gnu -Wl,-rpath=/usr/lib64/firefox,--enable-new-dtags -Wl,--compress-debug-sections=zlib"

**Comment by barolo** [comment]
@nivedita76 rebuilding world didn't help, this bug looks like a repeat from few weeks ago.
I had just 4 failures out of 1,4 k packages, due to ipa

**Comment by nivedita76** [comment]
Even with clang pgo isn't working for me (hangs during build). I finally got a clang lto build with no pgo and no custom optimization.

**Comment by nivedita76** [comment]
This is weird, it has mysteriously started working again. I rebuilt world yesterday with
CFLAGS="-march=native -O3 -fira-loop-pressure -flive-range-shrinkage -falign-{functions,jumps,loops}=32 ${FASTMATH} -fgraphite-identity -floop-nest-optimize ${IPA} -fno-plt ${SEMINTERPOS} -flto -fdevirtualize-at-ltrans"

firefox built fine with both clang and gcc with pgo/lto USE flags and no custom optimization.

**Comment by javashin** [comment]
hi @nivedita76 can u test for me if spotify works for you since you compiled everything with IPA please

**Comment by barolo** [comment]
@nivedita76 got it working. In my case it was RUSTFLAGS.... had march=native and O3

**Comment by javashin** [comment]
@nivedita76 i compiled mesa with falign-{functions,jumps,loops}=32 and i get graphical glitches and artifacts

**Comment by nivedita76** [comment]
That’s weird. Why would code alignment affect correctness?

**Comment by javashin** [comment]
you have a intel gfx ? too

**Comment by nivedita76** [comment]
Nope. Nvidia card

**Comment by javashin** [comment]
yeah thats why u dont see any glithces ok wait 2 cards smartswitch  gpu switchero , Optimus ?

**Comment by barolo** [comment]
@nivedita76 followup on firefox, we should make separate thread for it probably. I've managed to compile FF with rustflags native O3, and everything enabled from GLTO + ipa, fno-plt. The issue seems to be not in the compiler but in the build system/profiling of FF as following compiles fail unless system is restarted. At least for me. Possibly for you too as it seems it randomly started working for you.

**Comment by wolfwood** [comment]
@barolo there have been 2 version bumps to ffx since this conversation started, i think the latest one was what fixed gcc+lto+pgo for me too

**Comment by barolo** [comment]
@wolfwood I'm compiling latest beta always

**Comment by nivedita76** [comment]
@barolo and @wolfwood it actually started working for me with 66.0.3, and the two version bumps also worked without fine. Got all the goodies except I only have native in RUSTFLAGS (no optimization level specified I think it uses O2 by default in the ff build?) and the standard ltoworkarounds.conf, so -O2 instead of -O3 and no IPA/tls dialect.

**Comment by javashin** [comment]
Im Going Back To My Old Gentoo Without IPA and No NOPLT And Masking Gcc 9.1 anything beyond LTO GRAPHITE AND SEMA* , Like IPA PLT FASTMATH NOCOMMON JUST MAKE OVERHEAD EVERYTHING AND OVERHEAT CPU's  AND  Makes Everything SLOW . Not Recommended because i compiled 2 gentoos With Gcc 9.1 With Those Flags And I Get Just SLOwness And Hotness. No Real Benefit For Real , Anyone With Backups Make Comparisons Side By Side startup times , Compile Time , Temperature , For REAL...........

**Comment by InBetweenNames** [comment]
@javashin  if you're in a heat constrained environment (laptop, phone), your CPU will likely downclock to prevent overheating if you are running more watts (which you will be with this config -- more CPU utilization, as in die-space wise, means more power, means more heat!).  You'll need to manually play around with your CPU clocks and voltages to maintain the same heat envelope.

**Comment by javashin** [comment]
thanks @InBetweenNames

**Comment by InBetweenNames** [comment]
Fast math is probably the biggest culprit
