### ISSUE TITLE
lto-rebuild -r list never gets empty ?

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#285]
How works lto-rebuild after emerge the half of pkgs it failed because two pkgs wants to get rebuilt with clang and failed because not compatible with gcc Cflags and when i reload lto-rebuild -r there is the same pkgs i emerged before and i killed that and continued with emerge --resume . after emerge everything is going to get empty ? or is like this just a reminder ?

**Comment by javashin** [comment]
lto-rebuild -r

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-libs/libatomic_ops-7.6.10 
[ebuild   R    ] sys-devel/flex-2.6.4-r1 
[ebuild   R    ] app-emulation/vkd3d-1.1-r4 
[ebuild   R    ] dev-util/glslang-7.11.3114_pre20190415 
[ebuild   R    ] dev-util/spirv-tools-2019.1-r1 
[ebuild   R    ] sys-libs/libunwind-1.2.1-r3 
[ebuild   R    ] dev-lang/lua-5.1.5-r4 
[ebuild   R    ] dev-lang/tcl-8.6.9 
[ebuild   R    ] dev-libs/libfilezilla-0.15.1 
[ebuild   R    ] dev-libs/libfstrcmp-0.7 
[ebuild   R    ] dev-libs/xmlrpc-c-1.39.11-r1 
[ebuild   R    ] media-gfx/exiv2-0.27.0-r2 
[ebuild   R    ] media-sound/wavpack-5.1.0-r1 
[ebuild   R    ] sys-libs/binutils-libs-2.32-r1 
[ebuild   R    ] x11-libs/libfakekey-0.1-r3 
[ebuild   R    ] dev-lang/python-2.7.16 
[ebuild   R    ] dev-lang/python-3.6.8 
[ebuild   R    ] sys-devel/binutils-2.32-r1 
[ebuild   R    ] mate-base/mate-desktop-1.22.0 
[ebuild   R    ] mate-base/mate-menus-1.22.0 
[ebuild   R    ] dev-libs/elfutils-0.176 
[ebuild   R    ] dev-qt/qtcore-5.12.3 
[ebuild   R    ] mate-base/libmatekbd-1.22.0 
[ebuild   R    ] sys-libs/libcxxabi-8.0.0 
[ebuild   R    ] app-emulation/wine-staging-4.7_p1-r1 
[ebuild   R    ] app-text/atril-1.22.0 
[ebuild   R    ] dev-libs/libcdio-paranoia-2.0.0 
[ebuild   R    ] dev-libs/nss-3.43 
[ebuild   R    ] dev-libs/re2-0.2019.04.01 
[ebuild   R    ] media-libs/libbs2b-3.1.0-r2 
[ebuild   R    ] media-libs/libcue-2.2.1 
[ebuild   R    ] media-libs/libmatemixer-1.22.0 
[ebuild   R    ] media-libs/libsdl-1.2.15-r9 
[ebuild   R    ] sys-libs/db-6.0.35-r1 
[ebuild   R    ] dev-lang/yasm-1.3.0 
[ebuild   R    ] mate-base/mate-panel-1.22.0 
[ebuild   R    ] x11-wm/marco-1.22.0 
[ebuild   R    ] app-admin/syslog-ng-3.20.1 
[ebuild   R    ] dev-libs/newt-0.52.20 
[ebuild   R    ] dev-qt/qtgui-5.12.3-r1 
[ebuild   R    ] media-libs/shaderc-2018.0 
[ebuild   R    ] sys-libs/compiler-rt-8.0.0 
[ebuild   R    ] sys-libs/compiler-rt-sanitizers-8.0.0 
[ebuild   R    ] sys-libs/db-5.3.28-r3 
[ebuild   R    ] sys-libs/libcxx-8.0.0 
[ebuild   R    ] mate-base/mate-control-center-1.22.0 
[ebuild   R    ] mate-extra/mate-utils-1.22.0 
[ebuild   R    ] media-libs/x265-3.0 
[ebuild   R    ] media-libs/xvid-1.3.5 
[ebuild   R    ] sys-apps/util-linux-2.33.2 
[ebuild   R    ] dev-lang/python-3.7.3 
[ebuild   R    ] dev-libs/crossguid-0_pre20150817 
[ebuild   R    ] dev-libs/boost-1.69.0 
[ebuild   R    ] dev-python/numpy-1.16.1 
[ebuild   R    ] sys-apps/portage-2.3.66 
[ebuild   R   *] sys-fs/zfs-9999 
[ebuild   R    ] sys-libs/glibc-2.29-r2 
[ebuild   R    ] sys-apps/iproute2-5.0.0 
[ebuild   R    ] sys-devel/gcc-9.1.0 
[ebuild   R    ] net-misc/dhcp-4.4.1 

Would you like to merge these packages? [Yes/No] 

????? i finish emerging all these and qm ..\\\again ??

**Comment by InBetweenNames** [comment]
Ah no, it's not smart enough to "pick up where it left off".  Literally all it does is scan for static archives and `emerge --oneshot` them.  Don't call `lto-rebuild -r` again if it was interrupted.  If you want to resume yourself, you can use `emerge --resume`.

**Comment by InBetweenNames** [comment]
Okay, now it *is* smart enough to do this.  I'll be fully supporting crossdev in addition to Gentoo Prefix as well.

**Comment by javashin** [comment]
nice
