### ISSUE TITLE
 app-portage/lto-rebuild

### ISSUE THREAD

**Issue by zwim** [InBetweenNames/gentooLTO#289]
Hello,

lto-rebuild assumes that /bin/sh links to /bin/bash, which is not true for all of us!

So please change the SheBang to: #!/bin/bash

Thanks 
Martin

**Comment by InBetweenNames** [comment]
Well, it should work in other shells -- we actually just added a checkbashisms test to help with compliance.  Although, I should probably use a better tool for that.  What kind of problems are you having?

**Comment by zwim** [comment]
When using dash as /bin/sh, I am getting the following error's

```
t510 ~ # lto-rebuild -h
/usr/bin/lto-rebuild: 3: [: ==: unexpected operator
/usr/bin/lto-rebuild: 22: [: ==: unexpected operator
/usr/bin/lto-rebuild: 24: [: ==: unexpected operator
```

**Comment by InBetweenNames** [comment]
FYI: A test has been added to the overlay to help ensure POSIX compliance with `lto-rebuild` in the future.  Thanks!

**Comment by InBetweenNames** [comment]
I ended up making it dependent on bash -- however now it won't blindly go and rebuild things that are already on the newer GCC.
