### ISSUE TITLE
cc1plus: internal compiler error: Segmentation fault Gcc 9.1 PCSX2

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#296]
[PCSX2.build.log](https://github.com/InBetweenNames/gentooLTO/files/3152586/PCSX2.build.log)

**Comment by javashin** [comment]
compiled before with gcc 8.3 


games-emulation/pcsx2-9999::vampire was built with the following:
USE="" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=1 -fuse-linker-plugin -pipe"

**Comment by javashin** [comment]
Compiled fine with gcc 8.3.0 closing.......

**Comment by filialpails** [comment]
This will be fixed in GCC 9.1.1, or you can apply a patch to 9.1.0, see [the PCSX2 issue](https://github.com/PCSX2/pcsx2/issues/2948).

**Comment by javashin** [comment]
thanks
