### ISSUE TITLE
Spotify crash segfault after recompile -e world with -fipa-pta

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#298]
+++ killed by SIGSEGV (core dumped) +++
fish: “strace spotify” terminated by signal SIGSEGV (Address boundary error)

from dmesg [ 1073.688939] spotify[18240]: segfault at 0 ip 00007f6d05fe69a0 sp 00007ffcd70de108 error 4 in libcef.so[7f6d03ff4000+5bb7000]
[ 1073.688946] Code: 94 c0 c3 cc cc cc cc cc cc cc 8b 07 48 85 f6 74 0b 83 f8 07 75 06 48 89 3e b0 01 c3 83 f8 07 0f 94 c0 c3 cc cc cc cc cc cc cc <8b> 07 48 85 f6 74 0b 83 f8 06 75 06 48 89 3e b0 01 c3 83 f8 06 0f

i dont know what is the cause but after -fipa-pta was working fine 

how i can debug why its crashing to identify what pkg i compiled with fipa-pta is causing this crash please help i dont want to recompile everything

**Comment by javashin** [comment]
strace dont show much
http://dpaste.com/2A7568H

**Comment by javashin** [comment]
Who got everything compiled with -fipa-pta and uses spotify ???

**Comment by javashin** [comment]
well im going back to rollback to where i was without -fipa-pta

**Comment by javashin** [comment]
i need spotify or i will loose my money i pay on premium

**Comment by javashin** [comment]
now is just segfault on glibc for some reason

[ 1118.127430] spotify[20951]: segfault at 8 ip 00007f9652b3f5f9 sp 00007fffa6a0a3a0 error 4 in ld-2.29.so[7f9652b34000+27000]

**Comment by javashin** [comment]
Anyone has notice any performance improvement with -fipa-pta ? for real anything from just some breakage here and there ?

**Comment by javashin** [comment]
can we have any benchmark  ?

**Comment by javashin** [comment]
im going back and masking gcc 9.1 ..... if someone can give me a hand before undone all this work compiling everything with -fipa-pta solving why spotify is not working i will appreciate it

**Comment by InBetweenNames** [comment]
I'm using `-fipa-pta` right now without any issues, but I haven't tried Spotify.

**Comment by javashin** [comment]
Yes 
Can You Sr Try Install and Test IT its a binary app just try to run it and then remove please

**Comment by barolo** [comment]
@javashin I'm at world with IPA and it works for me

`media-sound/spotify-1.1.5-r1::gentoo was built with the following:
USE="-libnotify -pax_kernel -systray" ABI_X86="(64)"
CFLAGS="-O3 -fipa-pta -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=5 -fuse-linker-plugin -march=native -pipe -O2 -Wl,-O1 -Wl,--as-needed"
CXXFLAGS="-O3 -fipa-pta -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=5 -fuse-linker-plugin -march=native -pipe -O2 -march=native -pipe -O2 -Wl,-O1 -Wl,--as-needed"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -O3 -fipa-pta -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=5 -fuse-linker-plugin -march=native -pipe -O2"
`
I had to install by hand these two, as it's missing from deps and won't launch otherwise
app-accessibility/at-spi2-core-2.30.1:2::gentoo
app-accessibility/at-spi2-atk-2.30.1:2::gentoo

**Comment by nivedita76** [comment]
Is working for me too, and didn't need the manual installs.

media-sound/spotify-1.1.5-r1::gentoo was built with the following:
USE="libnotify -pax_kernel -systray" ABI_X86="(64)"
CFLAGS="-march=native -O2 -ggdb -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -falign-functions=32 -falign-jumps=32 -falign-loops=32 -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=12 -fdevirtualize-at-ltrans -fno-plt -fno-semantic-interposition -mtls-dialect=gnu2"
CXXFLAGS="-march=native -O2 -ggdb -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -falign-functions=32 -falign-jumps=32 -falign-loops=32 -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=12 -fdevirtualize-at-ltrans -fno-plt -fno-semantic-interposition -mtls-dialect=gnu2"

**Comment by nivedita76** [comment]
@barolo btw your CFLAGS looks backward? -O2 after -O3 means the actual optimization level is -O2

**Comment by barolo** [comment]
@nivedita76  as far as I know  O3 overrides O2 regardless of order,  and happens often when custom cflags    are mixed with package's defaults. Someone please correct me if I'm wrong

**Comment by nivedita76** [comment]
@barolo doesn't look like it from gcc -O3 -O2 -Q --help=optimize output -- that matches the plain -O2 output.

**Comment by barolo** [comment]
@nivedita76 using help won't work, You can check here: https://gcc.godbolt.org/  to see what gcc really does, just checked and O3 overrides O2 regardless

**Comment by javashin** [comment]
i dont think any of you 2 are using -O3

**Comment by javashin** [comment]
media-sound/spotify-1.1.5-r1::gentoo was built with the following:
USE="libnotify systray -pax_kernel" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe"

And dont work here 

just this 
fish: “spotify” terminated by signal SIGSEGV (Address boundary error)

**Comment by javashin** [comment]
[ 2746.373395] spotify[11729]: segfault at 8 ip 00007fbee3cf554d sp 00007ffe13a84680 error 4 in ld-2.29.so[7fbee3cea000+20000]

**Comment by barolo** [comment]
@javashin What would this matter? Spotify is a precompiled binary, unless it affected some of the libs it's using.

**Comment by javashin** [comment]
yes the libs i just posted the emerge info because everyone did

**Comment by javashin** [comment]
>>> Merging media-sound/spotify-1.1.5-r1 to /
 * removing unneeded *.la files

**Comment by barolo** [comment]
@javashin I'm rebuilding dependencies with O3 right now, we'll see how it goes in a moment

**Comment by nivedita76** [comment]
> i dont think any of you 2 are using -O3

I definitely am (for the libs)

**Comment by javashin** [comment]
im getting somewhere

**Comment by javashin** [comment]
i think is patchelf the problem

**Comment by nivedita76** [comment]
I'm using libnotify but not systray

**Comment by javashin** [comment]
im using both but i disabled both and still the same something bork the install of the spotify binaries and its patchelf i did extracted the content of spotify*.deb to /opt/spotify and its working !!!! lol too much work for this bloated app

**Comment by javashin** [comment]
dev-util/patchelf-0.10 pulled in by:
    media-sound/spotify-1.1.5-r1 requires >=dev-util/patchelf-0.10

dev-util/patchelf-0.10::gentoo was built with the following:
USE="" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -floop-block -floop-interchange -floop-strip-mine -falign-functions=32 -fipa-pta -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe"

**Comment by javashin** [comment]
![Screenshot at 2019-05-07 19-26-46](https://user-images.githubusercontent.com/15115613/57339095-17835d80-70fe-11e9-837e-8fc2ff19d68a.png)

**Comment by barolo** [comment]
@javashin weird, just redid all deps with -O3 with your flags and it's still fine for me, I'm on Plasma

**Comment by javashin** [comment]
problem here lies on 
        libnotify? ( x11-libs/libnotify )
        systray? ( gnome-extra/gnome-integration-spotify )
BDEPEND=">=dev-util/patchelf-0.10"

**Comment by javashin** [comment]
yeah its working fine now after emerge patchelf with 
ev-util/patchelf-0.10::gentoo was built with the following:
USE="" ABI_X86="(64)"
CFLAGS="-O3 -march=native -fipa-pta -fno-strict-aliasing -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-O3 -march=native -fipa-pta -fno-strict-aliasing -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu"

still using gold

**Comment by nivedita76** [comment]
My patchelf is built with everything -- but I am using bfd rather than gold.

dev-util/patchelf-0.10::gentoo was built with the following:
USE="" ABI_X86="(64)"
CFLAGS="-march=native -O2 -ggdb -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -falign-functions=32 -falign-jumps=32 -falign-loops=32 -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=12 -fdevirtualize-at-ltrans -fno-plt -fno-semantic-interposition -mtls-dialect=gnu2"
CXXFLAGS="-march=native -O2 -ggdb -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -falign-functions=32 -falign-jumps=32 -falign-loops=32 -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=12 -fdevirtualize-at-ltrans -fno-plt -fno-semantic-interposition -mtls-dialect=gnu2"

**Comment by barolo** [comment]
@nivedita76 I remember reading something recently about gold stagnating and Fedora wanting to get rid off it, that's why I've switched to bfd

**Comment by javashin** [comment]
well its a useless app this patchelf thats only spotify uses not any other single app uses this useless console app i dont need it to be compiled with lto or any other optimization , but i didn't know this until today :) good learning

**Comment by javashin** [comment]
i use gold for everything but not for curl and efivar i think

**Comment by barolo** [comment]
@javashin Case closed?

**Comment by javashin** [comment]
now im going to compile a startup time list of my more used apps something like a benchmark of every app i use calculating the time it tooks to start from this fresh compiled -e world compared with my old installation

**Comment by javashin** [comment]
Yes Case Closed Bye and Thanks I never Would Know What To Do Really :)

**Comment by ElDavoo** [comment]
I got this issue too, it would crash when trying to play a song. Just checked now, after an emptytree with ipa-pta and gcc 9 and the issue is magically gone.
