### ISSUE TITLE
packages manifest which fails to build.

### ISSUE THREAD

**Issue by sandikata** [InBetweenNames/gentooLTO#299]
https://gist.github.com/sandikata/b508489f6d6ab97143295ae08854ef21

here's build log.
There's no info how to proceed if something goes wrong.

**Comment by sandikata** [comment]
A little update

cat /etc/portage/package.cflags/noopt.conf                                                                                                                ──(вт,май07)─┘
sys-libs/libapparmor *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sys-apps/apparmor-utils *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sys-apps/apparmor *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sec-policy/apparmor-profiles *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*

But, i am not sure if there is better workaround.

**Comment by sandikata** [comment]
app-emulation/snapd *FLAGS-=-flto*

**Comment by InBetweenNames** [comment]
~~~
type ‘union YYSTYPE’ violates the C++ One Definition Rule [-Wodr]
~~~

It looks like there's an ODR violation in apparmor -- so this will certainly require a workaround.  Good find!

**Comment by sandikata** [comment]
I can provide you logs for all failed packages tomorrow, with all optimizations enabled, just to confirm what workarounds are best solution.

**Comment by sandikata** [comment]
Summary. From 1247 packages i have following failures during build.

https://gist.github.com/sandikata/a6cdbbee5690ff92e02139a609abfc9d - libostree
https://gist.github.com/sandikata/80886aa6278c899a2cb0d74ebeb24dff - flatpak
https://gist.github.com/sandikata/a9bcacf5cc0f8021a22ba1c04e3877e3 - gnome-disk-utility
https://gist.github.com/sandikata/b508489f6d6ab97143295ae08854ef21 - apparmor
https://gist.github.com/sandikata/3c1bc2071bc9dff727aba620420b3d25 - apparmor-utils
https://gist.github.com/sandikata/c969ba8cfc51a4772493a9a741fab904 - snapd

**Comment by sandikata** [comment]
update.
tracker segfault with LTO+Graphite.
i'd try with disabled lto+graphite.

**Comment by sandikata** [comment]
Well, i give up right now.
There is not a point to continue, after rebuilding world set, i am not satisfied with results, i don't see improvement, but impact of overall performance.
Improvements from lto and graphite are impacted hardly by -O3 level.
Best wishes, i respect your work guys!
Regards, and good luck in future.

**Comment by sandikata** [comment]
> ```
> type ‘union YYSTYPE’ violates the C++ One Definition Rule [-Wodr]
> ```
> 
> It looks like there's an ODR violation in apparmor -- so this will certainly require a workaround. Good find!

Have you found workaround, or just to use it like that ?

**Comment by InBetweenNames** [comment]
I've just been using it as-is, but there probably should be an LTO
workaround for it.  Would you mind submitting a PR?

**Comment by sandikata** [comment]
PR? What you mean?

**Comment by InBetweenNames** [comment]
No worries -- I got it.  I've only added `sys-apps/apparmor` as I found no issues with the other packages.
Are you using gold as your linker?

**Comment by sandikata** [comment]
> No worries -- I got it. I've only added `sys-apps/apparmor` as I found no issues with the other packages.
> Are you using gold as your linker?

i think so. but i can check.
lrwxrwxrwx 1 root root 22 11 май 21:30 /usr/bin/ld -> x86_64-pc-linux-gnu-ld
hmm it's not..

**Comment by InBetweenNames** [comment]
I'm strongly considering adding `-fuse-ld=gold` to the default configuration as it seems gold works in many situations where bfd does not, although there are some cases the other way around too

**Comment by sandikata** [comment]
> I'm strongly considering adding `-fuse-ld=gold` to the default configuration as it seems gold works in many situations where bfd does not, although there are some cases the other way around too

well, i will enable it as default linker. i don't see choice in binutils-config, they changed it via use flag of binutils..

* Found these USE flags for sys-devel/binutils-2.32-r1:
 U I
 + + cxx          : Build support for C++ (bindings, extra libraries, code generation, ...)
 - - default-gold : Set ld to point to ld.gold instead of ld.bfd
 - - doc          : Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of globally
 + + gold         : Build ld.gold linker
 - - multitarget  : Adds support to binutils for cross compiling (does not work with gas)
 + + nls          : Add Native Language Support (using gettext - GNU locale utilities)
 + + plugins      : Enable plugin support in tools
 - - static-libs  : Build static versions of dynamic libraries as well
 - - test         : Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can be toggled independently)

**Comment by InBetweenNames** [comment]
Oh!  You can use `binutils-config  --linker ld.gold`

**Comment by sandikata** [comment]
probably i'll have to rebuild world set again :D

**Comment by sandikata** [comment]
hm, it won't switch to ld.gold in any of mentioned ways.. wierd
~ ➜ ls /usr/bin/ld -l
lrwxrwxrwx 1 root root 22 13 май 19:39 /usr/bin/ld -> x86_64-pc-linux-gnu-ld
~ ➜ ls -l /usr/bin/x86_64-pc-linux-gnu-ld                      
lrwxrwxrwx 1 root root 31 13 май 19:39 /usr/bin/x86_64-pc-linux-gnu-ld -> /usr/x86_64-pc-linux-gnu/bin/ld
~ ➜ ls -ls /usr/x86_64-pc-linux-gnu/bin/ld
0 lrwxrwxrwx 1 root root 45 13 май 19:39 /usr/x86_64-pc-linux-gnu/bin/ld -> /usr/x86_64-pc-linux-gnu/binutils-bin/2.32/ld
~ ➜

**Comment by InBetweenNames** [comment]
I think if you have binutils built with `USE=gold` and you do `binutils-config --linker ld.gold` it should work.  And if it doesn't, you can add `-fuse-ld=gold` to your `CFLAGS` and that should force its usage.  No need for a world rebuild though!

**Comment by sandikata** [comment]
~ ➜ readlink -f /usr/bin/ld
/usr/x86_64-pc-linux-gnu/binutils-bin/2.32/ld.gold
~ ➜ ls -l /usr/bin/ld                    
lrwxrwxrwx 1 root root 22 13 май 19:48 /usr/bin/ld -> x86_64-pc-linux-gnu-ld
~ ➜ ls -l /usr/bin/x86_64-pc-linux-gnu-ld
lrwxrwxrwx 1 root root 31 13 май 19:48 /usr/bin/x86_64-pc-linux-gnu-ld -> /usr/x86_64-pc-linux-gnu/bin/ld
~ ➜ ls -l /usr/x86_64-pc-linux-gnu/bin/ld                               
lrwxrwxrwx 1 root root 45 13 май 19:48 /usr/x86_64-pc-linux-gnu/bin/ld -> /usr/x86_64-pc-linux-gnu/binutils-bin/2.32/ld
~ ➜ ls -l /usr/x86_64-pc-linux-gnu/binutils-bin/2.32/ld                               
lrwxrwxrwx 1 root root 7 13 май 19:48 /usr/x86_64-pc-linux-gnu/binutils-bin/2.32/ld -> ld.gold
~ ➜ ld -plugin                                         
ld: -plugin: missing argument
ld: use the --help option for usage information

success finally.

**Comment by sandikata** [comment]
so you're saying that only apparmor fails for you?

~ ➜ cat /etc/portage/package.cflags/noopt.conf 
sys-libs/libapparmor *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sys-apps/apparmor-utils *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sys-apps/apparmor *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
sec-policy/apparmor-profiles *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
app-emulation/snapd *FLAGS-=-flto*
sys-fs/libostree  *FLAGS-=-flto*
sys-apps/flatpak *FLAGS-=-flto*
sys-block/thin-provisioning-tools *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
dev-libs/libaio *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*
media-libs/mesa *FLAGS-="${GRAPHITE}" *FLAGS-=-flto*

this is my custom conf..

**Comment by InBetweenNames** [comment]
`libaio` was added back today, no issues with `libostree`, `sys-block/thin-provisioning-tools`, although `mesa` does need a workaround conditional on AMD.  I will add that in shortly.  I don't have any ebuilds for `flatpak` handy.

**Comment by sandikata** [comment]
flatpak is fine now, snapd fails with lto, so i've disabled it.

**Comment by sandikata** [comment]
oh yeah.. and spidermonkey-52 build failure, i think i've opened issue for it.

**Comment by InBetweenNames** [comment]
Any chance you can just use the newer spidermonkey?

**Comment by sandikata** [comment]
cinnamon java script depends on version 52. :<

**Comment by InBetweenNames** [comment]
Could it be hacked to work on a later version? AFAIK, spidermonkey is
backwards compatible

**Comment by sandikata** [comment]
i don't know, i am not cinnamon developer :>

**Comment by sandikata** [comment]
it will be added to CFLAGS, because it mess with kernel build. Kernel won't build with gold linker as default.
