### ISSUE TITLE
Can We Have/Open An IRC Chat Channel On Freenode ?

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#300]
Can Be Useful Have Presence on Irc An debug Our Errors In There And Discuss Solutions Before Open issues Here Or Try To Get The Bests Results Talking About Lto Etc Like A Support Channel not Off-topic

**Comment by InBetweenNames** [comment]
We actually had one, but I had a hard time staying online consistently.  I think the issues page is okay for now.  I agree it's not perfect though.

**Comment by javashin** [comment]
is ok
