### ISSUE TITLE
Can ltoworkarounds.conf be made a config file?

### ISSUE THREAD

**Issue by nivedita76** [InBetweenNames/gentooLTO#301]
Currently this is installed as a symlink in /etc/portage/package.cflags, so it can't be overridden easily in case the user wants to try out a package without one of the workarounds. Is it possible to install it as a regular file and mark it as a config (so etc-update will merge it) to make it easy to edit?

**Comment by barolo** [comment]
Yeah, I'm compiling firefox with clang and have to remove workarounds every time GLTO is update, as they're not valid with clang. Is there any way to avoid this?

**Comment by nivedita76** [comment]
Ok thanks. The git method or using z* as my local settings should work.
