### ISSUE TITLE
Start Up Times Of Most Used Apps With no -fipa-fta , Old Gentoo Diffs. Vs New Gentoo Fresh emerge -e @world with IPA.

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#304]
GENTOO OLD / OLD GENTOO SECTION BEGINS HERE>>>>>>>>><<<<<<<<<<<<

![Screenshot at 2019-05-07 21-14-22](https://user-images.githubusercontent.com/15115613/57343144-270ba200-7110-11e9-9722-96ed4e35fcb8.png)
![Screenshot at 2019-05-07 20-58-29](https://user-images.githubusercontent.com/15115613/57343145-270ba200-7110-11e9-982d-c29c59361903.png)
![Screenshot at 2019-05-07 20-58-12](https://user-images.githubusercontent.com/15115613/57343146-270ba200-7110-11e9-94bd-989e085cc259.png)
![Screenshot at 2019-05-07 20-57-46](https://user-images.githubusercontent.com/15115613/57343147-27a43880-7110-11e9-9b35-d8b43771c58e.png)
![Screenshot at 2019-05-07 20-57-31](https://user-images.githubusercontent.com/15115613/57343148-27a43880-7110-11e9-88c6-320ed10adba0.png)

**Comment by javashin** [comment]
[RECORD.TIME.txt](https://github.com/InBetweenNames/gentooLTO/files/3155083/RECORD.TIME.txt)
[systemd-analyze-critical-chain.systemd.txt](https://github.com/InBetweenNames/gentooLTO/files/3155084/systemd-analyze-critical-chain.systemd.txt)
[systemd-analyze-blame.systemd.txt](https://github.com/InBetweenNames/gentooLTO/files/3155085/systemd-analyze-blame.systemd.txt)
[services.systemd.txt](https://github.com/InBetweenNames/gentooLTO/files/3155086/services.systemd.txt)
[OLDGENTOO.DMESG.txt](https://github.com/InBetweenNames/gentooLTO/files/3155087/OLDGENTOO.DMESG.txt)

**Comment by javashin** [comment]
time filezilla

real	0m5.376s
user	0m0.203s
sys	0m0.104s

time pluma

real	0m2.850s
user	0m0.286s
sys	0m0.044s

time gnome-disks 

real	0m1.851s
user	0m0.278s
sys	0m0.028s

time engrampa 

real	0m1.988s
user	0m0.098s
sys	0m0.032s

time kvantummanager 

real	0m3.691s
user	0m0.187s
sys	0m0.068s

time mate-calculator 

real	0m1.820s
user	0m0.165s
sys	0m0.016s

time seahorse

real	0m1.509s
user	0m0.166s
sys	0m0.029s

time xfburn

real	0m3.080s
user	0m0.139s
sys	0m0.203s

time PCSX2 

real	0m7.167s
user	0m0.296s
sys	0m0.130s

time citra-qt 

real	0m2.485s
user	0m0.107s
sys	0m0.076s

time PPSSPPSDL

real	0m2.474s
user	0m0.127s
sys	0m0.087s


time gimp

real	0m8.087s
user	0m1.682s
sys	0m0.248s


time eom

real	0m1.395s
user	0m0.117s
sys	0m0.017s


time deluge-gtk 

real	0m10.086s
user	0m1.501s
sys	0m0.198s

time firefox

real	0m14.999s
user	0m4.101s
sys	0m0.818s

time thunderbird 

real	0m14.827s
user	0m2.613s
sys	0m0.387s

time chromium

real	0m14.394s
user	0m0.362s
sys	0m0.276s


time audacious

real	0m2.325s
user	0m0.125s
sys	0m0.044s


 time cheese

real	0m2.466s
user	0m0.371s
sys	0m0.051s


time gnome-mpv

real	0m1.928s
user	0m0.302s
sys	0m0.047s


 time brasero

real	0m3.823s
user	0m0.279s
sys	0m0.037s

time ghb HANDBRAKE

real	0m2.463s
user	0m0.849s
sys	0m0.052s


time spotify 

real	0m6.684s
user	0m0.161s
sys	0m0.153s


time VirtualBox 

real	0m7.280s
user	0m0.337s
sys	0m0.129s


time vmware

real	0m4.409s
user	0m0.671s
sys	0m0.221s

time porthole

real	0m8.791s
user	0m1.898s
sys	0m0.792s


time sudo gparted

real	0m22.808s
user	0m0.552s
sys	0m0.394s


time mate-system-monitor 

real	0m1.105s
user	0m0.142s
sys	0m0.019s

**Comment by javashin** [comment]
NEW GENTOO / GENTOO NEW START HERE >>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<

![Screenshot at 2019-05-07 22-13-55](https://user-images.githubusercontent.com/15115613/57344878-ecf1ce80-7116-11e9-9deb-6392c22c1365.png)
![Screenshot at 2019-05-07 22-13-04](https://user-images.githubusercontent.com/15115613/57344881-ecf1ce80-7116-11e9-953f-bc0aa545e566.png)
![Screenshot at 2019-05-07 22-12-37](https://user-images.githubusercontent.com/15115613/57344884-ed8a6500-7116-11e9-8f67-ff87a4f92139.png)
![Screenshot at 2019-05-07 22-12-03](https://user-images.githubusercontent.com/15115613/57344886-ed8a6500-7116-11e9-9f8f-360a5212dc3f.png)
![Screenshot at 2019-05-07 22-11-56](https://user-images.githubusercontent.com/15115613/57344887-ed8a6500-7116-11e9-84e8-4293bac31767.png)

**Comment by javashin** [comment]
1._First Concern After Enable IPA Boot Time Increased From 1 Minute 2 Seconds
UP To 1 Minute  48 Seconds. On The Same Machine Same Services ETC.

**Comment by javashin** [comment]
[SYSTEMD-ANALYZE_CRITITCALCHAIN_NEWGENTOO.txt](https://github.com/InBetweenNames/gentooLTO/files/3155183/SYSTEMD-ANALYZE_CRITITCALCHAIN_NEWGENTOO.txt)
[SYSTEMD-ANALYZE_BLAME_NEWGENTOO.txt](https://github.com/InBetweenNames/gentooLTO/files/3155184/SYSTEMD-ANALYZE_BLAME_NEWGENTOO.txt)
[SERVICES.SYSTEMD.NEWGENTOO.txt](https://github.com/InBetweenNames/gentooLTO/files/3155185/SERVICES.SYSTEMD.NEWGENTOO.txt)
[DEMESGNEWGENTOO.txt](https://github.com/InBetweenNames/gentooLTO/files/3155186/DEMESGNEWGENTOO.txt)

**Comment by javashin** [comment]
time filezilla

real	0m6.193s
user	0m0.201s
sys	0m0.125s


 time pluma

real	0m3.815s
user	0m0.278s
sys	0m0.060s

time gnome-disks

real	0m2.946s
user	0m0.335s
sys	0m0.028s

time engrampa

real	0m1.809s
user	0m0.114s
sys	0m0.021s


time kvantummanager

real	0m5.128s
user	0m0.172s
sys	0m0.084s


time mate-calculator

real	0m1.955s
user	0m0.152s
sys	0m0.019s

time seahorse

real	0m2.146s
user	0m0.193s
sys	0m0.046s


time xfburn

real	0m3.988s
user	0m0.142s
sys	0m0.217s



time PCSX2

real	0m8.992s
user	0m0.298s
sys	0m0.145s


 time citra-qt

real	0m3.474s
user	0m0.120s
sys	0m0.081s


time PPSSPPSDL

real	0m2.337s
user	0m0.133s
sys	0m0.068s



time gimp

real	0m14.927s
user	0m3.842s
sys	0m0.329s


 time eom

real	0m1.859s
user	0m0.120s
sys	0m0.028s


 time deluge-gtk

real	0m17.102s
user	0m1.503s
sys	0m0.263s


time firefox

real	0m9.378s
user	0m2.106s
sys	0m0.506s



time thunderbird

real	0m14.584s
user	0m2.655s
sys	0m0.403s


 time audacious

real	0m2.261s
user	0m0.085s
sys	0m0.027s


 time cheese

real	0m2.988s
user	0m0.387s
sys	0m0.078s


time gnome-mpv

real	0m2.326s
user	0m0.302s
sys	0m0.055s


 time brasero

real	0m4.964s
user	0m0.279s
sys	0m0.046s


time ghb 

real	0m2.873s
user	0m0.899s
sys	0m0.047s


time spotify

real	0m9.796s
user	0m0.185s
sys	0m0.188s

time VirtualBox

real	0m6.346s
user	0m0.337s
sys	0m0.142s


time vmware

real	0m5.040s
user	0m0.687s
sys	0m0.240s


 time porthole

real	0m8.396s
user	0m1.091s
sys	0m0.239s



time sudo gparted

real	0m28.624s
user	0m0.543s
sys	0m0.475s


time mate-system-monitor

real	0m1.616s
user	0m0.140s
sys	0m0.027s

**Comment by javashin** [comment]
Conclusion Some Ups , Some Downs , More Downs Slowdowns With NewGentoo + IPA Than OLDGentoo No IPA , What Do You People Think For Me Everything Seems To Be Slow , Note On Both I Created New Users For The Tests And Used The Same Kernel And In The Same ZFS Filesystem I Dont See Any Improvement Or Optimization At All and Booting Really Slow Some Apps Start Faster But Not All There Are A Lot of Them Which Start Slower Than My Old Installation Of Gentoo And The Old One Have More PKGS Compiled With Lto + -O3 + Graphite and Others Flags That Are The Same On Both OLD_NOIPA & NEW+IPA  . Thanks For Everthing @InBetweenNames This LTO OVERLAY is THE BEST SOURCE for Rice . LOL

**Comment by javashin** [comment]
eix-update is slow and emerge --update --newuse --deep --with-bdeps=y @world is more slow .............

**Comment by InBetweenNames** [comment]
Very interesting! Before pinning it down directly to `-fipa-pta`, I noticed you are using two different versions of GCC in the benchmarks.  Could I trouble you to rebuild world using GCC 9 and without `-fipa-pta` and try again?

**Comment by barolo** [comment]
@javashin It's a commendable effort, but you need several runs and average them, at least, to have any semblance of correctness. 
On a SSD [ and parts in RAM ] I couldn't care less about startup time, as almost everything launches instantly [ even spotify ]. I'd be more interested in run-time performance of things like compilers, web browsers, mesa, etc.

**Comment by javashin** [comment]
Claro , sure im in the middle of it i changed my old gentoo profile to normal profile without systemd , now using openrc and elogind on the old gentoo and recompiling everything with my sane cflags 

i recommend this cflags never got problems with anything before : 

NTHREADS="3"
MAKEOPTS="-j3"
source /etc/portage/make.conf.lto
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold ${CFLAGS} -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
CPPFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
LDFLAGS="${LDFLAGS} -Wl,--hash-style=gnu"

i was using with  -floop-block -floop-interchange -floop-strip-mine  but since those are included on -O3 and GRAPHITE i removed them to avoid redundancy

**Comment by javashin** [comment]
@barolo  yeah this is an old laptop with an HDD not sdd maybe thats why no one notice all this :+1:
