### ISSUE TITLE
Gcc Makes My Cpu Too Hot.

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#309]
before i compiled gcc with :-1: 
EXTRA_ECONF='--with-build-config=bootstrap-lto'
USE=pgo
BOOT_CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fipa-pta -fno-plt -fno-stack-protector"

CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fno-stack-protector -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
CPPFLAGS="${CFLAGS}"

The Temperatures Where Ok At 68C-70C compiling with -j3 and -flto=3

Now Gets Too Hot from 72C-75C compiling with -j3 and -flto=3 . 

Something Wrong Happen .

**Comment by javashin** [comment]
But the thing is that gcc is faster now compiling the kernel with -j3 took 18 minutes before 
now with this gcc takes real	16m51.456s

**Comment by InBetweenNames** [comment]
This makes sense -- your processor is probably being better utilized than
it was previously.  It's not too surprising that it's drawing more power as
a result.  More areas of the chip are active means more power draw.  It may
be that vector units on your processor are being used that weren't
previously, and those definitely increase power consumption.

**Comment by javashin** [comment]
yay good to know

**Comment by javashin** [comment]
Used More Extreme Gcc Conf Cflags To Compile Gcc And Temperatures Remains OK Something wrong was happening on the other installation 


i used this now :  


CC="gcc"
CXX="g++"
AR="gcc-ar"
NM="gcc-nm"
RANLIB="gcc-ranlib"
STRIP="gcc-strip"
LD="ld.gold"


EXTRA_ECONF='--with-build-config=bootstrap-lto'



BOOT_CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-ld=gold -O3 -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe"

CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
CPPFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"

**Comment by InBetweenNames** [comment]
You may get better results without `-funroll-loops` as it does override the compiler's judgement and may be worse for your processor's instruction cache.  I would only enable that flag when it has been demonstrated to be helpful on a particular package.  GCC is very good at deciding when to unroll loops on its own.

**Comment by javashin** [comment]
ok thanks for the info i will remove unroll loops also i have defualt-gold useflag on  binutils but the compiler now with those BOOT_CFLAGS is stable and dont make the temps so higher like before

**Comment by javashin** [comment]
and yes that its a gcc only conf in /etc/portage/env for gcc only

**Comment by javashin** [comment]
and gcc lto1 is linking faster that i like from this new build with all the flags
