### ISSUE TITLE
media-gfx/libimagequant ???

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#312]
>>> Emerging (2 of 16) media-gfx/libimagequant-2.12.2::gentoo
 * libimagequant-2.12.2.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                     [ ok ]
 * FEATURES='assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr'
 * CFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CXXFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CPPFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe'
 * FFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * FCFLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * F77FLAGS='-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * LDFLAGS='-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe'
 * MAKEOPTS='-j3'
 * gcc (Gentoo 9.1.0) 9.1.0
 * Linux igloo-l440 5.1.0-gentoo #1 SMP PREEMPT Thu May 9 20:47:43 AST 2019 x86_64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz GenuineIntel GNU/Linux
>>> Unpacking source...
>>> Unpacking libimagequant-2.12.2.tar.gz to /var/tmp/portage/media-gfx/libimagequant-2.12.2/work
>>> Source unpacked in /var/tmp/portage/media-gfx/libimagequant-2.12.2/work
>>> Preparing source in /var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2 ...
 * Applying libimagequant-2.12.2-respect-CFLAGS.patch ...                                                                                      [ ok ]
 * Applying libimagequant-2.12.2-fix-pkgconfig.patch ...                                                                                       [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2 ...

  Compiler: x86_64-pc-linux-gnu-gcc
     Debug: no
       SSE: yes
    OpenMP: yes

>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2 ...
make -j3 shared imagequant.pc 
x86_64-pc-linux-gnu-gcc -fPIC -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -fopenmp -fexcess-precision=fast -c pam.c -o pam.lo
x86_64-pc-linux-gnu-gcc -fPIC -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -fopenmp -fexcess-precision=fast -c mediancut.c -o mediancut.lo
x86_64-pc-linux-gnu-gcc -fPIC -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -fipa-pta -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -pipe -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -fopenmp -fexcess-precision=fast -c blur.c -o blur.lo
mediancut.c: In function ‘prepare_sort’:
mediancut.c:198:13: error: ‘colors’ not specified in enclosing ‘parallel’
  198 |     #pragma omp parallel for if (colors > 25000) \
      |             ^~~
mediancut.c:198:13: error: enclosing ‘parallel’
mediancut.c:201:56: error: ‘ind1’ not specified in enclosing ‘parallel’
  201 |         const float *chans = (const float *)&achv[ind1 + i].acolor;
      |                                                   ~~~~~^~~
mediancut.c:198:13: error: enclosing ‘parallel’
  198 |     #pragma omp parallel for if (colors > 25000) \
      |             ^~~
make: *** [Makefile:55: mediancut.lo] Error 1
make: *** Waiting for unfinished jobs....
 * ERROR: media-gfx/libimagequant-2.12.2::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/libimagequant-2.12.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/libimagequant-2.12.2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/media-gfx/libimagequant-2.12.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-gfx/libimagequant-2.12.2/temp/environment'.
 * Working directory: '/var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2'
 * S: '/var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2'

>>> Failed to emerge media-gfx/libimagequant-2.12.2, Log file:

>>>  '/var/tmp/portage/media-gfx/libimagequant-2.12.2/temp/build.log'

 * Messages for package media-gfx/libimagequant-2.12.2:

 * ERROR: media-gfx/libimagequant-2.12.2::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/libimagequant-2.12.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/libimagequant-2.12.2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/media-gfx/libimagequant-2.12.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-gfx/libimagequant-2.12.2/temp/environment'.
 * Working directory: '/var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2'
 * S: '/var/tmp/portage/media-gfx/libimagequant-2.12.2/work/libimagequant-2.12.2'

 * GNU info directory index is up-to-date.

**Comment by javashin** [comment]
is OpenMP broken on gcc 9.1 ?

**Comment by nivedita76** [comment]
https://www.gnu.org/software/gcc/gcc-9/porting_to.html

See the OpenMP data sharing section, there's been a change to conform to the OpenMP standard.
