### ISSUE TITLE
If After Emerge -e World and Using ~amd64 Find Yourself With No Sound.

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#327]
Pulseaudio is broken because of alsa 1.1.9
pulseaudio needs this patch , add it on user patches /etc/portage/patches also needs automake 1.15
alsa: Fix inclusion of use-case.h
https://github.com/pulseaudio/pulseaudio/commit/b89d33bb182c42db5ad3987b0e91b7bf62f421e8
fix >>> undefined reference to `pa_alsa_ucm_device_update_available

PATCH:
https://gist.github.com/javashin/c0c31779190ac511563de1e35670f712 

OFFTOPIC But Helpful To not Think The CFLAGS OR LDFLAGS Did This Like I Was ... a Little Crazy Seeking For Solution .
Who Can Lives Without Sound And Since We Use Some Experimental Stuff Who Knows Whats Breaks What Until You got To The Bottom Of The root Of The Problem.

**Comment by javashin** [comment]
OFFTOPIC But Helpful To not Think The CFLAGS OR LDFLAGS Did This Like I Was ... a Little Crazy Seeking For Solution .

**Comment by javashin** [comment]
Who Can Lives Without Sound And Since We Use Some Experimental Stuff Who Knows Whats Breaks What Until You got To The Bottom Of The root Of The Problem.

**Comment by pchome** [comment]
@javashin 
FYI: https://guides.github.com/features/mastering-markdown/

_PATCH START
...
PATCH END_

should be 

\```patch
...
\```

or https://gist.github.com/
for better readability.

**Comment by javashin** [comment]
thanks @pchome im learning a lot these days .

**Comment by pchome** [comment]
FYI2: also, there is "Edit" in message menu (top right), in case you want something to add or correct. No need to post several messages in a row ;)

**Comment by InBetweenNames** [comment]
This doesn't seem to be LTO related -- is it just a plain bug?

**Comment by javashin** [comment]
yes plain bug closing

**Comment by bobwya** [comment]
> @javashin
> FYI: https://guides.github.com/features/mastering-markdown/
> 
> _PATCH START ... PATCH END_
> 
> should be
> 
> ```patch
> ...
> ```
> 
> or https://gist.github.com/
> for better readability.

@pchome 

What about the box, under the **Issue** edit box, with the words:

_"Attach files by dragging & dropping, selecting or pasting them"_

This is what we should be directing new users to use - for their log files and patches (if they don't understand pull-requests)!

Although it defies my reality, that people can't find these things themselves... 8->

**Comment by pchome** [comment]
@bobwya 
The **[M](https://guides.github.com/features/mastering-markdown/)** link there too.

I don't know about "dragging & dropping", never used this, but the "Attach dialog" have only a few formats supported/allowed. And `*.patch` isn't there.

User should rename *.patch into something else, or zip/gzip file.
`*.log` should be fine.

See "edited" list of the first message, I don't know user's motivation, and I don't care, but my response could be interpreted as "If you want insert a piece of code -- better use formatting".
