### ISSUE TITLE
media-libs/libcaca No longer builds

### ISSUE THREAD

**Issue by lovesegfault** [InBetweenNames/gentooLTO#330]
media-libs/libcaca is no longer building. Log attached.
[media-libs:libcaca-0.99_beta19:20190523-173849.log](https://github.com/InBetweenNames/gentooLTO/files/3213488/media-libs.libcaca-0.99_beta19.20190523-173849.log)

**Comment by javashin** [comment]
media-libs/libcaca-0.99_beta19::gentoo was built with the following:
USE="X cxx ncurses opengl python truetype -doc -imlib -java -mono (-ruby) -slang -static-libs -test" ABI_X86="32 (64) (-x32)" PYTHON_TARGETS="python2_7"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -std=c++11"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe"

builds here

**Comment by lovesegfault** [comment]
@javashin Could you attach your `make.conf`?

**Comment by javashin** [comment]
https://gist.github.com/javashin/0456dfd30ed0a945d0847a2793f2971c
