### ISSUE TITLE
sys-apps/nix No longer builds

### ISSUE THREAD

**Issue by lovesegfault** [InBetweenNames/gentooLTO#331]
Seems to be an issue with gold, might need enforcing bfd. Log attached.
[sys-apps:nix-2.1.3:20190523-173955.log](https://github.com/InBetweenNames/gentooLTO/files/3213504/sys-apps.nix-2.1.3.20190523-173955.log)

**Comment by InBetweenNames** [comment]
I'm able to get this to build if I manually do a `binutils-config --linker ld.bfd` and then emerge it.  But passing `-fuse-ld=bfd` doesn't seem to be sufficient, nor does `-Wl,-fuse-ld=bfd`.  Weird.

**Comment by InBetweenNames** [comment]
Closing as reverting default linker to `ld.bfd` fixed these kinds of problems.
