### ISSUE TITLE
gnome-base/gnome-control-center runtime failure

### ISSUE THREAD

**Issue by automorphism88** [InBetweenNames/gentooLTO#335]
After a system rebuild with gcc 9.1 using the default flags from `make.conf.lto`, `gnome-control-center` fails to launch, although there are no errors at compile time. Rebuilding `gnome-base/gnome-control-center` with safe flags (just `-O2 -pipe -march=native`) fails to fix the issue, so it appears there is a problem with one of the flags used for one or more of the dependencies. I haven't yet tested all of them to figure out which it is and which flag causes the issue but saw https://github.com/InBetweenNames/gentooLTO/issues/275 and thought it might be something similar.

This is the error:
```
**
ERROR:../gnome-control-center-3.30.3/shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
```

**Comment by javashin** [comment]
https://bbs.archlinux.org/viewtopic.php?id=242686

**Comment by automorphism88** [comment]
Thanks! My first failed test was within a gnome session but others weren't. Just tried it again in a gnome session and it did work. That's currently with some stuff recompiled with the safe flags so it's not 100% certain that it's not a gentoo-lto issue but if I get this issue again while in a gnome-session I'll try to debug it further. In the meantime I'm closing this issue.

**Comment by InBetweenNames** [comment]
No worries, thanks for the followup!
