### ISSUE TITLE
Kernel doesn't build with gold

### ISSUE THREAD

**Issue by petronio** [InBetweenNames/gentooLTO#338]
The kernel has had issues with the gold linker for a long time. Even now you get errors such as `Invalid absolute R_X86_64_32S relocation: _etext` if you attempt to build with gold. Since the compile happens outside of portage, we can't simply override the ld in lto-workarounds. We can, however, patch the kernel's Makefile to force use of ld.bfd . This is easily handled through creating a patch file `/etc/portage/patches/sys-kernel/gentoo-sources/9999-force-bfd-linker.patch`

I'm adding this as an issue rather than a PR since I'm not sure what your preferred method of deploying it is.

Funny enough, GitHub doesn't seem to support attaching a .patch, so the attachment has an extra .txt to make it happy. Do note that you can't simply copy and paste, as there's some weird line ending or spacing stuff going on and it'll end up getting rejected if you do. [9999-force-bfd-linker.patch.txt](https://github.com/InBetweenNames/gentooLTO/files/3243094/9999-force-bfd-linker.patch.txt)

**Comment by jiblime** [comment]
@petronio,
Unless I am overlooking something, I have been building kernels with GCC 8.3.0/9.1.0 and ld.gold with success. I _used to_ have to use ld.bfd but now I don't have any issues (although I do not know the steps to reproduce). You can also use `binutils-config --linker ld.bfd` right before compilation.

If it helps any, I think it has to do with binutils (and I always had compiles fail with Gawk versions >=5). Here's my build info for binutils:
```
sys-devel/binutils-2.32-r1::gentoo was built with the following:

USE="cxx default-gold gold multitarget nls plugins -doc -static-libs -test" ABI_X86="(64)"
CFLAGS="-march=skylake -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -O2"
CXXFLAGS="-march=skylake -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -O2"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -march=skylake -pipe -O2"
```

Actually the thing I am likely overlooking is that I don't use gentoo-sources; I use pf-sources from the jps-gentoo overlay. It has an option to compile with -O3 ^^

**Comment by lferra** [comment]
> Unless I am overlooking something, I have been building kernels with GCC 8.3.0/9.1.0 and ld.gold with 
> success.

Same here: actually I've stumbled upon this thread because of the `Invalid absolute R_X86_64_32S relocation: _etext` issue I'm experiencing building the last kernel 5.1.6 (genkernel-next + ck-sources with a local overlay ebuild).

```
  CC      arch/x86/boot/cpu.o
  OBJCOPY arch/x86/boot/compressed/vmlinux.bin
  CC      arch/x86/boot/compressed/error.o
  RELOCS  arch/x86/boot/compressed/vmlinux.relocs
Invalid absolute R_X86_64_32S relocation: _etext
make[2]: *** [arch/x86/boot/compressed/Makefile:130: arch/x86/boot/compressed/vmlinux.relocs] Error 1
```

I'm using GCC 9.1.0/Binutils 2.32 and previous kernel 5.1.5 builds successfully with the same configuration

I've noticed this commit in 5.1.6:

```
commit a43bf1035db6f04dd6432e6c7bc968c891399916
Author: Kees Cook <keescook@chromium.org>
Date:   Tue Apr 23 11:38:27 2019 -0700

    x86/build: Move _etext to actual end of .text
    
    [ Upstream commit 392bef709659abea614abfe53cf228e7a59876a4 ]
    
    When building x86 with Clang LTO and CFI, CFI jump regions are
    automatically added to the end of the .text section late in linking. As a
    result, the _etext position was being labelled before the appended jump
    regions, causing confusion about where the boundaries of the executable
    region actually are in the running kernel, and broke at least the fault
    injection code. This moves the _etext mark to outside (and immediately
    after) the .text area, as it already the case on other architectures
    (e.g. arm64, arm).
    
    Reported-and-tested-by: Sami Tolvanen <samitolvanen@google.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>
    Cc: Borislav Petkov <bp@suse.de>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Link: http://lkml.kernel.org/r/20190423183827.GA4012@beast
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Signed-off-by: Sasha Levin <sashal@kernel.org>

```
I've found also this thread with a Gentoo user having issues: https://lkml.org/lkml/2019/4/23/938, but I'm not sure if it could be related.

Anyway, after switching to ld.bfd via `binutils-config --linker ld.bfd` kernel 5.1.6 build successfully.

**Comment by javashin** [comment]
Same Here

**Comment by ionenwks** [comment]
I've been using gold for the kernel a long time as well (currently on 5.1.6), albeit it's a very lean kernel rather than a more complete generic one (gold is system default, bfd never gets used including some workarounds to prevent gentoo from forcing it). I'm still using gcc 8.3 for the kernel though.

**Comment by javashin** [comment]
i had to binutils-config --linker ld.bfd on kernel 5.1.6 to build successfully with gcc 9.1

**Comment by jiblime** [comment]
Echoing the same for kernel 5.1.6. Making modules with ld.gold was fine, but I had to rerun `make bzImage` with ld.bfd. 

Sidenote, you can set optimization flags in the top-level Makefile (CONFIG_CC_OPTIMIZE_FOR*). I used `-O3 -fgraphite-identity -floop-nest-optimize`. I wouldn't know how to check if it applied, though...

**Comment by ionenwks** [comment]
^ You can use `make V=1` to see the commands being ran and confirm whatever is happening. That aside, don't overdo it with optimizations on the kernel, wrong codegen issues recently led to filesystem corruption when using bcache and gcc9 (it's fixed now I think).

**Comment by jiblime** [comment]
@ionenwks, For the kernel using V=x doesn't seem to output CFLAGS. They should be applying, though; adding -flto throws errors where it wasn't before. I've since switched to appending flags in scripts/Makefile.build and am trying `-falign-functions=32 -fsched2-use-superblocks -fipa-pta -fno-semantic-interposition -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-plt`. Objtool is throwing errors but it (hopefully) has to do with false positives. Are there any scheduler benchmarking tools out there besides perf?

**Comment by asaparov** [comment]
Same here, `ld.gold` leads to an `Invalid absolute R_X86_64_32S relocation: _etext` error for me too. For now, switching to `ld.bfd` right before compiling works.

**Comment by DarkPoe** [comment]
> @ionenwks, For the kernel using V=x doesn't seem to output CFLAGS. They should be applying, though; adding -flto throws errors where it wasn't before. I've since switched to appending flags in scripts/Makefile.build and am trying `-falign-functions=32 -fsched2-use-superblocks -fipa-pta -fno-semantic-interposition -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-plt`. Objtool is throwing errors but it (hopefully) has to do with false positives. Are there any scheduler benchmarking tools out there besides perf?

I fixed -flto with -ffat-lto-objects and when building with -fno-plt, kernel doesn't boot... Had to remove it

**Comment by automorphism88** [comment]
I get this error when I try to build the kernel with gold and standard flags:
```
arch/x86/entry/vdso/vclock_gettime.c:144: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:129: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:152: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:157: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:156: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:203: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:217: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
arch/x86/entry/vdso/vclock_gettime.c:218: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
./include/linux/compiler.h:193: error: relocation overflow: reference to 'vvar_vsyscall_gtod_data'
```

Using `make LD=ld.bfd` fixes it, no need to run `binutils-config` or patch the kernel. It seems like this fix could be implemented into genkernel as well (or any other script that's being used to compile the kernel), which would avoid the need to patch the kernel makefile.

**Comment by lferra** [comment]
well, they reverted commit `392bef709659abea614abfe53cf228e7a59876a4` in 5.1.8, and now I can successfully build kernel with gold again.

```
commit 474ec2dcfbcf268a4124145b5e08847595f67a4c
Author: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Date:   Wed Jun 5 20:40:30 2019 +0200

    Revert "x86/build: Move _etext to actual end of .text"
    
    This reverts commit 392bef709659abea614abfe53cf228e7a59876a4.
    
    It seems to cause lots of problems when using the gold linker, and no
    one really needs this at the moment, so just revert it from the stable
    trees.
```

**Comment by javashin** [comment]
NIce

**Comment by automorphism88** [comment]
> well, they reverted commit `392bef709659abea614abfe53cf228e7a59876a4` in 5.1.8, and now I can successfully build kernel with gold again.

I just downloaded 5.1.8 and got the same error I copy/pasted in my previous comment when I tried to build it with gold. That wasn't the same error @asaparov mentioned above though. I didn't realize anyone was able to build the kernel with gold - perhaps it's a question of which kernel config options are enabled?

**Comment by ionenwks** [comment]
@automorphism88 It most likely is, I haven't gotten any of the errors described in this thread even with 5.1.7 with my usual configs, gold linker, and gcc 8.3, but it's a very lean kernel that would work only for my box and things I use with it. If I try a generic 5.1.7 kernel with `make defconfig` I get `_etext` errors, with 5.1.8 it builds fine, so I would assume in your case it's a non-default configuration that's causing it but I have no idea which. May want to check if a `defconfig` kernel builds fine for you for starters.

**Comment by petronio** [comment]
Closing issue as we no longer use gold by default
