### ISSUE TITLE
lto-rebuild empty list after upgrading to gcc 9

### ISSUE THREAD

**Issue by funghetto** [InBetweenNames/gentooLTO#343]
Is it normal that lto-rebuild outputs: 

> Searching in
>         /usr/lib
>         /usr/lib64
>         /usr/lib32
> for static archives that were built using a different GCC...
> 
> No problems found!

after have I just upgraded from gcc 8 to 9?

**Comment by jiblime** [comment]
I can confirm lto-rebuild does not populate with 9.1.0-r1 after having upgrading from 9.1.0, but can't confirm when it stopped working.
Profile: default/linux/amd64/17.1/desktop/plasma/systemd

I have tried:
```
lto-rebuild -a
lto-rebuild -l
lto-rebuild -r
eselect gcc set 8.3.0-r1
lto-rebuild -l
lto-rebuild -r
emerge -1 =lto-rebuild-0.9.5
[...]
```
All output:
```
Searching in
        /usr/lib
        /usr/lib64
        /usr/lib32
for static archives that were built using a different GCC...

No problems found!
```
Here's the tail end of `gcc -dumpspecs`, I suspect I've done something wrong but can't pinpoint it.
```
*link_command:
%{!fsyntax-only:%{!c:%{!M:%{!MM:%{!E:%{!S:    %(linker) %{!fno-use-linker-plugin:%{!fno-lto:     -plugin %(linker_plugin_file)     -plugin-opt=%(lto_wrapper)     -plugin-opt=-fresolution=%u.res     %{flinker-output=*:-plugin-opt=-linker-output-known}     %{!nostdlib:%{!nodefaultlibs:%:pass-through-libs(%(link_gcc_c_sequence))}}     }}%{flto|flto=*:%<fcompare-debug*}     %{flto} %{fno-lto} %{flto=*} %l %{static|shared|r:;!no-pie:-pie} %{fuse-ld=*:-fuse-ld=%*}  %{gz|gz=zlib:--compress-debug-sections=zlib} %{gz=none:--compress-debug-sections=none} %{gz=zlib-gnu:--compress-debug-sections=zlib-gnu} %X %{o*} %{e*} %{N} %{n} %{r}    %{s} %{t} %{u*} %{z} %{Z} %{!nostdlib:%{!r:%{!nostartfiles:%S}}}     %{static|no-pie|static-pie:} %@{L*} %(mfwrap) %(link_libgcc) %{!nostdlib:%{!r:%{fvtable-verify=std: -lvtv -u_vtable_map_vars_start -u_vtable_map_vars_end}    %{fvtable-verify=preinit: -lvtv -u_vtable_map_vars_start -u_vtable_map_vars_end}}} %{!nostdlib:%{!r:%{!nodefaultlibs:%{%:sanitize(address):%{!shared:libasan_preinit%O%s} %{static-libasan:%{!shared:-Bstatic --whole-archive -lasan --no-whole-archive -Bdynamic}}%{!static-libasan:-lasan}}     %{%:sanitize(thread):%{!shared:libtsan_preinit%O%s} %{static-libtsan:%{!shared:-Bstatic --whole-archive -ltsan --no-whole-archive -Bdynamic}}%{!static-libtsan:-ltsan}}     %{%:sanitize(leak):%{!shared:liblsan_preinit%O%s} %{static-liblsan:%{!shared:-Bstatic --whole-archive -llsan --no-whole-archive -Bdynamic}}%{!static-liblsan:-llsan}}}}} %o      %{fopenacc|fopenmp|%:gt(%{ftree-parallelize-loops=*:%*} 1):     %:include(libgomp.spec)%(link_gomp)}    %{fgnu-tm:%:include(libitm.spec)%(link_itm)}    %(mflib)  %{fsplit-stack: --wrap=pthread_create}    %{fprofile-arcs|fprofile-generate*|coverage:-lgcov} %{!nostdlib:%{!r:%{!nodefaultlibs:%{%:sanitize(address): %{static-libasan|static:%:include(libsanitizer.spec)%(link_libasan)}    %{static:%ecannot specify -static with -fsanitize=address}}    %{%:sanitize(thread): %{static-libtsan|static:%:include(libsanitizer.spec)%(link_libtsan)}    %{static:%ecannot specify -static with -fsanitize=thread}}    %{%:sanitize(undefined):%{static-libubsan:-Bstatic} -lubsan %{static-libubsan:-Bdynamic} %{static-libubsan|static:%:include(libsanitizer.spec)%(link_libubsan)}}    %{%:sanitize(leak): %{static-liblsan|static:%:include(libsanitizer.spec)%(link_liblsan)}}}}}     %{!nostdlib:%{!r:%{!nodefaultlibs:%(link_ssp) %(link_gcc_c_sequence)}}}    %{!nostdlib:%{!r:%{!nostartfiles:%E}}} %{T*} 
```

**Comment by jelinekto** [comment]
[The previous commit](https://github.com/InBetweenNames/gentooLTO/blob/48f01df1bf7798f273aeb53eb1fa0d9daa15ffa4/app-portage/lto-rebuild/files/lto-rebuild) seems to be working.

**Comment by InBetweenNames** [comment]
GCC 9.1.0-r1 is a revision on Gentoo's side and not upstream, right?  In that case, there should be no need to lto-rebuild.

**Comment by funghetto** [comment]
But I upgraded from GCC 8 to 9.

**Comment by InBetweenNames** [comment]
Yeah that I can't explain.  A refactor was done on lto-rebuild to move more logic into `find` -- maybe that has something to do with it.

**Comment by InBetweenNames** [comment]
Just tested this and it seems to be working fine here.

**Comment by InBetweenNames** [comment]
`lto-rebuild` picks up whatever your default GCC is -- you can use `eselect gcc` or `gcc-config` to pick what that is.  So although you installed GCC 9.1.0, it may not have been selected as the default compiler.

**Comment by funghetto** [comment]
Really weird, I have GCC 9.1.0 selected.

**Comment by elsandosgrande** [comment]
Wait, assuming that `-static-libs` is in one's use flags, would `emerge --verbose @system` suffice? I mean, I did that and I do not receive any output from the tool other than that which is shown above.

**Comment by InBetweenNames** [comment]
@funghetto does the previous commit that @jelinekto linked work for you?  If so, I will revert it to the working version.

**Comment by InBetweenNames** [comment]
@elsandosgrande `emerge --verbose @system` probably won't suffice as your `@world` is probably much bigger than your `@system`.

**Comment by elsandosgrande** [comment]
Well, that is great.

**Comment by funghetto** [comment]
@InBetweenNames yes that commit rebuilds a list of packages (small probably because I've already rebuilt every multilib pkg for the profile switch).

**Comment by InBetweenNames** [comment]
@funghetto I think I found the bug -- `GCC_VER` is unset in the latest version which is making the script not pick up anything.

**Comment by InBetweenNames** [comment]
Could you give `app-portage/lto-rebuild-0.9.7` a try?

**Comment by funghetto** [comment]
Tested on my second machine and it works.

**Comment by InBetweenNames** [comment]
Wonderful, thanks!
