### ISSUE TITLE
sys-devel/binutils-9999::core-kit (Missing IUSE: gold)

### ISSUE THREAD

**Issue by nigga-china** [InBetweenNames/gentooLTO#348]
Well, I downloaded the Funtoo's stage3 and tried to follow the instructions from gentooLTO but when I tried "emerge sys-config/ltoize" appeared an message saying:

> !!! All ebuilds that could satisfy ">=sys-devel/binutils-2.32:*[gold]" have been masked.
> !!! One of the following masked packages is required to complete your request:
> - sys-devel/binutils-9999::core-kit (Masked by: missing keyword)

Because I use Funtoo, there is no ebuild for binutils-2.32 but only older version and the masked 9999. So I tried to unmask it but seemed that was missing the "gold" IUSE on that ebuild. I added "gold" to the IUSE of that ebuild.

After it, I tried to emerge ltoize again and although the binutils problem be "solved", appeared another problems like errors in eix (while calculating dependencies: "ERROR: app-portage/eix-99999999::mv failed (depend phase)"), and no ebuild to satisfy ">=app-portage/portage-utils-0.80_pre20190605".

I really don't know what to do. In the gentooLTO github repository says "adding it to your /etc/portage/package.accepted_keywords if necessary" but, in real, I tried to do it but I'm not sure if I did it right...

Can anybody explain me how to solve this issue?

**Comment by vkraven** [comment]
Jumping in quickly here as a long time funtoo user: funtoo uses a fork of gentoo portage. Some differences listed here: https://www.funtoo.org/Package:Portage_(Funtoo)

Best place to ask about the portage-utils dependency is probably on the Funtoo IRC. They’re pretty helpful. 

I also recall some basic portage tools (e.g. equery) broke after the shift to meta-repo. ego was modified to replace that functionality. Could be related to eix and it’s dependencies.

**Comment by nigga-china** [comment]
Ok, thank you.

**Comment by InBetweenNames** [comment]
I'm considering removing a few dependencies from ltoize, including requiring `USE=gold`.

**Comment by nigga-china** [comment]
I was using Funtoo when I attempted this. I heard that Funtoo doesn't support this overlay, so sorry for reporting my issues in here; my bad. ;-;

**Comment by InBetweenNames** [comment]
I removed gold as a dependency to ltoize, and reverted GentooLTO to `ld.bfd`.  This might help you using this on Funtoo.

**Comment by nigga-china** [comment]
Ohh, I'll try again so.
