### ISSUE TITLE
gold breaks curl

### ISSUE THREAD

**Issue by KlausMeier** [InBetweenNames/gentooLTO#351]
If I build curl with gold, I can't use it. `spotify 
/opt/spotify/spotify-client/spotify: /usr/lib64/libcurl.so.4: version `CURL_GNUTLS_3' not found (required by /opt/spotify/spotify-client/spotify)` With bfd no problem.

**Comment by javashin** [comment]
is known by almost everybody , patchelf and curl cant be linked with ld.gold , use ld.bfd instead if you want spotify to work

**Comment by KlausMeier** [comment]
Yes, I do it. But at the moment I build everything with the bfd-linker.

**Comment by javashin** [comment]
not me i built everything with ld.gold linker , clang things with ld.lld

**Comment by InBetweenNames** [comment]
Back from the honeymoon now and back into GentooLTO.  Looking into this.

**Comment by InBetweenNames** [comment]
OK -- can confirm `-fuse-ld=bfd` fixes it.  I'll check the ebuild to see if it can be worked around there.

**Comment by Kokokokoka** [comment]
In general, I'd advise to use ld.bfd or ld.lld as ld.gold has bugs and is not really maintained now.

**Comment by InBetweenNames** [comment]
Neither is `ld.bfd` really.  Does `ld.lld` support LTO plugins yet?

**Comment by Kokokokoka** [comment]
> Does `ld.lld` support LTO plugins yet?

I use it system-wide on clang/musl/libstdc++ with thin lto:
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--gc-sections -march=native -O3 -fuse-ld=lld -rtlib=compiler-rt -stdlib=libc++ -Wl,-lto-O3 -Wl,--build-id -Wl,--error-limit=0 -Wl,--icf=all -Wl,--thinlto-jobs=8 -Wl,--threads"

**Comment by InBetweenNames** [comment]
Yeah, AFAIK `ld.lld` does LTO just fine for Clang, but not via the same plugin mechanism GCC uses.  I know it supports the `--plugin` option, but it seemed like last time I checked it was ignored for compatibility (i.e it would accept the option to not error out, but wouldn't actually do anything with it).  It's too bad, because I'd love to try it out.

**Comment by ionenwks** [comment]
Despite using it system-wide for a while, I have been losing faith in Gold as well. Between being rarely used (leading to nothing being tested with it) and being hardly worked on as well, likely will just going to keep running into new issues with little to show for it.

**Comment by InBetweenNames** [comment]
Based on what has been said here and some more digging around, it sounds like we should revert back to `ld.bfd` for GentooLTO default.  It looks like Google has basically abandoned GCC and is focusing nearly all their efforts on LLVM and friends, which is a real shame.  If no bugs we find will be fixed upstream in `ld.gold`, it makes the effort kind of moot.

**Comment by InBetweenNames** [comment]
I'll make it official today and switch my own system back over to `ld.bfd`, and close this issue when I do so.

**Comment by InBetweenNames** [comment]
OK, we are back on `ld.bfd` by default now.
