### ISSUE TITLE
some breakage on gentoo ltoized.

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#352]
i have a system compiled with all the goodies of this overlay and the other day i compiled a normal gentoo no-multilib using just paludis and Cflags -march=native -O3 and today i notice this in inxi which is a perl script app and screenfetch another script based on gawk bash etc , 

with gentoo ltoized i get this on screenfetch ::
screenfetch 
awk: cmd. line:7: warning: regexp escape sequence `\"' is not a known regexp operator

and on gentoo no-multilib with no lto that line dont show up never 

and inxi give me this   ::

inxi 
Argument "" isn't numeric in numeric eq (==) at ./inxi line 378.

and gentoo no lto dont have this problem either

, having same versions of pkgs and deps on gentoo ~amd64

anyone can confirm this ?

**Comment by javashin** [comment]
well i fixed inxi , looks like after recompile bash with sane cflags -O3 -march=native i dont have 
Argument "" isn't numeric in numeric eq (==) at ./inxi line 378.

**Comment by ionenwks** [comment]
In case of awk, it just sounds like gawk 5.0.0. This is common and broke a lot of things, even the kernel outputs some errors ( https://bugzilla.kernel.org/show_bug.cgi?id=203337 ), nothing to do with optimizations), did you change awk version?

**Comment by javashin** [comment]
ok let me downgrade and see thanks

**Comment by javashin** [comment]
oh yes screenfetch fixed after downgrade gawk to 4.2.1  closing ,


but i learn something from this issue "bash" dont like lto or other optimizations after recompile bash with sane cflags inxi dont show up "Argument "" isn't numeric in numeric eq (==) at ./inxi line 378."
