### ISSUE TITLE
All ebuilds that could satisfy ">=sys-devel/binutils-2.32:*[gold]" have been masked.

### ISSUE THREAD

**Issue by nigga-china** [InBetweenNames/gentooLTO#353]
I'm trying to install gentooLTO but when I try to emerge ltoize this message is displayed and I can't proceed with the installation. Can anybody help to install, please? I have no much experience with portage, so I don't know how to solve this issue.

**Comment by OpenSourceAnarchist** [comment]
I'm not 100% sure but this looks like you are running a stable setup. Switching to ~amd64 (if you have a 64 bit system) should fix it, but it does mean you'll be following unstable packages (usually never an issue, but something to keep in mind).

Else, you can look up unmasking and just unmask core packages like gcc and binutils. That seems more unstable than running unstable itself to me, though!

**Comment by ionenwks** [comment]
Generally it's probably better to stick to a (fully) ~unstable if going to use gentooLTO. I think most users do so and as a result not much get tested from stable packages anymore (I feel gentooLTO needs to have a clear stance as to which it supports and recommend it in the documentation).

If you wish for a stable system with little trouble, you shouldn't use gentooLTO in the first place.

**Comment by ionenwks** [comment]
^ That aside, an error about being masked sounds strange. This should just about accepted keywords if stable vs unstable (not that I have a stable system around to check). Is it some custom version of gentoo? Do you have a old /etc/portage/package.mask laying around? I feel like the only situation where this could normally be masked is if not using a linux profile.

**Comment by nigga-china** [comment]
I tried it on Funtoo in VirtualBox. I just did layman -a mv layman -a lto-overlay and emerge ltoize and the only ebuild that could satisfy this dependence was a masked binutils (9999). I don't know how to switch to ~amd64, I would like if someone explain to me. I'm very young in the Linux world; I started using Linux about 5 months ago, so I have no much experience.

**Comment by OpenSourceAnarchist** [comment]
Funtoo is not supported by this overlay as far as I'm aware. Like @ionenwks said, an unstable Gentoo setup is what the vast majority of users run here. Mixing an overpay for Gentoo with a Funtoo system will never be fun :)

**Comment by nigga-china** [comment]
So sad. ;-;
But thanks to everyone! :><3

**Comment by InBetweenNames** [comment]
If there's an easy way to support Funtoo, I would absolutely be willing to do that.  I agree the README should be amended to clarify that only `~*` is generally supported, not stable.  I use `~amd64` and `~arm` myself.

**Comment by InBetweenNames** [comment]
Also, note that [gold] was removed as as a dependency today with the reversion to `ld.bfd`
