### ISSUE TITLE
Missing news announcements 

### ISSUE THREAD

**Issue by nivedita76** [InBetweenNames/gentooLTO#356]
Not sure what is going on but eselect news list is not showing me the 5/22 and 6/18 items. The older ones do show up.

**Comment by InBetweenNames** [comment]
Oh weird.  I'll take a look.

**Comment by javashin** [comment]
yeah for me too 
2019-06-05	amd64 17.1 profiles are now stable 
is missing

**Comment by javashin** [comment]
never mind it will not show up because im on 17.1 profile long time ago

**Comment by InBetweenNames** [comment]
I found the bug!  I forgot to add the language to the files.
