### ISSUE TITLE
How do I diagnose/debug why/which optimization flags will cause an ebuild to fail? (qtcore)

### ISSUE THREAD

**Issue by jiblime** [InBetweenNames/gentooLTO#363]
I am interesting in building a new system entirely with all the lto-overlay flags sans ${NOCOMMON} along with my own flags added. However, I don't know how to diagnose why an issue happens in an ebuild, so the limit of my own self-repair is rebuilding everything listed from `equery g ${package}` with saner CFLAGS. What programs can I use to find out why something isn't working?

In this case I cannot build qtcore-5.9999.

Here is what GCC:9.1.0 was built with:
```
USE="cxx fortran graphite lto nls nptl objc openmp pgo (pie) sanitize ssp vtv"
EXTRA_ECONF='--with-build-config=bootstrap-lto'
BOOT_CFLAGS="-O3 -march=native -fgraphite-identity -floop-nest-optimize -fipa-pta -fsched2-use-superblocks -fgcse-sm -fgcse-las -flive-range-shrinkage -falign-functions=64:7:32:3 -flimit-function-alignment -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-plt -fipa-pta -fuse-linker-plugin"
```

Here are the flags in question: 
```
-flto=4 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition 
-fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math 
-fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans 
-fcx-limited-range -fexcess-precision=fast -fdevirtualize-at-ltrans -fno-plt
```
And ones I wanted to try adding on my own:
```
-fsched-pressure -fsched-spec-load -fsched-spec-load-dangerous 
-fsched2-use-superblocks -fgcse-sm -fgcse-las -ftree-parallelize-loops=4
-flive-range-shrinkage -falign-functions=32 -falign-labels=32 -falign-loops=32 
-falign-jumps=32 -flimit-function-alignment
```

I have tried rebuilding all packages needed to build qtcore with `-O2 -march=native -flto=4 -fuse-linker-plugin -pipe` but this error keeps popping up:

```Cannot find file: /var/tmp/portage/dev-qt/qtcore-5.9999/work/qtcore-5.9999/src/tools/qfloat16-tables.```

And here's the build.log in question: [qtcore-5.9999:20190628-022755.log](https://github.com/InBetweenNames/gentooLTO/files/3337345/qtcore-5.9999.20190628-022755.log)

EDIT:
Seems like it was an issue with dev-qt/qtcore-5.9999 and not optimization flags itself, as 5.13.9999 is fine. Regardless of the specific example, how would I be able to have know where the source of the problem is?

**Comment by InBetweenNames** [comment]
https://github.com/InBetweenNames/gentooLTO/wiki/Debugging

**Comment by InBetweenNames** [comment]
Now, for the `qtcore-5.9999` case, that's an ebuild problem for sure and not LTO related.

It can be quite hard to figure out why a particular package isn't playing nice with LTO, in general.  I've tried to summarize a few things in the article I posted, but it's not comprehensive at all.  Compile time errors are much easier to debug than runtime errors, for example.

**Comment by jiblime** [comment]
Thanks @InBetweenNames. It turns out not just my global CFLAGS were causing issues but GCC compiled with with that set of BOOT_CFLAGS was unable to compile random packages like dev-lang/perl-5.30.0. Is there a way to test the sanity of a particular package at runtime? I'd like to be able to do so for bigger packages like GCC or Qt libraries but judging by 'debug' USE flags this is per-package and not that simple.

**Comment by javashin** [comment]
seems like you are doing something wrong

**Comment by javashin** [comment]
Look At my /etc/portage/env/gcc

CC="gcc"
CXX="g++"
AR="gcc-ar"
NM="gcc-nm"
RANLIB="gcc-ranlib"
STRIP="gcc-strip"
LD="ld.gold"


EXTRA_ECONF='--with-build-config=bootstrap-lto'



BOOT_CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fuse-ld=gold -O3 -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe"

CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
CPPFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"


and i have no problem with any Big pkg set like QT or Perl

**Comment by javashin** [comment]
+++ 

sys-devel/gcc-9.1.0-r1::gentoo was built with the following:
USE="cxx fortran graphite lto (multilib) nls nptl openmp pch pgo sanitize vtv (-altivec) -d -debug -doc (-fixed-point) -go (-hardened) (-jit) (-libssp) -objc -objc++ -objc-gc (-pie) (-ssp) -systemtap -test -vanilla" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -fdevirtualize-at-ltrans -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"

**Comment by InBetweenNames** [comment]
@javashin I have to say we've been recommending against:

~~~
AR="gcc-ar"
NM="gcc-nm"
RANLIB="gcc-ranlib"
STRIP="gcc-strip"
~~~

for quite some time.

Also, `LD="ld.gold"` is also no longer advisable (it may work/may not)

~~~
EXTRA_ECONF='--with-build-config=bootstrap-lto'
~~~

The above is no longer necessary with `USE=lto` on `sys-devel/gcc`, which was merged upstream.

~~~
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
~~~

`ld.bfd` actually does nothing beyond `-O1`.  There's also no need for `-z now` since you are using `-fno-plt`.  Also, your linker automatically does `--hash-style=gnu` for you now, so you could just omit modifying your profile's `LDFLAGS` entirely and receive the default `-Wl,-O1 -Wl,--as-needed`.

@jiblime thanks for the heads up with `BOOT_CFLAGS` and the flags you passed.  I think the best option we have currently for a sanity check is to use `-test` if it is available.  I'm very curious about the flags you're using too.  I know of at least one other user using `-flive-range-shrinkage`.  I'd like to take a deeper look at what these do in the coming weeks.

**Comment by javashin** [comment]
https://github.com/manjaro/packages-core/blob/master/pacman/makepkg.conf

**Comment by InBetweenNames** [comment]
They add `-z relro -z now` as a hardening measure.  `-fno-plt` basically implies `-z now` due to the missing PLT.  It doesn't hurt to add, but it won't gain you anything.

Documentation on relro: https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro

Now, I'm not sure what `--sort-common` gets you exactly.

**Comment by javashin** [comment]
cool

**Comment by jiblime** [comment]
@javashin, thanks for notifying me about working BOOT_CFLAGS, I'll recompile GCC with those. 

@InBetweenNames, a lot of the added flags are not enabled at any optimization level which is what made me interested in them. I haven't found much in the way of documented usage besides machine learning (https://opensky.ucar.edu/islandora/object/siparcs%3A66/datastream/PDF/view) and cryptocurrency mining rigs. I think in the future it'd be a good idea to have an ebuild to benchmark maximum potential gain from using a flag. Maybe even measuring benefits in different ways like binary size like OpenSUSE Tumbleweed did? My personal system is rather slow but I'd submit a before/after lto-overlay @world rebuilds for data.

**Comment by InBetweenNames** [comment]
@jiblime work has been done on that actually, see #288

**Comment by jiblime** [comment]
If anyone is interested in using `-ftree-parallelize-loops` and is encountering build failures, I've found that you can view the tail end of a build.log and look for errors like:
```
error: undefined reference to 'omp_get_thread_num'

error: undefined reference to 'GOMP_parallel'

multiple definition of # not sure about this one but filtering -ftree-parallelize-loops fixed it
```

If the package doesn't support `-pthread` it will fail. For example in dev-qt/qtscript-5.12.4:
```
scriptlexer.o obj/release/moc_qscriptextensionplugin.o  /usr/lib64/libQt5Core.so -lpthread # right here
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.2: error: undefined reference to 'omp_get_num_threads'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.2: error: undefined reference to 'omp_get_thread_num'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.1: error: undefined reference to 'omp_get_num_threads'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.1: error: undefined reference to 'omp_get_thread_num'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.6: error: undefined reference to 'omp_get_num_threads'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.6: error: undefined reference to 'omp_get_thread_num'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.5: error: undefined reference to 'omp_get_num_threads'
obj/release/pcre_compile.o:pcre_compile.cpp:function compileBranch._loopfn.5: error: undefined reference to 'omp_get_thread_num'
obj/release/BytecodeGenerator.o:BytecodeGenerator.cpp:function QTWTF::Vector<int, 0ul>::fill(int const&, unsigned long): error: undefined reference to 'GOMP_parallel'
obj/release/JSArray.o:JSArray.cpp:function QTJSC::JSArray::compactForSorting(): error: undefined reference to 'GOMP_parallel'
obj/release/JSONObject.o:JSONObject.cpp:function QTJSC::Stringifier::Stringifier(QTJSC::ExecState*, QTJSC::JSValue, QTJSC::JSValue): error: undefined reference to 'GOMP_parallel'
```

So far I've needed to add these to `/etc/portage/package.cflags`:
```
sys-apps/sandbox   *FLAGS-="-ftree-parallelize-loops"*
media-libs/x265    *FLAGS-="-ftree-parallelize-loops"*
media-video/ffmpeg *FLAGS-="-ftree-parallelize-loops"*
dev-qt/qtwebengine *FLAGS-="-ftree-parallelize-loops"*
dev-qt/qtscript    *FLAGS-="-ftree-parallelize-loops"*
sys-libs/ncurses   *FLAGS-="-ftree-parallelize-loops"*
```

I haven't needed to filter this particular flag for kde-frameworks/* or kde-plasma/*.

**Comment by wolfwood** [comment]
you should be able to do LDFLAGS+=-lpthread to fix linker errors in
unthreaded packages

**Comment by jiblime** [comment]
@wolfwood Interesting note, thank you. I've tried adding your workaround instead of removing `-ftree-parallelize-loops` but it doesn't seem to be working.

[sandbox-2.18.log](https://github.com/InBetweenNames/gentooLTO/files/3420152/sandbox-2.18.log)
