### ISSUE TITLE
app-emulation/libvirt - C compiler cannot create executables

### ISSUE THREAD

**Issue by bitthief** [InBetweenNames/gentooLTO#369]
Hi,
I found that **app-emulation/libvirt** doesn't build using the default LTO configuration, it fails during the configure phase with **C compiler cannot create executables**, the linker is unable to find  symbols.

Enabling fat LTO objects fixes it, but there might be a more elegant fix?
I just added the following to **ltoworkarounds**
`app-emulation/libvirt *FLAGS+=-ffat-lto-objects # compilation error during configure phase
`

**Comment by nivedita76** [comment]
What are your use flags/other flags? I have 5.4.0-r1 installed with no errors and I’ve been building previous versions as well.

`app-emulation/libvirt-5.4.0-r1::gentoo was built with the following:
USE="caps dbus libvirtd macvtap nls numa pcap (policykit) qemu udev vepa virt-network -apparmor -audit -dtrace -firewalld -fuse -glusterfs -iscsi -iscsi-direct -libssh -lvm -lxc -nfs (-openvz) -parted -phyp -rbd -sasl (-selinux) -virtualbox -wireshark-plugins -xen -zeroconf -zfs" ABI_X86="(64)"`

`CFLAGS="-pipe -march=native -O2 -falign-functions=32 -fno-plt -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=8 -fno-semantic-interposition -mtls-dialect=gnu2"`

`CXXFLAGS="-pipe -march=native -O2 -falign-functions=32 -fno-plt -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -fno-math-errno -fno-trapping-math -fgraphite-identity -floop-nest-optimize -fipa-pta -flto=8 -fno-semantic-interposition -mtls-dialect=gnu2 -fdevirtualize-at-ltrans -fvisibility-inlines-hidden"
`

**Comment by InBetweenNames** [comment]
Cannot reproduce this one unfortunately.

**Comment by javashin** [comment]
no errors here either

**Comment by bitthief** [comment]
My USE flags are:

```
app-emulation/libvirt-5.5.0-r1::gentoo was built with the following:
USE="audit caps dbus firewalld fuse libssh libvirtd lvm lxc macvtap nfs nls numa pcap policykit qemu (selinux) udev vepa virt-network -apparmor -dtrace -glusterfs -iscsi -iscsi-direct (-openvz) -parted -phyp -rbd -sasl -virtualbox -wireshark-plugins -xen -zfs"
CFLAGS="-pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -fno-lto -fno-use-linker-plugin -ffat-lto-objects -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
CXXFLAGS="-pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -fno-lto -fno-use-linker-plugin -ffat-lto-objects -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fno-lto -fno-use-linker-plugin -pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -ffat-lto-objects"
```

I've experienced it on all libvirt versions so far.

Is there any more debug info that'd help diagnose this?

**Comment by javashin** [comment]
where is the build.log?

**Comment by javashin** [comment]
remove -mtls-dialect=gnu2

**Comment by javashin** [comment]
-pipe goes in the end

**Comment by javashin** [comment]
lol what a mess

**Comment by javashin** [comment]
-flto=12 -fuse-linker-plugin plus -fno-lto -fno-use-linker-plugin -ffat-lto-objects in the same cflags

**Comment by wolfwood** [comment]
I'm building 5.4 just fine with LTO.

can't try 5.5 atm cuz the new qt version is causing all kinds of conflicts.

**Comment by javashin** [comment]
app-emulation/libvirt-5.5.0-r1::gentoo was built with the following:
USE="caps dbus dtrace fuse glusterfs iscsi iscsi-direct libssh libvirtd lvm macvtap nls parted policykit qemu udev vepa virt-network virtualbox zfs -apparmor -audit -firewalld -lxc -nfs -numa (-openvz) -pcap -phyp -rbd -sasl (-selinux) -wireshark-plugins -xen" ABI_X86="(64)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"

**Comment by javashin** [comment]
> My USE flags are:
> 
> ```
> app-emulation/libvirt-5.5.0-r1::gentoo was built with the following:
> USE="audit caps dbus firewalld fuse libssh libvirtd lvm lxc macvtap nfs nls numa pcap policykit qemu (selinux) udev vepa virt-network -apparmor -dtrace -glusterfs -iscsi -iscsi-direct (-openvz) -parted -phyp -rbd -sasl -virtualbox -wireshark-plugins -xen -zfs"
> CFLAGS="-pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -fno-lto -fno-use-linker-plugin -ffat-lto-objects -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
> CXXFLAGS="-pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -fno-lto -fno-use-linker-plugin -ffat-lto-objects -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
> LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -fno-lto -fno-use-linker-plugin -pipe -mtune=native -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -falign-functions=32 -ffat-lto-objects"
> ```
> 
> I've experienced it on all libvirt versions so far.
> 
> Is there any more debug info that'd help diagnose this?

There IS A Mess on those Cflags

**Comment by bitthief** [comment]
Hi,

Sorry, you're correct, I rechecked my portage config and I had a package.env definition disabling LTO for libvirt, was having some issues with it a while ago.
I've removed it and rebuilt, works perfectly now. Also reordered some of the flags, as per your suggestions.

Thanks.

**Comment by javashin** [comment]
Glad To Help @bitthief
