### ISSUE TITLE
dev-ml/camlbz2 makes dev-ml/dose3 fail compiling

### ISSUE THREAD

**Issue by flgw** [InBetweenNames/gentooLTO#37]
When camlbz2 is compiled with the proposed settings, emerging dose3 fails with:

Warning 58: no cmx file was found in path for module Pef, and its interface was not compiled with -opaque
+ ocamlfind ocamlopt -linkpkg doselibs/common.cmxa doselibs/versioning.cmxa doselibs/pef.cmxa doselibs/opam.cmxa doselibs/npm.cmxa doselibs/debian.cmxa doselibs/csw.cmxa doselibs/algo.cmxa doselibs/doseparse.cmxa -package extlib -package re.pcre -package unix -package cudf -package bz2 -package re.str -package ocamlgraph -I applications applications/deb-coinstall.cmx -o applications/deb-coinstall.native
doselibs/common.a(common.o):function camlCommon__Input__bzip_open_file_1279: error: undefined reference to 'mlbz_readopen'
doselibs/common.a(common.o):function camlCommon__Input__input_char_1298: error: undefined reference to 'mlbz_read'
doselibs/common.a(common.o):function camlCommon__Input__read_1369: error: undefined reference to 'mlbz_read'
doselibs/common.a(common.o):function camlCommon__Input__fun_2254: error: undefined reference to 'mlbz_readclose'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o):function camlBz2__entry: error: undefined reference to 'mlbz_version'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0xe0): error: undefined reference to 'mlbz_uncompress'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0xe8): error: undefined reference to 'mlbz_compress'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0xf0): error: undefined reference to 'mlbz_writeclose'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0xf8): error: undefined reference to 'mlbz_write'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x100): error: undefined reference to 'mlbz_writeopen'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x108): error: undefined reference to 'mlbz_readclose'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x110): error: undefined reference to 'mlbz_readgetunused'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x118): error: undefined reference to 'mlbz_read'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x120): error: undefined reference to 'mlbz_readopen'
/usr/lib64/ocaml/bz2/bz2.a(bz2.o)(.data+0x128): error: undefined reference to 'mlbz_version'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
Compilation unsuccessful after building 28 targets (0 cached) in 00:00:01.
make: *** [Makefile:31: apps] Error 10
 * ERROR: dev-ml/dose3-5.0.1::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-ml/dose3-5.0.1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-ml/dose3-5.0.1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-ml/dose3-5.0.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-ml/dose3-5.0.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-ml/dose3-5.0.1/work/dose3-5.0.1'
 * S: '/var/tmp/portage/dev-ml/dose3-5.0.1/work/dose3-5.0.1'

 * Messages for package dev-ml/dose3-5.0.1:

 * ERROR: dev-ml/dose3-5.0.1::gentoo failed (compile phase):

**Comment by InBetweenNames** [comment]
Did you try adding:
~~~
dev-ml/camlbz2 *FLAGS+=-ffat-lto-objects
~~~

to your config?  Also, did you try with LTO disabled?

**Comment by pchome** [comment]
You can use following command to find installed packages potentially caused similar problems:
`$ equery b -n $(find /lib* /usr/lib* -type f -name "*.a" 2>/dev/null) | sort | uniq`

and add `*FLAGS+=-ffat-lto-objects` for corresponding ones

**Comment by InBetweenNames** [comment]
@pchome I agree that command will help find potential problems, but in order for a problem to take place there has to be a package that links against one of those static libraries whose build system does not honour LTO.  We could issue a blanket `-ffat-lto-objects` for them, but I think the list of affected packages is much smaller than the number of packages in that list and it's worth having them categorized.

**Comment by InBetweenNames** [comment]
Curious, were you able to get `dev-ml/findlib` built at all?  It seems to me that OCaml may be one of those special cases where we have to `fat-lto-objects` or `no-lto` everything.  I've never done any OCaml development so I'm unsure of how their build systems function.

**Comment by flgw** [comment]
`dev-lang/ocaml *FLAGS+=-ffat-lto-objects`
seems to do the trick - at least for me...

**Comment by InBetweenNames** [comment]
Workaround added -- however I'll be keeping my eye on OCaml things in the future.  Thanks for bringing this to my attention @flgw
