### ISSUE TITLE
dev-python/notify-python fails to compile with lto

### ISSUE THREAD

**Issue by flgw** [InBetweenNames/gentooLTO#38]
I need to add
`dev-python/notify-python *FLAGS-=-flto*`
otherwise I get:
```
generating symbol list for `_pynotify.la'
gcc-nm  .libs/pynotifymodule.o .libs/pynotify.o  |  | /bin/sed 's/.* //' | sort | uniq > .libs/_pynotify.exp
../libtool: eval: line 4037: syntax error near unexpected token `|'
../libtool: eval: line 4037: `gcc-nm  .libs/pynotifymodule.o .libs/pynotify.o  |  | /bin/sed 's/.* //' | sort | uniq > .libs/_pynotify.exp'
make[2]: *** [Makefile:278: _pynotify.la] Error 2
make[2]: Leaving directory '/var/tmp/portage/dev-python/notify-python-0.1.1-r3/work/notify-python-0.1.1-python2_7/src'
make[1]: *** [Makefile:299: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-python/notify-python-0.1.1-r3/work/notify-python-0.1.1-python2_7'
make: *** [Makefile:209: all] Error 2
 * ERROR: dev-python/notify-python-0.1.1-r3::gentoo failed (compile phase):
 *   emake failed

```

**Comment by pchome** [comment]
`gcc-nm  .libs/pynotifymodule.o .libs/pynotify.o  |  | ` ...
similar to #23 

`# lt_cv_sys_global_symbol_pipe="sed '/ __gnu_lto/d'" emerge -1 -B dev-python/notify-python` compiles

Changed in build.log like this:
`gcc-nm  .libs/pynotifymodule.o .libs/pynotify.o  | sed '/ __gnu_lto/d' | /bin/sed 's/.* //' | sort | uniq > .libs/_pynotify.exp`

**Comment by InBetweenNames** [comment]
Indeed adding `no-lto` seems to fix this.  However, I found this interesting:

In the LTO build, we get this error:

~~~
../libtool: eval: line 4037: `gcc-nm  .libs/pynotifymodule.o .libs/pynotify.o  |  | /bin/sed 's/.* //' | sort | uniq > .libs/_pynotify.exp'
~~~

Notice the `| |`.  It's almost as if some kind of variable substitution isn't working right.  In the non-LTO build, the above line changes to:

~~~
/usr/bin/x86_64-pc-linux-gnu-nm -B  .libs/pynotifymodule.o .libs/pynotify.o  | sed -n -e 's/^.*[        ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[         ][      ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p' | /bin/sed 's/.* //' | sort | uniq > .libs/_pynotify.exp
~~~

So, we've got a: 

~~~
sed -n -e 's/^.*[        ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[         ][      ]*\([_A-Za-z][_A-Za-z0-9]*\)$/\1 \2 \2/p'
~~~

I'll commit the workaround for now, but this is interesting.

**Comment by InBetweenNames** [comment]
Thanks for bringing this to my attention @flgw !

**Comment by InBetweenNames** [comment]
Okay, I did a quick hack and copied my system's libtool over to the package.  It compiled just fine.

**Comment by elsandosgrande** [comment]
I wonder if it is possible to force Gentoo to always use the system's libtool in all packages. If not, just like with GCC's LTO flag, get on it please!

**Comment by InBetweenNames** [comment]
The problem is every project uses autotools differently, so a one size fits all approach isn't possible.  I will publish a fixed ebuild here and submit a PR upstream to fix it there too.

**Comment by InBetweenNames** [comment]
Upstream PR/bug: https://github.com/gentoo/gentoo/pull/12364

**Comment by elsandosgrande** [comment]
Let us hope that it gets accepted.
