### ISSUE TITLE
A proposal .

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#390]
Looking into this news at phoronix give the same idea for gentooLTO
https://www.phoronix.com/scan.php?page=news_item&px=Fedora-31-Possible-LLD-Support
it is possible for us to make LLD as Default To use As Replacement For Gold Or BFD ?
@InBetweenNames What Do U Think Can This Became True ?

**Comment by wolfwood** [comment]
i don't know if lld even has a linker plugin framework, but I'm fairly
certain no official gcc LTO plugin exists for lld to let it process the
gimple intermediate that gcc sticks in place of assembly when doing LTO.

**Comment by elsandosgrande** [comment]
> i don't know if lld even has a linker plugin framework, but I'm fairly certain no official gcc LTO plugin exists for lld to let it process the gimple intermediate that gcc sticks in place of assembly when doing LTO.

Well, here is an excerpt from https://lld.llvm.org/ :
> * Link-time optimization (LTO) is supported by default. Essentially, all you have to do to do LTO is to pass the -flto option to clang. Then clang creates object files not in the native object file format but in LLVM bitcode format. LLD reads bitcode object files, compile them using LLVM and emit an output file. Because in this way LLD can see the entire program, it can do the whole program optimization.

It appears as though GCC is not really in the picture.

**Comment by jiblime** [comment]
>Another late change proposal coming in for Fedora 31 is to allow update-alternatives to optionally point /usr/bin/ld as the default linker to /usr/bin/lld for the LLVM linker.

>This change would make it much easier for Fedora users wanting to switch from the GNU BFD linker over to LLVM's LLD via the update-alternatives tool. This tool already supports using the GNU Gold linker while this late proposal by Red Hat's Tom Stellard is to handle LLVM's increasingly used LLD linker. 

Unless I am reading OP incorrectly, it is compatible regardless of compiler. I currently do not have Gentoo system running, but is anyone willing to post a build.log using lld as linker?

**Comment by ionenwks** [comment]
I don't know much about lld but it does seem to have some degree of GNU linker compatibility, if called as `ld --version` it gives `LLD 8.0.1 (compatible with GNU linkers)`.

I "was" able to compile bash with lld+gcc, however, if I use `-flto` it fails during configure stage.

**Comment by InBetweenNames** [comment]
If you look at the actual options `lld` supports, the `-plugin` option is really just there so that warnings/errors aren't kicked up, but it is effectively a no-op.  `lld` has an entirely different LTO implementation than GCC unfortunately and I would be very surprised if it were supported eventually.

~~~
> ld.lld --help | grep plugin
...
  --plugin=<value>        Ignored for compatibility with GNU linkers
~~~

**Comment by InBetweenNames** [comment]
From `lld/ELF/Options.td`:

~~~
// Ignore LTO plugin-related options.
// clang -flto passes -plugin and -plugin-opt to the linker. This is required
// for ld.gold and ld.bfd to get LTO working. But it's not for lld which doesn't
// rely on a plugin. Instead of detecting which linker is used on clang side we
// just ignore the option on lld side as it's easier. In fact, the linker could
// be called 'ld' and understanding which linker is used would require parsing of
// --version output.
defm plugin: Eq<"plugin", "Ignored for compatibility with GNU linkers">;
~~~

**Comment by elsandosgrande** [comment]
So... `-fuse-linker-plugin` is unnecessary when it comes to LLD? Hmm...

**Comment by javashin** [comment]
I see what fedora Trying To Do Will Solve All Our Linking Problems lets wait How They Pull this  Out 
Opensuse Will Follow That LLd And Maybe They Make LTO GCC Works With LLD.

**Comment by javashin** [comment]
OpenSuse Tumbleweed Using LTO By Default :::::: with -O2 pretty safe im tempted to Change Over OpenSUSE :-< less work very optimized by default


![Screenshot at 2019-07-27 18-54-03](https://user-images.githubusercontent.com/15115613/62000260-72df3f00-b0a0-11e9-8329-af5cc03061fd.png)

**Comment by jiblime** [comment]
One of the main points of Gentoo is to be able to compile packages for your specific hardware and to know what exactly you are installing. Of course, you're more than welcome to change distros. I would like to hear how you enjoy it, as I've got it sitting on a USB but I don't have the space for another install.

**Comment by InBetweenNames** [comment]
Yeah honestly, if OpenSUSE Tumbleweed will do what you want, there's not much point to using Gentoo on your hardware.  The benefit of GentooLTO over just LTO is that you get `-march=native` and friends.

**Comment by javashin** [comment]
im not switching i was just  talking to the thin air :)

**Comment by javashin** [comment]
opensuse is not for me .... a bunch of split pkgs , -devel this and that , zypper is kinda faster than dnf and apt . but i do not really like it , i was just testing on virtualbox and on a zpool zfs dataset on bare metal is a good distro but not really for me.
