### ISSUE TITLE
sci-mathematics/calc segfaults if sys-libs/readline is build with SEMINTERPOS.

### ISSUE THREAD

**Issue by TheGreatMcPain** [InBetweenNames/gentooLTO#392]
When readline is build with SEMINTERPOS calc will build and run, but if I check my command history in calc it will segfault.

Rebuilding readline without -fno-semantic-interposition will allow calc to run as intended.

If it helps I'm running default GentooLTO optimizations, but with the "pie" useflag disabled on sys-devel/gcc.

**Comment by InBetweenNames** [comment]
Went ahead and disabled it.  Thanks!
