### ISSUE TITLE
What  vallue of NTHREADS

### ISSUE THREAD

**Issue by imesg** [InBetweenNames/gentooLTO#393]
How to determine the value for NTHREADS?

Thanks

**Comment by wolfwood** [comment]
cat /proc/cpuinfo | grep processor | wc -l

this will report the number of logical cpus on your machine.

**Comment by InBetweenNames** [comment]
The number of logical CPUs is a good start.

**Comment by InBetweenNames** [comment]
Note that future GCCs will include a `-flto=auto` option that makes `NTHREADS` unnecessary -- looking forward to that day!

**Comment by imesg** [comment]
Thanks. Close.
