### ISSUE TITLE
Getting ICE with lto on libssh-0.9.0

### ISSUE THREAD

**Issue by nivedita76** [InBetweenNames/gentooLTO#394]
FAILED: lib/libssh.so.4.8.1 
: && /usr/bin/x86_64-pc-linux-gnu-gcc -fPIC -pipe -march=native -O2 -falign-functions=32 -fno-plt -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -fno-math-errno -fno-trapping-math -fipa-pta -flto=8 -mtls-dialect=gnu2  -Wl,-O1 -Wl,--as-needed  -Wl,--version-script,"/var/tmp/portage/net-libs/libssh-0.9.0/work/libssh-0.9.0/src/libssh.map" -shared -Wl,-soname,libssh.so.4 -o lib/libssh.so.4.8.1 src/CMakeFiles/ssh_shared.dir/agent.c.o src/CMakeFiles/ssh_shared.dir/auth.c.o src/CMakeFiles/ssh_shared.dir/base64.c.o src/CMakeFiles/ssh_shared.dir/bignum.c.o src/CMakeFiles/ssh_shared.dir/buffer.c.o src/CMakeFiles/ssh_shared.dir/callbacks.c.o src/CMakeFiles/ssh_shared.dir/channels.c.o src/CMakeFiles/ssh_shared.dir/client.c.o src/CMakeFiles/ssh_shared.dir/config.c.o src/CMakeFiles/ssh_shared.dir/connect.c.o src/CMakeFiles/ssh_shared.dir/connector.c.o src/CMakeFiles/ssh_shared.dir/curve25519.c.o src/CMakeFiles/ssh_shared.dir/dh.c.o src/CMakeFiles/ssh_shared.dir/ecdh.c.o src/CMakeFiles/ssh_shared.dir/error.c.o src/CMakeFiles/ssh_shared.dir/getpass.c.o src/CMakeFiles/ssh_shared.dir/init.c.o src/CMakeFiles/ssh_shared.dir/kdf.c.o src/CMakeFiles/ssh_shared.dir/kex.c.o src/CMakeFiles/ssh_shared.dir/known_hosts.c.o src/CMakeFiles/ssh_shared.dir/knownhosts.c.o src/CMakeFiles/ssh_shared.dir/legacy.c.o src/CMakeFiles/ssh_shared.dir/log.c.o src/CMakeFiles/ssh_shared.dir/match.c.o src/CMakeFiles/ssh_shared.dir/messages.c.o src/CMakeFiles/ssh_shared.dir/misc.c.o src/CMakeFiles/ssh_shared.dir/options.c.o src/CMakeFiles/ssh_shared.dir/packet.c.o src/CMakeFiles/ssh_shared.dir/packet_cb.c.o src/CMakeFiles/ssh_shared.dir/packet_crypt.c.o src/CMakeFiles/ssh_shared.dir/pcap.c.o src/CMakeFiles/ssh_shared.dir/pki.c.o src/CMakeFiles/ssh_shared.dir/pki_container_openssh.c.o src/CMakeFiles/ssh_shared.dir/pki_ed25519.c.o src/CMakeFiles/ssh_shared.dir/poll.c.o src/CMakeFiles/ssh_shared.dir/session.c.o src/CMakeFiles/ssh_shared.dir/scp.c.o src/CMakeFiles/ssh_shared.dir/socket.c.o src/CMakeFiles/ssh_shared.dir/string.c.o src/CMakeFiles/ssh_shared.dir/threads.c.o src/CMakeFiles/ssh_shared.dir/wrapper.c.o src/CMakeFiles/ssh_shared.dir/external/bcrypt_pbkdf.c.o src/CMakeFiles/ssh_shared.dir/external/blowfish.c.o src/CMakeFiles/ssh_shared.dir/external/chacha.c.o src/CMakeFiles/ssh_shared.dir/external/ed25519.c.o src/CMakeFiles/ssh_shared.dir/external/fe25519.c.o src/CMakeFiles/ssh_shared.dir/external/ge25519.c.o src/CMakeFiles/ssh_shared.dir/external/poly1305.c.o src/CMakeFiles/ssh_shared.dir/external/sc25519.c.o src/CMakeFiles/ssh_shared.dir/chachapoly.c.o src/CMakeFiles/ssh_shared.dir/config_parser.c.o src/CMakeFiles/ssh_shared.dir/token.c.o src/CMakeFiles/ssh_shared.dir/threads/noop.c.o src/CMakeFiles/ssh_shared.dir/threads/pthread.c.o src/CMakeFiles/ssh_shared.dir/threads/libcrypto.c.o src/CMakeFiles/ssh_shared.dir/pki_crypto.c.o src/CMakeFiles/ssh_shared.dir/ecdh_crypto.c.o src/CMakeFiles/ssh_shared.dir/libcrypto.c.o src/CMakeFiles/ssh_shared.dir/dh_crypto.c.o src/CMakeFiles/ssh_shared.dir/libcrypto-compat.c.o src/CMakeFiles/ssh_shared.dir/sftp.c.o src/CMakeFiles/ssh_shared.dir/dh-gex.c.o src/CMakeFiles/ssh_shared.dir/gzip.c.o src/CMakeFiles/ssh_shared.dir/external/curve25519_ref.c.o  -lrt /usr/lib64/libcrypto.so -lz && :
during IPA pass: cp
lto1: internal compiler error: in meet_with, at ipa-cp.c:1073
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.gentoo.org/> for instructions.
lto-wrapper: fatal error: /usr/bin/x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status

**Comment by jiblime** [comment]
I cann't reproduce build failure. However, I can't tell if the files are even getting LTO'd. I did two builds. The test flag build notified me that it proper LTO plugin. The regular build didn't.

I used readelf to try and find signs that it did; I didn't find anything, at least nothing that literally said lto.

`readelf --headers  /usr/lib64/libssh_threads.so` (partial output)
```
 Section to Segment mapping:
  Segment Sections...
   00     .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_d .gnu.version_r .rela.dyn 
   01     .init .plt .plt.got .text .fini 
   02     .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .data.rel.ro .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .tbss 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .data.rel.ro .dynamic .got 
```

But you can clearly see that it took in OpenMP which is great because I like it. I'm pretty sure having a linker for a shared library also means it's LTO'd? 
```
Dynamic section at offset 0x905d8 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libssh.so.4]
 0x000000000000000c (INIT)               0xb000
 0x000000000000000d (FINI)               0x5d55c
 0x0000000000000019 (INIT_ARRAY)         0x90b60
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x90b70
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x238
 0x0000000000000005 (STRTAB)             0x4b08
 0x0000000000000006 (SYMTAB)             0x1328
 0x000000000000000a (STRSZ)              9283 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x92000
 0x0000000000000007 (RELA)               0x75f0
 0x0000000000000008 (RELASZ)             12936 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffc (VERDEF)             0x73f8
 0x000000006ffffffd (VERDEFNUM)          6
 0x000000006ffffffe (VERNEED)            0x74c0
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x6f4c
 0x000000006ffffff9 (RELACOUNT)          283
 0x0000000000000000 (NULL)               0x0
```

[libssh-0.9.0-test.log](https://github.com/InBetweenNames/gentooLTO/files/3474507/libssh-0.9.0-test.log)

[libssh-0.9.0-notest.log](https://github.com/InBetweenNames/gentooLTO/files/3474505/libssh-0.9.0-notest.log)

**Comment by javashin** [comment]
readelf --headers /usr/lib64/libssh_threads.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          583168 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         8
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .dynsym           DYNSYM           0000000000000200  00000200
       0000000000003738  0000000000000018   A       2     1     8
  [ 2] .dynstr           STRTAB           0000000000003938  00003938
       0000000000002333  0000000000000000   A       0     0     1
  [ 3] .gnu.hash         GNU_HASH         0000000000005c70  00005c70
       0000000000000a7c  0000000000000000   A       1     0     8
  [ 4] .gnu.version      VERSYM           00000000000066ec  000066ec
       000000000000049a  0000000000000002   A       1     0     2
  [ 5] .gnu.version_d    VERDEF           0000000000006b88  00006b88
       00000000000000c8  0000000000000000   A       2     6     4
  [ 6] .gnu.version_r    VERNEED          0000000000006c50  00006c50
       00000000000000c0  0000000000000000   A       2     4     4
  [ 7] .rela.dyn         RELA             0000000000006d10  00006d10
       00000000000031e0  0000000000000018   A       1     0     8
  [ 8] .rela.plt         RELA             0000000000009ef0  00009ef0
       0000000000000018  0000000000000018  AI       1    22     8
  [ 9] .init             PROGBITS         0000000000009f08  00009f08
       0000000000000017  0000000000000000  AX       0     0     4
  [10] .plt              PROGBITS         0000000000009f20  00009f20
       0000000000000020  0000000000000010  AX       0     0     16
  [11] .text             PROGBITS         0000000000009f40  00009f40
       00000000000518ab  0000000000000000  AX       0     0     32
  [12] .fini             PROGBITS         000000000005b7ec  0005b7ec
       0000000000000009  0000000000000000  AX       0     0     4
  [13] .rodata           PROGBITS         000000000005b800  0005b800
       0000000000025ebc  0000000000000000   A       0     0     32
  [14] .eh_frame         X86_64_UNWIND    00000000000816c0  000816c0
       00000000000087d4  0000000000000000   A       0     0     8
  [15] .eh_frame_hdr     X86_64_UNWIND    0000000000089e94  00089e94
       0000000000001244  0000000000000000   A       0     0     4
  [16] .tbss             NOBITS           000000000008cbe0  0008bbe0
       0000000000000018  0000000000000000 WAT       0     0     8
  [17] .data.rel.ro.loca PROGBITS         000000000008cbe0  0008bbe0
       00000000000009a8  0000000000000000  WA       0     0     32
  [18] .fini_array       FINI_ARRAY       000000000008d588  0008c588
       0000000000000010  0000000000000008  WA       0     0     8
  [19] .init_array       INIT_ARRAY       000000000008d598  0008c598
       0000000000000010  0000000000000008  WA       0     0     8
  [20] .dynamic          DYNAMIC          000000000008d5a8  0008c5a8
       0000000000000260  0000000000000010  WA       2     0     8
  [21] .got              PROGBITS         000000000008d808  0008c808
       00000000000007d0  0000000000000000  WA       0     0     8
  [22] .got.plt          PROGBITS         000000000008dfd8  0008cfd8
       0000000000000020  0000000000000000  WA       0     0     8
  [23] .data             PROGBITS         000000000008e000  0008d000
       0000000000001500  0000000000000000  WA       0     0     32
  [24] .tm_clone_table   PROGBITS         000000000008f500  0008e500
       0000000000000000  0000000000000000  WA       0     0     8
  [25] .bss              NOBITS           000000000008f500  0008e500
       0000000000000050  0000000000000000  WA       0     0     8
  [26] .shstrtab         STRTAB           0000000000000000  0008e500
       00000000000000f9  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001c0 0x00000000000001c0  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000008b0d8 0x000000000008b0d8  R E    0x1000
  LOAD           0x000000000008bbe0 0x000000000008cbe0 0x000000000008cbe0
                 0x0000000000002920 0x0000000000002970  RW     0x1000
  DYNAMIC        0x000000000008c5a8 0x000000000008d5a8 0x000000000008d5a8
                 0x0000000000000260 0x0000000000000260  RW     0x8
  GNU_EH_FRAME   0x0000000000089e94 0x0000000000089e94 0x0000000000089e94
                 0x0000000000001244 0x0000000000001244  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  TLS            0x000000000008bbe0 0x000000000008cbe0 0x000000000008cbe0
                 0x0000000000000000 0x0000000000000018  R      0x8
  GNU_RELRO      0x000000000008bbe0 0x000000000008cbe0 0x000000000008cbe0
                 0x0000000000001420 0x0000000000001420  RW     0x20

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .dynsym .dynstr .gnu.hash .gnu.version .gnu.version_d .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame .eh_frame_hdr 
   02     .data.rel.ro.local .fini_array .init_array .dynamic .got .got.plt .data .bss 
   03     .dynamic 
   04     .eh_frame_hdr 
   05     
   06     .tbss 
   07     .data.rel.ro.local .fini_array .init_array .dynamic .got .got.plt

**Comment by javashin** [comment]
hey @jiblime 
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]


are missing from Dynamic section
in /usr/lib64/libssh_threads.so here in my system how did u get those ?

**Comment by javashin** [comment]
locate libpthread.so.0
/lib/libpthread.so.0
/lib64/libpthread.so.0
javashin@igloo-l440 ~/Desktop $ locate libgomp.so.1
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/libgomp.so.1
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/libgomp.so.1.0.0
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/32/libgomp.so.1
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/32/libgomp.so.1.0.0

**Comment by javashin** [comment]
also when is compiling cmake says this 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed

**Comment by jiblime** [comment]
@javashin This is going to look silly:

Recommended by Intel.
`ALIGN="-falign-functions=32 -flimit-function-alignment"`

Let Graphite do as much as it wants.
`ISLMAX="--param=max-isl-operations=0 --param=graphite-max-nb-scop-params=0"`

Enable the OpenMP library, -ftree enables pthreads, -floop should help with both parallelizing and Graphite, the parloops params are for optimizing the former, -fvect is unlimited because I prefer the trade off of checking for profitability vs. vectorizing when it isn't needed. It also sets unlimited for `-fsimd-cost-model`
`PARLOOP="-fopenmp-simd -ftree-parallelize-loops=4 -floop-parallelize-all --param=parloops-chunk-size=65536 --param=parloops-schedule=dynamic  -fvect-cost-model=unlimited"`

..Sounded cool..I've only ever read that it *can* provide better performance and I haven't read anything on degrading code.
`SUPERBLOCK="-fsched2-use-superblocks -fsched2-use-traces -ftracer"`

-fvisibility optimizes code, increasing min-partition should optimize how LTO works, cacheline recommended by IBN.
`EXTRA_FLAGS="-fvisibility-inlines-hidden --param=lto-min-partition=50000 -malign-data=cacheline"`

All these flags trade compile time for runtime perfomance, and should be safe.
`INCREASED_TIME="--param=max-cselib-memory-locations=5000 --param=max-reload-search-insns=1000 --param=dse-max-alias-queries-per-store=2048 --param=dse-max-object-size=2048 --param=max-crossjump-edges=100000 --param=ipcp-unit-growth=100"`

As well as `-O3 ${GRAPHITE} ${IPAPTA} ${SEMINTERPOS} ${DEVIRTLTO} ${NOPLT} ${FLTO} ${SAFEST_FAST_MATH}`

Some references I used, validity=hidden lol:

[Increase lto-min-partition](https://patchwork.ozlabs.org/patch/673374/)

[-fopenmp-simd](https://gcc.gnu.org/ml/gcc-patches/2013-10/msg02275.html)

[Parloops chunk size](https://mapr.com/docs/61/AdministratorGuide/Chunk-Size.html)

[Visbility](https://gcc.gnu.org/wiki/Visibility)

I add most of these to my kernel builds, minus openmp, -fno-plt and a few other things. System stable so far, the only filter flags I ever have to apply is for -ftree-parallelize-loops, and it's really prevalent in audio/video packages for some reason.

**Comment by nivedita76** [comment]
@jiblime note that sched2-use-traces is obsolete since 2010 -- the option is ignored.

**Comment by javashin** [comment]
This Are My Flags @jiblime  
CFLAGS="-O3 -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -pipe"

i will get any goods adding what u posted????

**Comment by jiblime** [comment]
@nivedita76 
I built it with your flags and it emerged, and although this is unrelated I had started getting errors at linking when I rebuilt binutils with -fvisibility=hidden. 

`/var/tmp/portage/sys-devel/binutils-2.32-r1/work/binutils-2.32/gas/config/tc-i386.c:2124:1: warning: inlining failed in call to 'oper>
 2124 | operand_type_register_match (i386_operand_type g0,`

`tmp/portage/sys-devel/binutils-2.32-r1/temp/as-new.IIbD3M.ltrans0.ltrans.o: in function symbol_clone':
<artificial>:(.text+0xdabf): undefined reference to bfd_get_error'`


`/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/sys-devel/binutils-2.32-r1/temp/as-new.IIbD3M.ltrans1.ltrans.o:<artificial>:(.text.startup+0x1dac): more undefined references to _bfd_std_section' follow`
'`

Most sys-/ packages would not work. Could be a binutils/linker problem? 

@javashin 
Yours are good. My binaries are much smaller, and it has been really smooth using and even when emerging at the same time, emerging takes much longer though. But the smoothness could be the MuQSS scheduler I use.

**Comment by nivedita76** [comment]
Weird. I’ll try again.

**Comment by javashin** [comment]
@jiblime  hi i compiled libX11 with CFLAGS="-O3 -march=native -mfpmath=both -funroll-loops -falign-functions=32 -flimit-function-alignment -fgraphite-identity -floop-nest-optimize -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fipa-pta -fno-plt -fno-math-errno -fno-trapping-math -fdevirtualize-at-ltrans -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -fopenmp-simd -ftree-parallelize-loops=4 -pipe -Wl,-O2 -Wl,--as-needed,-z,now -fuse-ld=gold -Wl,--hash-style=gnu"

i added -fopenmp-simd -ftree-parallelize-loops=4 from you and  
readelf  --all /usr/lib64/libX11.so.6.3.0

shows 
Dynamic section at offset 0x18a6d0 contains 31 entries:

 0x0000000000000001 (NEEDED)             Shared library: [libxcb.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libX11.so.6]


Only

there is no 



0x0000000000000001 (NEEDED) Shared library: [libgomp.so.1]
0x0000000000000001 (NEEDED) Shared library: [libpthread.so.0]

**Comment by javashin** [comment]
> @javashin This is going to look silly:
> 
> Recommended by Intel.
> `ALIGN="-falign-functions=32 -flimit-function-alignment"`
> 
> Let Graphite do as much as it wants.
> `ISLMAX="--param=max-isl-operations=0 --param=graphite-max-nb-scop-params=0"`
> 
> Enable the OpenMP library, -ftree enables pthreads, -floop should help with both parallelizing and Graphite, the parloops params are for optimizing the former, -fvect is unlimited because I prefer the trade off of checking for profitability vs. vectorizing when it isn't needed. It also sets unlimited for -fsimd-cost-model.
> 
> `PARLOOP="-fopenmp-simd -ftree-parallelize-loops=4 -floop-parallelize-all --param=parloops-chunk-size=65536 --param=parloops-schedule=dynamic -fvect-cost-model=unlimited"`
> 
> ..Sounded cool..I've only ever read that it _can_ provide better performance and I haven't read anything on degrading code. Edit: Removed -fsched2-use-traces because it has been deprecated, thanks nivedita76.
> 
> `SUPERBLOCK="-fsched2-use-superblocks -fsched2-use-traces -ftracer"`
> 
> -fvisibility optimizes code, increasing min-partition should optimize how LTO works, cacheline recommended by IBN.
> 
> `EXTRA_FLAGS="-fvisibility-inlines-hidden --param=lto-min-partition=50000 -malign-data=cacheline"`
> 
> All these flags trade compile time for runtime perfomance, and should be safe.
> 
> `INCREASED_TIME="--param=max-cselib-memory-locations=5000 --param=max-reload-search-insns=1000 --param=dse-max-alias-queries-per-store=2048 --param=dse-max-object-size=2048 --param=max-crossjump-edges=100000 --param=ipcp-unit-growth=100"`
> 
> As well as `-march=native -fuse-linker-plugin -pipe -O3 ${GRAPHITE} ${IPAPTA} ${SEMINTERPOS} ${DEVIRTLTO} ${NOPLT} ${FLTO} ${SAFEST_FAST_MATH}`
> 
> Some references I used, validity=hidden lol:
> 
> [Increase lto-min-partition](https://patchwork.ozlabs.org/patch/673374/)
> 
> [-fopenmp-simd](https://gcc.gnu.org/ml/gcc-patches/2013-10/msg02275.html)
> 
> [Parloops chunk size](https://mapr.com/docs/61/AdministratorGuide/Chunk-Size.html)
> 
> [Visbility](https://gcc.gnu.org/wiki/Visibility)
> 
> https://gcc.gnu.org/wiki/Visibility
> 
> I add most of these to my kernel builds, minus openmp, -fno-plt and a few other things. System stable so far, the only filter flags I ever have to apply is for -ftree-parallelize-loops, and it's really prevalent in audio/video packages for some reason.

this way ???

**Comment by jiblime** [comment]
@javashin, I've been reading the gcc bug tracker and I'm going back on using most of those flags now. Apparently a lot of applications can't handle multithreading at execution time. I've been rebuilding all my packages to remove it. I rebuilt some system tools with it (binutils, zlib, qtcore) and they all caused segfaults in the apps that use them, although I honestly am not sure if it's partition corruption that is making pthread crash everything or pthread itself.

 Related to this open issue, I've tried adding `-Winline -Warray-bounds -Wstrict-overflow` and executing `tail -f /var/tmp/[category]/[pkg]/temp/build.log | grep warning` to watch what happens when it fails and see if my flags are making it worse. There are more flags [here](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html), some specifically for optimizations.

**Comment by funghetto** [comment]
I got the same ICE.

**Comment by javashin** [comment]
......................................

**Comment by javashin** [comment]
All Those Insane Flags Corrupted Your File System glad i didn't used any of that
@jiblime ^^^^^^

**Comment by javashin** [comment]
NO ICE here 
et-libs/libssh-0.9.0::gentoo was built with the following:
USE="sftp zlib -debug -doc -examples -gcrypt -gssapi -libressl -mbedtls -pcap -server -static-libs -test" ABI_X86="32 (64) (-x32)"
CFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
CXXFLAGS="-march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe -Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--hash-style=gnu -march=native -mfpmath=both -funroll-loops -falign-functions=32 -fuse-ld=gold -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=3 -fuse-linker-plugin -fno-plt -fno-math-errno -fno-trapping-math -fno-stack-protector -pipe"

**Comment by javashin** [comment]
my house is in order

**Comment by funghetto** [comment]
With latest gcc and updates now it compiles successfully on my system.

**Comment by javashin** [comment]
good

**Comment by elsandosgrande** [comment]
@nivedita76 So... What's the current status?

**Comment by elsandosgrande** [comment]
Huh, I guess that that's the status.
