### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by imesg** [InBetweenNames/gentooLTO#395]
First six packages failed with this error.

Need help with this.

What info can I provide?

make.conf.lto and make.conf.lto.defines are largely unchanged.

Below are the changes I made to make.conf to get started. But immediately encountered the 'cannot create executables' problem.

Thanks
...
checking whether the C compiler works... no
configure: error: in `/var/tmp/portage/sys-apps/kbd-2.2.0-r1/work/kbd-2.2.0':
configure: error: C compiler cannot create executables

############################
# LTO Overlay
source /etc/portage/make.conf.lto

CFLAGS="-march=native ${CFLAGS} -pipe" # -falign-functions=32" #NOTE: Consider using -falign-functions=32 if you use an Intel processor.  See issue #164.
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
############################

###########################
# Original
#COMMON_FLAGS="${CFLAGS} -march=native -O2 -pipe -falign-functions=32"
#CFLAGS="${COMMON_FLAGS}"
#CXXFLAGS="${COMMON_FLAGS}"
#FCFLAGS="${COMMON_FLAGS}"
#FFLAGS="${COMMON_FLAGS}"
###########################

MAKEOPTS="-j14"

USE="cups \
     graphite \
     gphoto2 \
     ieee1394 \
     lto \
     wayland \
     -multilib \
     -smartcard"

**Comment by jiblime** [comment]
Here is the error: 
`CFLAGS="-march=native ${CFLAGS} -pipe" # -falign-functions=32" #NOTE: Consider using -falign-functions=32 if you use an Intel processor. See issue #164.`

Too many quotes.

Fix:
```
NTHREADS="4" #REPLACE WITH NUMBER OF CORES
CFLAGS="-march=native ${CFLAGS} -pipe -falign-functions=32"
#CXXFLAGS="${CFLAGS}"
#FCFLAGS="${CFLAGS}"
#FFLAGS="${CFLAGS}"

MAKEOPTS=${NTHREADS}

USE="cups graphite gphoto2 ieee1394 lto wayland -multilib -smartcard"


How's your make.conf.lto and make.conf.lto.defines look? I was running flto= was the longest time because I didn't define $NTHREADS.
```

**Comment by imesg** [comment]
I still have the same problem as before. 

Here are my make.conf* files.

Thanks for help.

make.conf:
HTHREADS="16"
source /etc/portage/make.conf.lto.defines

CFLAGS="-march=native ${CFLAGS} -pipe -falign-functions=32" 
CXXFLAGS="${CFLAGS}"
#FCFLAGS="${CFLAGS}"
#FFLAGS="${CFLAGS}"
############################


###########################
# Original
#COMMON_FLAGS="${CFLAGS} -march=native -O2 -pipe"
#CFLAGS="${COMMON_FLAGS}"
#CXXFLAGS="${COMMON_FLAGS}"
#FCFLAGS="${COMMON_FLAGS}"
#FFLAGS="${COMMON_FLAGS}"
###########################

MAKEOPTS="-j${NTHREADS}"
#MAKEOPTS="-j16"

USE="cups \
     gphoto2 \
#     graphite \
     ieee1394 \
#     lto \
     wayland \
     -multilib \
     -smartcard"
...

make.conf.lto:

NTHREADS="16"
MAKEOPTS="-j${NTHREADS}"
source make.conf.lto.defines
CFLAGS="-O3 ${GRAPHITE} ${DEVIRTLTO} ${IPAPTA} ${SEMINTERPOS} ${FLTO} -fuse-linker-plugin"


make.confi.lto.defines:

FLTO="-flto=${NTHREADS}"

GRAPHITE="-fgraphite-identity -floop-nest-optimize"

IPAPTA="-fipa-pta"

SEMINTERPOS="-fno-semantic-interposition"

NOCOMMON="-fno-common"

SAFEST_FAST_MATH="-fno-math-errno -fno-trapping-math"
SAFER_UNSAFE_MATH_OPTS="-fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math"
SAFER_FAST_MATH="${SAFER_UNSAFE_MATH_OPTS} -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast"

DEVIRTLTO="-fdevirtualize-at-ltrans"

NOPLT="-fno-plt"

**Comment by jiblime** [comment]
Are you making new lines for each USE flag? I believe that doesn't work. If you want it to be easier to read, you can do something like:
```
KDEUSE="qt5 kde systray"
OPTIMIZATIONSUSE="pgo lto"

USE="${KDEUSE} ${OPTIMIZATIONSUSE}"
```

**Comment by imesg** [comment]
Been doing it for years. Seems to work ok. Easier to read that way. Cut and paste doesn't show the back slashes for some reason. There is a back slash after every line allowing continuation on the next line.

I continue to have the 'cannot create executable' problem.

**Comment by imesg** [comment]
Seems a reboot was all that was needed.
