### ISSUE TITLE
Add -fno-rtti to list of optimizations

### ISSUE THREAD

**Issue by jiblime** [InBetweenNames/gentooLTO#397]
Proposed set of flags to add:

```
# Disabling Run Time Type Information and
# exception handling should result in smaller binaries with low risk added.

NORTTI="-fno-rtti -fno-exceptions -fno-unwind-tables"
```
https://arobenko.gitbooks.io/bare_metal_cpp/content/compiler_output/rtti.html

>Run Time Type Information is also one of the core features of conventional C++. It allows retrieval of the object type information (using typeid operator) as well as checking the inheritance hierarchy (using dynamic_cast) at run time. The RTTI is available only when there is a polymorphic behaviour, i.e. the classes have at least one virtual function.
[...]
>For some bare metal platforms it may be undesirable or even impossible to have this amount of extra binary code added to the binary image. The GNU compiler (gcc) provides an ability to disable RTTI by using -no-rtti option. Let's check the virtual table of SomeClass class when this option is used:
[...]
>The virtual table looks much simpler now with single pointer to the SomeClass::someFunc() virtual function. There is no extra code size overhead needed to maintain type information. If the application above is compiled without exceptions (using -fno-exceptions and -fno-unwind-tables) as well as without RTTI support (using -no-rtti) the binary image size will be about 1.3KB which is much better.

>However, if -no-rtti option is used, the compiler won't allow usage of typeid operator as well as dynamic_cast. In this case the developer needs to come up with other solutions to differentiate between objects of different types (but having the same 'ancestor') at run time. There are multiple idioms that can be used, such as using simple C-like approach of switch-ing on some type enumerator member, or using polymorphic behaviour of the objects to perform double dispatch.

>CONCLUSION: Disabling Run Time Type Information (RTTI) in addition to eliminating exception handling is very common in bare metal C++ development. It allows to save about 10KB of space overhead in final binary image.

Edit:

So I just went and tested this on sandbox. The final size was exactly the same...is this a Gentoo default? Lol.....

**Comment by 6blender6** [comment]
The flags can only make differences on *some* C++ program.

**Comment by InBetweenNames** [comment]
Yeah this definitely falls into the category of "optimizations that change C++ semantics" -- there's a lot of code out there that depends on exception handling and RTTI.  I would argue this should be applied on a per-package basis rather than as a default.  I believe work has been done to officially support a variant of C++ that doesn't have any kind of exception handling, which is useful for embedded environments, but I have no idea how far along that is.

**Comment by jiblime** [comment]
That's fair. I've done more research and this doesn't seem to be the safest. Many packages also require -frtti to build, so working on it will be a pain.

**Comment by jiblime** [comment]
Unrelated to the original issue, but an idea for automating ltoworkarounds.conf additions.

Packages that have `dynamic_cast` fail to emerge with -fno-rtti. Instead of waiting for the pkg to fail, I can check the source tarball if it has `dynamic_cast` and edit my *cflags accordingly.


```zgrep -a dynamic_cost /var/tmp/portage/media-libs/vamp-plugin-sdk-2.7.1/distdir/vamp-plugin-sdk-2.7.1.tar.gz``` (or /var/cache/distfiles/wherever)

Output:
```
    wrapper = dynamic_cast<PluginWrapper *>(plugin);
    PluginWrapper *wrapper = dynamic_cast<PluginWrapper *>(m_plugin);
        WrapperType *w = dynamic_cast<WrapperType *>(this);
        PluginWrapper *pw = dynamic_cast<PluginWrapper *>(m_plugin);
        Plugin *plugin = dynamic_cast<Plugin *>(p);
```

Bingo! Most build failures I've been having recently are due to the packages not having the pthread library linked, so an empty output for `pthread` or `lpthread` would be a good way to filter.
