### ISSUE TITLE
sys-apps/man-db: whatis stops with SIGABRT at runtime when compiled with -flto

### ISSUE THREAD

**Issue by lucius-martius** [InBetweenNames/gentooLTO#403]
I have noticed this when using tab-completion with the fish shell. The command does what it should, but fails with SIGABRT, which leads to the tab-completion of fish to fail as well.

It can also be reproduced when calling apropos (/usr/bin/whatis) manually:

```
~> apropos apropos
apropos (1)          - search the manual page names and descriptions
free(): invalid pointer
fish: 'apropos apropos' terminated by signal SIGABRT (Abort)
```

This behaviour seems to be new with the testing versions of `>=sys-apps/man-db-2.8.5`,  as version `2.7.6.1-r2` does not show the issue.

A workaround I found is is to disable LTO with `sys-apps/man-db *FLAGS-=-flto*`. If others can confirm this issue I can create a pull request for this workaround.

**Comment by javashin** [comment]
i know about this 
readline ncurses bash with no lto too

**Comment by perfect7gentleman** [comment]
no error

**Comment by InBetweenNames** [comment]
Confirmed!
