### ISSUE TITLE
Building dev-qt/qtcore-5.12.4 with -O3 results in plasmashell crashes

### ISSUE THREAD

**Issue by Peter-Levine** [InBetweenNames/gentooLTO#411]
Building dev-qt/qtcore-5.12.4 with -O3 causes plasmashell to crash right before logging out of KDE (still logs out right after) and causes sporadic plasmashell crashes while using KDE.  The problem seems to be resolved with -O2.  Tested with gcc-8.3.0 and gcc-9.2.0.

**Comment by jiblime** [comment]
Can't reproduce. Have you tried recompiling kwin and kwindowsystem with saner CFLAGS?

dev-qt/qtcore-5.12.4::gentoo

`USE="debug icu systemd -test"`


```
CFLAGS="-O3 -mtune=skylake -march=native -malign-data=cacheline -falign-functions=32 -flimit-function-alignment -fsched2-use-superblocks -ftracer -fgraphite-identity -floop-nest-optimize -fno-plt -fipa-pta -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -pipe -fuse-linker-plugin -fopt-info-optimized-all -fopt-info-missed-all -Wall -Wextra"
```


```
CXXFLAGS="-O3 -mtune=skylake -march=native -malign-data=cacheline -falign-functions=32 -flimit-function-alignment -fsched2-use-superblocks -ftracer -fgraphite-identity -floop-nest-optimize -fno-plt -fipa-pta -fno-signed-zeros -fno-trapping-math -fassociative-math -freciprocal-math -fno-math-errno -ffinite-math-only -fno-rounding-math -fno-signaling-nans -fcx-limited-range -fexcess-precision=fast -pipe -fuse-linker-plugin -fopt-info-optimized-all -fopt-info-missed-all -Wall -Wextra -fvisibility-inlines-hidden"
```


```
FEATURES="multilib-strict usersandbox ipc-sandbox split-log strict ccache preserve-libs xattr protect-owned fixlafiles network-sandbox sandbox unmerge-orphans userfetch userpriv assume-digests binpkg-docompress merge-sync pid-sandbox distlocks candy downgrade-backup split-elog usersync binpkg-dostrip parallel-fetch unmerge-logs binpkg-logs news sfperms parallel-install unknown-features-warn config-protect-if-modified"
```

**Comment by lferra** [comment]
> Building dev-qt/qtcore-5.12.4 with -O3 causes plasmashell to crash right before logging out of KDE (still logs out right after) and causes sporadic plasmashell crashes while using KDE. The problem seems to be resolved with -O2. Tested with gcc-8.3.0 and gcc-9.2.0.

I have the same issue (plasmashell crash right before logging out), but also compiling qtcore with -O2 does not fix it (using gcc-9.2.0).

**Comment by Peter-Levine** [comment]
> I have the same issue (plasmashell crash right before logging out), but also compiling qtcore with -O2 does not fix it (using gcc-9.2.0).

Yeah.  It wasn't qtcore.

Just a sanity check.  Are you using nvidia proprietary driver?

**Comment by lferra** [comment]
> Just a sanity check. Are you using nvidia proprietary driver?

Nope, I have a hybrid graphic card (intel+ati), and I'm using open source drivers (xf86-video-ati and xf86-video-intel)

**Comment by barolo** [comment]
Just to chime in, I had such issue and had to rebuild all deps of plasma-meta without gLTO, it's not -O3 issue for sure as I'm building with -O3 everything anyway. I doubt that's only qtcore issue too, as I had it compiled with whole LTO shebang and it was fine for awhile. 
I'm using opensource amd gpu drivers.

**Comment by elsandosgrande** [comment]
I have had no such issues. As my laptop is updating right now, I will post the relevant details later. 

---

#### Side note

The AOSP (Android open-source project) keyboard is not half bad. I'm pretty sure that you can only get it on custom ROMs which are based on AOSP and on the AOSP builds which only really run on Google devices for the most part though...

**Comment by Peter-Levine** [comment]
I haven't had this problem in a long while so, assuming it is not an issue in the latest version, I'm closing this.
