### ISSUE TITLE
sys-libs/binutils-libs-2.32-r1 circular dependency

### ISSUE THREAD

**Issue by ElDavoo** [InBetweenNames/gentooLTO#413]
Hi,
I'm upgrading from gcc 9.1.0 to 9.2.0 so I'm re-emerging world, but I have a "circular dependency" issue. I'm pretty sure the solution for this issue is trivial but I do not know it :D
sys-libs/binutils-libs-2.32-r1 fails to compile with: 
lto1: fatal error: bytecode stream in file '/usr/lib/libiberty.a' generated with LTO version 8.0 instead of the expected 8.1

The problem is  '/usr/lib/libiberty.a' is part of sys-libs/binutils-libs so I cannot recompile it.

**Comment by InBetweenNames** [comment]
Ah yes, I have run into this problem as well, although it was on my cross compiled stuff.  What you need to do is unmerge `sys-libs/binutils-libs` and then re-emerge it.  If you only rebuild it, it seems to not update that file for some reason.

**Comment by ElDavoo** [comment]
Thanks, that worked.
