### ISSUE TITLE
Compile is broken when using gentoo-lto flags

### ISSUE THREAD

**Issue by shelterx** [InBetweenNames/gentooLTO#426]
I tried to compile mesa... it gave me this error:
https://pastebin.com/Jr0D1U3b

I also tried to compile kwin, similar error.

**Comment by wolfwood** [comment]
this is the same issue as #421 either recompile gcc with graphite USE flag enable or remove ${GRAPHITE} from CFLAGS. there is an open pull request to make this a bit smoother.

**Comment by shelterx** [comment]
I see, I'll just recompile gcc then, I saw no mention of special gcc USE flags when I read the instructions here on github tho'.

**Comment by shelterx** [comment]
Works as intended now after recompiling gcc.

**Comment by shelterx** [comment]
Works as intended now after recompiling gcc.
