### ISSUE TITLE
dev-python/grpcio Fails to build with LTO

### ISSUE THREAD

**Issue by wolfwood** [InBetweenNames/gentooLTO#429]
patch from #229 fails to apply

**Comment by jiblime** [comment]
Missing space at the end of file.
```
--- a/setup.py
+++ b/setup.py
@@ -174,7 +174,7 @@ if EXTRA_ENV_LINK_ARGS is None:
         ' -static-libgcc -static-libstdc++ -mcrtdll={msvcr} '
         '-static'.format(msvcr=msvcr))
   if "linux" in sys.platform:
-    EXTRA_ENV_LINK_ARGS += ' -Wl,-wrap,memcpy  -static-libgcc'
+    EXTRA_ENV_LINK_ARGS += ' -static-libgcc'
 
 EXTRA_COMPILE_ARGS = shlex.split(EXTRA_ENV_COMPILE_ARGS)
 EXTRA_LINK_ARGS = shlex.split(EXTRA_ENV_LINK_ARGS)
 # This bad boy right here
```

**Comment by wolfwood** [comment]
yeah, updated patch builds.

**Comment by InBetweenNames** [comment]
Tested it out without any patch as it looks like upstream conditionally adds in the `-Wl,-wrap,memcpy` already.  I'll accept @jiblime's patch for this though, as we probably want to be doing this regardless of the system in use (i.e., if you're using Gentoo Prefix with a non-Linux kernel)

**Comment by InBetweenNames** [comment]
It looks like `setup.py` is already good to go and it's just the `Makefile` that should be patched for extra assurance

**Comment by InBetweenNames** [comment]
Committed, thanks!

Also, I tried to run the tests but I didn't have much luck even on non-LTO, and unfortunately I can't spend too much time on this.  So, if we run into problems, comment and I'll reopen the issue
