### ISSUE TITLE
media-libs/ilmbase causes media-libs/openexr error

### ISSUE THREAD

**Issue by flgw** [InBetweenNames/gentooLTO#43]
Adding
`media-libs/ilmbase *FLAGS+=-ffat-lto-objects`
let's me emerge openexr again

**Comment by InBetweenNames** [comment]
Interesting, I tried to rebuild openexr today and I found that I had trouble rebuilding it.  However, 

~~~
 media-libs/ilmbase *FLAGS+=-ffat-lto-objects
~~~

did not help.

Instead, I found that the problems were some missing pthread symbols.  I managed to correct those with a:

~~~
media-libs/openexr *FLAGS+=-pthread
~~~

Can you provide more details about the build errors you encountered?  I just want to make sure we nail down the actual problem with this package (we do have a previous thread about this where OpenEXR requires an upstream patch)

**Comment by InBetweenNames** [comment]
As of GCC 8.1.0 the workaround above does not appear to be necessary and it seems to just work. I'm going to close this issue, however I'll reopen it if anyone starts having problems again.
