### ISSUE TITLE
Support for arm64?

### ISSUE THREAD

**Issue by Jannik2099** [InBetweenNames/gentooLTO#441]
If I understood the ltoize ebuild correctly, arm64 is currently not supported. Are there any plans to add support for arm64 and do you need any help with debugging on this platform? I'd really like to use GentoLTO on my pinebook pro and would be happy to help.

**Comment by elsandosgrande** [comment]
My guess is that:

1. Shane never thought of ARM before now.
2. It heavily depends on how this all plays out with GCC on ARM. Who knows, if some of the issues with workarounds in ltoworkarounds.conf are quirky enough, we might end up with a separate workarounds file for ARM, though I highly doubt that they are.

**Comment by necrose99** [comment]
some of the same graphite quirks , etc. 
a few more by hand. 
clang https://www.reddit.com/r/Gentoo/comments/bxmyeq/gentoo_on_pine64_rock64_pro/ might also be useful as a work arround /gcc for some.

**Comment by InBetweenNames** [comment]
I do run a very similar setup to GentooLTO on ARM, actually, but only armv7-a, as that's the only hardware I own.  In principle there should be nothing preventing GentooLTO from working in such an environment.

If you want, add `~arm` to the ebuild and see if you're able to start using the config.  The flags you use may need customization, but the defaults should work at least.

**Comment by jiblime** [comment]
Some absolutely wicked guy maintains updated stages for ARM: https://files.emjay-embedded.co.uk/unofficial-gentoo/arm-stages/testing/

Gentoo's officials are incredibly outdated. I've been really wanting to get Gentoo on my tablet but I've bricked one before haha.If it wouldn't trouble you, documenting your process if you do decide to try it out would be appreciated :)

**Comment by Jannik2099** [comment]
Thanks jiblime, I went with the experimental arm64 tarball from the gentoo website. I'm almost done setting up my system for daily use now, I will slap GentooLTO onto that afterwards, will probably get to that within the next two weeks.

**Comment by elsandosgrande** [comment]
@Jannik2099 Why the sudden closure without a status update? Is GentooLTO in its current state viable for ARM installations?

**Comment by Jannik2099** [comment]
@elsandosgrande oh sorry, completely forgot to comment on it lol. GentooLTO works like a charm on arm64, I can't remember having to do any arch specific fixes besides one asm related package
