### ISSUE TITLE
Is -Wl,-O1 correct in the LDFLAGS?

### ISSUE THREAD

**Issue by kanyck** [InBetweenNames/gentooLTO#447]
AFAIK when using LTO the final optimization decisions are postponed to the link stage. However, I can see 
`LDFLAGS="-Wl,-O1 -Wl,--as-needed"
`
in the `emerge -- info` output while CFLAGS show -O3 as expected.
That makes me think that real optimization level is eventually -O1, not -O3. Is this correct?

**Comment by elsandosgrande** [comment]
From what I know, BDF (the default linker) only supports levels up to O1. Gold, which is not exactly the most stable thing in the world at the moment, does support the third optimization level.

**Comment by wolfwood** [comment]
yes. it's the linker optimization level, different from compiler optimization (which also gets passed to the linker) and is meaningful whether or not you use LTO.

LTO uses the compiler flags. this controls other, ELF specific, linker behavior.

**Comment by kanyck** [comment]
Yep, thanks! Currently gentooLTO's default linker is bfd. So this is correct.
Closing.

**Comment by jiblime** [comment]
This bit of information may be helpful in understanding using `-Wl,-O` levels in LDFLAGS. 

For ld.bfd and ld.gold: https://linux.die.net/man/1/ld

>-O level
    If level is a numeric values greater than zero ld optimizes the output. This might take significantly longer and therefore probably should only be enabled for the final binary. At the moment this option only affects ELF shared library generation. Future releases of the linker may make more use of this option. Also currently there is no difference in the linker's behaviour for different non-zero values of this option. Again this may change with future releases. 

https://github.com/bminor/binutils-gdb/blob/binutils-2_33-branch/ld/lexsup.c#L1025

---

For ld.lld: https://man.openbsd.org/ld.lld

>-Ovalue
    Optimize output file size. value may be:
    0
        Disable string merging.
    1
        Enable string merging.
    2
        Enable string tail merging.
    -O1 is the default.

https://github.com/llvm-mirror/lld/blob/release_90/ELF/Driver.cpp#L849

ld.lld also has a separate LTO linking optimization option:

>--lto-Oopt-level
    Optimization level for LTO.

https://github.com/llvm-mirror/lld/blob/release_90/ELF/Driver.cpp#L954

Example of valid/invalid syntax in this test: https://github.com/llvm-mirror/lld/blob/release_90/test/ELF/lto/opt-level.ll

**Comment by kanyck** [comment]
Thanks for the explanations and the links!
