### ISSUE TITLE
LibreOffice doesn't build with GCC9: internal compiler error

### ISSUE THREAD

**Issue by kanyck** [InBetweenNames/gentooLTO#448]
I keep having
`internal compiler error: in record_target_from_binfo, at ipa-devirt.c:2667`
when trying to build LibreOffice with GCC9.
The full log
https://yadi.sk/d/T3O9vNkNAYMIbA
`emerge --info` output
http://dpaste.com/26N1QGD

**Comment by barolo** [comment]
> I keep having
> `internal compiler error: in record_target_from_binfo, at ipa-devirt.c:2667`
> when trying to build LibreOffice with GCC9.
> The full log
> https://yadi.sk/d/T3O9vNkNAYMIbA
> `emerge --info` output
> http://dpaste.com/26N1QGD

It definitely builds with gcc 9, as I've been doing it for some time. As far as I remember it never liked flto in flags but with EXTRA_ECONF="--enable-lto"  passed, it builds fine

**Comment by kanyck** [comment]
Well, adding two lines 
```
app-office/libreoffice *FLAGS-=-flto*
app-office/libreoffice EXTRA_ECONF="--enable-lto"
```
to `ltoworkarounds.conf ` makes libreoffice to build successfully, indeed. Thanks for the tip! Hope it's still got ltoized!

However, the compiler should not neither give internal error out nor segfault under any curcumstances. So there's still a bug in GCC, however this workaround allows us to live by.

And yes, I agree, if the package configuration has "--enable-lto" option I think it ought to be reflected in ebuild's USE flags.

**Comment by barolo** [comment]
@kanyck 
Are you sure that EXTRA_ECONF="--enable-lto" got picked from ltoworkarounds? I've never used it for env stuff, although I see that there are few "export EXTRA_ECONF*"  already

**Comment by kanyck** [comment]
> Are you sure that EXTRA_ECONF="--enable-lto" got picked from ltoworkarounds?

Looks like it does. Why not? AFACS there are not only FLAGS specified in ltoworkarounds. At least it it worked somehow and libreoffice has built this time, while previously it hasn't. Can't tell for sure, because my system cleans successful build logs. It takes way too long to check, though...

**Comment by barolo** [comment]
> > Are you sure that EXTRA_ECONF="--enable-lto" got picked from ltoworkarounds?
> 
> Looks like it does. Why not? AFACS there are not only FLAGS specified in ltoworkarounds. At least it it worked somehow and libreoffice has built this time, while previously it hasn't. Can't tell for sure, because my system cleans successful build logs. It takes way too long to check, though...

You did *FLAGS-=-flto*
This would fix build itself, you'd have to watch term o search it for flto during/after it builds to be certain, or just check binary size [ binary of LO, with LTO it ill be smaller than usual one ]

**Comment by elsandosgrande** [comment]
Did you notice all of those `One definition rule violation [-Wodr]` lines?  #382 is what you are experiencing.

**Comment by elsandosgrande** [comment]
@barolo @kanyck

**Comment by kanyck** [comment]
Thanks! Wlll try over the weekend!

**Comment by kanyck** [comment]
Okay. Just rebuild LO with the following in the ltoworkarounds.conf:
```
app-office/libreoffice *FLAGS-="${SEMINTERPOS}"
app-office/libreoffice EXTRA_ECONF="--enable-lto"
```
It has built successfully and sizes of binaries are just the same as before. So I believe `EXTRA_ECONF="--enable-lto"` enables LTO by itself.

**Comment by elsandosgrande** [comment]
Now, as this is a duplicate of my ticket (why do almost all of the tickets get replies other than mine!?), will you be closing it?

**Comment by kanyck** [comment]
Well, if you're ready to track the issue somehow, then yes.
At the moment I think it's reasonable to propose to add those two lines into overlay's ltoworkarounds.conf.
Closing so far.
