### ISSUE TITLE
Graphite info actualization for media-libs/lcms and dev-lang/python

### ISSUE THREAD

**Issue by pchome** [InBetweenNames/gentooLTO#45]
package.cflags/ltoworkarounds.conf:
```bash
#Packages which Graphite optimizations don't play nice with
media-libs/lcms *FLAGS-="${GRAPHITE}"
sys-apps/man-db *FLAGS-="${GRAPHITE}"
dev-lang/python *FLAGS-="${GRAPHITE}"
```

I have `media-libs/lcms` and `dev-lang/python` built w/o any flag overriding. Is this flags modification still needed ?

**Comment by InBetweenNames** [comment]
Nice!  Yes, I was able to reproduce this here.  I'll update it shortly.

**Comment by InBetweenNames** [comment]
I'm going to comment out `lcms`, but just to verify -- you were able to get all versions of python (latest version in each slot) built with Graphite?  I have some unrelated problems that are preventing me from building them all currently.

**Comment by pchome** [comment]
I have 2.7, 3.6 and 3.5 forced by only one package. So not sure about 3.4

**Comment by pchome** [comment]
Also I have no `sys-apps/man-db` installed so check it by yourself. Maybe it not affected too.

**Comment by InBetweenNames** [comment]
Thanks for bringing this to my attention!  Fixed in HEAD.
