### ISSUE TITLE
sys-libs/libcap-2.28 failing to build with LTO

### ISSUE THREAD

**Issue by jelinekto** [InBetweenNames/gentooLTO#453]
I'm not able to build the latest `libcap` update even with plain `-march=native -O1 -flto -pipe`. Gold throws out an error (see the log), bfd build hangs indefinitely. `-ffat-lto-objects` seems to be of no use here.
Can someone reproduce this?
[build.log](https://github.com/InBetweenNames/gentooLTO/files/3944663/build.log)

**Comment by corrmaan** [comment]
`=sys-libs/libcap-2.28::gentoo *FLAGS-=-flto*`

Works for me

**Comment by jiblime** [comment]
Unable to replicate after emerging successfully, but I was getting stuck when running in parallel.

`MAKEOPTS="" emerge -1 libcap` fixed it for me.

**Comment by elsandosgrande** [comment]
I am using the the BFD linker and I am not stuck, but getting the aforementioned undefined references. Only disabling LTO works for me. I have tried your workaround @jiblime, but it did not work for me. Yes, I am able to replicate it after emerging the package successfully. I event tried changing `NTHREADS` to 1, but to no avail.

**Comment by jiblime** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=d6502cd58680cab758144bfe51ec6c5556179695

Maybe try resyncing your trees, failing that you can just dash the test as described here https://bugs.gentoo.org/702516#c9

**Comment by elsandosgrande** [comment]
I'm currently in the middle of an update. I synced about ten hours ago.

**Comment by jelinekto** [comment]
Okay, I am now able to build LTOed `sys-libs/libcap-2.28-r1` using `-fuse-ld=bfd`. Gold build still fails for me.

**Comment by elsandosgrande** [comment]
Hm... This is not the first instance of Gold failing where BFD does not. That's actually why we now recommend BFD by default (read the updated README if you have not already).

**Comment by wolfwood** [comment]
same issue with `__wrap_pthread_create` seems to be present with sys-auth/elogind. it looks like removing `-Wl,--as-needed` / adding `-Wl,--no-as-needed`to LDFLAGS is recommended for this kind of issue

**Comment by wolfwood** [comment]
`LDFLAGS-="-Wl,--as-needed" LDFLAGS+="-Wl,--no-as-needed"` doesn't seem to work (probably needed for glibc, instead), but `sys-auth/elogind LDFLAGS+="-Wl,-fuse-ld=bfd"` does.

**Comment by elsandosgrande** [comment]
I pass my `COMMON_FLAGS` to `LDFLAGS`, so... I'll check it out again later.

**Comment by InBetweenNames** [comment]
Seems to be working here -- can you post a complete `build.log`?
