### ISSUE TITLE
dev-python/bcrypt-3.1.7-r2 ICE segfault with -O3

### ISSUE THREAD

**Issue by Admicos** [InBetweenNames/gentooLTO#463]
Full build log: https://issizler.club/build-bc-graphite.log

```
during GIMPLE pass: graphite
src/_csrc/sha2.c: In function ‘SHA256Transform’:
src/_csrc/sha2.c:259:1: internal compiler error: Segmentation fault
  259 | SHA256Transform(u_int32_t *state, const u_int8_t *data)
      | ^
Please submit a full bug report,
```

Workaround: (`/etc/portage/package.cflags`)

```
dev-python/bcrypt /-O3/-O2
```

**Comment by elsandosgrande** [comment]
Hm... What's your version of `dev-libs/isl`?

**Comment by Admicos** [comment]
On Thu, 09 Jan 2020 02:32:59 -0800
Sandy Vujaković <notifications@github.com> wrote:

> Hm... What's your version of `dev-libs/isl`?

    admicos ~ % eix -I isl
    [I] dev-libs/isl
         Available versions:  0.12.2(0/10) 0.21(0/21) (~)0.22(0/22) {static-libs ABI_MIPS="n32 n64 o32" ABI_RISCV="lp64 lp64d" ABI_S390="32 64" ABI_X86="32 64 x32"}
         Installed versions:  0.22(0/22)(01:24:50 PM 12/17/2019)(-static-libs ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
         Homepage:            http://isl.gforge.inria.fr/
         Description:         A library for manipulating integer points bounded by linear constraints

**Comment by elsandosgrande** [comment]
All right, you need an update. It's related to <https://github.com/InBetweenNames/gentooLTO/pull/462> (look at the last comment in #442).

**Comment by Admicos** [comment]
Yep, compiles fine after an update, thanks!

**Comment by elsandosgrande** [comment]
Any time.
