### ISSUE TITLE
more info for switching to gentooLTO

### ISSUE THREAD

**Issue by hedmo** [InBetweenNames/gentooLTO#467]
hi 

this week i wat trying out gcc-10 and got the info that gcc-10 has  flipped -fcommon -> -fno-common
and got info that GentooLTO  already using -fno-common so i am going to try this but need some more info.my make.conf looks like this at the top:
```
COMMON_FLAGS="-march=skylake  -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
```
and to use LTO i need to set this on top of it:

```
NTHREADS="12"

source make.conf.lto

CFLAGS="-march=native ${CFLAGS} -pipe" #NOTE: Consider using -falign-functions=32 if you use an Intel processor.  See issue #164.
CXXFLAGS="${CFLAGS}"
```
i  have modified it to this and dont know if it is correct:

```
source /etc/portage/make.conf.lto
CFLAGS="${CFLAGS} -march=skylake -O3 -pipe -fomit-frame-pointer"
CXXFLAGS="${CXXFLAGS} -march=skylake -O3 -pipe -DNDEBUG -DG_DISABLE_ASSERT"

COMMON_FLAGS="-march=skylake -O3 -pipe -fomit-frame-pointer "
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"


```

This is one thing i like to know.do i need to change something in the lto make.conf files to?
The next is gold.as i understand gold is set to default on gentooLTO but do i need to do something mannually?

regards hedmo

**Comment by elsandosgrande** [comment]
One, these kinds of questions are what the Gitter group chat is meant for (it is at the top of the README), not the issue tracker.

Two, Gold is no longer the default for GentooLTO (again, it is in the README; I even made sure to make it bold ant outlined). Workarounds for it are still being accepted, but BFD is default.

Three, this is a section of my `make.conf`:

~~~ bash
***
source /etc/portage/make.conf.lto.defines
CHOST="x86_64-pc-linux-gnu"
ABI_X86="32 64"
GENTOOLTO="${SAFEST_FAST_MATH} ${GRAPHITE} ${DEVIRTLTO} ${IPAPTA} ${SEMINTERPOS} ${NOPLT} ${FLTO} -fuse-linker-plugin"
COMMON_FLAGS="-O3 -march=bdver4 -pipe -pthread -fira-hoist-pressure -fira-loop-pressure -fbranch-target-load-optimize -fweb -ftracer -fsched2-use-superblocks ${GENTOOLTO} -fuse-ld=bfd -fstack-protector-all -fstack-clash-protection -Wall -Wextra"
LOG="trace"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS} -Wl,-z,relro -Wl,-z,now"
***
~~~

This is how I do it, but you can do this as well (the following is how I used to do things):

~~~ bash
***
source /etc/portage/make.conf.lto.defines
CHOST="x86_64-pc-linux-gnu"
ABI_X86="32 64"
COMMON_FLAGS="-O3 -march=bdver4 -pipe -pthread -fira-hoist-pressure -fira-loop-pressure -fbranch-target-load-optimize -fweb -ftracer -fsched2-use-superblocks ${SAFEST_FAST_MATH} ${GRAPHITE} ${DEVIRTLTO} ${IPAPTA} ${SEMINTERPOS} ${NOPLT} ${FLTO} -fuse-linker-plugin -fuse-ld=bfd -fstack-protector-all -fstack-clash-protection -Wall -Wextra"
LOG="trace"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS} -Wl,-z,relro -Wl,-z,now"
***
~~~

If you are sourcing `make.conf.lto`, then delete the `GENTOOLTO` line and replace `${GENTOOLTO}` with `${CFLAGS}`. I am at the character limit, so I cannot actually show you. 

Next time, please carefully read the README through to the end (read it thrice if once is not enough).

Oh, and finally, **do not modifiy the files provided by GentooLTO in any way!** I learned that the hard way.

**Comment by hedmo** [comment]
elsandosgrande

thank you for the info.i have never used the Gitter group chat and did not find any info about it in the text.if i have missed it the times a have read it i am sorry (not so good with English).i miss understood 
the eselect news when i read it (about Gold).next time i will try to find answer in the Gitter group chat.

regards hedmo

**Comment by elsandosgrande** [comment]
@hedmo The badge is in between The "**GentooLTO**" header and the line with the links to the translations (currently works in progress and only covering the Serbo-Croatian languages, since I only speak those and English). It reads "chat on gitter".
