### ISSUE TITLE
-ffinite-math-only is bad for dev-python/numpy

### ISSUE THREAD

**Issue by sheerluck** [InBetweenNames/gentooLTO#470]
see https://github.com/numpy/numpy/issues/15344

**Comment by asaparov** [comment]
Ah I see this problem too if I have `Ofast` enabled. Are you using `Ofast`, too?

**Comment by sheerluck** [comment]
no

**Comment by asaparov** [comment]
Oh.. then why is `finite-math-only` enabled for you?

**Comment by sheerluck** [comment]
hm... It's a default I guess 
I had to change sys-config/ltoize/files/package.cflags/ltoworkarounds.conf#L143 from 
```
dev-python/numpy /-Ofast/'-O3 ${SAFER_FAST_MATH}' /-ffast-math/'${SAFER_FAST_MATH}' /-funsafe-math-optimizations/'${SAFER_UNSAFE_MATH_OPTS}' 
```
to
```
dev-python/numpy /-Ofast/'-O3 ${SAFER_FAST_MATH}' /-ffast-math/'${SAFER_FAST_MATH}' /-funsafe-math-optimizations/'${SAFER_UNSAFE_MATH_OPTS}' *FLAGS-='-ffinite-math-only'
```

**Comment by asaparov** [comment]
Weird, I don't know why `-ffinite-math-only` would be added if you don't have `Ofast` or `fast-math` enabled. But I added a workaround in a pull request.
