### ISSUE TITLE
bluez-alsa fails with -fno-common

### ISSUE THREAD

**Issue by HellScre4m** [InBetweenNames/gentooLTO#487]
Hey folks.

[Emerge log](http://dpaste.com/3DHN6R8)

Adding 
`media-sound/bluez-alsa C*FLAGS+="-fcommon" C*FLAGS-="-fno-common"`
to cflags, package compiles.

[Emerge log](http://dpaste.com/2YEZDGC)

I'm sorry for long logs it's because of `flto-report`.

**Comment by InBetweenNames** [comment]
Fixed in `master`.  Thanks!
