### ISSUE TITLE
sys-apps/flatpak does not compile with LTO

### ISSUE THREAD

**Issue by kryptt** [InBetweenNames/gentooLTO#489]
The flatpak ebuild is in a third party overlay; so I'm not sure if I should even file this; but just FYI:

when trying to merge sys-apps/flatpak-1.6.2 and 1.4.3 I get a missing symbol; so adding: 

=sys-apps/flatpak-1.4.3 *FLAGS-=-flto*
=sys-apps/flatpak-1.6.2 *FLAGS-=-flto*

to my local workarounds works....

**Comment by gcarq** [comment]
@kryptt What are your USE flags and what is the missing symbol?
It works without workarounds on my machine:

```
sys-apps/flatpak-1.6.2::flatpak-overlay was built with the following:
USE="kde (policykit) seccomp -doc -gnome -gtk -introspection" ABI_X86="(64)"
CFLAGS="-march=native -fno-stack-protector -fomit-frame-pointer -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,-O3 -Wl,--sort-common"
CXXFLAGS="-march=native -fno-stack-protector -fomit-frame-pointer -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -pipe -fvisibility-inlines-hidden -Wl,-O1 -Wl,--as-needed -Wl,-O3 -Wl,--sort-common"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-O3 -Wl,--as-needed -Wl,--sort-common -march=native -fno-stack-protector -fomit-frame-pointer -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -pipe -fvisibility-inlines-hidden"
```

**Comment by kryptt** [comment]
Thanks, 

It was due to the **'introspection'** USE flag; I recompiled with it disabled, and LTO enaabled again successfully, is there anything known around that use flag?

**Comment by kryptt** [comment]
This worked:

sys-apps/flatpak-1.6.2::flatpak-overlay was built with the following:
USE="doc gnome gtk policykit seccomp -introspection -kde" ABI_X86="(64)"
CFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -fno-plt -pipe -Wl,-O1 -Wl,--as-needed"
CXXFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -fno-plt -pipe -Wl,-O1 -Wl,--as-needed"
