### ISSUE TITLE
wine-vanilla doesn't build with -no-plt

### ISSUE THREAD

**Issue by ElDavoo** [InBetweenNames/gentooLTO#491]
Succesfully compiling without -no-plt.
[wine.log](https://github.com/InBetweenNames/gentooLTO/files/4311831/wine.log)

**Comment by InBetweenNames** [comment]
Now this is interesting, because wine-staging works with `-fno-plt` for me.  Does wine-staging work for you at all?

**Comment by InBetweenNames** [comment]
Just looking at your flags, FYI `-fno-stack-protector` is default in GCC as is `-fno-stack-check`, so no need to manually add those. `-fomit-frame-pointer` is also default at `-O1` and higher.  Just in case you wanted to simplify a bit.

**Comment by ElDavoo** [comment]
The issue went away as mysteriously as it came out. Probably the world rebuild helped.
For the explicit flags, there are some packages that manually claim stack-protector and noomit-frame-pointer
