### ISSUE TITLE
dev-lang/ocaml-4.09.0 fails to compile with LTO

### ISSUE THREAD

**Issue by skinkie** [InBetweenNames/gentooLTO#492]

**Comment by nivedita76** [comment]
WFFM

dev-lang/ocaml-4.09.0::gentoo was built with the following:
USE="emacs flambda latex ocamlopt -spacetime -xemacs" ABI_X86="(64)"
CFLAGS="-pipe -march=native -O2 -falign-functions=32 -flimit-function-alignment -fno-plt -Wl,-O1 -Wl,--as-needed -O3 -fira-loop-pressure -flive-range-shrinkage -fno-common -fno-math-errno -fno-trapping-math -flto=32 -mtls-dialect=gnu2"

**Comment by skinkie** [comment]
I can confirm that I can now also compile ocaml.
