### ISSUE TITLE
sys-devel/clang-9.0.1 fails to build with GCC 9.3.0

### ISSUE THREAD

**Issue by ElDavoo** [InBetweenNames/gentooLTO#493]
If I recall correctly, it was working in GCC 9.2.0.

`[1188/1502] /usr/bin/x86_64-pc-linux-gnu-g++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/extra/clang-tidy/modernize -I/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize -I/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/include -Iinclude -I/include -I/usr/lib/llvm/9/include  -DNDEBUG -O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe -Wl,-O1 -Wl,--as-needed -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -MD -MT tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o -MF tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o.d -o tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o -c /var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize/PassByValueCheck.cpp
FAILED: tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/extra/clang-tidy/modernize -I/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize -I/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/include -Iinclude -I/include -I/usr/lib/llvm/9/include  -DNDEBUG -O2 -fno-stack-protector -fno-stack-check -fomit-frame-pointer -march=native -mtune=native -falign-functions=32 -O2 -pipe -Wl,-O1 -Wl,--as-needed -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -MD -MT tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o -MF tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o.d -o tools/extra/clang-tidy/modernize/CMakeFiles/obj.clangTidyModernizeModule.dir/PassByValueCheck.cpp.o -c /var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize/PassByValueCheck.cpp
during GIMPLE pass: eipa_sra
/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize/PassByValueCheck.cpp: In member function ‘bool clang::RecursiveASTVisitor<Derived>::TraverseObjCBoxableAttr(clang::ObjCBoxableAttr*) [with Derived = clang::tidy::modernize::paramReferredExactlyOnce(const clang::CXXConstructorDecl*, const clang::ParmVarDecl*)::ExactlyOneUsageVisitor]’:
/var/tmp/portage/sys-devel/clang-9.0.1/work/x/y/clang/tools/extra/clang-tidy/modernize/PassByValueCheck.cpp:235:1: internal compiler error: Segmentation fault
  235 | } // namespace clang
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.gentoo.org/> for instructions.`

**Comment by tashrifsanil** [comment]
I just came across this issue today. A temporary fix I found was to append `sys-devel/clang LTO_ENABLE_FLAGOMATIC=yes` to `/etc/portage/package.cflags/clang`. But this strips away lto flags when compiling clang

**Comment by ElDavoo** [comment]
I enable flagomatic and it compiled.

**Comment by ElDavoo** [comment]
nevermind, it self-fixed for some reason

**Comment by tashrifsanil** [comment]
Really? I initially commented to try out flagomatic but I realized my build failed and I deleted my comment. 

Did you compile it with flagomatic enabled or disabled in the end?
Also Do you mind sharing your make.conf 😅 ?

**Comment by ElDavoo** [comment]
I enabled it and it worked
