### ISSUE TITLE
sys-devel/clang fails to build

### ISSUE THREAD

**Issue by tashrifsanil** [InBetweenNames/gentooLTO#496]
I'm new to using LTO and gentoo, and I've tried everything I can think of to fixing this issue. I apologize if this is a noob mistake. I tried removing graphite from my use flags, I've tried enabling flagomatic but I still keep getting the same issue. This happens when compiling chromium too.

I've read the issue at https://github.com/InBetweenNames/gentooLTO/issues/493, but the fixes didn't help me.

I tried putting `sys-devel/clang LTO_ENABLE_FLAGOMATIC=yes` in my `/etc/portage/package.cflags/ltoworkarounds.conf`. This is what my make.conf file looks like too:

## My make.conf
```NTHREADS="16"

source make.conf.lto

CFLAGS="-march=znver1 ${FLTO} ${IPAPTA} ${SEMIINTERPOS} -pipe"
CXXFLAGS="${CFLAGS}"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"


USE="luks1_default gnuefi cryptsetup crypt device-mappers graphite -elogind consolekit"

MAKEOPTS="-j16"
PORTDIR="/usr/portage"
DISTDIR="/distfiles"
PKGDIR="/packages"

GENTOO_MIRRORS="http://gentoo.gossamerhost.com rsync://gentoo.gossamerhost.com/gentoo-distfiles/ http://gentoo.mirrors.tera-byte.com/ rsync://mirrors.tera-byte.com/gentoo ftp://mirrors.tera-byte.com/pub/gentoo http://mirror.csclub.uwaterloo.ca/gentoo-distfiles/ ftp://mirror.csclub.uwaterloo.ca/gentoo-distfiles/ https://mirror.csclub.uwaterloo.ca/gentoo-distfiles/"
#FEATURES="ccache"
#CCACHE_DIR="/var/cache/ccache"

ACCEPT_KEYWORDS="~amd64"
#LTO_ENABLE_FLAGOMATIC=yes
```
Heres the gist for the build log https://gist.github.com/tashrifsanil/ea4c317ade05a23244199cb448e36c66

## The long error message:
`FAILED: lib64/libclang.so.10 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -fPIC -march=znver1 -flto=16 -fipa-pta -pipe -Wl,-O1 -Wl,--as-needed -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long  -Wl,-O1 -Wl,--as-needed -march=znver1 -flto=16 -fipa-pta -pipe -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/var/tmp/portage/sys-devel/clang-10.0.0_rc4/work/x/y/clang-abi_x86_64.amd64/./lib64  -Wl,-O3 -Wl,--gc-sections  -Wl,--version-script,"/var/tmp/portage/sys-devel/clang-10.0.0_rc4/work/x/y/clang-abi_x86_64.amd64/tools/libclang/libclang.exports" -shared -Wl,-soname,libclang.so.10 -o lib64/libclang.so.10 tools/libclang/CMakeFiles/libclang.dir/ARCMigrate.cpp.o tools/libclang/CMakeFiles/libclang.dir/BuildSystem.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndex.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexCXX.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexCodeCompletion.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexDiagnostic.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexHigh.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexInclusionStack.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexUSRs.cpp.o tools/libclang/CMakeFiles/libclang.dir/CIndexer.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXComment.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXCursor.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXIndexDataConsumer.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXCompilationDatabase.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXLoadedDiagnostic.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXSourceLocation.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXStoredDiagnostic.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXString.cpp.o tools/libclang/CMakeFiles/libclang.dir/CXType.cpp.o tools/libclang/CMakeFiles/libclang.dir/Indexing.cpp.o tools/libclang/CMakeFiles/libclang.dir/FatalErrorHandler.cpp.o -L/usr/lib/llvm/10/lib64 -Wl,-rpath,"\$ORIGIN/../lib64"  lib64/libclangAST.a  lib64/libclangBasic.a  lib64/libclangDriver.a  lib64/libclangFrontend.a  lib64/libclangIndex.a  lib64/libclangLex.a  lib64/libclangSema.a  lib64/libclangSerialization.a  lib64/libclangTooling.a  /usr/lib/llvm/10/lib64/libLLVMSupport.a  lib64/libclangARCMigrate.a  lib64/libclangTidyPlugin.a  lib64/libclangIncludeFixerPlugin.a  -ldl  -lz  -lrt  -ldl  -ltinfo  -lm  /usr/lib/llvm/10/lib64/libLLVMDemangle.a  lib64/libclangTidyAndroidModule.a  lib64/libclangTidyAbseilModule.a  lib64/libclangTidyBoostModule.a  lib64/libclangTidyCERTModule.a  lib64/libclangTidyDarwinModule.a  lib64/libclangTidyFuchsiaModule.a  lib64/libclangTidyHICPPModule.a  lib64/libclangTidyBugproneModule.a  lib64/libclangTidyCppCoreGuidelinesModule.a  lib64/libclangTidyGoogleModule.a  lib64/libclangTidyLinuxKernelModule.a  lib64/libclangTidyLLVMModule.a  lib64/libclangTidyMiscModule.a  lib64/libclangTidyModernizeModule.a  lib64/libclangTidyObjCModule.a  lib64/libclangTidyOpenMPModule.a  lib64/libclangTidyPerformanceModule.a  lib64/libclangTidyPortabilityModule.a  lib64/libclangTidyReadabilityModule.a  lib64/libclangTidyZirconModule.a  lib64/libclangTidyMPIModule.a  lib64/libclangTidyUtils.a  lib64/libclangTidy.a  lib64/libclangStaticAnalyzerFrontend.a  lib64/libclangTransformer.a  lib64/libclangToolingRefactoring.a  lib64/libclangStaticAnalyzerCheckers.a  lib64/libclangStaticAnalyzerCore.a  lib64/libclangCrossTU.a  lib64/libclangIndex.a  -lpthread  lib64/libclangIncludeFixer.a  lib64/libfindAllSymbols.a  lib64/libclangTooling.a  lib64/libclangFrontend.a  lib64/libclangDriver.a  lib64/libclangParse.a  lib64/libclangSerialization.a  lib64/libclangSema.a  lib64/libclangEdit.a  lib64/libclangAnalysis.a  lib64/libclangFormat.a  lib64/libclangToolingInclusions.a  lib64/libclangToolingCore.a  lib64/libclangRewrite.a  lib64/libclangASTMatchers.a  lib64/libclangAST.a  lib64/libclangLex.a  lib64/libclangBasic.a  /usr/lib/llvm/10/lib64/libLLVM-10.so && :
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.`

**Comment by pixelherodev** [comment]
Dumb question, but how much RAM do you have? LTO uses a _lot_, so you might not have enough.

**Comment by wolfwood** [comment]
i used to have segfaults trying to build chromium with USE=jumbo-build
which eats about 2 GB per cpu. you could try limiting parallelism or, for
chromium there is also USE=component-build which trades longer compiles for
lower memory use.

i didn't see you defining NTHREADS in your make.conf, this gets passed to
-flto to control parallelism during linking, so you might try setting it to
1 and seeing if that helps. you could also disabling parallelism in emerge
and/or removing -j16 from NAKEOPTS to limit the number of other things
using memory while you are linking.

**Comment by tashrifsanil** [comment]
Thanks a lot for the replies !😅. I have 16 gigs of RAM I read somewhere about increasing swap size so I bumped that up to 8 gb but I still had the same issue.

But oh shoot completely forgot about NTHREADS. PS set it ideally to number of threads I have, and if I get issues bump it down? 

Thanks again guys, I'll try these fixes and update!

**Comment by wolfwood** [comment]
on NTHREADS, yes, ideally the number of logical cores.

**Comment by InBetweenNames** [comment]
Yeah, I have 32GB of memory and sometimes that doesn't feel like enough haha.

**Comment by tashrifsanil** [comment]
So I finally got it to work guys, the combination of setting make opts to -j1 and nthreads to 1 did the trick! Thanks again!
