### ISSUE TITLE
sys-cluster/ceph fails to build with LTO

### ISSUE THREAD

**Issue by jonesmz** [InBetweenNames/gentooLTO#500]
> [ 87%] Linking CXX executable ../../bin/ceph-mgr
> cd /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7_build/src/mgr && /usr/bin/cmake -E cmake_link_script CMakeFiles/ceph-mgr.dir/link.txt --verbose=1
> /usr/bin/x86_64-pc-linux-gnu-g++  -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=5 -fuse-linker-plugin -Wl,-O1 -Wl,--as-needed -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -Wno-unknown-pragmas -rdynamic -O2 -pipe -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wl,-O1 -Wl,--as-needed -ftemplate-depth-1024 -Wnon-virtual-dtor -Wno-unknown-pragmas -Wno-ignored-qualifiers -Wstrict-null-sentinel -Woverloaded-virtual -fno-new-ttp-matching -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fdiagnostics-color=auto -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -Wl,-O1 -Wl,--as-needed -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=5 -fuse-linker-plugin -O2 -pipe -march=x86-64 -mtune=generic -pie CMakeFiles/ceph-mgr.dir/__/ceph_mgr.cc.o CMakeFiles/ceph-mgr.dir/__/mon/PGMap.cc.o CMakeFiles/ceph-mgr.dir/ActivePyModule.cc.o CMakeFiles/ceph-mgr.dir/ActivePyModules.cc.o CMakeFiles/ceph-mgr.dir/BaseMgrModule.cc.o CMakeFiles/ceph-mgr.dir/BaseMgrStandbyModule.cc.o CMakeFiles/ceph-mgr.dir/ClusterState.cc.o CMakeFiles/ceph-mgr.dir/DaemonHealthMetricCollector.cc.o CMakeFiles/ceph-mgr.dir/DaemonServer.cc.o CMakeFiles/ceph-mgr.dir/DaemonState.cc.o CMakeFiles/ceph-mgr.dir/Gil.cc.o CMakeFiles/ceph-mgr.dir/Mgr.cc.o CMakeFiles/ceph-mgr.dir/MgrStandby.cc.o CMakeFiles/ceph-mgr.dir/OSDPerfMetricTypes.cc.o CMakeFiles/ceph-mgr.dir/OSDPerfMetricCollector.cc.o CMakeFiles/ceph-mgr.dir/PyFormatter.cc.o CMakeFiles/ceph-mgr.dir/PyModule.cc.o CMakeFiles/ceph-mgr.dir/PyModuleRegistry.cc.o CMakeFiles/ceph-mgr.dir/PyModuleRunner.cc.o CMakeFiles/ceph-mgr.dir/PyOSDMap.cc.o CMakeFiles/ceph-mgr.dir/StandbyPyModules.cc.o CMakeFiles/ceph-mgr.dir/mgr_commands.cc.o  -o ../../bin/ceph-mgr  -Wl,-rpath,/var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7_build/lib: ../../lib/libosdc.a ../../lib/libclient.a ../../lib/libheap_profiler.a ../../lib/libglobal-static.a ../../lib/libceph-common.so.0 ../../boost/lib/libboost_python36.a /usr/lib64/libpython3.6m.so -ldl ../../lib/libosdc.a /usr/lib64/libtcmalloc.so ../../lib/libcommon.a ../../lib/libjson_spirit.a ../../lib/libcommon_utf8.a ../../lib/liberasure_code.a ../../lib/libcrc32.a ../../lib/libarch.a -lresolv ../../boost/lib/libboost_thread.a ../../boost/lib/libboost_chrono.a ../../boost/lib/libboost_atomic.a ../../boost/lib/libboost_system.a ../../boost/lib/libboost_random.a ../../boost/lib/libboost_program_options.a ../../boost/lib/libboost_date_time.a ../../boost/lib/libboost_iostreams.a ../../boost/lib/libboost_regex.a -lblkid /usr/lib64/libssl3.so /usr/lib64/libsmime3.so /usr/lib64/libnss3.so /usr/lib64/libnssutil3.so /usr/lib64/libplds4.so /usr/lib64/libplc4.so /usr/lib64/libnspr4.so /usr/lib64/libcrypto.so -lpthread -ludev -lz -ldl
> /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7/src/msg/Message.h:536: warning: virtual table of type ‘struct MessageSubType’ violates one definition rule   [-Wodr]
>   536 | class MessageSubType : public M {
>       |
> /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7/src/msg/Message.h:536: note: the conflicting type defined in another translation unit
>   536 | class MessageSubType : public M {
>       |
> <built-in>: note: virtual method ‘__cxa_pure_virtual’
> /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7/src/msg/Message.h:501:16: note: ought to match virtual method ‘print’ but does not
>   501 |   virtual void print(ostream& out) const {
>       |                ^
> /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7/src/msg/Message.h:536: warning: virtual table of type ‘struct MessageSubType’ violates one definition rule   [-Wodr]
>   536 | class MessageSubType : public M {
>       |
> /var/tmp/portage/sys-cluster/ceph-14.2.7/work/ceph-14.2.7/src/msg/Message.h:536: note: the conflicting type defined in another translation unit
>   536 | class MessageSubType : public M {
>       |
> <built-in>: note: virtual method ‘__cxa_pure_virtual’
>

**Comment by InBetweenNames** [comment]
Ah yes, looks like an ODR violation -- will accept your PR.  Thank you!
