### ISSUE TITLE
games-fps/gzdoom-4.3.3::gentoo doesn't build with ninja or lto

### ISSUE THREAD

**Issue by nightloli** [InBetweenNames/gentooLTO#524]
i got 

ERROR: compile
ERROR: games-fps/gzdoom-4.3.3::gentoo failed (compile phase):
  ninja -v -j4 -l0 failed

Call stack:
    ebuild.sh, line  125:  Called src_compile
  environment, line 3559:  Called cmake_src_compile
  environment, line 1976:  Called cmake_build
  environment, line 1955:  Called eninja
  environment, line 2415:  Called die
The specific snippet of code:
      "$@" || die "${nonfatal_args[@]}" "${*} failed"

when i was trying to build games-fps/gzdoom with ninja
and i was getting segfault when i was trying to build it with either just -flto or -flto -ffat-lto-objects
It only compiled with

games-fps/gzdoom CMAKE_MAKEFILE_GENERATOR=emake
games-fps/gzdoom *FLAGS-=-flto*

**Comment by elsandosgrande** [comment]
> It only compiled with
> 
> games-fps/gzdoom CMAKE_MAKEFILE_GENERATOR=emake
> games-fps/gzdoom FLAGS-=-flto

Do you need both, or is it just that either one will make the compilation succeed?

**Comment by nightloli** [comment]
I needed both to successfully compile it

**Comment by elsandosgrande** [comment]
In that case, can you compile GZDoom on a clean system, a Gentoo testing installation without ever having GentooLTO installed, without either environment variable?

**Comment by InBetweenNames** [comment]
Indeed this seems to not work on GCC 9.  On GCC 10, I can't reproduce -- just built `games-fps/gzdoom` without any issues on that one.

**Comment by TheGreatMcPain** [comment]
Using GCC 9 gzdoom builds just fine with ninja.  I'm also able to build it using LTO, but the resulting binary segfaults.

**Comment by elsandosgrande** [comment]
@TheGreatMcPain Have you tried it with GCC 10? If so, what is your mileage?

**Comment by TheGreatMcPain** [comment]
@elsandosgrande I haven't used it yet, but I plan to in the coming days.

**Comment by InBetweenNames** [comment]
Is this the error you get?

~~~
GZDoom <unknown version> -  - SDL version
Compiled on May 15 2020

M_LoadDefaults: Load system defaults.
gzdoom: /tmp/portage/games-fps/gzdoom-4.3.3/work/gzdoom-g4.3.3/src/dobject.h:252: PClass* DObject::GetClass() const: Assertion `Class != nullptr' failed.
fish: “gzdoom” terminated by signal SIGABRT (Abort)
~~~

**Comment by billyb2** [comment]
@InBetweenNames, that's the exact same error that I got when I ran `emerge gzdoom` (with LTO, no ninja).

**Comment by TheGreatMcPain** [comment]
Interesting, I tested gzdoom last night using GCC 10 + LTO + Ninja, and it compiled and worked without any issues.

**Comment by TheGreatMcPain** [comment]
@billyb2 Can you provide a build.log of it failing with Ninja?

**Comment by TheGreatMcPain** [comment]
I attempted to compile gzdoom manually with only `-flto=auto` which actually
fails to compile with both Ninja and Make.

Not sure how the ebuild manages to compile it using LTO.

**Comment by InBetweenNames** [comment]
LTO/Ninja disabled via #682

**Comment by billyb2** [comment]
@TheGreatMcPain you're right, it builds fine with ninja, I'll make another pull.

**Comment by billyb2** [comment]
I was going off @nightloli
