### ISSUE TITLE
www-client/firefox fails to configure with EXTRA_ECONF="--with-build-config=bootstrap-lto"

### ISSUE THREAD

**Issue by telans** [InBetweenNames/gentooLTO#531]
Is this the best place to report this issue (even related to lto)? Bails out with:

```
 0:09.35 mozbuild.configure.options.InvalidOptionError: Unknown option: --with-build-config
 0:09.39 *** Fix above errors and then restart with\
 0:09.39                "./mach build"
 0:09.39 gmake: *** [client.mk:115: configure] Error 1
 * ERROR: www-client/firefox-76.0.1::gentoo failed (configure phase):
```

Fixed by adding `EXTRA_ECONF-="--with-build-config=bootstrap-lto" ` to ltoworkarounds.conf, but I am unsure as to if this really fits this repo/config file. I don't believe this truly is an LTO issue.

**Comment by elsandosgrande** [comment]
@telans It appears that the `mozbuild` configuration tool does not support the configuration flag which you are trying to set.

**Comment by telans** [comment]
Yeah, but I'm not sure if you'd be interested in adding it to ltoworkarounds as the flags is related to lto, but the root cause of the failure isn't lto. Just thought I'd see if that was worth a change in this repo.
