### ISSUE TITLE
I'm a new gentoo/gentoolto and github user so pardon me if this issue isn't related to gentoolto

### ISSUE THREAD

**Issue by RefinedAnarchy** [InBetweenNames/gentooLTO#532]
The package flaggie will not work if I source make.conf.lto from make.conf, I've also attempted to source make.conf.lto.defines directly but the same error still appears.
For example, the error after running the line doas flaggie clang -llvm_targets_AMDGPU
  File "/usr/lib/python-exec/python3.7/flaggie", line 25, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.7/site-packages/flaggie/cli.py", line 195, in main
    porttree, cache)
  File "/usr/lib/python3.7/site-packages/flaggie/makeconf.py", line 537, in __init__
    self.parse(mf, path)
  File "/usr/lib/python3.7/site-packages/flaggie/makeconf.py", line 582, in parse
    self.files[fn] = self.MakeConfFile(fn, path)
  File "/usr/lib/python3.7/site-packages/flaggie/makeconf.py", line 455, in __init__
    f = codecs.open(path, 'r', 'utf8')
  File "/usr/lib/python3.7/codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
NotADirectoryError: [Errno 20] Not a directory: '/etc/portage/make.conf/make.conf.lto'

A workaround is to comment out the source make.conf.lto line, run flaggie and then uncomment it again, but I found that to be quite inconvenient, is there any other ways to avoid this problem?

**Comment by InBetweenNames** [comment]
Try sourcing it using the fully qualified path, like `source /etc/portage/make.conf.lto` -- this seems to fix a few other packages that have the same problem.

**Comment by RefinedAnarchy** [comment]
I tried that, didn't solve the problem, i also tried copying the line from make.conf.lto to make.conf and sourcing it directly to make.conf.lto.defines and that did not work either

**Comment by Peter-Levine** [comment]
I don't use flaggie but I assume it's https://github.com/mgorny/flaggie/issues/23
