### ISSUE TITLE
colord-1.3.5 fails to build with LTO

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#545]
`x11-misc/colord-1.3.5:0/2::gentoo` fails to build with LTO with the following error:
```
../../libtool: eval: line 1774: syntax error near unexpected token `|'
```

Adding `*FLAGS-=-flto*` solves the problem, `*FLAGS+=-ffat-lto-objects` is not enough.

**Comment by telans** [comment]
https://bugs.gentoo.org/708340

binutils bug

**Comment by Althorion** [comment]
PEBKAC, forgot to eselect it…
