### ISSUE TITLE
can't compile python (3.9) because of incorrect pgo data??

### ISSUE THREAD

**Issue by ElDavoo** [InBetweenNames/gentooLTO#548]
Hi,
Because of the massive amount of text i have no clue of why i'm having this issue, would you please give me some ideas :(
Thanks

It also happens with other python versions
[build.log](https://github.com/InBetweenNames/gentooLTO/files/4908799/build.log)

**Comment by coffee-lord** [comment]
```
FEATURES=-ccache emerge ...
```

Disabling ccache worked for me. Weird.

**Comment by ElDavoo** [comment]
So it was ccache's fault. I suspected that. Thanks
