### ISSUE TITLE
[meta] Issue cleanup

### ISSUE THREAD

**Issue by telans** [InBetweenNames/gentooLTO#550]
Meta issue for closing issues which no longer should be open. Assuming GCC 10.1.0 is the default target as mentioned in the news release.

Inactive/Outdated:

- https://github.com/InBetweenNames/gentooLTO/issues/184
- https://github.com/InBetweenNames/gentooLTO/issues/461
- https://github.com/InBetweenNames/gentooLTO/issues/404
- https://github.com/InBetweenNames/gentooLTO/issues/381
- https://github.com/InBetweenNames/gentooLTO/issues/402
- https://github.com/InBetweenNames/gentooLTO/issues/317
- https://github.com/InBetweenNames/gentooLTO/issues/313
- https://github.com/InBetweenNames/gentooLTO/issues/223
- https://github.com/InBetweenNames/gentooLTO/issues/183
- https://github.com/InBetweenNames/gentooLTO/issues/184
- https://github.com/InBetweenNames/gentooLTO/issues/139
- https://github.com/InBetweenNames/gentooLTO/issues/91
- https://github.com/InBetweenNames/gentooLTO/pull/364
- https://github.com/InBetweenNames/gentooLTO/pull/365

Answered questions:

- https://github.com/InBetweenNames/gentooLTO/issues/203
- https://github.com/InBetweenNames/gentooLTO/issues/475
- https://github.com/InBetweenNames/gentooLTO/issues/412
- https://github.com/InBetweenNames/gentooLTO/issues/103
- https://github.com/InBetweenNames/gentooLTO/issues/324
- https://github.com/InBetweenNames/gentooLTO/issues/297
- https://github.com/InBetweenNames/gentooLTO/issues/295

Fixed (including upstream):

- https://github.com/InBetweenNames/gentooLTO/issues/484
- https://github.com/InBetweenNames/gentooLTO/issues/428
- https://github.com/InBetweenNames/gentooLTO/issues/437
- https://github.com/InBetweenNames/gentooLTO/issues/438
- https://github.com/InBetweenNames/gentooLTO/issues/408
- https://github.com/InBetweenNames/gentooLTO/issues/347
- https://github.com/InBetweenNames/gentooLTO/issues/314
- https://github.com/InBetweenNames/gentooLTO/issues/268
- https://github.com/InBetweenNames/gentooLTO/issues/190
- https://github.com/InBetweenNames/gentooLTO/issues/143

Cannot reproduce:

- https://github.com/InBetweenNames/gentooLTO/issues/479
- https://github.com/InBetweenNames/gentooLTO/issues/480
- https://github.com/InBetweenNames/gentooLTO/issues/414
- https://github.com/InBetweenNames/gentooLTO/issues/405
- https://github.com/InBetweenNames/gentooLTO/issues/366
- https://github.com/InBetweenNames/gentooLTO/issues/371
- https://github.com/InBetweenNames/gentooLTO/issues/249
- https://github.com/InBetweenNames/gentooLTO/pull/337

There might be some you wish to be left open - but for the most part I believe these can be closed

@InBetweenNames pinging as updated

**Comment by InBetweenNames** [comment]
Thanks for taking the time to do this.  I agree, the number of issues is a bit out of hand.  In the morning I'll officially move all the docs over to GCC 10 and hopefully weed some of these out.

**Comment by barolo** [comment]
#444 is still an active issue with no resolution in sight, it's lost in bickering between Qt folks and compiler guys, affected projects just disable LTO altogether

**Comment by telans** [comment]
I think all the above issues should be closed
