### ISSUE TITLE
use built-in python lto/pgo?

### ISSUE THREAD

**Issue by Hello71** [InBetweenNames/gentooLTO#552]
I used these options with standard Gentoo ebuild:

```
export PROFILE_TASK="-m test -j $(nproc) --pgo-extended"
EXTRA_ECONF="--with-lto --enable-optimizations"
```

**Comment by InBetweenNames** [comment]
I'm all for enabling PGO via an easy way.  What does `--pgo-extended` do?

`--with-lto` just manually adds `-flto` to `CFLAGS`, without any parallelization (may have changed in 3.9)

**Comment by Hello71** [comment]
https://github.com/python/cpython/blob/master/configure.ac#L1286
https://github.com/python/cpython/blob/master/Makefile.pre.in#L261

**Comment by Hello71** [comment]
regarding the parallelization, I think it is intended upstream. they explicitly set lto-partition=none.

**Comment by telans** [comment]
I did a couple tests regarding pgo for python-3.8.5

Using `emerge -uDvpU --with-bdeps=y @world`:

|                     | -pgo   | +pgo   | --pgo-extended |
|---------------------|--------|--------|----------------|
| **time**                | 14.56s | 13.03s | 12.48s         |
| **speedup<br>vs. -pgo** | 0%     | 11.74% | 16.67%         |

For `--pgo-extended` the following was using in the ebuild:

```
if use pgo; then
	emake profile-opt PROFILE_TASK="-m test -x test_gdb test_compileall -j $(nproc) --pgo-extended"
else
```

The full command used was `time for i in {1..10}; do emerge -uDvpU --with-bdeps=y @world &> /dev/null; done` averaged over three consecutive runs.

**Comment by InBetweenNames** [comment]
@telans Thanks for investigating -- it seems like this is an easy way to get a nice performance boost.
