### ISSUE TITLE
GCC in package.use

### ISSUE THREAD

**Issue by naurias** [InBetweenNames/gentooLTO#558]
Do I need to add
`sys-devel/gcc lto`
In package.use 
Or the overlay would work by simply emerging ltoize and then sourcing make.conf.lto in make.conf and finally `emerge -e @world`

Would lto work without gcc lto in package.use?

**Comment by telans** [comment]
gcc needs the `graphite` use flag in order to use the ${GRAPHITE} flags provided in make.conf.lto.defines. I believe the `lto` flags just builds gcc with lto.

**Comment by InBetweenNames** [comment]
Yeah the `lto` flag is only if you want to build GCC itself with LTO.  GCC will support LTO regardless.
