### ISSUE TITLE
Is there a clean way to modify ltoworkarounds.conf?

### ISSUE THREAD

**Issue by adamk90** [InBetweenNames/gentooLTO#560]
Hi,

A few packages don't work for me if i dont remove the lto flags, so when i have to, i modify the ltoworkarounds.conf. I maybe blind, but i can not see any other userfriendly way to do this so i have to stash the modifications every time i sync the gentoo-lto repo.

thanks in advance!

**Comment by telans** [comment]
Easiest way would be to submit a PR

**Comment by wolfwood** [comment]
you can create another file in `/etc/portage/package.cflags/` such as `myhacks.conf` for tests and local changes. that's way there will be no git conflicts.

**Comment by adamk90** [comment]
Thanks @wolfwood great advice!

**Comment by barolo** [comment]
@adamk90 how to override ltoworkarounds that way though? Because it still gets picked over "myhacks.conf"
