### ISSUE TITLE
Python 2.7 not compiling

### ISSUE THREAD

**Issue by yibaba** [InBetweenNames/gentooLTO#562]
With GCC 10.2.0 python 2.7 from the overlay doesnt compile
Are there any known fixes?

**Comment by telans** [comment]
Very descriptive bug report, shall I just read your mind to see why it isn't compiling?

**Comment by wolfwood** [comment]
@yibaba please provide a build.log file for the failed build

**Comment by yibaba** [comment]
I am sorry my gentoo installation imploded so I decided to try artix for a while, so the build log is forever lost
