### ISSUE TITLE
kde-plasma/plasma-integration fails with LTO error

### ISSUE THREAD

**Issue by acjones8** [InBetweenNames/gentooLTO#563]
Greetings everyone! I have a bunch of plasma updates, and I keep running into an issue with some of them. With plasma integration, it's this:

    lto1: internal compiler error: bytecode stream: expected tag identifier_node instead of LTO_UNKNOWN
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <https://bugs.gentoo.org/> for instructions.
    lto-wrapper: fatal error: /usr/bin/x86_64-pc-linux-gnu-g++ returned 1 exit status
    compilation terminated.
    /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

kwin also fails to build, but it fails silently with only a "error occurred while compiling". I have a suspicion that they're related though. I'm curious to see if other people are also running into this, so I know whether it's an issue with the KDE ports or if I need to poke around in my config for something. If you need any more info, feel free to ask and I'll do my best to deliver!

**Comment by zeule** [comment]
Did you run lto-rebuild? Usually kwin builds break because of the static library in dev-qt/designer or dev-qt/qtdeclarative.

**Comment by barolo** [comment]
yep, had the same issue, need to rebuild qtdeclatrative or just use lto-rebuild

**Comment by acjones8** [comment]
Thank you, that was indeed the fix! After a bunch of packages were rebuilt by lto-rebuild, plasma-integration installed happily and I'm chipping away at the rest. I did run lto-rebuild when I first switched to LTO, but I didn't realize I might need to run it again in the future, I'll keep that in mind if I run into a similar issue again. Thank you once again!

**Comment by barolo** [comment]
Just watch for compiler [gcc] updates, because that's what breaks it almost always, gcc got updated recently.

**Comment by barolo** [comment]
@acjones8  Just watch for compiler [gcc] updates, because that's what breaks it almost always, gcc got updated recently.

**Comment by jiblime** [comment]
Hey, sorry to comment on a closed issue but I'd like to chime in on an alternative solution if `lto-rebuild` doesn't resolve a future problem (quickly enough).

https://github.com/clearlinux/autospec/pull/336

With GCC 10.2.0, I was unable to emerge kross or kwin even without `-flto`. Here is what I have in a local package.cflags/*.conf file:

```
kde-frameworks/kross *FLAGS-=-flto*
kde-frameworks/kross LDFLAGS+=-fno-lto

kde-plasma/kwin *FLAGS-=-flto*
kde-plasma/kwin LDFLAGS+=-fno-lto
```

Although this is much less ideal than using `lto-rebuild`, could be helpful if you need a fully congruent kde-package desktop asap.
