### ISSUE TITLE
Make.conf from fresh install changed

### ISSUE THREAD

**Issue by Retidurc** [InBetweenNames/gentooLTO#568]
Hello ! 

default portage configuration on a fresh install seems to have changed and now use a COMMON_FLAGS variable this way : COMMON_FLAGS=" -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

so the make.conf.lto CFLAGS get overriden by the on in make.conf

I have made local changes to get it to work, but I guess you will want to change something on your side to get along the new defaults

**Comment by jiblime** [comment]
Hm..this is partly how I operate my own flags. What change would be ideal? 

```
source /etc/portage/make.conf.lto
FLTO="-flto -flto-compression-level=9"
CFLAGS="${GRAPHITE} ${IPAPTA} ${DEVIRTLTO} ${SEMINTERPOS} ${FLTO}"

COMMON_FLAGS="-O3 -march=native ${CFLAGS} -pipe"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
```

WRT to the different default format, perhaps the README.md could instead suggest:
```
source /etc/portage/make.conf.lto

COMMON_FLAGS="-O2 ${CFLAGS} -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
```

**Comment by InBetweenNames** [comment]
I'll have to take a look at this one -- hopefully it's a simple fix for new users.  Which profile is this?
