### ISSUE TITLE
Clarification on which architectures have support in gentooLTO 

### ISSUE THREAD

**Issue by jiblime** [InBetweenNames/gentooLTO#575]
A lot of our workarounds are more for i386/amd64 architecture and their related packages.

Would it be ideal to clarify if other architectures, ex. armv7/armv8, would be able to use the lto-overlay 'out of the box'? Storage constrained devices that use such architectures would benefit greatly from LTO.

Edit: Has anyone tried it with armv8? Was my original question :p

**Comment by telans** [comment]
I can't imagine anything is stopping the overlay/ltoize from working on those architechtures, but as you point out it might need a whole new set of workarounds.

I'm not sure if there's *any* demand at all for other architechture workarounds, although I think seperating the files into ltoworkarounds.conf.{amd64,i386,arm} for each to only apply if the host arch matches would be a way to go about it if someone wants to try. Relating to this, are there any workarounds at the moment which seem to be x86 only?

**Comment by jiblime** [comment]
Possibly relating to the -Ofast set of workarounds:

`On Darwin systems, the math library never sets errno. There is therefore no reason for the compiler to consider the possibility that it might, and -fno-math-errno is the default. `
https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/Optimize-Options.html

Though I don't know if Gentoo prefixes work on MacOS.

I'm interested in testing if gentooLTO will work with a Raspberry Pi so I can utilize LTO. If not, I think I'll use a download-n-go distro instead for the time being just to get it up

**Comment by jiblime** [comment]
Closing for now; I think I should re-open the issue once I actually run into any errors, if at all.
