### ISSUE TITLE
media-libs/mesa: i965_dri.so segfaults with LTO

### ISSUE THREAD

**Issue by TheGreatMcPain** [InBetweenNames/gentooLTO#577]
`i965_dri.so` segfaults when mesa is compiled with LTO enabled.

The error from `dmesg` looks like this:
```
kernel: kitty[14653]: segfault at 3b ip 00007f1e20c848c0 sp 00007ffd02ebc330 error 4 in i965_dri.so[7f1e201d3000+c12000]
```

Adding this to `package.cflags` makes it work without disabling LTO on setups that don't use `i965`.
```
media-libs/mesa "has video_cards_i965 ${IUSE//+} && use video_cards_i965 && FlagSubAllFlags -flto*"
```

I'm using the default GentooLTO configuration, but with the `pie` and `ssp` useflags disabled, and my glibc version is 2.32.

Here's my [emerge --info](https://github.com/InBetweenNames/gentooLTO/files/5087935/emerge-info.txt), and [build.log](https://github.com/InBetweenNames/gentooLTO/files/5088144/build.log), if needed.

**Comment by barolo** [comment]
It's worth mentioning that it doesn't affect modern iintel ris driver, and users of broadwell or newer should switch to it
As per: https://forums.gentoo.org/viewtopic-t-1110144-start-0.html

**Comment by InBetweenNames** [comment]
Yeah, I think this workaround is very reasonable -- also thanks for the reminder about the Iris driver, I will have to switch to that when I get a minute.
