### ISSUE TITLE
gnustep-base/gnustep-base fails with CFLAGS="-march=native -O3 ${SAFEST_FAST_MATH} ${GRAPHITE} ${DEVIRTLTO} ${IPAPTA} ${SEMINTERPOS} ${FLTO} -fuse-linker-plugin"

### ISSUE THREAD

**Issue by King-Mucus** [InBetweenNames/gentooLTO#581]
Unicode.m: In function ‘GSSetupEncodingTable.part.0’:
Unicode.m:339:9: note: length computed here
In function ‘strncpy’,
    inlined from ‘newDataWithEncodedPort’ at NSMessagePort.m:199:3:
/usr/include/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^
NSMessagePort.m: In function ‘newDataWithEncodedPort’:
NSMessagePort.m:199:41: note: length computed here
  199 |   strncpy((char*)pi->addr, (char*)name, strlen((char*)name) + 1);
      |                                         ^
/var/tmp/portage/gnustep-base/gnustep-base-1.27.0/temp/ccf282Pz.s: Assembler messages:
/var/tmp/portage/gnustep-base/gnustep-base-1.27.0/temp/ccf282Pz.s:17929: Error: symbol `__objc_class_ref__GSMutableInsensitiveDictionary.lto_priv.1' is already defined
make[5]: *** [/var/tmp/portage/gnustep-base/gnustep-base-1.27.0/temp/cc6CRVb8.mk:218: /var/tmp/portage/gnustep-base/gnustep-base-1.27.0/temp/libgnustep-base.so.1.27.0.OxSAn7.ltrans72.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
gmake[4]: *** [/usr/share/GNUstep/Makefiles/Instance/library.make:293: obj/libgnustep-base.so.1.27.0] Error 1
gmake[3]: *** [/usr/share/GNUstep/Makefiles/Instance/library.make:278: internal-library-all_] Error 2
gmake[2]: *** [/usr/share/GNUstep/Makefiles/Master/rules.make:297: libgnustep-base.all.library.variables] Error 2
gmake[1]: *** [/usr/share/GNUstep/Makefiles/Master/library.make:37: internal-all] Error 2
gmake[1]: Leaving directory '/var/tmp/portage/gnustep-base/gnustep-base-1.27.0/work/gnustep-base-1.27.0/Source'
make: *** [/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2

**Comment by King-Mucus** [comment]
BTW, it fails to compile even with *FLAGS="-march=native -O2 -pipe -fcommon"

**Comment by telans** [comment]
Does it fail in the same way?

**Comment by King-Mucus** [comment]
> Does it fail in the same way?

Yes.

**Comment by telans** [comment]
If I had to guess it's because of ${SAFEST_FAST_MATH} being system wide - it can make some things act weird

**Comment by jbcjorge** [comment]
At least in my case this is because the tools needed to compile the package `gnustep-base/gnustep-base` doesn't play well to build packages when are built with LTO.

I already uploaded the PR with the addition of the package to the no-lto

**Comment by InBetweenNames** [comment]
Should be fixed -- just comment if you're still having this issue and I'll reopen.
