### ISSUE TITLE
flto=auto + clang

### ISSUE THREAD

**Issue by kryptt** [InBetweenNames/gentooLTO#587]
As a consecuence of #527 , projects that compile with clang fail to build. 

Since clang does not support -flto=auto but instead -flto=full or -flto=thin and for projects that require CLANG to build like sys-devel/llvm-roc for amd gpu drivers get confused here.. 

The workaround I did was: 

sys-devel/llvm-roc *FLAGS-="${FLTO}" *FLAGS+="-flto=full"
dev-libs/rocm-device-libs *FLAGS-="${FLTO}" *FLAGS+="-flto=full"

but it might make sense to make FLTO more aware of whatever CC turns out to be?...?

**Comment by jiblime** [comment]
GentooLTO takes heavy advantage of `app-portage/portage-bashrc-mv`; it's good stuff. One of the things it comes with is the directory `/etc/portage/bashrc.d`. In it, you can edit `/etc/portage/bashrc.d/10-flag.sh` and add `'-flto=auto'` under the `FLAG_FILTER_NONGNU=(` section.

I've submitted a PR for it here: https://github.com/vaeth/portage-bashrc-mv/pull/23

---

I may be mistaken but I believe GCC 10 has had `-flto`, when invoked without auto/jobserver/2/3/4/etc., default to parallelize based on an observation if multiple jobs are running. IIRC some people had OOM issues when not explicitly stating number of LTO threads?

https://github.com/gcc-mirror/gcc/commit/e75c29e7c8be4ae62f2ab68eb1e18e22dca06a88

**Comment by jiblime** [comment]
@kryptt `app-portage/portage-bashrc-mv` from the mv overlay has been bumped to 20.2 and will now filter out `-flto=auto`.

Regarding your workaround using *FLAGS+="-flto=full":

https://releases.llvm.org/10.0.0/tools/clang/docs/UsersManual.html

```
-flto=<value>           Set LTO mode to either 'full' or 'thin'
  -flto                   Enable LTO in 'full' mode
```

Setting -flto is sufficient to use LTO in full mode

**Comment by jiblime** [comment]
@kryptt `app-portage/portage-bashrc-mv` from the mv overlay has been bumped to 20.2 and will now filter out `-flto=auto`.

Regarding your workaround using *FLAGS+="-flto=full":

https://releases.llvm.org/10.0.0/tools/clang/docs/UsersManual.html

```
-flto=<value>           Set LTO mode to either 'full' or 'thin'
  -flto                   Enable LTO in 'full' mode
```

Setting -flto is sufficient to use LTO in full mode for Clang.

`-flto` in GCC 10 will autoparallelize the linking stage, `-flto` in Clang will also autopar and link in full mode. IMO the solution to your problem would be to use `-flto` for both compilers.

Does that work? If not, you can write a separate script in /etc/portage/bashrc.d to detect if the build env is NONGNU, or check what CC/CXX is being used, then use the functions defined in `10-flag.sh` and `bashrcd.sh` to replace/filter flags accordingly.

**Comment by kryptt** [comment]
@jiblime thanks for all the thorough description! I've learned a lot with this, and yes; this solves my problem!
