### ISSUE TITLE
Clang-based programs don’t compile with `custom-cflags`

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#589]
`www-client/firefox` and `mail-client/thunderbird` fail to compile iff I set `custom-cflags` USE flag. Could this be related to https://github.com/InBetweenNames/gentooLTO/issues/587?

With `www-client/firefox-80.0.1`:
* Gist with environment: https://gist.github.com/Althorion/6259cda994beaaf06a881fb15e28fa7a
* Compressed build log (10 MiB uncompressed, 251.5 kiB compressed): https://mega.nz/file/yVl1RKrS#hDBvoflVkoFhgOorw-qF5jis1WUMDzrNgDuSRBPUtuI

**Comment by perfect7gentleman** [comment]
It's better to define custom *FLAGS specially for clang.
like this 
```
$ cat /etc/portage/env/clang_compiler
CC="clang"
CXX="clang++"

ADDR2LINE="llvm-addr2line"
AR="llvm-ar"
AS="llvm-as"
CXXFILT="llvm-cxxfilt"
DWP="llvm-dwp"
LD="ld.lld"
CC_LD="/usr/bin/ld.lld"
CXX_LD="/usr/bin/ld.lld"
OBJCOPY="llvm-objcopy"
OBJDUMP="llvm-objdump"
NM="llvm-nm"
RANLIB="llvm-ranlib"
READELF="llvm-readelf"
SIZE="llvm-size"
STRINGS="llvm-strings"
STRIP="llvm-strip"

COMMON_FLAGS="-march=native -mtune=native -O3 -pipe -flto=thin -fomit-frame-pointer -fslp-vectorize -fvectorize -mllvm -polly -fno-common -fno-plt -fno-stack-protector -fno-unwind-tables"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS} -stdlib=libc++"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--icf=all -Wl,--lto-O3 -Wl,--thinlto-jobs=9 -fuse-ld=lld -stdlib=libc++ -rtlib=compiler-rt -unwindlib=libunwind -s ${COMMON_FLAGS}
```

**Comment by Althorion** [comment]
Is this a working config for you? Because when I use it, I get some flag errors, like:

```
 0:10.60 DEBUG: clang (LLVM option parsing): Unknown command line argument '-polly'.  Try: 'clang (LLVM option parsing) --help'
```

**Comment by perfect7gentleman** [comment]
of course for me it works.
remove ''-mllvm -polly' since you surely don't have it

**Comment by Althorion** [comment]
Installed polly instead. ;) Thanks!

**Comment by Althorion** [comment]
Worked with Firefox, but I can’t compile Thunderbird. I have tried the “regular” version, the version from your overlay, been playing with USE flags, can’t seem to get a combination that would work—so it’s probably a different package causing problems.

Compilation errors are the same: lot of noise, ending with:
```
ESC7ESC8ESC[1GESC[KESC[34m 9:40.18ESC(BESC[m gmake[2]: *** [/var/tmp/portage/mail-client/thunderbird-68.12.0/work/thunderbird-68.12.0/config/recurse.mk:34: compile] Error 2ESC(B
ESC[m
ESC7ESC8ESC[1GESC[KESC[34m 9:40.18ESC(BESC[m gmake[1]: *** [/var/tmp/portage/mail-client/thunderbird-68.12.0/work/thunderbird-68.12.0/config/rules.mk:413: default] Error 2ESC(BESC[m
```

Full log for Thunderbird (compressed from 10.2 MiB to 275.8 KiB): https://mega.nz/file/KI9TyR4J#OJZseTrBMsbYGvva_fBOOv3vwRKYUR7FXNkQdyNAITk

**Comment by perfect7gentleman** [comment]
```
USE="clang cross-lto custom-cflags custom-optimization dbus eme-free gmp-autoupdate jit kde lto pgo pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp wayland -bindist -debug -hardened -jack -lightning (-selinux) -startup-notification -test -thinlto -wifi" ABI_X86="(64)" CPU_FLAGS_X86="-avx2" L10N="ru -de -en-GB"
```
the working installation

**Comment by Althorion** [comment]
Thanks, it works now!
