### ISSUE TITLE
Feature request: bash script to autodetect common LTO problems

### ISSUE THREAD

**Issue by pchome** [InBetweenNames/gentooLTO#60]
Something like:
`for i in ${LIST}; do;`
* then cat or symlink something like `pkg-cat/pkg-name $i` to `package.cflags/lto.check.tmp`
* `emerge -1 pkg-cat/pkg-name -q`
* produce output on success/fail
* ...

`done`

Maybe some flags like `--keep-graphite`, `--keep-lto`, or even `--quick, -q` to do most common checks only.
It's ease to self write as one-string command but better to make standardised/supported and maybe redirect output to common "paste" services (app-text/pastebinit ?) to be included in bug report.

**Comment by InBetweenNames** [comment]
It would be neat to have as a Portage addon that would detect for the presence of linker errors, etc.  I know Portage does support some form of plugins at least.  That way this could be integrated seamlessly in the build process
