### ISSUE TITLE
app-arch/zstd fails to build on my system

### ISSUE THREAD

**Issue by gorrila20** [InBetweenNames/gentooLTO#600]
app-arch/zstd fails to build (in prepare phase) when doing a world update. 
Maybe I just did something stupid, but some help will be appreciated anyways!
::

>>> Unpacking source...
>>> Unpacking zstd-1.4.4.tar.gz to /var/tmp/portage/app-arch/zstd-1.4.4-r4/work
>>> Source unpacked in /var/tmp/portage/app-arch/zstd-1.4.4-r4/work
 * Applying zstd-1.4.5-multi-thread-default.patch ...
patching file programs/zstdcli.c
Hunk #1 succeeded at 624 with fuzz 1 (offset -71 lines).
patching file programs/README.md
Hunk #1 FAILED at 168.
1 out of 1 hunk FAILED -- saving rejects to file programs/README.md.rej
patching file programs/zstdcli.c
Hunk #1 FAILED at 160.
1 out of 1 hunk FAILED -- saving rejects to file programs/zstdcli.c.rej                             [ !! ]
 * ERROR: app-arch/zstd-1.4.4-r4::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch
 *
 * Call stack:
 *               ebuild.sh, line  762:  Called __ebuild_main 'prepare'
 *      phase-functions.sh, line  970:  Called __source_all_bashrcs
 *               ebuild.sh, line  409:  Called __try_source '--no-qa' '/etc/portage/bashrc'
 *               ebuild.sh, line  458:  Called source '/etc/portage/bashrc'
 *                  bashrc, line    6:  Called BashrcdMain '/etc/portage/bashrc'
 *             environment, line  598:  Called LTOPatch
 *             environment, line 1265:  Called eapply '/var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1812:  Called _eapply_patch '/var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1750:  Called __helpers_die 'patch -p1  failed with /var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 *
 * If you need support, post the output of `emerge --info '=app-arch/zstd-1.4.4-r4::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-arch/zstd-1.4.4-r4::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-arch/zstd-1.4.4-r4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-arch/zstd-1.4.4-r4/temp/environment'.
 * Working directory: '/var/tmp/portage/app-arch/zstd-1.4.4-r4/work/zstd-1.4.4'
 * S: '/var/tmp/portage/app-arch/zstd-1.4.4-r4/work/zstd-1.4.4'

>>> Failed to emerge app-arch/zstd-1.4.4-r4, Log file:

>>>  '/var/tmp/portage/app-arch/zstd-1.4.4-r4/temp/build.log'

 * Messages for package net-libs/libpsl-0.21.0:

 * "icu" and "idn" USE flags are enabled.
 * Using "idn".

 * Messages for package sys-fs/eudev-3.2.9:

 *
 * As of 2013-01-29, eudev-3.2.9 provides the new interface renaming functionality,
 * as described in the URL below:
 * https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames
 *
 * This functionality is enabled BY DEFAULT because eudev has no means of synchronizing
 * between the default or user-modified choice of sys-fs/udev.  If you wish to disable
 * this new iface naming, please be sure that /etc/udev/rules.d/80-net-name-slot.rules
 * exists: touch /etc/udev/rules.d/80-net-name-slot.rules
 *

 * Messages for package app-arch/zstd-1.4.4-r4:

 * ERROR: app-arch/zstd-1.4.4-r4::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch
 *
 * Call stack:
 *               ebuild.sh, line  762:  Called __ebuild_main 'prepare'
 *      phase-functions.sh, line  970:  Called __source_all_bashrcs
 *               ebuild.sh, line  409:  Called __try_source '--no-qa' '/etc/portage/bashrc'
 *               ebuild.sh, line  458:  Called source '/etc/portage/bashrc'
 *                  bashrc, line    6:  Called BashrcdMain '/etc/portage/bashrc'
 *             environment, line  598:  Called LTOPatch
 *             environment, line 1265:  Called eapply '/var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1812:  Called _eapply_patch '/var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *             environment, line 1750:  Called __helpers_die 'patch -p1  failed with /var/lib/layman/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 *
 * If you need support, post the output of `emerge --info '=app-arch/zstd-1.4.4-r4::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-arch/zstd-1.4.4-r4::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-arch/zstd-1.4.4-r4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-arch/zstd-1.4.4-r4/temp/environment'.
 * Working directory: '/var/tmp/portage/app-arch/zstd-1.4.4-r4/work/zstd-1.4.4'
 * S: '/var/tmp/portage/app-arch/zstd-1.4.4-r4/work/zstd-1.4.4'

emerge --info ::

Portage 3.0.4 (python 3.7.8-final-0, default/linux/amd64/17.1/desktop, gcc-10.2.0, glibc-2.31-r6, 5.8.8-gentoo x86_64)
=================================================================
System uname: Linux-5.8.8-gentoo-x86_64-AMD_Ryzen_5_3600_6-Core_Processor-with-gentoo-2.7
KiB Mem:    16381824 total,    443876 free
KiB Swap:   20971516 total,  20968700 free
Timestamp of repository gentoo: Fri, 11 Sep 2020 16:00:01 +0000
Head commit of repository gentoo: 976ef028d3a1c18cfa64f3880a8a2754da35afea
Timestamp of repository eclipse: Fri, 11 Sep 2020 16:07:10 +0000
Head commit of repository eclipse: 24fa4835b7ec1c22167e19e70b6967de4bfcce8b

Timestamp of repository libressl: Fri, 11 Sep 2020 16:06:23 +0000
Head commit of repository libressl: f7927ff54c627eb96796e672e82fd3874e19872d

sh bash 5.0_p18
ld GNU ld (Gentoo 2.34 p6) 2.34.0
ccache version 3.7.11 [disabled]
app-shells/bash:          5.0_p18::gentoo
dev-java/java-config:     2.3.1::gentoo
dev-lang/perl:            5.30.3::gentoo
dev-lang/python:          2.7.18-r100::lto-overlay, 3.7.8-r2::gentoo, 3.8.5::gentoo
dev-util/ccache:          3.7.11::gentoo
dev-util/cmake:           3.16.5::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.34-r2::gentoo
sys-devel/gcc:            10.2.0-r1::gentoo
sys-devel/gcc-config:     2.3.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.4-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.31-r6::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts:

eclipse
    location: /var/db/repos/eclipse
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/eclipse.git
    masters: gentoo

libressl
    location: /var/db/repos/libressl
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/libressl.git
    masters: gentoo

gentoo-zh
    location: /var/lib/layman/gentoo-zh
    masters: gentoo
    priority: 50

linxon
    location: /var/lib/layman/linxon
    masters: gentoo
    priority: 50

lto-overlay
    location: /var/lib/layman/lto-overlay
    masters: gentoo mv
    priority: 50

mv
    location: /var/lib/layman/mv
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

vampire
    location: /var/lib/layman/vampire
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=12 -fuse-linker-plugin -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="ftp://mirror.netcologne.de/gentoo/ https://mirror.netcologne.de/gentoo/ http://mirror.netcologne.de/gentoo/ rsync://mirror.netcologne.de/gentoo/ https://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/ http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/ https://ftp.halifax.rwth-aachen.de/gentoo/ https://mirror.leaseweb.com/gentoo/ http://mirror.leaseweb.com/gentoo/ rsync://mirror.leaseweb.com/gentoo/ https://ftp.snt.utwente.nl/pub/os/linux/gentoo http://ftp.snt.utwente.nl/pub/os/linux/gentoo ftp://ftp.snt.utwente.nl/pub/os/linux/gentoo rsync://ftp.snt.utwente.nl/gentoo"
LANG="nl_NL.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="nl"
MAKEOPTS="-j12"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 berkdb bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus dri dts dvd dvdr elogind emboss encode exif flac fortran gdbm gif graphite gtk gui iconv icu ipv6 jpeg lcms libglvnd libnotify libressl libtirpc mad mng mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pdf png policykit ppds pulseaudio qt5 readline sdl seccomp spell split-usr ssl startup-notification svg tcpd tiff truetype udev udisks unicode upower usb vorbis vulkan wxwidgets x264 xattr xcb xinerama xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" CURL_SSL="libressl" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput" KERNEL="linux" L10N="nl" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2 php7-3 php7-4" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_7" RUBY_TARGETS="ruby25" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi radeon" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by jiblime** [comment]
Sorry, this one is my fault (https://github.com/InBetweenNames/gentooLTO/pull/598). I use `ACCEPT_KEYWORDS=~amd64` as recommended for gentooLTO which builds `app-arch/zstd-1.45` and didn't test `app-arch/zstd-1.4.4-r4`.

I'd recommend either unmasking `app-arch/zstd-1.45` or replacing this file:

`/var/db/repos/lto-overlay/sys-config/ltoize/files/patches/app-arch/zstd/zstd-1.4.5-multi-thread-default.patch`

with:

```
diff --git a/programs/zstdcli.c b/programs/zstdcli.c
index 70e2b70..ebd5b33 100644
--- a/programs/zstdcli.c
+++ b/programs/zstdcli.c
@@ -695,7 +695,7 @@ int main(int const argCount, const char* argv[])
     if ((filenames==NULL) || (file_of_names==NULL)) { DISPLAY("zstd: allocation error \n"); exit(1); }
     programName = lastNameFromPath(programName);
 #ifdef ZSTD_MULTITHREAD
-    nbWorkers = 1;
+    nbWorkers = 0;
 #endif
 
     /* preset behaviors */
```

The reason the patch is failing to apply to 1.4.4-r4 is because `${S}/programs/README.md` doesn't have `-T` documented in it yet, and the second hunk for `${S}/programs/zstdcli.c` fails because of line changes. Those two failed hunks are purely cosmetic.

I'm not too sure how to handle version-specific patching, but I will look into it when I have the time.

**Comment by gorrila20** [comment]
Thanks that unmasking worked! Didn't expect it to be that easy of a fix.
