### ISSUE TITLE
www-client/firefox-81.0 fails to build

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#608]
Similarly to https://github.com/InBetweenNames/gentooLTO/issues/589, I can’t build `www-client/firefox-81.0`, getting similar error messages—megabytes of compile logs, ending with:

```
14:26.19 gmake[4]: Leaving directory '/var/tmp/portage/www-client/firefox-81.0/work/firefox_build/toolkit/library/rust'
14:26.19 gmake[3]: Leaving directory '/var/tmp/portage/www-client/firefox-81.0/work/firefox_build'
14:26.19 gmake[2]: *** [/var/tmp/portage/www-client/firefox-81.0/work/firefox-81.0/config/recurse.mk:34: compile] Error 2
14:26.19 gmake[2]: Leaving directory '/var/tmp/portage/www-client/firefox-81.0/work/firefox_build'
14:26.19 gmake[1]: *** [/var/tmp/portage/www-client/firefox-81.0/work/firefox-81.0/config/rules.mk:384: default] Error 2
14:26.19 gmake[1]: Leaving directory '/var/tmp/portage/www-client/firefox-81.0/work/firefox_build'
14:26.19 gmake: *** [client.mk:125: build] Error 2
```

This time, however, nothing I’ve tried works: in particular, turning off the `lto` use flags, setting `*FLAGS-=-flto* *FLAGS+=-fno-strict-aliasing /-O3/-O2`, using perfect7gentleman’s envs, and using really basic envs with just `-O2 -march=native -pipe` (no LTO, no aggresive flags).

Is there anything I should try before giving up and using the pre-built version?

**Comment by barolo** [comment]
Use the one from pg_overlay, preferably with clang.

**Comment by Althorion** [comment]
Same problem. I don’t think it’s the Firefox issue, but something maybe with Clang and/or Rust?

**Comment by perfect7gentleman** [comment]
How do you build it? What toolchain is used?

**Comment by Althorion** [comment]
@perfect7gentleman I’m tinkering with this at the moment. I’ve tried a few different toolchains. Right now, I’m using Clang 10.0.1 with LLVM 10.0.1 from the official Gentoo ebuilds and have replaced Rust with the `dev-lang/rust-bin-1.46.0` from the official Gentoo repo. And at least I get a different build error this time, by far less cryptic:

```
 * ERROR: www-client/firefox-81.0.1::pg_overlay failed (install phase):
 *   !!! newins: /var/tmp/portage/www-client/firefox-81.0.1/files/gentoo-default-prefs.js does not exist
```

Is this possibly something wrong with your ebuild? I’ll try building the ::gentoo one to compare…

**Comment by Althorion** [comment]
Yes, but I was afraid that it could mean that it did finished the build stage and returned 0 or whatever, but only because some files were skipped silently.

When/if the vanilla version will build (it’s still compiling…), I’ll give your newest ebuild a try, too.

**Comment by Althorion** [comment]
OK, so the vanilla version builds, too. I’ll spend some time over the weekend to find out what exactly I have done to fix this, but I strongly suspect that my Rust was the culprit.

Thanks for the help and all the work you put in your overlay!
