### ISSUE TITLE
lto-rebuild has incorrect install phase

### ISSUE THREAD

**Issue by Jannik2099** [InBetweenNames/gentooLTO#620]
lto-rebuild currently does this:

pkg_preinst() {
    dobin "${FILESDIR}"/lto-rebuild
}

however, ${FILESDIR} is not guaranteed to be populated in any non-src phase. This is an issue when installing the package from a PORTAGE_BINHOST

the solution is to just do

src_install() {
    dobin "${FILESDIR}"/lto-rebuild
}

Additionally, lto-rebuild has some dependencies that are in @system :

app-shells/bash:*
sys-devel/binutils:*
sys-devel/gcc:*

Packages are not supposed to depend on @system packages except for USE toggles, conditional blockers or others.
See https://devmanual.gentoo.org/general-concepts/dependencies/#implicit-system-dependency

**Comment by InBetweenNames** [comment]
Thank you!

**Comment by davidsmind** [comment]
This seems to have broken the ebuild

**Comment by davidsmind** [comment]
> * ERROR: app-portage/lto-rebuild-0.9.8::lto-overlay failed (install phase):
 *   The source directory '/tmp/portage/app-portage/lto-rebuild-0.9.8/work/lto-rebuild-0.9.8' doesn't exist
 * 
 * Call stack:
 *            ebuild.sh, line  762:  Called __ebuild_main 'install'
 *   phase-functions.sh, line 1050:  Called __dyn_install
 *   phase-functions.sh, line  574:  Called die
 * The specific snippet of code:
 *              die "The source directory '${S}' doesn't exist"
 *

**Comment by telans** [comment]
I'm not sure it would, `S` wasn't added or removed

**Comment by davidsmind** [comment]
I think the two functions operate differently.

https://github.com/InBetweenNames/gentooLTO/issues/675

If I figure out the right way to get this to work, I'll submit a patch for -r1
