### ISSUE TITLE
OpenMP + LTO(?) + Graphite(?) breaks emerge

### ISSUE THREAD

**Issue by GitGangGuy** [InBetweenNames/gentooLTO#638]
I've applied a couple of optimizations (mainly from gentooLTO) to a stage3 hardened profile with libressl instead of openssl.
This was my `make.conf` afterwards:
```
# VARS
THREADS="16"
AVERAGE="12"
MARCH="znver1"
LICENSE="@FREE"
PRIORITY="5"
NTHREADS="${THREADS}"
CPUFLAGS="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"

# THIRD-PARTY
source make.conf.lto.defines # from gentooLTO

# USE FLAGS
UTLS="ssl gnutls libressl -openssl"
UCRYPT="crypt gnupg gpg"
UCONN="networkmanager wifi bluetooth"
UCOMPRESSION="bzip2 zlib zstd gzip lzo lzma"
UOPTIMIZE="openmp threads"
UDEVEL="git"
UMISC="ncurses unicode vim-syntax udev dbus"
USE="${UTLS} ${UCRYPT} ${UCONN} ${UCOMPRESSION} ${UOPTIMIZE} ${UDEVEL} ${UMISC}"

# SETTINGS
CPU_FLAGS_X86="${CPUFLAGS}"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
ACCEPT_LICENSE="-* ${LICENSE}"
ACCEPT_KEYWORDS="~amd64"
PORTAGE_NICENESS="${PRIORITY}"
INPUT_DEVICES="libinput"
CURL_SSL="libressl"
LC_MESSAGES=C
FEATURES="collision-protect downgrade-backup parallel-fetch parallel-install downgrade-backup unmerge-backup mount-sandbox network-sandbox news pid-sandbox sandbox strict unknown-features-warn userfetch userpriv usersandbox"

# COMPILATION FLAGS
CBASE="-O3 -march=${MARCH} -fomit-frame-pointer -msse3 -mmmx -pipe ${SEMINTERPOS} ${NOCOMMON} -malign-data=cacheline"
CTREE="-ftree-vectorize"
CLTO="${FLTO} -flto-compression-level=9 -fuse-linker-plugin ${DEVIRTLTO} -fdevirtualize-speculatively"
CGRAPHITE="${GRAPHITE} -floop-parallelize-all"
CIPA="${IPAPTA}"
CIRA="-fira-region=mixed -fira-algorithm=CB -fira-hoist-pressure -fira-loop-pressure"
COMMON_FLAGS="${CBASE} ${CTREE} ${CLTO} ${CGRAPHITE} ${CIPA} ${CIRA}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${LDFLAGS} -Wl,--hash-style=gnu"
MAKEOPTS="-j${THREADS} -l${AVERAGE}"
EMERGE_DEFAULT_OPTS="--jobs ${THREADS} --load-average ${AVERAGE}"
CMAKE_MAKEFILE_GENERATOR="ninja"
RUSTFLAGS="-Copt-level=3 -Ctarget-cpu=${MARCH} -Ccodegen-units=${THREADS}"
```
These are my custom `package.cflags` (in addition to the ones provided by gentooLTO):
```
sys-libs/libomp LDFLAGS-=-lm # bug: https://bugs.gentoo.org/665474
dev-util/pkgconf *FLAGS-=-fno-common *FLAGS+=-fcommon
```
Emerging `@world` went successful without any problems. 
___
I decided to add OpenMP to the optimization stack like so: (`/etc/portage/make.conf`)
```
...
COPENMP="-fopenmp -ftree-parallelize-loops=${THREADS} -pthread -lpthread"
COMMON_FLAGS="${CBASE} ${COPENMP} ${CTREE} ${CLTO} ${CGRAPHITE} ${CIPA} ${CIRA}"
...
```
**After emerging libomp, I re-emerged @world, and after it was finished with like 80 from 400 packages, it would never finish compilation of anything afterwards.
This is the point where I'm at right now.** I can't emerge/compile anything, it will just **hang endlessly** after reporting
```
 * Final size of build directory: X KiB
 * Final size of installed tree:  Y KiB
```
in the logs. I've attached the `--debug` logs of a libintl emerge as an example [here](https://bin.snopyta.org/?4c1cdf0564716b6d#66d9wGeTwjgA2KhSYnz9wv5GxRqfWytCHpiUnNqFsPid), the last part is the important one.
___
**Why is OpenMP causing this breakage? Is there something I can do to successfully use OpenMP in this combination?**
I suspect it might be related to [this bug](https://bugs.gentoo.org/734554)?
And, more importantly, **how can I get back to the working system I had before openmp? Is this even possible?**
How can I try out new CFLAGS/gentooLTO without potentially bricking my runtime environment?
Although I'd appreciate help regardless of whether or not this is related to LTO+Graphite, can anyone confirm that openmp works fine without gentooLTO? Did I misconfigure something?

**Comment by Titaniumtown** [comment]
> how can I get back to the working system I had before openmp? Is this even possible?

As a general rule, I always use zfs which has good snapshot functionality and sanoid (which just creates/manages auto-snapshots) idk what you can do right now, but in the future you should (in my opinion) use zfs and sanoid to take snapshots.

**Comment by GitGangGuy** [comment]
@Titaniumtown I use btrfs which has snapshots as well (prefer it because of native kernel support), just forgot to make one :/ I guess I'll have to start over again? That "solves" question b I guess, but does anyone here have experience with OpenMP and a workaround for LTO+Graphite+hardened+OpenMP? I'd really like to use it, but I'm unsure why it didn't work out.

**Comment by Titaniumtown** [comment]
I am going to test with openmp right now, I'll report back if I find anything interesting.

**Comment by petronio** [comment]
To my knowledge enabling the use flag for openmp takes care of enabling the necessary compiler and linker flags for the packages that support it. Enabling the cflag should only enable the pragmas (i.e. does nothing on packages that don't explicitly use it), so I wager you basically ended up forcibly enabling it in a package where it was intentionally disabled or ignored due to a bug or conflict with other flags (e.g. a package that supports multiple threading methods).

**Comment by Titaniumtown** [comment]
Ah, ok. Interesting. So is it not worth testing if the openmp USE flag already takes care of that?

**Comment by GitGangGuy** [comment]
@petronio What should I leave out then? `-fopenmp` obviously, but what about `-ftree-parallelize-loops=${THREADS}`? I can hardly believe that flag is being set by the openmp USE flag automatically, and I think its an important optimization improvement. Should I leave that in my `COMMON_FLAGS`?

**Comment by GitGangGuy** [comment]
@Titaniumtown Did LTO+Graphite+hardened+OpenMP work out for you? What COMMON_FLAGS are you using?

**Comment by petronio** [comment]
If you dig into the ebuild and source for portage-utils (as an example), you'll see that the openmp use is passed into autotools and sets the needed configuration there starting in [line 5569](https://gitweb.gentoo.org/proj/portage-utils.git/tree/configure#n5569).

**Comment by petronio** [comment]
@GitGangGuy I'm not sure about `-ftree-parallelize-loops`, but it shouldn't break anything. Whether you will actually see a performance improvement (or degradation) when combined with LTO and O3 is another matter.

**Comment by Titaniumtown** [comment]
> @Titaniumtown Did LTO+Graphite+hardened+OpenMP work out for you? What COMMON_FLAGS are you using?

Well since the openmp use flag exists, I don't really think there is a need.

**Comment by SudoNova** [comment]
pstree $(pgrep emerge)
Find the last node and attach to it via gdb.
Print the stacktrace via `thread apply bt full`
If you see something including futexes, it's most probably gcc's fault doing parallelization wrong.
I guess your last emerged package is bash. Try re-emerging it to see if portage starts working again.

**Comment by perfect7gentleman** [comment]
Package code should support OpenMP, if it's not then it breaks.

**Comment by Titaniumtown** [comment]
This is strange, I took some compiler flags (excluding openmp) and added it to my make.conf, and not I get the same issue. This issue may not be related to openmp at all.

**Comment by GitGangGuy** [comment]
@Titaniumtown Ok, thats very strange, I had no issue recompiling the full world set (with all the standard hardened stage3 packages) with the flags I had before.

**Comment by Titaniumtown** [comment]
Good thing I had a zfs backup. The interesting thing is that it took like 2 days to break. and I didn't really emerge anything major that would've broken portage.

**Comment by GitGangGuy** [comment]
@Titaniumtown Yeah, I think I'll also restrain from using gentooLTO on my production machine. I've only had problems with it so far (this is not the fault of the devs!) and apparently, benchmarks show that O3+LTO actually performs (on average) worse than plain O2 (+ `ftree-vectorize`). I'd still like to know if using OpenMP is stable, though.

**Comment by sliwowitz** [comment]
Interesting. I've had a problem with the same symptoms after some update. Emerge would hang indefinitely after the 
``` * Final size of build directory: X KiB
 * Final size of installed tree:  Y KiB```
part. I tracked it down to the *strip* phase (I don't remember the specifics of how exactly I've found out, but the log posted here also end near the *strip* phase). Now I'm at a state where I cannot emerge (probably) anything with default the default FEATURES set, but what worked for me was setting 
```
FEATURES="nostrip"
```
Could you check if it helps in your case?

**Comment by Titaniumtown** [comment]
Thank you! I didn't know the terminology for that phase, but that is what I was experiencing. I wonder why that happens.

**Comment by SudoNova** [comment]
@sliwowitz yes that's because portage spwans `ebuild.sh` and it reaches strip phase, where your files should be opened and locked by bash, but because of wrong loop parallelization by gcc for bash, there are `n` (as in `- ftree-loop-parallelize=n`) running loops trying to lock the files via futexes, which leads to deadlock.
Try re-emerging bash (restore from binpkg, binhost, snapshot...) and portage should start working.

**Comment by Titaniumtown** [comment]
Should I add `app-shells/bash *FLAGS-=-ftree-loop-parallelize*` to my `/etc/portage/package.cflags/personal.conf`?

**Comment by GitGangGuy** [comment]
@SudoNova 
> Find the last node and attach to it via gdb.
> Print the stacktrace via `thread apply bt full`

I don't have gdb emerged and it isn't available as a binary :/

> `pstree $(pgrep emerge)`

Returned something with `misc-functions` or so as a child node.

> I guess your last emerged package is bash. Try re-emerging it...
> Try re-emerging bash (restore from binpkg, binhost, snapshot...) and portage should start working

I re-emerged bash as a binary (`emerge -K bash` for anyone who runs into the same problem) and EMERGE IS WORKING AGAIN! YAY \*\o/\*

@Titaniumtown 
> Should I add `app-shells/bash *FLAGS-=-ftree-loop-parallelize`...

I did and I was able to regularly emerge bash afterwards without any further issues.

---
Thank you so much to y'all for helping me out, what a simple fix for such a convoluted mess!
One question remains unanswered:
Does it make sense to pass `-fopenmp -pthread -lpthread` as compilation flags in addition to the `openmp` USE flag + `-ftree-parallelize-loops=...`? Is there any benefit or disadvantage to that approach?
Does passing `-D_GLIBCXX_PARALLEL` additionally improve performance in combination with openmp?

**Comment by SudoNova** [comment]
>  EMERGE IS WORKING AGAIN! YAY *\o/*
Glad it helped :)

> Should I add app-shells/bash *FLAGS-=-ftree-loop-parallelize...
@GitGangGuy @Titaniumtown sure it's a good idea, and I think other shells like `fish`, `zsh`, `csh`, etc are also good candidates.
I remember `-fopenmp` was messing with `x11-libs/libX11` as well, always resulting in segmentation fault.
I would also disable it (as well as bunch of other optimizations) for `gdb`, `valgrind` and other debugging tools, especially valgrind because it's for detecting memory issues.
And `libomp` as well because is it's clang's version of openmp.

> -fopenmp -pthread -lpthread
The latter is not needed, just add `-fpthread` to ldflags as well. GCC takes care of proper flags in both static/dynamic linking situations.

> Does passing -D_GLIBCXX_PARALLEL additionally improve performance in combination with openmp?

I don't know how exactly GCC deals with special C++ macros, please let me know if you found the answer.

One more thing, always avoid using `-floop-parallelize-all` with openmp, I had lots of headaches because of it.

**Comment by Titaniumtown** [comment]
Someone should fork gentooLTO and add openmp and all those other flags, then people can start adding compiler overrides and stuff.

**Comment by telans** [comment]
> Someone should fork gentooLTO and add openmp and all those other flags, then people can start adding compiler overrides and stuff.

Or just create another .conf file for openmp with a use flag on ltoize

**Comment by Titaniumtown** [comment]
Good idea.

**Comment by GitGangGuy** [comment]
Since I stopped using advanced optimizations - I constantly ran into issues, even with the great gentooLTO configs and the performance impact of -O3 etc seems to go in both directions (on average even worsening it), as numerous benchmarks posted here as issues have shown - and this issue seems to be solved, I will close it. Feel free to continue discussing if there is anything relevant worth adding.
