### ISSUE TITLE
Building dev-libs/gjs with lto causes gnome-shell to crash on startup

### ISSUE THREAD

**Issue by killbox998** [InBetweenNames/gentooLTO#647]
This issue is somewhat weird and only happens on my laptop.
when gjs is build with LTO gnome-shell encounters a general protection fault on startup. adding `dev-libs/gjs *FLAGS=-flto*` causes this issue to go away. I am not sure why this doesn't effect my other machine. gjs still compiles just fine with lto, the error occurs at runtime.

**Comment by telans** [comment]
https://github.com/InBetweenNames/gentooLTO/pull/645

**Comment by InBetweenNames** [comment]
Merged, thank you!
