### ISSUE TITLE
numactl and cvs fail without *FLAGS-=-flto

### ISSUE THREAD

**Issue by joe4379** [InBetweenNames/gentooLTO#65]
I had to turn off lto for numactl and cvs.  They install now.  

`#Packages which cannot be built with LTO at all (previously was nolto.conf)
sys-process/numactl *FLAGS-=-flto*
dev-vcs/cvs *FLAGS-=-flto*`

**Comment by joe4379** [comment]
they were both undefined references i think

**Comment by InBetweenNames** [comment]
Confirmed here.  Thanks!

I tried `fat-lto-objects` and removing `as-needed` too, but no luck.  To the no-lto bin they go.
