### ISSUE TITLE
Awesome wm fails to build

### ISSUE THREAD

**Issue by toniz4** [InBetweenNames/gentooLTO#654]
Awesome wm fails to build

- build log (/var/tmp/portage/x11-wm/awesome-4.3-r1/temp/build.log): https://dpaste.com/9JC5ZYAWU
- build env (emerge --info '=x11-wm/awesome-4.3-r1::gentoo') https://dpaste.com/7N439UDCS

**Comment by toniz4** [comment]
adding `x11-wm/awesome *FLAGS+="-fcommon"` to package.cflags solves the issue. Is this eligible to a pull request?

**Comment by telans** [comment]
This is a GCC 10 issue, not related to lto. You should file a bug report on the gentoo bugzilla if there isn't one already

**Comment by telans** [comment]
https://bugs.gentoo.org/707262
