### ISSUE TITLE
sys-process/audit-2.8.4 not linking

### ISSUE THREAD

**Issue by davidsmind** [InBetweenNames/gentooLTO#657]
Hi Team, It looks like on my system this version of audit is building but not linking, log below.

Any advice on CFLAGS to try here. I did just rebuild glib, but audit wasn't building before that.

> /bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -D_GNU_SOURCE -Wno-pointer-sign -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -pipe -falign-functions=32 -ffat-lto-objects -Wl,-O1 -Wl,--as-needed  -Wl,-O1 -Wl,--as-needed -march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -flto=4 -fuse-linker-plugin -pipe -falign-functions=32 -ffat-lto-objects -o autrace autrace.o delete_all.o auditctl-llist.o -L../lib -laudit 

> collect2: error: ld returned 1 exit status

[buildlog.txt](https://github.com/InBetweenNames/gentooLTO/files/5631079/buildlog.txt)

**Comment by telans** [comment]
Can you try with 2.8.5 in ~amd64? That version links fine for me

> libtool: link: x86_64-pc-linux-gnu-gcc -D_GNU_SOURCE -march=znver2 -O3 -flto=17 -flto-compression-level=9 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans -pipe -Wl,-O1 -Wl,-O1 -march=znver2 -O3 -flto=17 -flto-compression-level=9 -fgraphite-identity -floop-nest-optimize -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans -pipe -o .libs/auvirt auvirt.o auvirt-list.o ausearch-time.o  -Wl,--as-needed -L../../auparse /var/tmp/portage/sys-process/audit-2.8.5-r2/work/audit-userspace-80866dc78b5db17010516e24344eaed8dcc6fb99-abi_x86_64.amd64/auparse/.libs/libauparse.so /var/tmp/portage/sys-process/audit-2.8.5-r2/work/audit-userspace-80866dc78b5db17010516e24344eaed8dcc6fb99-abi_x86_64.amd64/lib/.libs/libaudit.so -lcap-ng

**Comment by davidsmind** [comment]
Thanks, That works. But It should be noted about 2.8.4 not linking.
