### ISSUE TITLE
FIXED ||| ncurses fails

### ISSUE THREAD

**Issue by joe4379** [InBetweenNames/gentooLTO#66]
It installs after disabling lto in sys-config/...workarounds

`!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/sys-libs/ncurses-6.0-r1/work/ncurses-6.0-abi_x86_32.x86/ncursestw/config.log
 *               ebuild.sh, line  124:  Called src_configure
 * ERROR: sys-libs/ncurses-6.0-r1::gentoo failed (configure phase):
configure: error: Cannot link test program for libdl
 * Call stack:
 *   econf failed
 *             environment, line 3670:  Called multilib-minimal_src_configure
configure: error: Cannot link test program for libdl

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/sys-libs/ncurses-6.0-r1/work/ncurses-6.0-abi_x86_64.amd64/ncursesw/config.log
 *             environment, line 3670:  Called multilib-minimal_src_configure
 *               ebuild.sh, line  124:  Called src_configure
 * ERROR: sys-libs/ncurses-6.0-r1::gentoo failed (configure phase):
`

**Comment by InBetweenNames** [comment]
Strange, we actually include a workaround for this in `ltoworkarounds.conf`:

~~~
sys-libs/ncurses LDFLAGS+=-ldl # checking whether able to link to dl*() functions... configure: error: Cannot link test program for libdl
~~~

I just tried re-emerging it myself and could not reproduce this bug (with the workaround applied).  Are you updated to the latest config?

**Comment by joe4379** [comment]
That's my bad for not reading the news carefully.  STRIP_FIX fixed it.  Thanks for the fix in my wayland issue thread.

**Comment by flgw** [comment]
I still run into this, but `*FLAGS-=-flto*` helps.
