### ISSUE TITLE
app-arch/zstd-1.4.7 fails to patch

### ISSUE THREAD

**Issue by paulmootrey** [InBetweenNames/gentooLTO#668]
New version of zstd fails to patch using zstd-1.4.5-multi-thread-default.patch

**Comment by telans** [comment]
https://github.com/InBetweenNames/gentooLTO/issues/663

**Comment by mid-kid** [comment]
Since 41-lto-patch.sh also has `$P` in its options, and this patch keeps breaking every single update, I'd suggest dropping the patch in a version-specific directory, and handle updates manually like python...

**Comment by InBetweenNames** [comment]
Just comment if this is still a problem.  It should be fixed.
