### ISSUE TITLE
FIXED ||| wayland fails

### ISSUE THREAD

**Issue by joe4379** [InBetweenNames/gentooLTO#67]
with many undefined references.  it installs w/o lto.

`libtool: link: x86_64-pc-linux-gnu-gcc -m32 -Wall -Wextra -Wno-unused-parameter -g -Wstrict-prototypes -Wmissing-prototypes -fvisibility=hidden -O3 -pipe -march=skylake -Wl,--hash-style=gnu -flto=4 -ftree-vectorize -floop-interchange -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -Wl,--hash-style=gnu -O3 -pipe -march=skylake -flto=4 -ftree-vectorize -floop-interchange -flto=4 -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -o .libs/event-loop-test tests/event-loop-test.o  -Wl,--as-needed ./.libs/libtest-runner.a /var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/.libs/libwayland-client.so -L/usr/lib32/../lib32 /var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/.libs/libwayland-server.so -lm -lrt -ldl -lffi -pthread
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccEsZa1n.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccEsZa1n.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccEsZa1n.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1463: interface-test] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc7INYSq.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc7INYSq.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc7INYSq.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1447: fixed-test] Error 1
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccCZ0U2p.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccCZ0U2p.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccCZ0U2p.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc1ScU5q.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc1ScU5q.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc1ScU5q.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1411: connection-test] Error 1
make[2]: *** [Makefile:1399: client-test] Error 1
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccNAQm0n.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccNAQm0n.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccNAQm0n.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1393: array-test] Error 1
libtool: link: x86_64-pc-linux-gnu-gcc -m32 -Wall -Wextra -Wno-unused-parameter -g -Wstrict-prototypes -Wmissing-prototypes -fvisibility=hidden -O3 -pipe -march=skylake -Wl,--hash-style=gnu -flto=4 -ftree-vectorize -floop-interchange -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -Wl,--hash-style=gnu -O3 -pipe -march=skylake -flto=4 -ftree-vectorize -floop-interchange -flto=4 -fuse-linker-plugin -fgraphite-identity -floop-nest-optimize -o .libs/list-test tests/list-test.o  -Wl,--as-needed ./.libs/libtest-runner.a /var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/.libs/libwayland-client.so -L/usr/lib32/../lib32 /var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/.libs/libwayland-server.so -lm -lrt -ldl -lffi -pthread
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccqrOogo.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccqrOogo.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccqrOogo.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1429: event-loop-test] Error 1
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccRH3B6t.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccRH3B6t.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/ccRH3B6t.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1423: display-test] Error 1
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc8OshuJ.ltrans0.ltrans.o: In function `usage':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:124: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc8OshuJ.ltrans0.ltrans.o: In function `main':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__start_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:389: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/temp/cc8OshuJ.ltrans0.ltrans.o: In function `find_test':
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__stop_test_section'
/var/tmp/portage/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0-abi_x86_32.x86/../wayland-1.14.0/tests/test-runner.c:107: undefined reference to `__start_test_section'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1469: list-test] Error 1`

**Comment by InBetweenNames** [comment]
Hi @joe4379 , just curious, did you do a full system rebuild when you set up LTO on your system?  Also, did you apply the `STRIP_MASK` fix?  I have wayland installed here without issues.  I'll take a look at your other reports as well.

**Comment by joe4379** [comment]
Hi, I can't remember.  I'll reread the docs again on this and the ncurses report.  Thanks!

**Comment by joe4379** [comment]
The STRIP_FIX fixed it!  Thanks for your support, and the effort in general.  ltoize is awesome.
