### ISSUE TITLE
Can't build Firefox 84.0 when using Gold linker

### ISSUE THREAD

**Issue by Phate6660** [InBetweenNames/gentooLTO#673]
It gets all the way up linking libxul and it fails with this error:

```
131:51.88 /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.gold: internal error in set_xindex, at ../../binutils-2.35.1/gold/object.h:1007
131:51.98 collect2: error: ld returned 1 exit status
131:51.99 gmake[4]: *** [/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox-84.0/config/rules.mk:545: libxul.so] Error 1
131:51.99 gmake[4]: Leaving directory '/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox_build/toolkit/library/build'
131:51.99 gmake[3]: *** [/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox-84.0/config/recurse.mk:72: toolkit/library/build/target] Error 2
131:51.99 gmake[3]: Leaving directory '/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox_build'
131:51.99 gmake[2]: *** [/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox-84.0/config/recurse.mk:34: compile] Error 2
131:51.99 gmake[2]: Leaving directory '/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox_build'
131:51.99 gmake[1]: *** [/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox-84.0/config/rules.mk:355: default] Error 2
131:51.99 gmake[1]: Leaving directory '/var/tmp/notmpfs/portage/www-client/firefox-84.0/work/firefox_build'
131:51.99 gmake: *** [client.mk:89: build] Error 2
```

Trying to build Firefox with GCC, along with having LTO and PGO enabled.

Here are my CFLAGS:

```
CFLAGS="-march=ivybridge -O3 -fdevirtualize-at-ltrans -fno-semantic-interposition -fgraphite-identity -floop-nest-optimize  -flto=auto -fuse-linker-plugin -pipe -falign-functions=32"
```

Sorry if this isn't the right place to post this issue. I'm not exactly sure if this is a GentooLTO issue or if it's just a gold linker issue. So I figured it'd be best to just post this anyway in case anyone knows.

**Comment by barolo** [comment]
There's note in the docs about gold linker depreciation as it's unmaintained. Just don't use it. Also, I gave up on building FF with gcc, upstream switched to clang years ago.
I'm using ebuild from pg_overlay, with clang ( pgo + cross lto )

**Comment by Jannik2099** [comment]
Gold is pretty much abandoned as of some years, and mozilla has been using clang + lld exclusively for a long time aswell - I doubt you'll have much fun going forward with gold

**Comment by Phate6660** [comment]
Guess I'm not compiling Firefox. I hate Clang.

**Comment by Jannik2099** [comment]
You can use firefox-bin which is compiled with clang+lto, or alternatively resort to your browser of choice on your iPhone / android phone which is fully built with clang aswell - Gentoo aims to provide user choice where reasonably possible - maintaining our own toolchain patchset is certainly not within that realm, nor do we prioritize building with GPL-only or whatever else restriction.

If you REALLY want to get firefox going with gcc, you can try look at what fedora does - last time I checked they still build it with gcc.

Also note that gcc can use lld just fine if you omit lto.

**Comment by elsandosgrande** [comment]
@Jannik2099 That seems to have changed recently: https://fedoraproject.org/wiki/Changes/CompilerPolicy

**Comment by perfect7gentleman** [comment]
```
# Disable PGO on Rawhide due to build failures
%if 0%{?fedora} > 33
%global build_with_pgo    0
%endif
```
