### ISSUE TITLE
x264 and x264-encoder patch no longer needed for 9999 versions.

### ISSUE THREAD

**Issue by TheGreatMcPain** [InBetweenNames/gentooLTO#680]
This [commit](https://code.videolan.org/videolan/x264/-/commit/6bc7fe4f36ea95db77e6df6d76153dd5a2c770a0) was pushed to x264's repository today.

**Comment by InBetweenNames** [comment]
Fixed via 530494cc1c3ef39ce75c7b68a26ec28ac75c2e37 - thanks!
