### ISSUE TITLE
sys-libs/readline breaks ncurses rendering with -fno-semantic-interposition

### ISSUE THREAD

**Issue by Tule44** [InBetweenNames/gentooLTO#681]
The rendering in ncurses apps breaks whenever I resize the terminal. I added this to ltoworkarounds.conf to solve it/
`sys-libs/readline *FLAGS-="${SEMINTERPOS}"`

**Comment by TheGreatMcPain** [comment]
Yup, happened on my system too. See #392

Are you using no-pie aswell?

**Comment by Tule44** [comment]
Im using pie in my useflags so it might not be a pie issue

**Comment by InBetweenNames** [comment]
Went ahead and disabled this just in case, even though I haven't been able to reproduce this myself.  Thanks!
