### ISSUE TITLE
remove-la breaks colm and ragel

### ISSUE THREAD

**Issue by kartebi** [InBetweenNames/gentooLTO#690]
dev-util/colm-0.14.6 fails to build but works with noflto
but then
dev-util/ragel-7.0.3 fails to build needing libfsm.la

removing the remove-la flag both packs build fine

**Comment by tashrifsanil** [comment]
I'm still running into issues with this, I tried adding this to my ltoworkarounds.conf

`dev-util/ragel *FLAGS-=-remove-la*`
`dev-util/colm *FLAGS-=-remove-la*`

But nada I get this with issue ragel 
`*** No rule to make target '/usr/lib64/libfsm.la', needed by 'ragel'.  Stop`

**Comment by petronio** [comment]
remove-la isn't a language flag, it's a use flag for portage-bashrc-mv. See the linked pull request to see how to resolve this issue.

**Comment by tashrifsanil** [comment]
Yeah my bad, I read the pull request and it fixed my issue thanks!!
