### ISSUE TITLE
Unsupported EAPI=5 (too old) for python-utils-r1

### ISSUE THREAD

**Issue by imrebuild** [InBetweenNames/gentooLTO#726]
`python-3.4.8-r2` and `python-3.5.5-r2` are affected.

**Comment by thubble** [comment]
These versions have been unsupported by Gentoo for a long time and have been removed from Portage. Probably the best fix would be to just remove them?

**Comment by InBetweenNames** [comment]
Yeah, going to do just that.  Thanks for reporting!

**Comment by InBetweenNames** [comment]
Fixed!
