### ISSUE TITLE
app-office/libreoffice- 7.1.2.2[clang] fails to build

### ISSUE THREAD

**Issue by jian-lin** [InBetweenNames/gentooLTO#734]
If USE `clang` is enabled, `app-office/libreoffice-7.1.2.2` fails to build. Adding `NOLDADD=1` is a workaround for this.

Also, if both `custom-cflags` and `clang` are enabled, some flags are needed to be disabled to build libreoffice. Please refer to the linked PR for more information.

**Comment by jian-lin** [comment]
[clang_build.log](https://github.com/InBetweenNames/gentooLTO/files/6661579/clang_build.log)
[clang_custom-cflags_build.log](https://github.com/InBetweenNames/gentooLTO/files/6661580/clang_custom-cflags_build.log)
[clang_custom-cflags_info.log](https://github.com/InBetweenNames/gentooLTO/files/6661581/clang_custom-cflags_info.log)
[clang_info.log](https://github.com/InBetweenNames/gentooLTO/files/6661582/clang_info.log)

**Comment by jian-lin** [comment]
Those are my build logs and the outputs of `emerge --info`.
I still cannot build it without my PR.
@telans Since you have [no problem](https://github.com/InBetweenNames/gentooLTO/pull/735#issuecomment-856623719) building it, could you take a look at my logs?

**Comment by telans** [comment]
Can you provide `/var/tmp/portage/app-office/libreoffice-7.1.4.2/work/libreoffice-7.1.4.2/config.log`?

**Comment by jian-lin** [comment]
Thanks. Here are those logs.
[clang_config.log](https://github.com/InBetweenNames/gentooLTO/files/6664126/clang_config.log)
[clang_custom-cflags_config.log](https://github.com/InBetweenNames/gentooLTO/files/6664128/clang_custom-cflags_config.log)

**Comment by telans** [comment]
Okay yeah, turns out I added NOLDADD=1 for testing and completely forgot about it. Sorry!

**Comment by telans** [comment]
Whoops, sorry for the noise! I have NOLDADD specified in an env for all my packages I forgot about
