### ISSUE TITLE
/usr/bin/gnome-extensions-app Segfaults, can't pinpoint the source of the issue

### ISSUE THREAD

**Issue by AdelKS** [InBetweenNames/gentooLTO#745]
Hello,

On gnome-shell 40.0, I cannot run extensions for a reason I cannot seem to pin-point. When running the `extensions` app, that manages extensions, I get this:
```
gnome-extensions-app 
/usr/bin/gnome-extensions-app: line 2: 407685 Segmentation fault      (core dumped) /usr/bin/gjs /usr/share/gnome-shell/org.gnome.Extensions "$@"
```
`coredumpctl` gives me this:
```
           PID: 407685 (gjs)
           UID: 1000 (adel)
           GID: 1000 (adel)
        Signal: 11 (SEGV)
     Timestamp: Wed 2021-05-12 18:28:52 CEST (1min 57s ago)
  Command Line: /usr/bin/gjs /usr/share/gnome-shell/org.gnome.Extensions
    Executable: /usr/bin/gjs-console
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slic>
          Unit: user@1000.service
     User Unit: vte-spawn-b88e3f97-d1ec-4563-b4bb-1c956497231f.scope
         Slice: user-1000.slice
     Owner UID: 1000 (adel)
       Boot ID: 40b100ff97544e78a28e3d1f832c1db9
    Machine ID: 9d2ad4e2ef1620a6d0f5e2046057eb9d
      Hostname: leyantoo
       Storage: /var/lib/systemd/coredump/core.gjs.1000.40b100ff97544e78a28e3d1f832c1db9.407685.162>
     Disk Size: 1.8M
       Message: Process 407685 (gjs) of user 1000 dumped core.
```
I recompiled `dev-libs/gjs`, version 1.68.1, 1.68.0 and 1.66.2 without any optimization, aka `-march=native -O2 -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed`, with GCC 11.1 on a Zen 3 CPU and it did not fix the issue.

Does anyone else have this same issue ?

**Comment by AdelKS** [comment]
Okay, latest updates, 40.1, fixed this.

**Comment by jacob-swanson** [comment]
I ran into the same issue. The reinstalled `gui-libs/gtk` with `-ffat-lto-objects` and `gjs` started working.

**Comment by enx1998** [comment]
Hi all,
I have the same problem with "=gnome-base/gnome-shell-41.4" but I don't know how to solve: I tried adding `x11-libs/gtk+ *FLAGS+=-ffat-lto-objects` to my .cflags file without success.
Thanks ENx
