### ISSUE TITLE
=media-libs/dav1d-0.9.0 requires *FLAGS-=-flto*

### ISSUE THREAD

**Issue by F3rdinan** [InBetweenNames/gentooLTO#750]
=media-libs/dav1d-0.9.0 fails compilation with 1990 CPU flag related errors such as ``/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: <artificial>:(.text+0x4689): undefined reference to `dav1d_msac_decode_hi_tok_sse2'`` unless `*FLAGS-=-flto*` is used to override.

**Comment by F3rdinan** [comment]
Looks like this has already been fixed by f1a21580d74f5d7565b3108d69d93e09f84a2c26 . It does happen with gcc-10.3.0 for me, though, not just 11.0.

Closing issue.

**Comment by lucius-martius** [comment]
For me #737 does not fix this issue since ltoworkarounds is no longer symlinked on my system in favor of lto.conf.

Can you confirm the fix is in fact working for you @F3rdinan?

**Comment by F3rdinan** [comment]
Looks like you got it handled in #737 already @lucius-martius. Good catch - I had put it to my manual workarounds and didn't realize the file in pull request was not symlinked.
