### ISSUE TITLE
ltoworkarounds.conf doesn't exist?

### ISSUE THREAD

**Issue by Gooberpatrol66** [InBetweenNames/gentooLTO#769]
/etc/portage/package.cflags/ltoworkarounds.conf is a dangling symlink. I tried reinstalling ltoize-0.9.7 but it didn't help. Is this supposed to happen?

**Comment by leandrolnh** [comment]
Even though the 0.9.7 ebuild tries to install the `ltoworkarounds.conf`, this commit removed it from tree:
https://github.com/InBetweenNames/gentooLTO/commit/0f3a616c76a4d5065a8d22e44798a7db919d6c93
So, this ebuild tries to install the file but it cannot find it, thus the symlink points to nowhere.

**Comment by petronio** [comment]
ltoize >= 0.9.8 doesn't create the symlink since the file has been removed (the big main file was split into smaller workaround-specific files). The latest ltoize is 0.9.10, I recommend just upgrading.

**Comment by Gooberpatrol66** [comment]
Oh, ok thanks.
