### ISSUE TITLE
Lua 5.1 needs to be built w/o LTO

### ISSUE THREAD

**Issue by samheiden** [InBetweenNames/gentooLTO#772]
I have just enabled LTO on my system, and the packages app-editors/neovim x11-wm/awesome failed with weird errors coming from lua. As it turns out, lua segfaulted. As I went through the debugging process, it seems that disabling LTO with `*FLAGS-=-flto*` was enough to get it to build without segfaulting. For reference, this is occurrring on dev-lang/lua-5.1.5-r106. No such issue occurs in dev-lang/lua-5.4.2-r1.

**Comment by thecakeisalie25** [comment]
Can confirm, had the same issue with neovim
