### ISSUE TITLE
net-libs/webkit-gtk-2.32.3 fails to configure

### ISSUE THREAD

**Issue by rugubara** [InBetweenNames/gentooLTO#773]
>>> Configuring source in /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkitgtk-2.32.3 ...
 * Working in BUILD_DIR: "/var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build
"
cmake -C /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build/gentoo_common_co
nfig.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_UNIFIED_BUILDS=yes -DENABLE_QUARTZ_TARGET
=no -DENABLE_API_TESTS=no -DENABLE_GTKDOC=no -DENABLE_GEOLOCATION=yes -DCMAKE_DISABLE_FIND_PACKAGE
_OpenGLES2=ON -DENABLE_GLES2=no -DENABLE_MINIBROWSER=no -DENABLE_VIDEO=yes -DENABLE_WEB_AUDIO=yes
-DENABLE_INTROSPECTION=yes -DUSE_LIBNOTIFY=yes -DUSE_LIBSECRET=yes -DUSE_OPENJPEG=yes -DUSE_WOFF2=
ON -DENABLE_SPELLCHECK=yes -DUSE_SYSTEMD=yes -DENABLE_GAMEPAD=no -DENABLE_WAYLAND_TARGET=yes -DUSE
_WPE_RENDERER=ON -DCMAKE_DISABLE_FIND_PACKAGE_EGL=OFF -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=OFF -DEN
ABLE_X11_TARGET=yes -DUSE_OPENGL_OR_ES=ON -DENABLE_WEBGL=ON -DENABLE_WEBGL2=OFF -DENABLE_BUBBLEWRA
P_SANDBOX=yes -DBWRAP_EXECUTABLE:FILEPATH=/usr/bin/bwrap -DDBUS_PROXY_EXECUTABLE:FILEPATH=/usr/bin/xdg-dbus-proxy -DPORT=GTK -DRUBY_EXECUTABLE=/usr/bin/ruby30 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build/gentoo_toolchain.cmake  /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkitgtk-2.32.3
loading initial cache file /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/usr/bin/x86_64-pc-linux-gnu-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/ninja cmTC_1cf6c && [1/2] Building CXX object CMakeFiles/cmTC_1cf6c.dir/testCXXCompiler.cxx.o
    FAILED: CMakeFiles/cmTC_1cf6c.dir/testCXXCompiler.cxx.o
    /usr/bin/x86_64-pc-linux-gnu-g++    -DNDEBUG -march=native -O3 -fno-semantic-interposition -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -falign-functions=32 -pipe -stdlib=libstdc++ -Wl,-O1 -Wl,--as-needed -o CMakeFiles/cmTC_1cf6c.dir/testCXXCompiler.cxx.o -c /var/tmp/portage/net-libs/webkit-gtk-2.32.3/work/webkit-gtk-2.32.3_build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    x86_64-pc-linux-gnu-g++: error: unrecognized command-line option ‘-stdlib=libstdc++’
    ninja: build stopped: subcommand failed.

**Comment by rugubara** [comment]
Submitting it here, since the pure Gentoo machine without lto overlay compiles it just fine.

**Comment by 2secslater** [comment]
I believe you have the `clang` USE flag enabled for `sys-config/ltoize`, but are not using clang(++) for building `net-libs/webkit-gtk`. Are your CC and CXX variables set correctly (to `clang` and `clang++` respectively)?

**Comment by rugubara** [comment]
Indeed. Sorry for the noise.

**Comment by erikrodrgz** [comment]
> I believe you have the `clang` USE flag enabled for `sys-config/ltoize`, but are not using clang(++) for building `net-libs/webkit-gtk`. Are your CC and CXX variables set correctly (to `clang` and `clang++` respectively, see https://wiki.gentoo.org/wiki/Clang if unsure)?

The recommendation of using GentooLTO with clang is to set CC="clang"  CXX="clang++" in make.conf or create environments?
