### ISSUE TITLE
How can I return my system to normal?

### ISSUE THREAD

**Issue by typecasto** [InBetweenNames/gentooLTO#786]
I'm not really noticing any performance gains, but I am noticing a lot of build failures (including the kernel), gcc segfaulting, and just strange behavior when it comes to packages. I really like the concept, but I want to have a stable system again.

How would I go about removing gentooLTO from my system completely?

**Comment by haimeh** [comment]
step 1)
emerge --depclean sys-config/ltoize

step 2)
emerge --depclean

step 3)
Restore your make.config file using a copy you saved from before you did gentoo-lto OR if you didnt make a backup, remove the USE flags "pgo lto graphite" and remove the line where you source from the make.conf.lto file and restore your COMMON_FLAGS to something like "-march=native -O2 -pipe"

step 3.5)
you may wish to review your zz-autounmask file if you used autounmask-continue during the upgrade to gentoo-lto


step 4)
eselect repository remove mv lto-overlay

step 5)
emerge --changed-use --deep @world

Now you are back to normal gentoo

**Comment by jiblime** [comment]
Along with the above advice, this may help.

```
# Rebuild toolchain without LTO
root# emerge --ask @system sys-devel/binutils sys-libs/binutils-libs sys-devel/libtool
# Rebuild the entire system without LTO
root# emerge --emptytree --keep-going @world
```

Alternatively, you can chroot a stage 3 and use its "untainted" toolchain instead if you believe yours is broken beyond repair.

Had you tried running `lto-rebuild` recently?
