### ISSUE TITLE
media-libs/mesa-21.3.1 does not build

### ISSUE THREAD

**Issue by kanyck** [InBetweenNames/gentooLTO#813]
Few undefined references (build log attached)
[build.log](https://github.com/InBetweenNames/gentooLTO/files/7693252/build.log)
Gentoo, ~arch LLVM 13.0.0

**Comment by kanyck** [comment]
`emerge --info llvm`
[llvm-emerge.txt](https://github.com/InBetweenNames/gentooLTO/files/7761754/llvm-emerge.txt)

**Comment by TheMBL09898** [comment]
One I had mesa fail and I removed the llvm use flag from the package so it could build. Try that.

**Comment by kanyck** [comment]
Thanks for your tip. Yet mesa 22 builds fine with llvm flag enabled. So I belive that was temporary inconsistence between two packages. Closing.
