### ISSUE TITLE
Remove custom Python ebuilds

### ISSUE THREAD

**Issue by aruhier** [InBetweenNames/gentooLTO#821]
Hi,
As the official Gentoo packages of Python now handle LTO and PGO (through the uses `lto` and `pgo`), should the custom ebuilds for Python be removed?

**Comment by mid-kid** [comment]
Duplicate of https://github.com/InBetweenNames/gentooLTO/issues/814
And yeah, these ebuilds should be removed, as they can override the default ebuilds in nasty ways. I've masked them for now.

**Comment by aruhier** [comment]
OK, I close this one to redirect to your issue.
