### ISSUE TITLE
Enable graphite for gcc before switching to GentooLTO

### ISSUE THREAD

**Issue by StefanSalewski** [InBetweenNames/gentooLTO#842]
I guess this is important, but not mentioned in the docs?

For a newly installed system, I just had a situation that graphite was not enabled globally in /etc/portage/make.conf, so lto-rebuild -r failed with a not too helpful message like "gcc could not built executables". So I just modified make.conf again to temporary disable GentooLTO, and are now building my gcc with graphite support.

**Comment by 2secslater** [comment]
On Tue, 31 May 2022 01:45:31 -0700
StefanSalewski ***@***.***> wrote:

> I guess this is important, but not mentioned in the docs?

This is mentioned in the readme.

https://github.com/InBetweenNames/gentooLTO/blob/master/README.md#how-to-use-this-configuration

> The default configuration of GentooLTO enables the following:
> ...
> * Graphite ( requires gcc to be built with the `graphite` use flag )

Though maybe it could be made more obvious.
