### ISSUE TITLE
Wondering

### ISSUE THREAD

**Issue by ignamartinoli** [InBetweenNames/gentooLTO#849]
Is it possible to remove the `mv` overlay after finishing the **LTO**-ization/installation process?

**Comment by wolfwood** [comment]
no. it is what allows the wildcard *FLAGS modification rules that let us
work around broken packages easily. it's central to the way this technique
works.

you can add `*/*::mv` to your **package.mask** file and then add
`app-portage/portage-bashrc-mv::mv` and `app-shells/runtitle::mv` to
**package.unmask** if you don't want to match non-essentials from this repo.

**Comment by ignamartinoli** [comment]
Thanks! Another question, after running `emerge -e @world` I went to sleep and when I woke up I saw that `ghc` couldn't get compiled, does it mean that every other package in the queue after it wasn't re-compiled and now I should remove `ghc`, run `emerge -e @world` again and hope for it to not happen again with another package?

**Comment by wolfwood** [comment]
read up on the options `--keep-going`, `--resume` and `--skipfirst` in the `emerge` man page.

**Comment by ignamartinoli** [comment]
Thanks, I didn't knew them
