### ISSUE TITLE
Add dev-lang/python 3.6.4 --with-lto

### ISSUE THREAD

**Issue by fedan** [InBetweenNames/gentooLTO#89]
python-3.6.4 support configure flag --with-lto:

`  --with-lto              Enable Link Time Optimization in PGO builds.
                          Disabled by default.`

**Comment by InBetweenNames** [comment]
Interesting.  I wonder if this just adds `-flto[=n]` to `*FLAGS`, or if it does something more?

If I do an `objdump -t /usr/lib64/libpython3.6m.a` with the way it is now, I see these symbols:

~
0000000000000000 l    d  .gnu.lto_.profile.97cd3fbf9e52e88      0000000000000000 .gnu.lto_.profile.97cd3fbf9e52e88
0000000000000000 l    d  .gnu.lto_.icf.97cd3fbf9e52e88  0000000000000000 .gnu.lto_.icf.97cd3fbf9e52e88
0000000000000000 l    d  .gnu.lto_.jmpfuncs.97cd3fbf9e52e88     0000000000000000 .gnu.lto_.jmpfuncs.97cd3fbf9e52e88
0000000000000000 l    d  .gnu.lto_.inline.97cd3fbf9e52e88       0000000000000000 .gnu.lto_.inline.97cd3fbf9e52e88
0000000000000000 l    d  .gnu.lto_.pureconst.97cd3fbf9e52e88    0000000000000000 .gnu.lto_.pureconst.97cd3fbf9e52e88
0000000000000000 l    d  .gnu.lto_hashtable_compare_pointer_t.97cd3fbf9e52e88   0000000000000000 .gnu.lto_hashtable_compare_pointer_t.97cd3fbf9e52e88...
~

So it is indeed being built with LTO already with PGO.  Could you investigate the build system of Python to see what `--with-lto` does?

**Comment by fedan** [comment]
It's add LTOFLAGS="-flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none" in Makefile.
See Makefile.pre.in:
```Makefile
build_all_generate_profile:
	$(MAKE) @DEF_MAKE_RULE@ CFLAGS_NODIST="$(CFLAGS) $(PGO_PROF_GEN_FLAG) @LTOFLAGS@" LDFLAGS="$(LDFLAGS) $(PGO_PROF_GEN_FLAG) @LTOFLAGS@" LIBS="$(LIBS)"
...
build_all_use_profile:
	$(MAKE) @DEF_MAKE_RULE@ CFLAGS_NODIST="$(CFLAGS) $(PGO_PROF_USE_FLAG) @LTOFLAGS@" LDFLAGS="$(LDFLAGS) @LTOFLAGS@"
```

I build for test:
```shell
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
export AR=/usr/bin/gcc-ar
export NM=/usr/bin/gcc-nm
export RANLIB=/usr/bin/gcc-ranlib
export CFLAGS="-O2 -march=native -fomit-frame-pointer -pipe -Wno-all"
export CXXFLAGS="-O2 -march=native -fomit-frame-pointer -pipe -Wno-all"
export LDFLAGS="-O2 -march=native -fomit-frame-pointer -pipe -Wno-all -Wl,--sort-common,--hash-style=gnu,--as-needed"
export PYTHON_DISABLE_MODULES="_tkinter"

./configure --with-fpectl --enable-shared --disable-ipv6 --with-threads --with-computed-gotos --with-libc= --enable-loadable-sqlite-extensions --without-ensurepip --with-system-expat --with-system-ffi --enable-optimizations --with-lto

make profile-opt PROFILE_TASK="-m test.regrtest -w -uall,-audio -x test_gdb test_multiprocessing test_subprocess test_tokenize test_signal test_faulthandler test_asyncio test_ctypes"
```

**Comment by InBetweenNames** [comment]
Thanks for the followup!  It's interesting that they have chosen to use `-ffat-lto-objects`.  I believe we once did that too, before the `STRIP_MASK` workaround here.  From what I can tell, the only significant flag being passed in is `-flto-partiton=none`.  I didn't need that one to built it with LTO here.

By the way, does the current 3.6.4 ebuild in this repo work for you with PGO?  If so, it may be worth making a PR upstream to remove `-ffat-lto-objects` and even `-flto-partition=none` from their build system.

**Comment by fedan** [comment]
I have not yet building from this repository

**Comment by fedan** [comment]
If add --enable-optimizations in the configure, the Makefile will be
```shell
# Default target
all:		profile-opt
```

**Comment by InBetweenNames** [comment]
Indeed, but the default isn't the best way of doing PGO last time I checked.  Our approach uses a much more comprehensive profiling stage.  There has been discussion upstream with Gentoo about this, although progress is very slow.

**Comment by InBetweenNames** [comment]
After some looking it appears it makes no difference.  We can reopen this later if it turns out to be important.  Thanks for bringing this to my attention!
