### ISSUE TITLE
media-libs/openjpeg-2.3.0 fails with FLTO and/or GRAPHITE

### ISSUE THREAD

**Issue by juippis** [InBetweenNames/gentooLTO#98]
Hey, just did a fresh emerge -e world and had troubles with media-libs/openjpeg-2.3.0. First it failed with lto, so I disabled it *FLAGS-=-flto* (sorry I didnt log the error) however later on after resuming emerge it failed again with the following error, 
`/tmp/portage/media-libs/openjpeg-2.3.0/work/openjpeg-2.3.0/src/lib/openjp2/dwt.c:2171:13: internal compiler error: in outer_projection_mupa, at graphite-sese-to-poly.c:1019`

After disabling GRAPHITE as well, it compiled just fine. I can do a PR but looking at _equery d openjpeg_ it seems like a common package and Im just wondering am I the only one with this error?

**Comment by InBetweenNames** [comment]
@juippis sorry for not getting back to you sooner -- I'll make sure I investigate this later tonight.  Which version of GCC are you using?  7.3.0?

**Comment by InBetweenNames** [comment]
Just built it on my system.  No issues here whatsoever with 2.3.0 -- I have Graphite and LTO enabled on it.  I'm on GCC 7.3.0, binutis 2.30, gold linker.  Could you post your `build.log` when you get a chance?

**Comment by juippis** [comment]
Don't worry about the delay, as even to my surprise, rest of my -e world compiled just fine with your settings. 

I tried compiling again with LTO and Graphite enabled, and it failed. I just noticed I can compile it with LTO enabled but Graphite disabled, when LTO & Graphite are enabled the error is the same as it is when only Graphite is enabled, but it fails in a different spot and prints:
>/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: fatal error: lto-wrapper failed
which probably threw me off thinking it's a problem with LTO. I'll paste both logs, LTO & Graphite enabled and LTO Disabled & Graphite enabled. 

[openjpeg-build-fail-graphite.log](https://github.com/InBetweenNames/gentooLTO/files/1739239/openjpeg-build-fail-graphite.log)
[openjpeg-build-fail-lto.log](https://github.com/InBetweenNames/gentooLTO/files/1739240/openjpeg-build-fail-lto.log)

as I said, compiled it now with LTO enabled & Graphite disabled. And yes, I'm using GCC-7.3.0, Binutils-2.30 and Gold linker.

**Comment by InBetweenNames** [comment]
Interesting!  We have very similar configurations.  I have noticed that Graphite can be a little inconsistent sometimes -- I believe depending on the exact uarch being compiled for (for example Haswell, Zen) it can work and sometimes not.  I think this is one of those cases.  Thanks for the detailed report -- I think it's best we universally disable Graphite for this package for now.  Perhaps the situation will improve with GCC 8.  Do you want to do the PR?

**Comment by juippis** [comment]
I noticed that I am able to build earlier versions of openjpeg with LTO and Graphite, just not 2.3.0. So I added *FLAGS-="${GRAPHITE}" only to 2.3.0. Gonna see how it goes when it updates!

**Comment by InBetweenNames** [comment]
Excellent, thanks!

**Comment by InBetweenNames** [comment]
Note: as of `master` all optimizations have been re-enabled, as I've managed to build this package with LTO and Graphite
